### ISSUE TITLE
Document DW::Plugin::FormHTML in the style guide

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1019]
The style guide has code examples and form styling examples -- what's not clear is that when making, e.g., a text field, we should be using `[% form.textbox( ... ) %]` instead of `<input type=textbox>` because the former will handle proper linking to a provided label, default classes, etc.

**Comment by kareila** [comment]
I think this was resolved in #1163 yes?

**Comment by afuna** [comment]
Yup
