### ISSUE TITLE
Convert BML files under htdocs/admin

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1044]

**Comment by Sophira** [comment]
I noticed that /admin/healthy hasn't had its translation strings added - I see "[missing string /admin/index.tt.admin.healthy.link]" on the admin page, as well as "[missing string /admin/index.tt.admin.healthy.text]" for the description. Just a heads-up in case you're not already aware!

**Comment by afuna** [comment]
Oops yup thanks @Sophira

**Comment by kareila** [comment]
I'm also seeing some missing strings on /admin/index.  Both /admin/healthy and /admin/sendmail/ are missing itemhead text and itemdef text.

**Comment by kareila** [comment]
Never mind, I see now that the healthy strings are fixed in develop, just not on the live site.  The missing text for /admin/sendmail must be my fault, but I'm surprised I didn't notice sooner!

**Comment by kareila** [comment]
Currently working on converting spamreports as prep for #1522.
