### ISSUE TITLE
Tags label invisible in Planet Caravan/some themes

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1067]
http://www.dreamwidth.org/support/see_request?id=29745

.tag-text or some parent element is black and the entry footer bkg is also black making the 'Tags:' label is invisible in Cheerfully, Oceanic and Sunrise, and users have no way of changing that color via the customize UI as there is no corresponding prop for it. I see
```
.entry .footer, .comment .footer {
    background: $*color_entry_footer_background;
    padding: .75em;
}
```

but no corresponding text color(s).

**Comment by momijizukamori** [comment]
claiming because WHOOPS my bad
