### ISSUE TITLE
Investigate/remove dead code in views/multisearch.tt and cgi-bin/DW/Controller/Search/Multisearch.pm

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#1079]
So, probably as a result of https://github.com/dreamwidth/dw-free/commit/c292ef5d6f66b18849a284160afe4dceda537240 , it looks to me like /multisearch is no longer called with type=nav, and code around https://github.com/dreamwidth/dw-free/blob/develop/views/multisearch.tt#L16 and https://github.com/dreamwidth/dw-free/blob/develop/cgi-bin/DW/Controller/Search/Multisearch.pm#L200 is (I think) now dead and can be removed.

**Comment by me-and** [comment]
Claimed
