### ISSUE TITLE
treat - and _ interchangeably in forwarding email addresses

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1080]
user_name@dreamwidth.org works for the forwarding email address, but user-name@dreamwidth.org doesn't. People don't really think of their usernames as being user_name anymore, since they see it up in the URL bar as user-name, and everything else on the site treats them as interchangeable, so we should also make them interchangeable in forwarding email addresses.

**Comment by alierak** [comment]
After reading Postfix source code I'm somewhat more confident that it accepts arbitrary SQL.

**Comment by afuna** [comment]
Hmmm, but are we confident enough in arbitrary SQL, that’s the question.


On Tue, Mar 3, 2015, at 07:01 AM, alierak wrote:
> After reading Postfix source code I'm somewhat more confident that it
> accepts arbitrary SQL.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1080#issuecomment-76961203

**Comment by zorkian** [comment]
Hi! Sorry for being slow here -- two points of feedback.

1. Whatever we put in the database should be exactly the username. Usernames have underscores. If we want to build some way of allowing the system to accept hyphens, that's great, but I don't think the correct approach would be to put hyphens in the database.

2. Updating the SQL so it basically converts the email being sent to down to underscores to match what we put in the database makes the most sense, IMO. That'd be pretty easy to do operationally assuming #1 is true and we can predict what alias would be in the DB.

Make sense? Thank you for working on this!

**Comment by pauamma** [comment]
Should I submit a pull request to dw-ops, considering the turn the review took? Or is someone else taking care of it? (I'd rather not do it myself, because I'm too lazy to do the fork&clone dance for what would likely be a single PR.)
