### ISSUE TITLE
Whitelist embeds from Vine

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1106]
http://www.dreamwidth.org/support/see_request?id=30060
Sample code:
```
<iframe class="vine-embed" src="https://vine.co/v/OHa76XHVqXm/embed/simple" width="600" height="600" frameborder="0"></iframe><script async src="//platform.vine.co/static/scripts/embed.js" charset="utf-8"></script> 
```
Dunno if the script part is necessary...

**Comment by hotlevel4** [comment]
Simple embeds work with just adding the following line to the whitelist:

`"vine.co"               => [ qr!^/v/[a-zA-Z0-9]{11}/embed/(simple|postcard)!, 1 ],`

However, the postcard embeds do not work appropriately. Unsure if this is related to the script portion of the embed code?

**Comment by afuna** [comment]
Quite possibly, because we strip out the script tags. I bet simple is simple enough it works even without the scripts...

How badly is the postcard broken when you try to embed it? Is is completely unusable or just sort of basic?

**Comment by hotlevel4** [comment]
Unusable. At 600 height/width, it shows a screencap of the paused video but as soon as you click play, the entire video frame disappears. At 300 height/width, the paused screencap of the video is not properly resized. See, for example: http://system.hotlevel4.hack.dreamwidth.net/3711.html -- 4 videos on the page: simple @ 600, postcard @ 600, simple @ 300, postcard @ 300.

**Comment by afuna** [comment]
Hmmmm I think in that case we should only allow the simple one through.

**Comment by hotlevel4** [comment]
Okay, will submit a patch just for the simple version then.

Just FYI, the tests for embed-whitelist.t are failing all the ones where the second variable is set to 0 instead of 1.
