### ISSUE TITLE
Remove MSN Messenger from profile

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1110]
MSN Messenger shut down 31 October; we can remove it from the profile.

**Comment by Sophira** [comment]
Weren't you fixing this already? (Issue #918 / PR #919)

Are you still working on it? Do you need any help?

**Comment by rahaeli** [comment]
Sigh. Nevermind.

(No, I don't need any help, since three separate people tried to give me steps to fix it and each time it got progressively more fucked up. I need to nuke the branch and completely redo the changes, I just gave up on it because it was walk away or throw my laptop out the window. Have I mentioned recently how much I despise git?)
