### ISSUE TITLE
can't create new accounts

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1124]
Trying to create a new account: hitting 'submit' on the form and the browser tries to load for a really long time before timing out. The problem is, it's trying to submit to https://perlbal/create .

News post comments say this is happening with other calls to HTTPS pages as well.

**Comment by zorkian** [comment]
This is resolved. Added to our nginx config, so that we pass the initial host header through:

```
proxy_set_header Host $http_host;
```
