### ISSUE TITLE
adult content interstitial not loading

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1125]
When hitting a page that requires the adult-content interstitial, you get a blank  page with no way to carry on.

User-supplied screenshots:

http://i.imgur.com/P0Y0I20.png
https://images.plurk.com/3P1E3ONfgfaetuGJRgxBli.jpg

**Comment by afuna** [comment]
Uuurgh it works as ?uselang=en but not ?uselang=en_DW. Translation system :(

**Comment by afuna** [comment]
Fixt by clearing memcache of these specific keys
