### ISSUE TITLE
tweaks to tag nav forward/back arrows

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1126]
Unless anybody else can come up with a better solution that addresses all the problems people have with this, my proposed solution is:

a) Give the forward/back arrows a CSS class so they can be hit with custom CSS or a Stylish script;

b) Toggle the display/nondisplay of the forward/back arrows by tag with a turnable arrow at the start of the tag module, much like on the profile. Hitting that arrow will remove all the forward/back arrows in the tag block (and redraw the tag list, obvs), and the system should remember last used value.

**Comment by afuna** [comment]
Let's brainstorm a bit. Discussed with Mark, came up with the idea of
having something (arrows?) by the "Tags:" label which turns on tag
navigation mode. Then you can select the tag and just go forward/back
through it.

This solves the issue of clutter, without causing issues as in the case
of hover, etc.

But how to flesh out the interface further? Any way to make this work
without clunkiness?

**Comment by rahaeli** [comment]
I like that idea, too!  I don't really have much of a sense of what it would look like, though.

**Comment by ninetyd** [comment]
Dunno if this should be a separate issue but there's a blank space before the comma on journal pages without arrows, which didn't use to be there before. Any page, any style. See http://dw-dev.dreamwidth.org/ for example.

**Comment by afuna** [comment]
new issue please! thank you :)

**Comment by afuna** [comment]
Okay couple proposals.

Currentl form, we have the tag navigation arrows on all tags when we're in tags view or entry/reply view:

![screenshot 2015-01-23 12 27 15](https://cloud.githubusercontent.com/assets/364169/5882130/909e554c-a2fb-11e4-8b66-55af495555e1.png)

    Tags: <-- foo -->, <-- bar -->

Alternative proposals:
1) Turn on tag edit mode, inline fashion

* in tags view and entry/reply view, start with one set of arrows for the tags section (not one set overall)

    Tags: < > foo, bar

* clicking an arrow turns on tag navigation mode (additional styling on tags to make it clear that clicking on them does something different -- that is, we're picking the tag to navigate through). Clicking the other arrow turns navigation on that way; clicking the current arrow turns off navigation mode entirely. Clicking the tag navigates in the way indicated by the selected arrow.

    Tags: **≤** > foo, bar
                   
* on subsequent pages, the selected tag is bolded or otherwise emphasized to show we're still in the previous mode

    Tags: **≤** > **foo**, bar



2) Turn on tag edit mode, but only starting from the tags browsing page

* in tags view, have arrows on the specific tags that are being browsed through. So on http://example.dreamwidth.org/tag/foo, we have:

    Tags: <-- foo -->, bar

Clicking the arrows will navigate back and forth. clicking the tag will bring you to the specific tags page.

* when you click through to the individual entry and we detect that we came from a tags page (either via having an argument on the URL of the entry when you're clicking through, or referer -- prefer the former though because then you can trigger manually, but may or may not be an issue)

If from tags page (has URL argument):

    Tags: <-- foo -->, bar 


If not from tags page (no URL argument):

    Tags: foo, bar


(1) is more discoverable, but also quite indirect and I think we might have to figure out affordances very carefully.. (2) is less discoverable and involves a URL argument, so we risk having yet another hidden feature, but also might work out to be more context sensitive

Thoughts opinions etc etc?

**Comment by rahaeli** [comment]
I think we should go for 'discoverable' over anything else, but agree that the affordances are going to be a bitch to figure out.

**Comment by afuna** [comment]
Hmmm, but now I wonder whether I overstated it. Do we have any idea how people are going to be using this? That is, is it likely that someone reading an entry will randomly decide to start browsing entry-by-entry by tag, or is it more likely that someone sees an entry with a tag that's relevant sequentially (e.g., fic series that's been going on a while that's gone under their radar), click through to the tag page, and then go to the earliest entry in that tag to start reading?

**Comment by zorkian** [comment]
Since the feature was released, my usage is "viewing entry, want to view
more by this tag, click left arrow next to tag".

I never use the tag page.

--
Mark Smith mark@qq.is


On Sat, Jan 24, 2015, at 08:29 PM, Afuna wrote:
> Hmmm, but now I wonder whether I overstated it. Do we have any idea
> how people are going to be using this? That is, is it likely that
> someone reading an entry will randomly decide to start browsing
> entry-by-entry by tag, or is it more likely that someone sees an entry
> with a tag that's relevant sequentially (e.g., fic series that's been
> going on a while that's gone under their radar), click through to the
> tag page, and then go to the earliest entry in that tag to start
> reading?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71351520

**Comment by rahaeli** [comment]
Ditto to Mark: the biggest use case is "linked to a specific entry, want to go forward/back in tags to read other entries with the same tag". It avoids having to go to the "all entries with this tag" page, find the entry you were reading, and then continuing onward.

For instance, say you get linked to http://synecdochic.dreamwidth.org/59305.html and want to read the next story I wrote after that, chronologically. If you go to http://synecdochic.dreamwidth.org/tag/fic you have to page back five or six pages before you find the original entry. Using the tag arrow lets you click straight forward and get http://synecdochic.dreamwidth.org/59948.html without the intervening search.

**Comment by afuna** [comment]
Okay soooo let's figure out the affordances. In the current proposal,
clicking the tag moves you either forward or backward, depending on
which arrow is highlighted at the beginning of the tag list.

I am thinking between that and adding forward/back arrows, which brings
up the problem of more clutter (again). and magic icons, and the like.

Hmmm. How about an expand arrow to the right of the "Tags" label, as
someone suggested but something like:

Tags: > foo, bar

Clicking that either:

(a) adds the arrows to all tags:

Tags: < <-- foo -->, <-- bar -->

or (b) lets you select a specific tag:


Tags: < *foo*, bar

Which then has arrows?

Tags: < <-- foo -->, bar?




On Sun, Jan 25, 2015, at 12:43 PM, Denise Paolucci wrote:
> Ditto to Mark: the biggest use case is "linked to a specific entry,
> want to go forward/back in tags to read other entries with the same
> tag". It avoids having to go to the "all entries with this tag" page,
> find the entry you were reading, and then continuing onward.


> For instance, say you get linked to
> http://synecdochic.dreamwidth.org/59305.html and want to read the
> next story I wrote after that, chronologically. If you go to
> http://synecdochic.dreamwidth.org/tag/fic you have to page back
> five or six pages before you find the original entry. Using the tag
> arrow lets you click straight forward and get
> http://synecdochic.dreamwidth.org/59948.html without the
> intervening search.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71352020

**Comment by rahaeli** [comment]
Hm. At the moment I think "click the arrow, which then adds arrows to all the tags" is still probably the best option I can come up with -- if we make it a "remember the last used value" arrow, that will let people who always want the arrows on keep them on, people who always want the arrows off keep them off, and people who only want the arrows on when they're actively browsing a tag turn the arrows on when they want them and turn the arrows off when they don't want them.

That proposal will make things wiggle around on the screen a bit when it redraws the tag list with the arrows, but it's the best thing I can come up with that will satisfy the most use cases, and I have been thinking about this...

**Comment by zorkian** [comment]
Why isn't it "affordant" to have it as a modifier?

Tags < > foo bar baz

You click the <, it highlights/bolds/something, and then you click foo
and you go backwards. No extra arrows appear, nothing else happens to
the tag list. But it's obvious you turned something on because it became
highlighted/glowing/whatever we want to use to say "this is now active".

--
Mark Smith mark@qq.is


On Sat, Jan 24, 2015, at 09:00 PM, Afuna wrote:
>
>
Okay soooo let's figure out the affordances. In the current proposal,
>
>
clicking the tag moves you either forward or backward, depending on
>
>
which arrow is highlighted at the beginning of the tag list.
>
>
>
I am thinking between that and adding forward/back arrows, which brings
>
>
up the problem of more clutter (again). and magic icons, and the like.
>
>
>
Hmmm. How about an expand arrow to the right of the "Tags" label, as
>
>
someone suggested but something like:
>
>
>
Tags: > foo, bar
>
>
>
Clicking that either:
>
>
>
(a) adds the arrows to all tags:
>
>
>
Tags: < <-- foo -->, <-- bar -->
>
>
>
or (b) lets you select a specific tag:
>
>
>
>
Tags: < *foo*, bar
>
>
>
Which then has arrows?
>
>
>
Tags: < <-- foo -->, bar?
>
>
>
>
>
>
On Sun, Jan 25, 2015, at 12:43 PM, Denise Paolucci wrote:
>
>
> Ditto to Mark: the biggest use case is "linked to a specific entry,
>
>
> want to go forward/back in tags to read other entries with the same
>
>
> tag". It avoids having to go to the "all entries with this tag" page,
>
>
> find the entry you were reading, and then continuing onward.
>
>
>
>
> For instance, say you get linked to
>
>
> http://synecdochic.dreamwidth.org/59305.html and want to read the
>
>
> next story I wrote after that, chronologically. If you go to
>
>
> http://synecdochic.dreamwidth.org/tag/fic you have to page back
>
>
> five or six pages before you find the original entry. Using the tag
>
>
> arrow lets you click straight forward and get
>
>
> http://synecdochic.dreamwidth.org/59948.html without the
>
>
> intervening search.
>
>
>
>
> — Reply to this email directly or view it on GitHub[1].
>
>
>
>
>
>
>
>
>
Links:
>
>
>
  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71352020
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  2. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71352611

**Comment by afuna** [comment]
Hmmm, if it's a remember thing, though, then I'm not super worried about
the wiggling -- because it'll open happen once :)


On Sun, Jan 25, 2015, at 01:03 PM, Denise Paolucci wrote:
> Hm. At the moment I think "click the arrow, which then adds arrows to
> all the tags" is still probably the best option I can come up with --
> if we make it a "remember the last used value" arrow, that will let
> people who always want the arrows on keep them on, people who always
> want the arrows off keep them off, and people who only want the arrows
> on when they're actively browsing a tag turn the arrows on when they
> want them and turn the arrows off when they don't want them.


> That proposal will make things wiggle around on the screen a bit when
> it redraws the tag list with the arrows, but it's the best thing I can
> come up with that will satisfy the most use cases, and I have been
> thinking about this...


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71352764

**Comment by afuna** [comment]
I've been trying to mock it up, and basically things sort of make sense
on the first page.

My thinking is:
* selected arrow -> unselect
* unselected arrow --> select
* tag --> navigate forward or backward through the tag

But once I'm on the second page -- that is, once I've jumped once it
seems less clear to me. The action of selecting the arrow is no longer
immediately tied to the action of selecting the tag, so here my
instinct becomes:

* any arrow --> click == go in that direction
* tag --> go to the tags page

**Comment by afuna** [comment]
Rough prototypes of the two proposals:

Tag Navigation Mode:
![nav-mode](https://cloud.githubusercontent.com/assets/364169/5914584/2d3140b4-a5ad-11e4-8179-a82a32264719.gif)

Arrow Reveal:
![reveal-arrows](https://cloud.githubusercontent.com/assets/364169/5914585/2d31f324-a5ad-11e4-83a6-d05d141367c8.gif)

**Comment by zorkian** [comment]
For the top one, put the arrows next to each other on the left side.
Predictable locations are important for UI elements.

Also I still think that when they're on, we might consider doing some
hover/something on the tags just to indicate that there's a different
behavior. But maybe that's too much.

I still am a fan of the first one. ;)

--
Mark Smith mark@qq.is


On Mon, Jan 26, 2015, at 10:47 PM, Afuna wrote:
> Rough prototypes of the two proposals:


> Tag Navigation Mode: nav-mode


> Arrow Reveal: reveal-arrows


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71597543

**Comment by rahaeli** [comment]
Ooh, fancy!

I think I like the arrow reveal best still. The tag nav mode just seems too confusing.

**Comment by zorkian** [comment]
The arrow thing is not good, it causes the UI to reflow which is
crazy. Especially on mobile, where you might possibly have to scroll
around to find the thing you were just looking at. I don't think it's
good UX at all.

--
Mark Smith mark@qq.is


On Mon, Jan 26, 2015, at 10:50 PM, Denise Paolucci wrote:
> Ooh, fancy!


> I think I like the arrow reveal best still. The tag nav mode just
> seems too confusing.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71597727

**Comment by rahaeli** [comment]
I honestly don't think people will wind up triggering the arrows frequently -- I think in practice people will leave it on or off, depending on their preferences.

I'm willing to consider the tag nav mode but I really hate magic selectors -- they're equally bad UI. There's no explanation of what clicking the arrow does and it's not easily discoverable: people have to either know what the arrows do or experiment a lot, and if it doesn't click for you immediately what it's doing, you wind up with a situation where clicking the same link has two different behaviors based on whether the arrow's triggered or not. The benefit to the arrow reveal is that it's very obvious that you're in a different mode and can do something different, and it's pretty visually obvious what the difference is and what it's going to do.

**Comment by afuna** [comment]
Alternative placements for the tag nav arrows:

![screenshot 2015-01-26 22 55 54](https://cloud.githubusercontent.com/assets/364169/5914671/afeb5dd6-a5ae-11e4-9b20-d6dafaf8c4c6.png)
![screenshot 2015-01-26 22 56 34](https://cloud.githubusercontent.com/assets/364169/5914672/afeb9350-a5ae-11e4-8357-d7b167cc1f04.png)

**Comment by kareila** [comment]
I also have a strong preference for the arrow reveal option.  The other mockup is super confusing to me.

**Comment by zorkian** [comment]
I am unfamiliar with any other site that uses either of these modes. Can
we find some prior art here and figure out how companies with lots of
people doing UX have solved these kinds of issues?

I really dislike the arrow reveal and am gonna fight it. I'm not going
to fight in favor of the first one too much, though, it's just the
best I happened to come up with. I'm sure there's a better option out
there, though.

--
Mark Smith mark@qq.is


On Tue, Jan 27, 2015, at 09:09 AM, Jen wrote:
> I also have a strong preference for the arrow reveal option. The other
> mockup is super confusing to me.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1126#issuecomment-71685799

**Comment by woggy** [comment]
Don't we already do something very similar to the proposed arrow reveal,
with entry cuts and the collapse arrows?

Not quite wrapping my head around why this would be Different. And like Fu
said, if we remember folks' preferences it likely won't be something that
takes much actual redrawing.

**Comment by rahaeli** [comment]
I've been looking for prior art, and haven't found any.

**Comment by kareila** [comment]
I've been brainstorming on a third solution that combines elements of the first two proposals, with a collapsed browsing element like the second option that expands to a browsing mode like the first option.  It could also allow browsing by multiple tags (see issue #1166).

Here's my rough sketch:

![tag1](https://cloud.githubusercontent.com/assets/1976742/5943632/39e636cc-a6e6-11e4-9cc3-c3c246c48089.png)

Clicking on the plus element would reveal forward and back arrows, along with an icon indicating whether multiple tags are browsed as an intersection (mode=all) or union (mode=any), using the appropriate mathematical symbol.  This could be explained with hover text, and clicking that element would toggle between the two states.

![tag2i](https://cloud.githubusercontent.com/assets/1976742/5943656/8565fad8-a6e6-11e4-89be-255f073f9dbd.png) ![tag2u](https://cloud.githubusercontent.com/assets/1976742/5943658/891ebe9e-a6e6-11e4-9086-5f41b2e9a11e.png)

Once revealed, the tag links would change style to indicate the new mode, and clicking a tag would highlight it as being added to the list of tags currently activated for browsing.  Then clicking the arrow would go forward or back as expected.

![tag3](https://cloud.githubusercontent.com/assets/1976742/5943680/ad82c4c4-a6e6-11e4-9b1e-b5bccc0ca612.png)

Anyway, that's the functionality I would like to see, and my attempt to diagram it.  Let me know if you think it's workable.

**Comment by rahaeli** [comment]
Huh, something like that could work!

**Comment by afuna** [comment]
I agree I like that! Clicking on the arrows directly would address my main concern with the other one without cluttering up the interface :)

**Comment by afuna** [comment]
Ping @zorkian in case you have any feedback. Otherwise I'm about to start working on implementing @kareila's suggestion.

**Comment by afuna** [comment]
I've put up a draft of the changes (clicking the arrows does nothing yet). Would love if I could get people to pull this and try it out, see how that looks to you!

**Comment by afuna** [comment]
Oh hrrm. realization: the /go redirect can only handle one tag at a time. Do we want to have it handle multiple now (and if so, any or all?). Hrrm, we could add it along with the multiple tag navigation too.

**Comment by afuna** [comment]
Will leave the multiple selection until we have and/or, and for now enforce only one :)

**Comment by rahaeli** [comment]
Yeah, that might be a good future enhancement, but I don't think it's necessary now!

**Comment by afuna** [comment]
I believe this was addressed in #1206
