### ISSUE TITLE
Mood icons not displaying

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1128]
Mood icons are not displaying on user journals or on http://www.dreamwidth.org/customize/options?group=display .

**Comment by kareila** [comment]
I poked at this a bit.  My own icons show up just fine for me on all pages, and one other friend's icon worked on my reading page, so it's not all icons across the board.  But when I check http://www.dreamwidth.org/moodlist for the public mood themes, nothing is loading, so there's definitely an issue there.

It's possible that every one of my mood icons was in my browser cache, but unlikely, I think.

**Comment by afuna** [comment]
Fixed. Must make sure this doesn't happen again when we fix #1134
