### ISSUE TITLE
Link given in rename token email is not correct

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1129]
Link given in rename token email, to use the token: 

http://www.dreamwidth.org/rename/XXXXXX

Link should be: 

http://www.dreamwidth.org/rename?giventoken=XXXXXXX

**Comment by pauamma** [comment]
I'm pretty sure I fixed that already. Did https://github.com/dreamwidth/dw-free/pull/961 not make it to the push? Or are we talking about different emails?

**Comment by afuna** [comment]
Restarted workers so this should be fixed now.
