### ISSUE TITLE
loading icons via <img src> no longer triggers contextual hover menu

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1130]
Prior to this code push, if you put a DW icon in a comment using the <img src> tag like so:

<img src="http://www.dreamwidth.org/userpic/1/3">

...hovering over it would trigger the contextual hover menu. It's not doing that anymore, and people did find it useful; if we can fix it to bring that back, it would be awesome.

**Comment by afuna** [comment]
Fixed. Must make sure this doesn't happen again when we fix #1134
