### ISSUE TITLE
rename tokens being marked as used when someone even views them

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1132]
Related to #1129, people are reporting that after they clicked the (wrong) link in the email, the rename token is marked as used. I've had to reissue 5 of them so far. Tokens shouldn't be marked used until they're used to actually rename an account.

**Comment by afuna** [comment]
I'm not seeing this (and the rename token shouldn't have been marked as used anyway if it was a 404? idk).

I did see that /rename/ now 404s, when both /rename and /rename/ should have worked. Is it at all possible that they saw the 404 error message and assumed that that meant they had no tokens left?

**Comment by pauamma** [comment]
I'm not seeing a codepath where this might happen either. Can we see whether we still get complaints following https://github.com/dreamwidth/dw-free/commit/a6d9a2ed259caf4e92ef62ae0242f21517adec32 ?

**Comment by rahaeli** [comment]
No, it wasn't user error -- I tried using the token directly myself and got the same thing. But sure, I'll see if I get any more reports.

**Comment by afuna** [comment]
Hmmmmm. Okay one other possibility, is it possible that rename tokens
bought before the code push have the problem, and rename tokens bought
after don't?


On Wed, Jan 21, 2015, at 04:15 AM, Denise Paolucci wrote:
> No, it wasn't user error -- I tried using the token directly myself
> and got the same thing. But sure, I'll see if I get any more reports.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1132#issuecomment-70724616

**Comment by rahaeli** [comment]
One of the ones did say they'd just bought it, sadly! (I thought the same thing.)

**Comment by pauamma** [comment]
OK, some questions:
- What are the IDs of the tokens that users complained about, saying they were incorrectly reported as applied?
- Of those, which (if you know) were bought before/during/after the push?
- Did any/all the replacement tokens you issued work for renaming?
- Which action (such as revoking), if any, did you perform on the replaced tokens?
- Did it work?
- Were there any other successful renamings since the push (if you have that info)?

**Comment by rahaeli** [comment]
No new reports of this in the past week, closing. Looks like restarting the workers fixed it.
