### ISSUE TITLE
HTTPS: embedded.dreamwidth.net is not covered by *.dreamwidth.org

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1133]
I was scrolling through [Latest Things](https://www.dreamwidth.org/latest) and as I passed by [a particular post](http://mysliwiec.dreamwidth.org/1855564.html) I saw that the embedded videos would not display in Firefox. This is also true if I directly go to [that post via HTTPS](https://mysliwiec.dreamwidth.org/1855564.html). In each frame(?) that would be displaying the YouTube video, I instead see a Firefox warning:

> This Connection is Untrusted

> You have asked Firefox to connect securely to embedded.dreamwidth.net, but we can't confirm that your connection is secure.

> Normally, when you try to connect securely, sites will present trusted identification to prove that you are going to the right place. However, this site's identity can't be verified....

> Details: embedded.dreamwidth.net uses an invalid security certificate. The certificate is only valid for the following names: *.dreamwidth.org, dreamwidth.org (Error code: ssl_error_bad_cert_domain)

**Comment by afuna** [comment]
@zorkian figure you're the one most up on this

**Comment by zorkian** [comment]
SNI is cool. SSL is now supported on embedded.dreamwidth.net.

**Comment by zorkian** [comment]
@afuna I'll say it still doesn't work, though, because the response we're giving is an `iframe` that contains an HTTP link to YouTube.

**Comment by afuna** [comment]
@zorkian I’ll open a bug for that then and figure out how to deal with
it. Thanks!


On Fri, Feb 13, 2015, at 04:53 PM, Mark Smith wrote:
> @afuna[1] I'll say it still doesn't work, though, because the response
> we're giving is an iframe that contains an HTTP link to YouTube.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/afuna
  2. https://github.com/dreamwidth/dw-free/issues/1133#issuecomment-74352729
