### ISSUE TITLE
Fix mixed content issues with URLs generated in S2

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1134]
Problem: S2 caches IMGROOT, etc urls. But on http pages, these should be http://.. and on https pages these should be https.

We tried a quick fix using protocol-relative links, but this broke DW-hosted mood themes, icons in emails, etc.

So we need to do this a better way!

**Comment by kareila** [comment]
This didn't auto-close for some reason. Fixed in PR 1145.
