### ISSUE TITLE
Remove blank space after tag and before comma in lists without tag arrows

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1138]
When you look at tags, there's a blank space before the comma on journal pages without arrows, which didn't use to be there before. Any page, any style. See http://dw-dev.dreamwidth.org/ for example.

**Comment by afuna** [comment]
this should be a relatively quick fix but going to try this after we figure out #1126 so that we don't fix it here then reintroduce it there

**Comment by afuna** [comment]
On second thought might as well do this now :)
