### ISSUE TITLE
investigate mixed content issues in /latest

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1150]
Need to check that we're proxying images, etc, from entries in here.

**Comment by afuna** [comment]
Need to check this after next code push, because we've made https proxying more universal now.

**Comment by afuna** [comment]
Nope not fixed.

**Comment by afuna** [comment]
Sudden thought: maybe we need to restart the latest feed worker? need to check the code to see if that makes a difference.

**Comment by afuna** [comment]
Oh, I know what this is now. We memcache the page content so we're seeing the http version of the page from someone else's previous page load. This should go away five minutes or so after we switch the entire website to HTTPS.

Leaving open so I remember to double-check and confirm.

**Comment by rahaeli** [comment]
Yes, this did start working two years ago after the memcache expired. ;)
