### ISSUE TITLE
Quicker Reply not working in Database

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1154]
Database has custom code for the reply link because it uses an image instead of text. Doesn't seem like it was updated to work with Quicker Reply. This may be true of other styles but I don't think there are others doing this. Worth checking, though.

**Comment by afuna** [comment]
Based on the code -- only Database overrides Entry::print_interaction_links and CommentInfo::print which are the two places that need to be changed, so I think we're good!
