### ISSUE TITLE
Tweaks to header for Foundation pages

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1174]
![7223576](https://cloud.githubusercontent.com/assets/1716035/5969379/e6b7be92-a7f0-11e4-82c9-d405c8aac59a.png)

Tiny things that are irrationally bugging me about this header: 

* the font of the post/reading/inbox/etc action links is about 2pt too large;
* the logout button is not flush with the bottom of the username so it looks askew;
* the combined line-height of the username + action links is so tall that it makes the logo look undersized (the two should be roughly the same height).

**Comment by afuna** [comment]
![screen shot 2015-02-06 at 12 27 00 pm](https://cloud.githubusercontent.com/assets/364169/6087040/8eab200c-adfb-11e4-9b9e-a2b92d833313.png)

**Comment by rahaeli** [comment]
Thumbs up!

**Comment by afuna** [comment]
Ah I guess i just figured out what needs to be done  to link a pull request to an issue: need to make sure to have the issue number in the body of the pull request (not just the title).
