### ISSUE TITLE
Typo in /editicons

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1179]
http://www.dreamwidth.org/support/see_request?id=30321:
When uploading an icon with no keyword: "We strongly *recommand* that you assign keywords to your icons before using them."

**Comment by rahaeli** [comment]
Fixed on the site, just needs to be fixed in code now.

**Comment by afuna** [comment]
Didn't bother to do the label2 etc, under the assumption that my change reflects what's live on the site exactly so no need to force it.

**Comment by rahaeli** [comment]
Sounds good to me!
