### ISSUE TITLE
Inconsistent behavior between htdocs/admin/fileedit/index.bml and ljlib.pl

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#1188]
htdocs/admin/fileedit/index.bml looks for files in: $LJ::BML_INC_DIR_ADMIN || $LJ::BML_INC_DIR || "$LJ::HTDOCS/inc". However, the sub in ljlib.pl that retrieves files to display (load_include) loads from $LJ::HOME/htdocs/inc, and likewise for bin/upgrading/import-includes.pl. Those should be made consistent.

**Comment by kareila** [comment]
Looks like $LJ::HTDOCS is set to $LJ::HOME/htdocs by default, so it would only make a difference if someone wanted to change $LJ::HTDOCS.  That's probably the better variable to use.
