### ISSUE TITLE
"Task no longer known to Gearman" timeouts randomly on payments

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1189]
This has been going on for absolutely ages, but I never actually opened an issue for it. @zorkian and @afuna have done some poking at it, but nothing's worked so far. (Maybe y'all could enumerate what you tried already?)

Frequency comes and goes -- anywhere from "fifteen days between reports" to "five or six times a week" over the three months I was keeping careful count of the reports.

**Comment by afuna** [comment]
Mmph I don't remember what we tried. Maybe something about closing the DB connection in between requests?

**Comment by rahaeli** [comment]
Yeah, I believe the last effort was clearing the DB connection right before each attempt. (I went looking through the usual suspects for the discussion, but I can't find it in -staff, -lounge, or -issues.) That worked to the point where now when the phantom cart happens, it's a total failure instead of the former half-failure state (where the charge would be run through payment processor, and be applied to the CC, but not credit the account with the paid time) -- now it at least fails before it gets to the payment procesor part. 

Which is definitely progress, since it doesn't result in charges being run on the card but not credited to the account, but it is obviously Less Than Optimal!

**Comment by rahaeli** [comment]
This seems to have been FIXEDBYPROXY by something else!
