### ISSUE TITLE
design: secondary (gray) buttons on gray backgrounds

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1192]
For example, the browse buttons in /entry/new.

Trying to figure out what's best here. They definitely fade in too much, but I don't want to make them the same bright primary color as the other buttons. Ideally they'd be neutral still but distinct.

**Comment by afuna** [comment]
choices~

* darken
* lighten
* apply COLOR THEORY

**Comment by rahaeli** [comment]
hmmmmmm

lighten to the bg color?

**Comment by afuna** [comment]
Hmmm okay tried that. This is how it looks originally:

![screen shot 2015-02-05 at 9 51 04 pm](https://cloud.githubusercontent.com/assets/364169/6075126/66e2ef48-ad81-11e4-9b24-9d4a739e411e.png)

Here are a couple variations of it lightened:
![screen shot 2015-02-05 at 9 51 18 pm](https://cloud.githubusercontent.com/assets/364169/6075125/66e2e6f6-ad81-11e4-9099-bcc6c484cfa6.png)

![screen shot 2015-02-05 at 9 50 51 pm](https://cloud.githubusercontent.com/assets/364169/6075124/66e2acae-ad81-11e4-936f-b509782a2ca4.png)

Not shown: a bunch of experiments with tinting the button with the primary color; none of them were particularly good.

**Comment by rahaeli** [comment]
I like the bottom-most best! (In general I am in favor of anything that puts shadows in; Foundation in general looks 'flat' to me and this really helps.)

**Comment by afuna** [comment]
Going with this then! Now live on the site. I keep changing my mind over whether it's a good fit :)

**Comment by rahaeli** [comment]
Oh, they look great.

**Comment by afuna** [comment]
*salutes*
