### ISSUE TITLE
/manage/circle/editfilters doesn't doublecheck that accounts are still trusted at time of saving, only time of loading

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1208]
and therefore, editing filters can re-add access to someone who'd had it revoked in edge cases with multiple tabs at once.

1) Have someone (we'll call them 'username' for the purposes of this bug) in your circle, with access.

2) Open a tab to manage your access filters -- http://www.dreamwidth.org/manage/circle/editfilters . Make a few changes to your filters, but don't save. (I'm not sure if 'username' needs to be moved into or out of a filter or not. I tested-to-reproduce with moving the account out of a filter.)

3) Still without saving, open another tab to 'username''s journal and remove access by using the hover menu or the navstrip -- anything that will get you to /circle/username/edit using the 'revoke access' button on that page.

4) Go back to the unsaved /manage/circle/editfilters. Save.

5) 'username' will be re-granted access when the filters are saved.

Solution: when saving the form, doublecheck that account is still trusted and we're only changing the groupmask before calling add_edge.

**Comment by chrisboyle** [comment]
claim
