### ISSUE TITLE
embedded iframes: mixed content issue

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1213]
When a video / embed uses http instead of https, we'll run into mixed content issues.

So thoughts:

* more popular sites which we know support http, we can rewrite from http -> https 
* less popular sites, placeholder? just live with the mixed content?

We could also try to proxy the videos, but videos are a much bigger space / bandwidth commitment than images so I'm hesitant to start with that!

**Comment by zorkian** [comment]
I don't think proxying would work for videos, given our current proxy
solution involves local caching. We'd have to download the videos, which
would be rough.

Don't we only allow embedding certain content? We can make sure they
support HTTPS and just rewrite them?

--
Mark Smith mark@qq.is


On Fri, Feb 13, 2015, at 05:34 PM, Afuna wrote:
> When a video / embed uses http instead of https, we'll run into mixed
> content issues.


> So thoughts:


>  * more popular sites which we know support http, we can rewrite from
>    http -> https
>  * less popular sites, placeholder? just live with the mixed content?
>    We could also try to proxy the videos, but videos are a much bigger
>    space / bandwidth commitment than images so I'm hesitant to start
>    with that!


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1213

**Comment by afuna** [comment]
Sure, so the first bullet point, but applied to everything we whitelist?
that sounds doable.


On Fri, Feb 13, 2015, at 05:41 PM, Mark Smith wrote:
>
>
I don't think proxying would work for videos, given our current proxy
>
solution involves local caching. We'd have to download the videos, which
>
would be rough.
>
>
Don't we only allow embedding certain content? We can make sure they
>
support HTTPS and just rewrite them?
>
>
--
>
Mark Smith mark@qq.is
>
>
>
On Fri, Feb 13, 2015, at 05:34 PM, Afuna wrote:
>
> When a video / embed uses http instead of https, we'll run into mixed
>
> content issues.
>
>
>
> So thoughts:
>
>
>
>  * more popular sites which we know support http, we can rewrite from
>
>    http -> https
>
>  * less popular sites, placeholder? just live with the mixed content?
>
>    We could also try to proxy the videos, but videos are a much bigger
>
>    space / bandwidth commitment than images so I'm hesitant to start
>
>    with that!
>
>
>
> — Reply to this email directly or view it on GitHub[1].
>
>
>
>
>
>
>
Links:
>
>
  1. https://github.com/dreamwidth/dw-free/issues/1213
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  2. https://github.com/dreamwidth/dw-free/issues/1213#issuecomment-74355479
