### ISSUE TITLE
t/atom-post.t is broken

### ISSUE THREAD

**Issue by anall** [dreamwidth/dw-free#1219]
I have been fixing ALL the tests after the move to a separate test DB.

However, this seems like code-break, not test-break.

**Comment by kareila** [comment]
It's actually config-break.  Everything is fine if you put `$LJ::ONLY_USER_VHOSTS = 1;` somewhere.

My first instinct was to add it to the test since the test breaks without it, but it probably belongs in config-test.pl instead?

**Comment by afuna** [comment]
Hmmmm yes that is the right place for it

**Comment by kareila** [comment]
Yep, that's what's in the PR.
