### ISSUE TITLE
Site skinned comment pages claim UTC at all times, even when inappropriate

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1222]
Site skinned comment pages claim the entry was posted in UTC even when the user has selected a timezone. 

Displaying the user's timezone (if set) would be an excellent life choice.

**Comment by azurelunatic** [comment]
Likely pages involved: 

dw-free/htdocs/stc/entrypage.css
dw-free/htdocs/stc/replypage.css

**Comment by ninetyd** [comment]
Possibly related: http://dw-suggestions.dreamwidth.org/1362037.html (can't remember if this is on any page or just comment ones).

**Comment by kareila** [comment]
It appears that LJ::S2::sitescheme_secs_to_iso has the same bug but since it's only used in comment preview, it is less likely to be noticed.  (The bug, in both cases, being that the entry's eventtime claims to be UTC, even though it's almost always the poster's local time.)

I... don't know if this can really be fixed.  Reading pages avoid the problem by not displaying time zones at all.  We could make a guess based on the poster's chosen timezone, but it will not always match.

**Comment by afuna** [comment]
Could we just avoid showing timezones completely?

**Comment by zorkian** [comment]
Showing timezones is best practice, as long as it's correct. If it's
wrong, then not showing at all would be OK, but that seems a less
optimal direction to go. Don't we have the data?

--
Mark Smith mark@qq.is


On Tue, Feb 17, 2015, at 05:04 PM, Afuna wrote:
>
>
Could we just avoid showing timezones completely?
>
> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1222#issuecomment-74790728

**Comment by kareila** [comment]
I don't believe we have the data.  The event time is whatever the user says it is.  It could be the logtime in a different time zone, or it could be ten years in the past, or it could be in the year 2037.  We don't ask for a timezone when the entry is posted.  I think we have to either not display a timezone (which is the solution used elsewhere) or use the logtime converted to the viewer's preferred timezone (which is what comments do).

**Comment by zorkian** [comment]
Oh, I'm sorry, the subject says "comment", so I assumed it meant
comments. When it comes to entries we definitely don't have tz data
that's for sure. :(

I think not displaying is probably reasonable, unless we want to
deprecate "selecting a time" (which is probably not a good idea).

--
Mark Smith mark@qq.is


On Tue, Feb 17, 2015, at 05:50 PM, Jen wrote:
> I don't believe we have the data. The event time is whatever the user
> says it is. It could be the logtime in a different time zone, or it
> could be ten years in the past, or it could be in the year 2037. We
> don't ask for a timezone when the entry is posted. I think we have to
> either not display a timezone (which is the solution used elsewhere)
> or use the logtime converted to the viewer's preferred timezone (which
> is what comments do).


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1222#issuecomment-74796117
