### ISSUE TITLE
Add an "are you sure?" dialog to the ban user process

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1227]
From http://dw-suggestions.dreamwidth.org/1414165.html

> Right now, it is easy to hit "Ban User" unintentionally and not know it. A dialog asking if you're sure would be helpful.

**Comment by woggy** [comment]
This is already live on the site - https://github.com/dreamwidth/dw-free/pull/501

**Comment by afuna** [comment]
Thanks for letting us know!
