### ISSUE TITLE
Allow "Use the time when entry is posted" to be set as default

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1229]
From http://dw-suggestions.dreamwidth.org/1394378.html

>Allow "Use the time when entry is posted" to be set as default when posting entries.

**Comment by afuna** [comment]
I believe that the easiest way to do this is to remember last state of the checkbox.

**Comment by rahaeli** [comment]
Implement as "remember the last state of the checkbox", not as a new preference, please!
