### ISSUE TITLE
Make the landing page after you post an entry be more useful

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1231]
From http://dw-suggestions.dreamwidth.org/1361214.html:

> The landing page after a user posts an entry should have more information on it.

**Comment by woggy** [comment]
@rahaeli I have a branch for this that adds the security status, but am being mildly confused by the dw-suggestions post and am not sure what else, if anything, I should add.

(also, um, starting to get a bit anxious about the 1 Jun OSB deadline and if the branch-as-stands is Good Enough I can work on one of my other Open Bugs. <.<)

**Comment by rahaeli** [comment]
Go work on other things! 

The suggestions post also asked for post title, icon keyword, and tags. I'm on the fence about icon keyword and tags since discussion in the comments was split, but it should also include post title if any.
