### ISSUE TITLE
audit all uses of "http:" 

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1246]
Example: redirecting to another page if the URL does not check out (where we mistakenly redirect because we're only checking for "http://" instead of "https?://"

**Comment by afuna** [comment]
Otherwise we get into hilarious cases like trying to access /profile doing an infinite redirect loop.

**Comment by rahaeli** [comment]
ahahahaha that sounds like the tiny despairing voice of "....but why is that HAPPENING?" speaking

**Comment by afuna** [comment]
Noting here that I've also looked at the $*font_sources (which have as values external stylesheet urls) and these are all fine because they go through the cssproxy.
