### ISSUE TITLE
Turn on $LJ::CONCAT_RES_SSL

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1251]
So that we're not negotiating a new connection for every JS/CSS file and slowing everything down.

Note: this isn't as simple as toggling the config, because http://www.dreamwidth.org/stc/??widgets/quickupdate.css,widgets/latestinbox.css,widgets/friendbirthdays.css,widgets/communitymanagement.css,widgets/currenttheme.css?v=1348362434 returns blank.

**Comment by zorkian** [comment]
Oh I know why

--
Mark Smith mark@qq.is


On Wed, Feb 25, 2015, at 10:38 PM, Afuna wrote:
> So that we're not negotiating a new connection for every JS/CSS file
> and slowing everything down.


> Note: this isn't as simple as toggling the config, because
>       http://www.dreamwidth.org/stc/??widgets/quickupdate.css,widgets/latestinbox.css,widgets/friendbirthdays.css,widgets/communitymanagement.css,widgets/currenttheme.css?v=1348362434
>       returns blank.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1251

**Comment by zorkian** [comment]
Fixed

--
Mark Smith mark@qq.is


On Wed, Feb 25, 2015, at 10:46 PM, Mark Smith wrote:
> Oh I know why
>
> --
> Mark Smith mark@qq.is
>
>
> On Wed, Feb 25, 2015, at 10:38 PM, Afuna wrote:
>> So that we're not negotiating a new connection for every JS/CSS file
>> and slowing everything down.


>> Note: this isn't as simple as toggling the config, because
>>       http://www.dreamwidth.org/stc/??widgets/quickupdate.css,widgets/latestinbox.css,widgets/friendbirthdays.css,widgets/communitymanagement.css,widgets/currenttheme.css?v=1348362434
>>       returns blank.


>> — Reply to this email directly or view it on GitHub[1].

>>
>


Links:

  1. https://github.com/dreamwidth/dw-free/issues/1251

**Comment by afuna** [comment]
Soooo what did you do?

I’m guessing it had to do with us using perlbal for the concatenated
files. is nginx handling concatenation now, or is it just serving the
request up to perlbal?

**Comment by zorkian** [comment]
We had two flows for traffic, and the SSL flow didn't go through the same static content path. It would pass all requests to the backend directly, which would bypass Perlbal's ability to concatenate files.

This still isn't perfect though, we need to make it so SSL goes through Varnish. At the moment it doesn't, which will end badly if we switch a large part of traffic over to it.

**Comment by zorkian** [comment]
I turned it on.
