### ISSUE TITLE
missing text in country list on stats page

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1252]
I just noticed that on the stats page (http://www.dreamwidth.org/stats) under "Demographics" we have a list of the top 15 countries our users are affiliated with.  The second line down has no text at all, and I'm guessing it ought to correspond to the UK, given that I don't see that country anywhere else in the list.  Did the text somehow get zapped when we recently changed our source of country data?

![screen shot 2015-02-26 at 9 31 26 am](https://cloud.githubusercontent.com/assets/1976742/6394962/c3070dda-bd9a-11e4-8097-c8c04dcc571b.png)

**Comment by afuna** [comment]
you're right -- it looks like we store it as UK while the new countries list uses GB.
