### ISSUE TITLE
missing left border on post destination if spilled over (create entries beta)

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1258]
User info:

http://dw-beta.dreamwidth.org/14352.html?thread=435216#cmt435216

Firefox 36.0 / Windows 7 / 23" monitor / browser size 1473x920.

Looks like something is eating the left border on the "post destination" element once it spills over. Doesn't do that for me in Chrome, does do it in Firefox.

**Comment by afuna** [comment]
argh. but when they're side by side and there's a doubled link it just looks clunky.

ponder

**Comment by rahaeli** [comment]
Yeah, I was going to tell the user "it's because if there's a double border it looks weird", but  then I saw that in Chrome when things spill over, there IS a left border. So I figured there might be a browser bug.

**Comment by afuna** [comment]
Hmm, but in chrome there isn't, at least not in my version.

Browsers :(

**Comment by afuna** [comment]
It might be a small versus medium screen thing, with the medium screen
lack of border kicking in when we have the sidebar.

Anyway, I’ll go check it out.


On Fri, Feb 27, 2015, at 03:15 PM, Denise Paolucci wrote:
> Yeah, I was going to tell the user "it's because if there's a double
> border it looks weird", but then I saw that in Chrome when things
> spill over, there IS a left border. So I figured there might be a
> browser bug. — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1258#issuecomment-76490783

**Comment by rahaeli** [comment]
![create entries](https://cloud.githubusercontent.com/assets/1716035/6422983/41618efe-bead-11e4-915e-f92fd881b12d.png)

Browsers :(

That's Chrome 39.0.2171.99 (slightly out of date but I don't relaunch Chrome frequently) on OSX 10.8.5.
