### ISSUE TITLE
Move t/config-test.pl to ext/local/etc

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#1264]
The checked-in version isn't appropriate for dreamhacks and needs to be modified without polluting diffs. The easiest fix is to move it alongside other config files.

**Comment by afuna** [comment]
Had a sudden thought. Would ext/local/t work to override?

**Comment by pauamma** [comment]
Maybe? But I can't help thinking that having an overridable-configuration for tests would be more than we need?

**Comment by afuna** [comment]
Hmmm but ext/local/etc is not under our control, in the same way that ext/local/t wouldn't be so I'm not sure there's much difference here.

**Comment by Sophira** [comment]
I'm sorry; this whole thing is basically my fault. I said in #931 that I would create test databases for Dreamhack users to use and I haven't done that yet. I've been meaning to do so.

I can get that sorted in the next few days, if that helps any!

**Comment by afuna** [comment]
No that's fine, it's something we have to figure out anyway!

Is there anything we need to do to make it flexible? Do you want separate test dbs for each 'hack user? 

Maybe a t/config-private which only covers the database credentials so we don't need to override the whole file?
