### ISSUE TITLE
add German-language headers to the reply-by-email cleaner

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1277]
http://www.dreamwidth.org/support/see_request?id=30429

German-language email headers aren't being stripped by the "strip headers and quoted text" check in reply-by-email. From the screenshot, looks like the things to filter on are "Von:", "An:", "Gesendet", and "Betreff". (Or, for best futureproofing, maybe strip anything after 'Username - DW comment &lt;dw-null@dreamwidth.org>' -- I think that's the same in any language, right?)

**Comment by afuna** [comment]
Technically, no. But we don't really translate DW so that'll work for us.

**Comment by afuna** [comment]
Hmmm. How about if I just match on `<dw-null@dreamwidth.org>`?

**Comment by rahaeli** [comment]
That seems like it would work best, since it comes before the reply-to address (which is the biggest concern in not stripping quoted text -- that the reply-to will be quoted, and thus the token exposed).
