### ISSUE TITLE
banning a user does not remove them from your profile

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1279]
Expected behavior (ie, the way LJ does it and the way I thought we did it too): when you ban a user from your journal, that account should no longer appear on your Subscribers/Has Access From lists.

Actual behavior: account still appears on your profile.

(This shouldn't affect the banned user's profile -- that is to say, if I susbcribe to Alice, and she bans me from her journal, my name should not appear on Alice's profile under 'Subscribers', but Alice's name should still appear on my profile as one of my subscriptions.)

**Comment by kareila** [comment]
Claiming

**Comment by kaberett** [comment]
Yo Jen, if you're not super-invested in this one is there any chance I could nab it from you? I would find it Quite Cathartic for reasons and have some time I could spend on it this weekend ("no" is of course fine!).

**Comment by kareila** [comment]
Sure, I just figured I could do it quickly since I'm familiar with that code, but if you want first crack at it be my guest :)

**Comment by ninetyd** [comment]
Related: http://dw-suggestions.dreamwidth.org/485089.html

**Comment by ninetyd** [comment]
Also pretty sure this was a bug in Zilla somebody was working on or worked on at some point, possibly you, D, so there might so useful implementation notes.

**Comment by kareila** [comment]
You're right, @ninetyd, it was bug 3499.  There was a patch submitted by @rahaeli which wasn't fully functional.  Unfortunately, the email archives from Bugzilla don't include the submitted patches, but I can put up a copy of the surviving comments somewhere if that's helpful.
