### ISSUE TITLE
convert journal search page from BML to TT

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1284]
This conversion doesn't look difficult, but setting up a working test environment for Sphinx on a dreamhack might be...

**Comment by afuna** [comment]
Yeah. If it was simply a matter of changing the appearance, I'd be happy enough with mock data. (As it is, it may be reasonable to mock data most of the way through the conversion anyway).

**Comment by zorkian** [comment]
+1 to using fake data to prove out the UI. Setting up the whole search system is... entertaining at best.
