### ISSUE TITLE
while browsing DW over HTTPS, journal profile, permalink, reply, etc. links are HTTP

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1289]
I am at (as an example) visiting the page https://ursula.dreamwidth.org/ .

As I look at the user's journal, some of the links are HTTP and others are HTTPS.  I go to click on the user's profile link -- it's http://ursula.dreamwidth.org/profile (instead of an HTTPS link), but the Tags link is https://ursula.dreamwidth.org/tag/ . Reply and permalink links for individual entries are plain HTTP, no SSL, but Add Memory and Share This Entry are HTTPS. If you would like I'll do a search through View Source to give you a more complete list (sanitized of course to remove friends-locked/private stuff). This all seems to be the case whether I'm logged into DW or not.

If I am logged in to Dreamwidth: Some of the links in my top navbar are HTTPS links - Home, Post, Settings, Inbox, Add to Your Circle, Track Account, https://www.dreamwidth.org/editicons (the link on the image of my avatar). But Reading, the "ursula" link telling me about whether that user and I grant each other access/subscribe to each other, and "mine" and "light" ("Reload page in style") are all in HTTP.

I suggest that, to reduce this kind of inconsistency, DW use protocol-relative links throughout. But I'm totally willing to be told this is the wrong approach!

May be related to #1150.

**Comment by kareila** [comment]
I think we caught most of these already, but the fixes won't be live on the site until after the next code push, which will probably happen this coming weekend.  If you could check again after that to see if we missed anything, that would be great!  Thanks :)

**Comment by afuna** [comment]
Should be fixed by now, thanks for letting us know!
