### ISSUE TITLE
Create Entries beta getting Unicode boxes instead of icons in Firefox

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1290]
see:
http://dw-beta.dreamwidth.org/14352.html?thread=436752#cmt436752
http://dw-beta.dreamwidth.org/14352.html?thread=437008#cmt437008 (has screenshots)

**Comment by afuna** [comment]
Should be fixed by a combination of #1268 and #1267.

**Comment by afuna** [comment]
Hmm, going to close this since #1268 is done and #1267 can have that work done there.
