### ISSUE TITLE
?mode=reply has discrepancies in HTML cleaning

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1294]
Issue #1221 added <span> to the list of HTML that's stripped in anon comments (to stop pagebreaking trolling). After the code push, though, the ?mode=reply view (reached by doing an open-in-new-tab on the 'Reply' link for the comment), the span is still there.

I seem to remember this being a problem with auto-linkifying as well -- with ?mode=reply autolinking links in anon comments, while the standard view didn't -- so I'm wondering if something's going on with that being run through a different path in the cleaner? we should clean that up.

**Comment by kareila** [comment]
This didn't automatically close for some reason.
