### ISSUE TITLE
Inconsistent userpic height on beta update page causes UI bouncing with random icons

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1299]
So if you're like me, you may like to spin the random userpic button a few times on the Create Entry page. If you're like me, you may also have icons which aren't the full 100x100 allowed size. 

The placement of the random icon button depends on the height of the userpic. Thus the button moves based on the size of the thing. Which means you have to play hunt-the-button if you're a mouse user. 

There should probably be a 100x100 space reserved for the userpic even if it doesn't take up all that space, to reduce the obnoxious jiggling when randomizing the userpic repeatedly.

**Comment by chrisboyle** [comment]
claim
