### ISSUE TITLE
Create Entries beta: Custom filters doesn't work in lynx site skin, posts entry privately

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1304]
I've been seeing people reference this here and there and could never reproduce it, but somebody FINALLY told me that they were using the lynx site skin when it happened and now I've got it:

* Set site skin to lynx
* Go to Create Entries beta
* Choose 'custom filtered' for posting security in the drop down

Expected: you should see a lightbox prompting you to choose details of the filter. Actual: nothing happens, and when the entry's posted, it's posted privately. (I'm guessing it's actually 'custom filtered, filter set to nothing, icon gets the private icon', but I can't be sure.)

**Comment by afuna** [comment]
Oh good detective work!

**Comment by rahaeli** [comment]
I just feel so much better that we've finally figured out a way to reproduce it! I kept seeing people mention it but never made the connection...
