### ISSUE TITLE
quicker reply not working 

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1305]
Got a report in dw-maint for this, and I noticed I'm getting it myself: quickerreply is no longer working in Chrome. (On Mac, at least.) It is working in Firefox and Safari.

(Current version of Chrome,  41.0.2272.89 (64-bit).)

**Comment by rahaeli** [comment]
Nevermind! User error, I always forget we only implemented that on reading page. Okay, I'll chalk it up to the user having the problem that we fixed with JS not loading.

**Comment by afuna** [comment]
If we ever want it other than the reading page just let me know!

**Comment by rahaeli** [comment]
Thinking about it, yeah, let's do that! I opened a bug.
