### ISSUE TITLE
spamreports by IP does not recognize IPv6 IPs

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1315]
We're getting IPv6 IPs now, and /admin/spamreports by IP doesn't recognize 'em; it gives a "No such IP" error when you try to load the "by IP" view (eg, http://www.dreamwidth.org/admin/spamreports?mode=view&by=ip&what=2001:db8:0:1&state=open ) (IP replaced by an example IP).

**Comment by zorkian** [comment]
Wait, how the heck are we getting IPv6 IPs? This will cause a lot of trouble.

**Comment by rahaeli** [comment]
I don't know, I thought it was deliberate! I've been seeing them since at least our last code push.

**Comment by alierak** [comment]
Cloudflare is my conclusion as well.

**Comment by pauamma** [comment]
So I guess the first question is: do we want to do IPv6 now or at all, through CF or otherwise?

**Comment by zorkian** [comment]
Well we don't have much choice if CF is giving it to us. Or, well, I
suppose our choices are:

1. Plumb IPv6 support (ouch, but ultimately, the right decision)

2. Put in some hook in Apache::LiveJournal that sees IPv6 and converts
   them to some RFC1918 address like 10.x and then store the IPv6 in
   some database table, then we can fix the display layer in a few
   places to show the IPv6 but still internally store them as unique
   IPv4s (this assumes we don't get more than 24 bits of IPv6
   addresses... I know, a bad assumption, but probably true for a while)

--
Mark Smith mark@qq.is


On Sun, Mar 29, 2015, at 01:10 PM, Pau Amma wrote:
> So I guess the first question is: do we want to do IPv6 now or at all,
> through CF or otherwise?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1315#issuecomment-87467558

**Comment by rahaeli** [comment]
What's involved in 1? 2 seems like a lot of work for something that is not futureproof...

**Comment by pauamma** [comment]
Comment IP address display already works fine, judging by http://www.dreamwidth.org/support/see_request?id=30590

**Comment by azurelunatic** [comment]
We're up to 5 stuck open, which is somewhat distressing to spamwhackers.

**Comment by kareila** [comment]
The IP address field in the spamreports table is limited to 15 characters, which means the IPv6 addresses in the existing reports are truncated and thus useless.

If we remove or somehow modify the error check on line 245 of spamreports.bml, we ought to be able to at least load the page and close the bogus reports, but going forward we need to widen the field in the database in order to capture the full IP.
