### ISSUE TITLE
label bot does not clear "status: claimed" when an issue is unassigned

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1322]
Is it possible to monitor for this? I just cleaned out a bunch of these by hand.

**Comment by me-and** [comment]
Claimed

**Comment by kareila** [comment]
To be clear, @me-and, I'm not sure the API fires an event when the unassignment happens. If not, we can't trigger the action.

**Comment by me-and** [comment]
@kareila from looking at the API documentation, I'm pretty sure it does.

Even if it doesn't, I'm doing a bunch of work as part of this to remove dead code in the script, which should improve maintainability.

**Comment by afuna** [comment]
It didn't when we were investigating this long ago, but they've since added new actions which might be relevant.

**Comment by kareila** [comment]
:+1:

**Comment by afuna** [comment]
Ps if you're touching the bot I suggest the Python version rather than perl. Want to rip out that one soon.

**Comment by kareila** [comment]
Did we give the Python version all the features that the existing had? Is there any non-overlap of features we need to be aware of?

Btw the Python version is located at @afuna/ghi-assist

**Comment by me-and** [comment]
Right, okay. I shall go poking the Python version then :)

**Comment by afuna** [comment]
The Python version has all the same features; I think I fixed a couple edge cases while transferring over too.

**Comment by me-and** [comment]
This should be addressed by afuna/ghi-assist#22. I don't have a suitable setup to test this -- I suspect @afuna is better set up to do any testing required -- but I can try to create a test setup myself if needed.

**Comment by me-and** [comment]
...wait, there's a bunch of tests here. Let me go add one of those.

**Comment by me-and** [comment]
@afuna I've written some a test script in the associated pull request that looks similar to the existing test scripts, but just running these scripts doesn't actually test anything. How do I run these tests in a useful fashion?

**Comment by afuna** [comment]
Try py.test -- might need to install the prereqs under
requirements.txt first.


On Wed, Jun 24, 2015, at 08:00 PM, Adam Dinwoodie wrote:
> @afuna[1] I've written some a test script in the associated pull
> request that looks similar to the existing test scripts, but just
> running these scripts doesn't actually test anything. How do I run
> these tests in a useful fashion?


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/afuna
  2. https://github.com/dreamwidth/dw-free/issues/1322#issuecomment-115085496

**Comment by me-and** [comment]
Tests added! Pull request good to go.
