### ISSUE TITLE
"list-style-position: inside;" breaks list display in markdown

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1324]
Tabula Rasa uses this:

/* To prevent overlapping when icon's on the left */
/* and list is the first thing in content */
.entry-content li,
.comment-content li {
    list-style-position: inside;
    }

If you create an unordered list in markdown with several sub-items, it makes the list not display correctly (the circle's on one line and the text on another). See http://experiment.dreamwidth.org/.

**Comment by momijizukamori** [comment]
claiming - I'll poke at this (and maybe our Markdown implementation)

**Comment by momijizukamori** [comment]
I think this may have been fixed by something else - I'm not able to produce it again.

**Comment by afuna** [comment]
Okay! Closing this. We can reopen if this happens again.

**Comment by momijizukamori** [comment]
http://suitedforit.dreamwidth.org/846.html test entry with nested lists on a TR layour, which looks like it's behaving properly

**Comment by ninetyd** [comment]
Sorry but this is still true for me: https://experiment.dreamwidth.org/. Compare the first entry which uses markdown to the second entry which uses ULs and LIs directly. Is your list in markdown momijizukamori?

**Comment by momijizukamori** [comment]
Yeah, it was. Hmmmm.

**Comment by ninetyd** [comment]
Maybe it has to do with the way one writes markdown. Would you paste your code?

**Comment by momijizukamori** [comment]
'''
!markdown

* one  
    * sub one  
    * sub two  
    * sub three  
* two
* three
* four
'''

**Comment by momijizukamori** [comment]
```
!markdown

* one  
    * sub one  
    * sub two  
    * sub three  
* two
* three
* four
```

**Comment by ninetyd** [comment]
oh this works but the issue happens when you don't have a * for one, two, three, etc. Like if you want a list with bullets only for subitems.

**Comment by ninetyd** [comment]
Nevermind, this was me doing markdown wrong!!

**Comment by momijizukamori** [comment]
Markdown in it's base form is weird and tetchy about line breaks, haha.

**Comment by kareila** [comment]
Thanks for sorting this out :)
