### ISSUE TITLE
http://www.dreamwidth.org/file/edit doesn't work with trailing slash 

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1325]
http://www.dreamwidth.org/file/edit works. http://www.dreamwidth.org/file/edit/ doesn't work. 

h/t to SporkyRat in #dreamwidth

**Comment by rahaeli** [comment]
Hm. I could've sworn we had an issue already open for problems with the trailing slash in TT-ized pages, but I can't find it on a quick look.

**Comment by azurelunatic** [comment]
Was that https://github.com/dreamwidth/dw-free/pull/1293 ?

**Comment by rahaeli** [comment]
Yes! I believe that is the same issue as this, but I'm not closing this, since #1293 should be live on the site now and if it's still not working this might need more attention.

**Comment by afuna** [comment]
#1293 is for fixing redirects in general.

/file/edit/ does not redirect to /file/edit because it’s not a directory
(there’s not expected to be a /file/edit/subpage; it’s the same way
that, e.g., /update/ does not work, or /editjournal/


On Sun, Mar 29, 2015, at 07:11 PM, Denise Paolucci wrote:
> Yes! I believe that is the same issue as this, but I'm not closing
> this, since #1293[1] should be live on the site now and if it's still
> not working this might need more attention.


> — Reply to this email directly or view it on GitHub[2].

>



Links:

  1. https://github.com/dreamwidth/dw-free/pull/1293
  2. https://github.com/dreamwidth/dw-free/issues/1325#issuecomment-87513802

**Comment by rahaeli** [comment]
Hmmmm. I would argue that asking the user to remember whether a page is supposed to have subpages or not is bad user experience and we should just silently redirect in all cases whether there's a trailing slash or not. (So, yeah, /update/ should redirect to /update as well.)

(If we didn't have the mixed trailing-slash-works-on-some-pages-but-not-others case, that'd be different, but having it work in some places but not others is kind of confusing.)

**Comment by anall** [comment]
@afuna I've got smartness for registering `/foo/index` for this exact case. -- Is smart enough to also register `/foo` as a redirect to `/foo/`, and register `/foo/` as an alias of `/foo/index`

@rahaeli I am unsure how much I like this "make it work on pages without subpages", but could be persuaded.

**Comment by afuna** [comment]
I think if we do this it makes sense to just have it work across all URLs instead of on a per-page basis.

**Comment by me-and** [comment]
What's the status of this one now that #1293 has actually been resolved?

**Comment by afuna** [comment]
Separate things! #1293 is about making sure that when we redirect, and
there's multiple redirects (without ending slash to ending slash), we
just do the redirect all at once. This one is about enabling a redirect
from no ending slash to ending slash.


On Thu, Jun 25, 2015, at 11:26 PM, Adam Dinwoodie wrote:
> What's the status of this one now that #1293[1] has actually been
> resolved?


> — Reply to this email directly or view it on GitHub[2].


>



Links:

  1. https://github.com/dreamwidth/dw-free/pull/1293
  2. https://github.com/dreamwidth/dw-free/issues/1325#issuecomment-115540383

**Comment by me-and** [comment]
Cool! I had misunderstood then, and shall keep this on my list of bugs I'm thinking about poking at.
