### ISSUE TITLE
journal search not picking up some results

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1328]
http://www.dreamwidth.org/search?user=synecdochic returns 'no results' searching for 'Mage' (should return at least http://synecdochic.dreamwidth.org/649194.html ) and 'Engine' (should return the same entry); searching for 'djinn' (should return http://synecdochic.dreamwidth.org/652421.html ); searching for 'aziraphale' (should return http://synecdochic.dreamwidth.org/659326.html ), a few others. (Those are all using BPAL perfume names because they're reasonably unique and I could easily ID at least one of the posts they should return.) Ditto searching 'Mondays, every week' (no quotes), which should return the 400 posts tagged 'pride thread' (http://synecdochic.dreamwidth.org/tag/pride+thread). All of them get the "Error: Sorry, we didn't find any matches for the search X. We looked for 15.014 seconds, too!"

Account is a seed account.

I did some searching in various other accounts I control and it looks like it's only that one that isn't being indexed. I can try the "turn it off and turn it back on" method of troubleshooting -- revoke the seed account and reapply it -- no problem, but I figured I should open an issue to see if it was a wider problem with search indexing or something.

**Comment by kareila** [comment]
That's really weird.  My first thought was to make sure the sphinx-copier job is running on whatever machine that account is stored on, but that would explain if only recent posts weren't being indexed.  I can't figure out why none of the posts would be indexed.  I don't think paid status would affect it, since even free users have their content indexed for full site search unless they opt out.

**Comment by rahaeli** [comment]
Maybe I have offended the search gods! IDK, I figured it was better to open a ticket than not ...

**Comment by kareila** [comment]
I agree it's worth investigating, and I have duplicated your lack of results!

**Comment by rahaeli** [comment]
"synecdochic is located on the Epsilon Eridani Cluster."

(just for troubleshooting purposes)

I don't think it's cluster-based, though; don't we only have the one?

**Comment by rahaeli** [comment]
Got a report of this happening in another comm:

http://www.dreamwidth.org/support/see_request?id=30666

**Comment by rahaeli** [comment]
From the request, I asked the user for more examples of stuff that wasn't being picked up for specific search terms:

This thread doesn't mention "Jaime": http://cfud.dreamwidth.org/6879868.html?thread=3521737852#cmt3521737852 

This thread doesn't come up for "Jade" (or "Cesare"): http://cfud.dreamwidth.org/6879868.html?thread=3521711740#cmt3521711740 

"Alphonse": http://cfud.dreamwidth.org/6879868.html?thread=3522294396#cmt3522294396 

"Brianna": http://cfud.dreamwidth.org/6880509.html?thread=3522443005#cmt3522443005

**Comment by kareila** [comment]
We poked at this during the AWS migration and I think we determined that there was no pattern to the failures, and that reindexing the affected user fixes the problem.  I haven't seen any new reports of this since the week after the migration when the indices were still being rebuilt.

**Comment by alierak** [comment]
I vaguely recall fixing a problem with the sphinx config where its queries to select new entries since the last indexer run could have gaps lasting the duration of each indexer run.

**Comment by rahaeli** [comment]
Agree that we haven't seen new reports, and I can find shit in my journal again, so :)

**Comment by kareila** [comment]
I updated the sample Sphinx config on the wiki to look more like the one in production, which presumably includes @alierak's fix.

**Comment by alierak** [comment]
The fix was the introduction of a third counter for the deltas. The part about using ranged queries turned out to be unnecessary (but it does work, so I guess it stays).
