### ISSUE TITLE
admin tool to view user's notification subscriptions

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1330]
Sometimes it would help for troubleshooting to see a user's notifications, the way they'd appear on http://www.dreamwidth.org/manage/settings/?cat=notifications -- it's possible to do so, but only by impersonating them and loading that page, and I feel dirty every time I impersonate someone and would like to minimize the usage as much as possible! Minimum necessary data access, etc.

So, I would like an /admin/subscriptions -- hinged off (a new sub-priv) canview:subscriptions, returns the user's subscriptions in some fashion, including both entries/threads they've subscribed to (the bottom half) and their settings for the checkboxes on the top half. It doesn't have to be an exact duplicate of http://www.dreamwidth.org/manage/settings/?cat=notifications the way the user would see it, but it should contain all the info that page contains.

**Comment by pseudomonas** [comment]
Would a console command be OK, or does this want a GUI?

**Comment by rahaeli** [comment]
Console output is kind of crappy for large amounts of data. 

Thinking about it a bit more, maybe the best way to do this is like manage/logins, where if you have the right priv (I think it's canview:logins but I'm not 100% sure) it gives you a textbox to put a username into and then shows you that page as they'd see it. Doing the same on manage/settings/?cat=notifications would probably be a lot easier. (I don't know why I didn't think of it when I opened the bug.)
