### ISSUE TITLE
add title text for the tagnav image

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1332]
http://www.dreamwidth.org/support/see_request?id=30621 brought up that the tagnav image (the green plus sign that brings up the forward/back arrows) has alt text, but not title text. It would probably be helpful to have title text that describes what to do with the image, for people for whom it isn't intuitive.

Let's say title text of "Tag navigation: select this, then select a tag to browse forward or backward through that tag." (A bit long for title text, but it's the most succinct I can make that explanation!)

**Comment by me-and** [comment]
Claimed
