### ISSUE TITLE
enable Cyrillic in site search

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1334]
http://www.dreamwidth.org/support/see_request?id=29609

We had a bug open for this in Bugzilla, but it went foom: there's something that needs to be done to enable Cyrillic language support in Sphinx, though I'm not sure what it is. (Assigning to Mark as a sysadmin thing and because I remember you knowing what needs to be done, unassign if I'm wrong)

**Comment by kareila** [comment]
Hey @zorkian, if you don't have time to look at this, @alierak has expressed interest in investigating this, assuming he can get Sphinx working in a dev environment.

**Comment by zorkian** [comment]
I'm about to be out of the country for two weeks, so I definitely won't have time before them.

Definitely search problems are usually awkward and frustrating and there's some magic incantation to make it work. We're also running a fairly old version of Sphinx, but upgrading it seemed non-trivial last time I looked.

**Comment by kareila** [comment]
Good to know, thanks. Have a great trip!

**Comment by kareila** [comment]
Got another request for this: http://www.dreamwidth.org/support/see_request?id=32579

**Comment by kareila** [comment]
Relevant comments in #1792 indicating a starting point for a possible fix.

**Comment by kareila** [comment]
Got another request for this: http://www.dreamwidth.org/support/see_request?id=34974

**Comment by srukle** [comment]
Was there any progress made as of yet? I can schedule some hours towards this issue unless someone is actively working on it.

**Comment by alierak** [comment]
No, at this point we’re more likely to swap out the sphinx search system for something else.

**Comment by srukle** [comment]
Sounds like a hefty project. Are there relevant work tickets, or will this be done internally with DW staff?

**Comment by alierak** [comment]
We’re looking at a bunch of upgrades and migrations near the end of this month and will reach a decision about search during that process.

**Comment by alierak** [comment]
Decision is to keep sphinx for now, but we will move it to a new server.

**Comment by kareila** [comment]
We are also going to try installing the most recent version which will hopefully fix some issues.

**Comment by alierak** [comment]
I can't tell whether having Cyrillic support in Sphinx is going to matter or not -- as best I can tell the Search controller / template are munging user input badly enough without even involving the underlying search infrastructure. If you enter a search query, the results page should show it exactly as entered, and that's not what's happening.

**Comment by alierak** [comment]
Click "More Results..." and the query gets mangled even further. Yeah.

**Comment by alierak** [comment]
That said, Sphinx::Search has a SetEncoders method that defaults to using encode_utf8 and decode_utf8 on strings passed from Perl to Sphinx and vice versa. Since we (I think) are already dealing with utf8 byte sequences instead of real Perl strings, we should probably set those to dummy functions that just return their input (sub { shift; }).
