### ISSUE TITLE
can we remove nowrap from navstrip?

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1335]
The center cell of the navstrip, that contains the "you and so-and-so have mutual subscriptions and access" part, is set to nowrap:

<td id='lj_controlstrip_actionlinks' nowrap='nowrap'>

That was a relic of the days before we responsived the navstrip (yes that is a verb) to keep things from getting funky, I think. Can we remove that nowrap now? It forces the third cell onto a second line at smaller screen widths with longer relationships ("you and verylongusername have mutual subscriptions, and verylongusername grants access to you", etc), and I don't see a problem with making longer relationships spill over onto a second line.

('No, we can't remove that nowrap because reasons' is a valid answer here, I just don't think we rethought the nowrap when we responsived it.)

Brought up in http://www.dreamwidth.org/support/see_request?id=29510.

**Comment by pauamma** [comment]
Is this the same as bug 835?

**Comment by kareila** [comment]
@pauamma I think so, with the caveat that #835 mentions removing it on smaller screens and here it is suggested to remove it completely.
