### ISSUE TITLE
Spam reports can't deal with reports about deleted-and-purged users

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1337]
[Error: Can't call method "selectrow_array" on an undefined value at /home/dw/current/cgi-bin/LJ/User.pm line 4352. @ sb-web09.dreamwidth.org] 

Seen in the wild at http://www.dreamwidth.org/admin/spamreports?mode=view&by=posterid&what=2109448&state=open

**Comment by kareila** [comment]
I fixed this in #1318 but the fix isn't live on the site.

**Comment by azurelunatic** [comment]
Yay fix!! <3 <3 <3
