### ISSUE TITLE
payment processor "duplicate transaction" response code not separate from "payment type not supported" response code

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1338]
I _think_ this is -free and not -nonfree, but I'm not 100% sure -- please let me know if I need to move it.

There are several possible failure states for payments. The two most common are:
1. payment type not supported (customer trying to use a CC we don't support or trying to use a debit card that is not also a credit card)
2. customer is trying to make a second payment for an identical amount within a certain range of time (I think I've narrowed it down to ~1 hour) -- most commonly, "buying X months of time for Account X" and then "buying X months of time for Account Y" on two separate transactions instead of as one transaction -- and the payment processor is rejecting the transaction as a possible duplicate.

The error message that both of those failure conditions display to the user is /shop/cart.bml.payment.failed, which only makes reference to situation 1, payment type not supported. This results in a lot of very confused people who ask me "but I know the payment type is supported because I JUST USED IT, why is it failing", and I have to explain situation 2 to them and tell them to chill out for an hour and then try again (oh and next time either do it on the same transaction or buy points and apportion them out).

Ideally, I would love it if we could detect the two different failure modes based on the response code we get from the processor and display a different error message, something like:

> Duplicate transaction
> Our payment processor prevents <a href="http://www.dreamwidth.org/support/faqbrowse?faqid=232">two transactions for the same amount</a> within a short timeframe. This helps to prevent accidental double charges. Please try your payment again in an hour or two. To keep this from happening in the future, you can either upgrade all your accounts in a single transaction, by buying the upgrades for your other accounts as a gift, or you can buy Dreamwidth points for the total amount of the payments you want to make and then transfer them to your other accounts.

If that can't be done, and I'm genuinely not sure if it can be, let me know and I will edit the error message in /shop/cart.bml.payment.failed to be inclusive of that language instead.

**Comment by rahaeli** [comment]
Just noting here that I did go ahead and edit /shop/cart.bml.payment.failed on the live site:

> Your card was declined by our payment processor. Usually, this happens because you just made a payment, and are trying to make another payment for the same amount on the same credit card: our payment processor tries to prevent duplicate charges. If that's what happened, please wait an hour and try again, or add or remove something from your cart so the amount you're charging is different. If you didn't make a payment just now, please try checking out again, making sure that you've entered your address and security code (CVN) correctly. You can also check with your credit card company to make sure they don't think the charge is suspicious. If none of that helps and you still get an error, <a href="https://www.dreamwidth.org/support/submit">submit a support request</a> in the Account Payments category and we'll help you figure out what the problem is.

(I also am tweaking <a href="https://www.dreamwidth.org/support/faqbrowse?faqid=232">FAQ 232</a> to be clearer, and making a new "Why is my credit card being rejected?" FAQ.)

It still would be awesome if we could differentiate the two messages so I can avoid telling people about duplicate transactions when they're being declined for address mismatch or because their credit card company is fraud-flagging the charge, but hopefully those tweaks will help.

**Comment by kareila** [comment]
In order to figure this out, I went digging through the cc_trans table in production, compiling statistics on all the different values for 'responsetext' corresponding to failed jobs.  I'm not going to post the full list here, but "Duplicate transaction" was the clear winner.  So we can definitely return a different error for that one case, and then a more generic message for all other failures.
