### ISSUE TITLE
Mood themes aren't https

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1342]
They need to be run through the proxy I think! Because they break https on read pages ;)

**Comment by anall** [comment]
For the mood themes we host, we should bypass the proxy and use the direct HTTPS url, yes?

**Comment by afuna** [comment]
Yup, but we have logic that detects if we're on the DW host and switches
us over transparently.


On Tue, May 5, 2015, at 03:35 PM, Andrea Nall wrote:
> For the mood themes we host, we should bypass the proxy and use the
> direct HTTPS url, yes?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1342#issuecomment-99251613
