### ISSUE TITLE
Beta update: sticky entry getting unstickied when edited

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1343]
http://www.dreamwidth.org/support/see_request?id=30644

Sticky an entry; edit it; refresh. The entry is not longer stickied. The URL is gone from Account settings.

**Comment by kareila** [comment]
It looks like this only happens if the user has opted into the beta update page. There are different edit codepaths for that situation.

**Comment by kareila** [comment]
Looking at views/entry/form.tt, I think the sticky module is only being included on the page if the user is posting to a community. So for sticky entries in the user's personal journal, when the checkbox isn't included on the form, that's being interpreted as clearing the element.

**Comment by afuna** [comment]
Hmm I think that code is only meant to force sticky when community admin but shouldn't affect personal. Ponder ponder
