### ISSUE TITLE
Fix Google Docs spreadsheet embeds

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1344]
At some point (likely within the last couple code pushes), we broke Google Docs spreadsheet embeds. I was able to replicate this issue, but it looks like text-type Google Docs embed fine. The original issue for this seems to be here: https://github.com/dreamwidth/dw-free/pull/573

http://www.dreamwidth.org/support/see_request?id=30609 is the Support request.

**Comment by rahaeli** [comment]
I think it's probably more likely that Google changed the form of their code than we broke something! Can somebody get a sample of current embed code?

**Comment by zarhooie** [comment]
Here is a spreadsheet:
<iframe src="https://docs.google.com/spreadsheets/d/1P84CUNTo5O4ZW7R58Gl1ksCknFx3p59XzzQa7y67IaI/pubhtml?gid=23737011&amp;single=true&amp;widget=true&amp;headers=false"></iframe>

For comparison, here's a document (which embeds just fine):
<iframe src="https://docs.google.com/document/d/1vWvTaEjbnwozqahvJRZXC3oMIUTMCjjqX_vDauB00hg/pub?embedded=true"></iframe>

**Comment by zarhooie** [comment]
Here is a spreadsheet:
```<iframe src="https://docs.google.com/spreadsheets/d/1P84CUNTo5O4ZW7R58Gl1ksCknFx3p59XzzQa7y67IaI/pubhtml?gid=23737011&amp;single=true&amp;widget=true&amp;headers=false"></iframe>```

For comparison, here's a document (which embeds just fine):
```<raw><iframe src="https://docs.google.com/document/d/1vWvTaEjbnwozqahvJRZXC3oMIUTMCjjqX_vDauB00hg/pub?embedded=true"></iframe></raw>```

Let's pretend that I have always known how to do code blocks in Markdown.

**Comment by rahaeli** [comment]
So stipulated :D

**Comment by afuna** [comment]
oh... I think this has always been broken, oops. We allow /spreadsheet/, not /spreadsheets/ :blush:

**Comment by me-and** [comment]
Claimed
