### ISSUE TITLE
"Insert" button to insert image on RTE no longer exists

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1345]
Problem: When you pull up the insert image dialog on the RTE, there is not a "insert" or "submit" button, only a cancel button. There used to be, but it disappeared at some point. There have been at least three reqs about it in the last week.
Workaround: once you've put the image URL into the box, hit enter.
Fix: please make there be a nice tidy button again, or at least a note on the box that says something like, "when you're done, hit enter."

![insert](https://cloud.githubusercontent.com/assets/4575445/7149040/8b56c6f6-e2ce-11e4-86a0-4e39f2e9f545.png)
http://www.dreamwidth.org/support/see_request?id=30743

**Comment by kareila** [comment]
I am 99.9% sure this is related to af3dba54f4d0134a0c02f86af9ef4506398e186f - the relevant file seems to be htdocs/stc/fck/editor/dialog/fck_image/fck_image.js.
