### ISSUE TITLE
Planet Caravan style: gap between bottom of entry userpics and border

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1346]
http://www.dreamwidth.org/support/see_request?id=30745

Swich to Planet Caravan, see the gap at the bottom of every entry userpic. Might wanna see if borders should be applied to .userpic img instead of .userpic.

**Comment by momijizukamori** [comment]
claimed - that totally didn't used to be there, but CSS *hands*

**Comment by afuna** [comment]
Bitrot! Bitrot?

**Comment by kareila** [comment]
Maybe it showed up when we switched to HTML5? Seems likely given the timing.

**Comment by afuna** [comment]
Possibly! Hmmm I know there was something with <br> showing up
differently wrt line-height, and that's probably not directly relevant
but might be related.


On Wed, May 6, 2015, at 01:27 PM, Jen wrote:
> Maybe it showed up when we switched to HTML5? Seems likely given
> the timing.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1346#issuecomment-99597522

**Comment by momijizukamori** [comment]
Yeah, I'm going to guess it's a difference with HTML5's implementation. I'll have a poke and see if any other layouts are affected, I know we have a couple with icon borders.
