### ISSUE TITLE
Unable to edit image properties in certain RTE use cases

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1353]
Issue: if the user copies and pastes an image into the RTE, they can't use the image properties pop-up to edit the alt text etc.
To reproduce:
-Copy an image from the internet (I've been using the Dreamwidth header)
-paste image into RTE update page
-Click on the image button on the RTE toolbar
-This should allow you to modify the alt-text etc of the image, but it doesn't. It is just blank.
-If you switch into HTML, the alt-text from the image's hosting site seems to be automatically pulled over, at least on this computer. YMMV.

http://www.dreamwidth.org/support/see_request?id=30754

**Comment by kareila** [comment]
My fix from #1347 also seems to fix this.
