### ISSUE TITLE
Update links in automated emails to point to HTTPS

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1354]
Right now, when I receive an email with, for instance, notification of a new comment, all the links -- links to "Reply at the webpage", "View all comments to this entry", "Go to the top of the thread this comment is part of", my notification settings, and so on -- are HTTP rather than HTTPS.

I presume that we'd prefer to just turn those links into HTTPS links rather than offer an HTTP vs. HTTPS option in https://www.dreamwidth.org/manage/settings/?cat=privacy .

**Comment by afuna** [comment]
Yesssss.

Hmm. I do believe that this should be all fixed once we turn on HTTPS everywhere; grabbing and assigning to myself to double check so that this doesn't fall through the cracks.

**Comment by kaberett** [comment]
@afuna, is it okay if I take this one off you? HTTPS Everywhere's happened and it's not fixed, and it's a topic Dear To My Heart etc etc :-)

**Comment by afuna** [comment]
Sure!

**Comment by kaberett** [comment]
Awesome, thank you :D Claiming presumably won't work automagically, but nonetheless this is my precious and I shall curl up around it hissing, yes yes.

**Comment by kareila** [comment]
I just switched it over to you :heart:
