### ISSUE TITLE
OpenID logins from providers that use HTTPS URLs are broken

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1355]
There has been a recent increase in reports of OpenID login failures.  Upon closer inspection, I have realized a common thread between the different providers is that they have all switched to using HTTPS by default, so I believe the problem is SSL-related.

These are some of the OpenID providers that are currently not working:
- Twitter
- Tumblr
- Etsy
- Yahoo

(UPDATE: it has been rightly pointed out that Twitter, Tumblr and Etsy do not provide OpenID logins; that was a false conflation on my part.  Yahoo is still a legitimate problem, however.)

As reported here: http://www.dreamwidth.org/support/see_request?id=29682

The error message displayed when attempting to log in is "no_identity_server: Could not determine ID provider from URL".  This is the value of `$csr->err` set when the following statement is executed in /openid/login.bml (currently line 108):

`my $claimed_id = eval { $csr->claimed_identity($url); };`

Here `$csr` is a Net::OpenID::Consumer object.  I expect the fix will likely involve upgrading some of our installed OpenID and/or SSL modules, or we may need to implement a workaround.

I found this article helpful in researching the problem: http://ikiwiki.info/bugs/openid_login_fails_wirth_Could_not_determine_ID_provider_from_URL/

I tried the `$ENV{PERL_LWP_SSL_CA_PATH} = '/etc/ssl/certs';` workaround mentioned there, but it didn't seem to fix the problem.  They also mention `$ENV{PERL_LWP_SSL_VERIFY_HOSTNAME} = 0;` but that is already in ljlib.pl.

I also tried locally installing newer versions of the relevant modules, with no apparent change in behavior.

**Comment by zorkian** [comment]
OpenID is a mostly deprecated protocol, AIUI, and I don't think people are really supporting it anymore. We might continue to have increasing trouble supporting it (read: hacks on hacks) if we do.

**Comment by kareila** [comment]
I realize it's not a high priority, but I suspect this may be more of an SSL problem than an OpenID problem, and as such is worth investigating, especially if the fix turns out to be as simple as installing newer versions of some modules.

**Comment by kareila** [comment]
Making a note to retest this soon.

**Comment by kareila** [comment]
I just tried an OpenID login on prod and got a new but hopefully easier to diagnose error:

    Not an ARRAY reference at /home/dw/current/extlib/lib/perl5/Net/DNS/Paranoid.pm line 91.

**Comment by kareila** [comment]
More information: the above error happens with both SSL and non-SSL OpenID providers when trying to login on dreamwidth.org. My hack environment seems to still have the old behavior, where non-SSL logins work and SSL logins give the no_identity_server error.

**Comment by me-and** [comment]
The title for this needs updating to note it's not just HTTPS affected now. Also there are support tickets coming in for this regression now:

* [31121](http://www.dreamwidth.org/support/see_request?id=31121)
* [31123](http://www.dreamwidth.org/support/see_request?id=31123)

**Comment by kareila** [comment]
Okay, I see why it is doing two different things on the different servers.  In LJ/OpenID.pm, line 67, `$ua` isn't set if `$LJ::IS_DEV_SERVER` is true, and Net::OpenID::Consumer will default to using `LWP::UserAgent`.  In the case where `$LJ::IS_DEV_SERVER` is false, LJ/OpenID.pm calls `LJ::get_useragent` which uses `LWP::UserAgent::Paranoid`.  That dev server check is not new; it dates all the way back to the LJ fork.  I don't understand the difference between paranoid and non-paranoid user agents so can't judge if making it always use `LWP::UserAgent::Paranoid` in every case is the right thing to do here.

**Comment by me-and** [comment]
(not sure if it's actually going to be better to track HTTP OpenID being broken in a different ticket, given the fix for the recent regression and the long-term HTTPS problem have a decent chance of being different.)

**Comment by kareila** [comment]
We can get back the old behavior (HTTP providers work, HTTPS providers don't) by removing the code that uses the paranoid useragent and use the default useragent in all cases, then diagnose why the new behavior is failing at a later date.

**Comment by afuna** [comment]
Paranoid::Useragent basically has additional security stuff -- we shouldn't be disabling it. I don't know why dev servers don't use it (weird and probably lost to the mists of time).

We did recently switch modules for the paranoid useragent which probably
has something to do with it!


On Fri, Jun 26, 2015, at 10:07 PM, Jen wrote:
> We can get back the old behavior (HTTP providers work, HTTPS providers
> don't) by removing the code that uses the paranoid useragent and use
> the default useragent in all cases, then diagnose why the new behavior
> is failing at a later date.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1355#issuecomment-115962378

**Comment by kareila** [comment]
I tried removing the dev server check on my hack and weirdly the behavior hasn't changed, which makes me wonder if something else is going on with the production setup.

**Comment by kareila** [comment]
Yep, the paranoid agent definitely works normally on my dreamhack too, so that's not the problem. What could be causing the agent to fail in production and not elsewhere?

Unfortunately I've also verified that using the new paranoid agent module does NOT fix the no_identity_server error.

**Comment by kareila** [comment]
I think I figured out the problem. It's with `blocked_hosts` in LJ::OpenID which also has a dev server special case that skips the code being run in production. I'll land a patch on the release branch that should fix it.

**Comment by kareila** [comment]
Submitted a patch that should fix the "everything fails" error but not the "ssl providers fail" error, so we're back to where we started.

**Comment by afuna** [comment]
I'm sad that the LWP::ParanoidAgent module change did not end up fixing this the way it did HTTPS feeds

**Comment by kareila** [comment]
Okay, I have successfully nailed down the problem.  In `LJ::get_useragent` we have:

    ssl_opts => { verify_hostname => 0 }

If we change this to:

    ssl_opts => { verify_hostname => 0, SSL_verify_mode => 0 }

Then I can successfully proceed with OpenID login using me.yahoo.com.

According to https://bugs.launchpad.net/ubuntu/+source/libwww-perl/+bug/1408331/comments/6 this is fixed in LWP::Protocol::https version 6.06 (dreamhacks have 6.04) where `verify_hostname => 0` will also activate `SSL_verify_mode => 0` automatically, but it's probably simpler just to add the line to `LJ::get_useragent` and be done with it.

Of course this means we aren't verifying SSL certificates when negotiating OpenID logins but I'm not sure that's something we really need to care about in this context.

**Comment by me-and** [comment]
> Of course this means we aren't verifying SSL certificates when negotiating OpenID logins but I'm not sure that's something we really need to care about in this context.

I don't think that's true; certainly it seems to be against best practices. Quoting from the [OpenID 2.0 spec §15.1.2](http://openid.net/specs/openid-authentication-2_0.html#anchor41):

> … If DNS resolution or the transport layer is compromised signatures on messages are not adequate, since the attacker can impersonate the [OpenID Provider (OP)] and issue its own associations, or its own decisions in Stateless Mode. If an attacker can tamper with the discovery process they can specify any OP, and so does not have to impersonate the OP. …
>
> Using SSL with certificates signed by a trusted authority prevents these kinds of attacks by verifying the results of the DNS look-up against the certificate. Once the validity of the certificate has been established, tampering is not possible. Impersonating an SSL server requires forging or stealing a certificate, which is significantly harder than the network based attacks.
>
> In order to get protection from SSL, SSL must be used for all parts of the interaction, including interaction with the end user through the User-Agent. While the protocol does not require SSL be used, its use is strongly RECOMMENDED. Current best practices dictate that an OP SHOULD use SSL, with a certificate signed by a trusted authority, to secure its Endpoint URL as well as the interactions with the end user's User-Agent. In addition, SSL, with a certificate signed by a trusted authority, SHOULD be used so that a Relying Party can fetch the end user's URL in a secure manner. Following its own security policies, a Relying Party MAY choose to not complete, or even begin, a transaction if SSL is not being correctly used at these various endpoints.

(The above found via [a bug report at ikiwiki complaining about the lack of SSL verification](https://ikiwiki.info/bugs/ssl_certificates_not_checked_with_openid/).)

If it makes sense to just say "it's the only practical way to get this working", then that's a bit sad but fair enough, but I do think it's worth noting that it's not following best practices.

**Comment by rahaeli** [comment]
What about upgrading module versions? Does that break anything?

**Comment by kareila** [comment]
Upgrading the module version does the same thing implicitly that we just did explicitly, namely turning off both modes of verification.  The traffic is still encrypted, and the likelihood of spoofing is very low. Obviously it's not an ideal solution, but we haven't figured out any other way to get this working at all.

**Comment by rahaeli** [comment]
Right, I'm just wondering if it might be better to upgrade than to patch.

**Comment by kareila** [comment]
It makes no difference to the issue at hand.
