### ISSUE TITLE
OpenID community maintainers are unable to edit tags

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1356]
http://www.dreamwidth.org/support/see_request?id=30652

I dug into the code and found this in LJ::Tags::can_add_tags:
```
# we don't allow identity users to add tags, even when tag permissions would otherwise allow any user on the site                                                                                                          
# exception are communities that explicitly allow identity users to post in them                            
# FIXME: perhaps we should restrict on all users, but allow for more restrictive settings such as members?  
return undef unless $remote->is_personal || $remote->is_identity && $u->prop( 'identity_posting' );         
```

So I looked to see where in the settings we can turn on `identity_posting` for a community, and... it doesn't seem to be available.  Maybe our treatment of OpenID users changed somewhere along the line, and this got missed?

Either we should update cgi-bin/DW/Setting/CommunityPostLevel.pm to allow this setting to be turned on, or we should remove the check for it from `can_add_tags`, `can_add_entry_tags`, and `can_control_tags` in LJ/Tags.pm.  There is also a check for it in LJ/Protocol.pm.

**Comment by rahaeli** [comment]
identity_posting is probably an old hook that was added in to allow for future expansion, and then we didn't know about it/didn't realize when we enabled OID community posting and implemented it a different way.

I see no reason why OID accounts shouldn't be able to manage tags in comms the same way normal users can -- add/remove from their own posts, add/remove from all posts if a maintainer.

**Comment by afuna** [comment]
I bet that's just legacy, because openid users couldn't post in
communities before, so maybe it was just so that they wouldn't be able
to fiddle with tags that they otherwise couldn't use? idk.

**Comment by rahaeli** [comment]
We can probably just switch that check from is_personal to is_individual (I think that's the sub) and allow all OID users to wrangle tags, come to think of it. (Subject to the same checks for membership, yadda.)

**Comment by rahaeli** [comment]
@kareila -- I left a screened answer on the support request, but if you want to take credit for it, go ahead and answer instead. :) Otherwise just approve me or let me know to approve myself!

**Comment by kareila** [comment]
I think we were both responding at the same time! I'll go ahead and approve mine then.

**Comment by rahaeli** [comment]
Sweet! (Didn't know if you wanted to reply or not.)
