### ISSUE TITLE
FAQ 199 needs update for multiple sticky 

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1360]
http://www.dreamwidth.org/support/faqbrowse?faqid=199 

Current: 

There isn't currently a way to make multiple entries sticky, although the feature is planned. Instead, you can use the Date Out of Order option to make entries appear at the top of your journal by giving the entry a date in the far future. You could also write an "index" post that links to all the entries you want to make sticky, then make the index post into your sticky entry.

**Comment by azurelunatic** [comment]
Proposed: 

The number of sticky entries allowed depends on your account type (faqid=4). If you still need more sticky entries than that, you can use the Date Out of Order option to make entries appear at the top of your journal by giving the entry a date in the far future. You could also write an "index" post that links to all the entries you want to make sticky, then make the index post into your sticky entry.

**Comment by rahaeli** [comment]
done!
