### ISSUE TITLE
FAQ 104 needs update for multiple sticky entries

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1361]
http://www.dreamwidth.org/support/faqbrowse?faqid=104 

Current: 
You might want to use this option when you're posting archived entries so they appear on the right dates. It can also be used to date a post in the future so it stays at the top of your Recent Entries page. You can also use the Sticky Entries feature to do this, though you can only have one Sticky entry at a time.

**Comment by azurelunatic** [comment]
Proposed: 
You might want to use this option when you're posting archived entries so they appear on the right dates. It can also be used to date a post in the future so it stays at the top of your Recent Entries page. You can also use the Sticky Entries feature to do this.

**Comment by kaberett** [comment]
I apparently fixed this in about September and totally failed to update the issue. @kareila, @azurelunatic, whichever of you gets here first can close this! :-)

**Comment by rahaeli** [comment]
Hey, or me!

**Comment by kaberett** [comment]
... whoops yes sorry :-)
