### ISSUE TITLE
FAQ 64 should probably mention the possibility for manually entering the rename token

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1362]
http://www.dreamwidth.org/support/faqbrowse?faqid=64

Current: 

If you have a rename token available, you will see a link on the Rename Journal http://www.dreamwidth.org/rename page that lets you choose to rename your account (or you can rename a community you admin http://www.dreamwidth.org/support/faqbrowse?faqid=214). Once you start the process, you will be prompted to choose the rename options http://www.dreamwidth.org/support/faqbrowse?faqid=213 you want for your rename.

**Comment by azurelunatic** [comment]
Proposed: 

If you have a rename token available, you will see a link on the Rename Journal http://www.dreamwidth.org/rename page that lets you choose to rename your account (or you can rename a community you admin http://www.dreamwidth.org/support/faqbrowse?faqid=214). If someone has given you a rename token (or you have bought it in another account) you can use it on this page. Once you start the process, you will be prompted to choose the rename options http://www.dreamwidth.org/support/faqbrowse?faqid=213 you want for your rename.

**Comment by kaberett** [comment]
Done. @azurelunatic, @kareila -- whichever of you gets to this first can close the issue!
