### ISSUE TITLE
tagnav memory doesn't handle special-characters

### ISSUE THREAD

**Issue by woggy** [dreamwidth/dw-free#1363]
Navigating using the tagnav links is intended to 'remember' which tag you had selected. When the tag in question has any sort of special characters (including, notably, space characters), the new page does not remember the tag selection and it must be reselected.

as best as I can tell it's something gone sideways in the 'compare with the URL string' logic. As an example: `http://synecdochic.dreamwidth.org/353197.html#tagnav-broken+wings` doesn't work but `http://synecdochic.dreamwidth.org/353197.html#tagnav-broken wings` (hand-edited to such) works as expected.

**Comment by afuna** [comment]
spaces in tags strikes again! I'm only seeing the issue with space characters though. Do you have any examples of non-space special characters where it's broken?

**Comment by woggy** [comment]
I've also seen it hork on * and square-brackets. My guess is it's anything that gets replaced with Something Else in the URL - colons seem to be fine.

**Comment by afuna** [comment]
Gotcha, thanks for the additional info


On Tue, Apr 28, 2015, at 05:53 AM, woggy wrote:
> I've also seen it hork on * and square-brackets. My guess is it's
> anything that gets replaced with Something Else in the URL - colons
> seem to be fine.


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1363#issuecomment-97051710

**Comment by afuna** [comment]
Sorry, took me a while to loop back to this! The few things I tried involving "*" and "[]" seemed to work. Is there any chance that tags with the asterisks and braces are more likely to have spaces in them as well?

**Comment by woggy** [comment]
No spaces in the ones I've looked at.
http://synecdochic.dreamwidth.org/tag/%5Bdraft%5D is one of the ones that
breaks.

**Comment by afuna** [comment]
Oh huh interesting, I just checked in another browser and it was
working in one browser but not another. Will also address that thanks
for the info!
