### ISSUE TITLE
need some admin way to break rename redirect while freeing up redirected username for immediate re-use

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1367]
If a user chooses the wrong options while renaming, they can wind up not being able to do what they want to do, and I can't fix it.

Scenario: User has 3 accounts, A, B, and C. They want to rename B to C, and then A to B. (And don't care what happens to A afterwards.)

If they do the B->C rename first, and accidentally select the redirect option when renaming, they are then locked out of renaming A->B because username B is still technically 'in use' (as a redirect). Even if I use the rename admin tool to break the redirect, the user still can't perform the rename.

If I use the rename admin tool to break a redirect from old->new, the 'old' username should be freed up for re-use immediately (via rename token, same as any other deleted account).

**Comment by kaberett** [comment]
(See also #1088, maybe?)
