### ISSUE TITLE
make two-token rename swap possible independent of which account the tokens are on

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1374]
In order for the two-token username swap to work, right now you need to have two rename tokens available on the account you're logged into when you initiate the swap, not one token on each account. This is confusing to people. Instead, the system should check both accounts for available tokens, and if it finds one token on each account (or even 0 tokens on the logged-in account and 2 tokens on the other account) it should use those tokens and succeed.

**Comment by kareila** [comment]
Claiming this - I looked at this code recently and I know I saw where the check was happening, so I can probably figure out how to fix it.
