### ISSUE TITLE
Proxy causes system to run out of file descriptors when left running too long

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1381]
http://www.dreamwidth.org/support/see_request?id=30863

An image in an entry won't display.

The image lives over at photobucket.com/albums/bb317/AndrewDucker/2015-infographic.jpg.png 

The URL we're showing is https://p.dreamwidth.org/12b0d34ed254/i207.photobucket.com/albums/bb317/AndrewDucker/2015-infographic.jpg.png

So somewhere between when they posted and when we served the content, something went sideways. I am probably explaining this poorly, so hopefully someone can figure out what happened. Fu said to open a ticket.

**Comment by rahaeli** [comment]
Visiting the link directly gives you:

> Get http://i207.photobucket.com/albums/bb317/AndrewDucker/2015-infographic.jpg.png: dial tcp: lookup i207.photobucket.com: Temporary failure in name resolution

**Comment by afuna** [comment]
Ping @zorkian:

Something's up with the proxy. Lots of failures in logs/proxy.log, this
stands out to me:

2015/05/11 04:38:09 http: Accept error: accept tcp [::]:6250: too many
open files; retrying in 5ms

**Comment by afuna** [comment]
http://craigwickesser.com/2015/01/golang-http-to-many-open-files/ ?

**Comment by afuna** [comment]
Restarted the worker -- that should help with the fd exhaustion problem
for now. Could someone please confirm that things work fine now?

We'll run into it again once this runs long enough so let's leave this
issue open so we can have a *real* fix in place for the future (probably
just making sure we close the connection before anything happens, but
it's taking me longer to set up the proxy on my dev env so I can test so
that's... not happening tonight!)

**Comment by rahaeli** [comment]
I'm seeing an image in the post linked in the request, so it's working for now.

**Comment by zarhooie** [comment]
Sweet. Thanks for the quick resolution! I replied to the user.

**Comment by anall** [comment]
Do we have the code for the proxy anywhere public?

**Comment by alierak** [comment]
dw-free/src/proxy/

**Comment by anall** [comment]
Hah, thanks. I thought `src` was legacy so didn't even think to look in there.

**Comment by rahaeli** [comment]
Possibly cause of #1452.

**Comment by afuna** [comment]
Closing this as it turns out the fix had not been live when #1452 happened. Now it is live, and we shall see if it worked.

**Comment by kareila** [comment]
This is still happening: http://www.dreamwidth.org/support/see_request?id=31909

**Comment by kareila** [comment]
@alierak restarted the proxy again, but we need a long-term fix.

**Comment by alierak** [comment]
Ok, we now have a weekly preventative restart scheduled in cron.

**Comment by sgsabbage** [comment]
I am claiming for today. I may find that I get nowhere with it, but might as well try!

**Comment by sgsabbage** [comment]
The fix I have PR'd seems to solve the problem but would appreciate additional eyes on it. I was testing this locally against my own HTTP server (as I don't believe it's possible to do this on the dreamhack with ease), and found that the only thing that was keeping connections open was Chrome trying to be helpful (I think):

```
sean$ sudo lsof -i -n -P | grep TCP | grep 6250
Google    82338           sean  128u  IPv6 0x409a461b54d9fce1      0t0  TCP [::1]:59294->[::1]:6250 (ESTABLISHED)
proxy     84021           sean    3u  IPv6 0x409a461b54db1ce1      0t0  TCP *:6250 (LISTEN)
proxy     84021           sean    5u  IPv6 0x409a461b54d9f7e1      0t0  TCP [::1]:6250->[::1]:59294 (ESTABLISHED)
```

The proxy was, as far as I can see, happily closing connections to the webserver that it was getting files from when it was done with them.

I didn't spot this with Firefox. This fix as far as I've found will always close the TCP connection once we've served the file back to the user (or if we 404 or error out). 

What might be useful is a `netstat -anp | grep 6250` on the proxy box before this code is applied to check that I'm understanding the problem right!

**Comment by zorkian** [comment]
Your understanding is basically correct, but it's not a problem. The server was just never given a higher-than-default limit of file descriptors. They're trivial as far as resource usage goes, but the default in Linux is usually around 1024. Bummer.

I raised it to 100,000 for the proxy in production so we shouldn't see this problem again.
