### ISSUE TITLE
if given a proxy URL for an image, need to be able to remove the image at that URL from the proxy

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1390]
Related to #1389, and also for DMCA compliance purposes: if we're given a proxy URL for an image, we need an admin tool to do two separate things:

1). Force-remove the image from our proxy, so it's no longer available at the URL reported in the DMCA report.

2). Prevent the image from being re-fetched and re-proxied, replacing it instead with a "click here to see the image" or some such thing.

**Comment by zorkian** [comment]
Neither of these are particularly easy as written. The proxy is an entirely separate service that is run "outside" of DW. Purging data from it involves building in a way to give it commands, and there is no such mechanism right now.

I think that suspending the entry to make the link go away, and actually making the proxy expire things after an hour, is the ideal way to do this.

**Comment by alierak** [comment]
At the moment I've just got a dumb cron job on the proxy running every 4 hours, removing anything older than 90 minutes. Chances are by the time you get a DMCA report and suspend the entry, it's already gone.

**Comment by rahaeli** [comment]
Okay, if we get #1389 and I can find the entry from the proxy URL (which I can't right now), that should be fine then!
