### ISSUE TITLE
Admin Console Reference missing CSS styling

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1398]
The list of console commands in the console reference guide used to have different styling depending on whether or not you were allowed to use the command.  Since it was converted to Foundation/SCSS, that styling has disappeared.

The two div classes are "enabled" (for commands you can use) and "disabled" (for unavailable commands).  The current styling is fine for enabled, but disabled commands used to be printed in much lighter text to indicate that they were unavailable to use.

We need to readd some CSS so that enabled and disabled commands can once again be differentiated from each other.

**Comment by me-and** [comment]
Claimed
