### ISSUE TITLE
Ban and Unban Accounts page undiscoverable

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1400]
As discussed in -dev last week, as best I can tell the only place manage/banusers.bml is linked from is the FAQ about it. I propose adding a link from manage/circle/edit.

**Comment by kaberett** [comment]
claimed

**Comment by afuna** [comment]
Hmm, so there's a link from https://www.dreamwidth.org/manage/settings/?cat=privacy

Do we still need the link here as well?

(oh also fyi, need "#1400" to link to issues from pull requests! The "#" part is what tells github to consider it as an issue number)

**Comment by rahaeli** [comment]
/manage/circle/edit sounds fine to me! (Belatedly.)
