### ISSUE TITLE
Status field on support history page less useful than it might be

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1402]
The 'status' column on http://www.dreamwidth.org/support/history only distinguishes between 'open' and 'closed'. This is not very useful! It should use the same as the support board itself: 'open', 'answered, awaiting close', 'answered, still needs help', and 'closed'.

**Comment by kaberett** [comment]
claimed!

**Comment by kaberett** [comment]
Okay, so support/history pulls directly from the database table support, for which the "status" property *only* offers "open" or "closed" (http://wiki.dreamwidth.net/wiki/index.php/Database_Table:_support). support/help looks to be doing a closer approximation to working out _subtype_ of "open" status on the fly. Consequently the best way I'm seeing of handling this at the moment is if, for support/history, the database status field is set to "open", do the same set of checks as are done over in support/help and display the appropriate subtype. I'm going to go ahead with trying to implement that for the time being but appreciate input!

**Comment by rahaeli** [comment]
Of course it's not that easy, heh.

I haven't looked at the actual code, but your proposed method is probably the best, as long as you refactor it so both areas are calling out to the same code as a subroutine instead of duplicating the checks in both places. (I might be overruled, though!)
