### ISSUE TITLE
Allow embeds from gist.github.com

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1411]
Request: https://www.dreamwidth.org/support/see_request?id=30818

Sample:
```<script src="https://gist.github.com/spinda/b261167303515cc8a1d9.js"></script>```

**Comment by rahaeli** [comment]
IIRC, the last time we looked into this we couldn't do it for some reason, but I don't remember what that reason was.

**Comment by afuna** [comment]
From the code snippet they use script tags not, eg, iframes.

**Comment by rahaeli** [comment]
Right! That would be it, and it would indeed be staring me right in the face.

**Comment by srukle** [comment]
Ah shucks. Any work around?

**Comment by kareila** [comment]
Not that we know of!

**Comment by rahaeli** [comment]
Convince Gist to offer a noscript embed version ;)

**Comment by azurelunatic** [comment]
Ticket asking politely has been filed.

**Comment by azurelunatic** [comment]
It has been entered into the feature request list! Now we wait. ;)

**Comment by kaberett** [comment]
\o/
