### ISSUE TITLE
Captcha failing on Android mobile platform

### ISSUE THREAD

**Issue by zarhooie** [dreamwidth/dw-free#1412]
http://www.dreamwidth.org/support/see_request?id=31005 (Peterstein req)

The user wrote in complaining about /lostinfo not working on Android phones.

Steps to replicate:
On a Droid phone, go to www.dreamwidth.org/lostinfo
Answer CAPTCHA
The "proceed" button will not become clickable

I was able to replicate using my own Droid Maxx, but was NOT able to replicate on my friend's iPhone 6+. I do not have access to any other mobile devices, or I'd have checked on those too.

Possibly related: the captcha fails to load at all if Javascript is not enabled on a browser. This is not the exact issue that we're having here, but I figured I'd mention it just in case. I can also open a separate bug for that if needed.

**Comment by Sophira** [comment]
It works for me on my Samsung Galaxy S3 running Android 4.2.2, but that's highly modified and runs a non-stock ROM. In any case, maybe a useful data point?

**Comment by afuna** [comment]
Not sure if related, but the captcha should show up when there's no JS.
Is captcha not showing up with JS disabled happening on all browsers or
just the one reported above?

For the android browser, unfortunately I don't have one of my own to
check, but can you try going to the page in question and then putting
"about:debug" in the URL?


On Sun, Jun 7, 2015, at 09:26 PM, Sophira wrote:
> It works for me on my Samsung Galaxy S3 running Android 4.2.2, but
> that's highly modified and runs a non-stock ROM. In any case, maybe a
> useful data point?


> — Reply to this email directly or view it on GitHub[1].

>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1412#issuecomment-109857634

**Comment by momijizukamori** [comment]
Stock JB (4.1.2), works properly in Chrome and the Motorola system browser.

**Comment by afuna** [comment]
Okay! Sending up signal again -- would love if we figure out what's
causing this issue.

**Comment by kaberett** [comment]
A friend says in unprompted comment to me elseweb yesterday: No chance of fixing the DW password recovery page? The final button to complete the process never enables itself on Android mobile devices.

I'm also not replicating (Samsung something running CyanogenMod.)

**Comment by zarhooie** [comment]
I was able to replicate the javascriptless issues on Chromium, I think. Will test in a bit.

**Comment by afuna** [comment]
I think this is two issues:

One is that entering a username/etc isn't turning on the proceed button
The second is that without JS there's no captcha?

Filling out captcha is not meant to turn on the proceed button though!


On Wed, Jun 24, 2015, at 03:45 PM, MissKat wrote:
> I was able to replicate the javascriptless issues on Chromium, I
> think. Will test in a bit.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1412#issuecomment-115035277

**Comment by afuna** [comment]
I suggest we keep the proceed button stuff here, and then have
javascriptless captcha in a different issue please!

**Comment by kaberett** [comment]
I know this is now closed but dumping this more detailed report here in case useful in future:
Filled in Captcha, account name and email: enter key navigates from
  textbox to texbox and changes from 'return key' symbol to 'done' on
  completing the email address but the 'proceed' key does not receive the
  focus, does not lose the greyed-out appearance, and does not respond to
  touchscreen 'tap' actions.

  Repeated after page refresh, repeated after clearing browser cache.
  Entering a known bad answer into the Captcha does not change the
  behaviour: I had expected an error message for that.
▼ Hide quoted text

  Observed in 2013 on an HTC Desire II in 2013 using the Android native
  browser, Opera Mini, and Chrome.

  Replicated ten days ago on a Sony Experia D5803 running Android 5.0.2
  with the OEM browser, Opera Mini 9.0, and in Chrome 43.0.2357.93 running
  Javascript V8 4.3.61.22 (failed on mobile site, failed again in Chrome
  using 'request desktop' on the site).

  Replicated today in Opera Mini 9.0

  However, I succeeded at the first attempt in Chrome, using the mobile
  site. Can now log in with Opera and with Chrome, have not tested the OEM
  browser. I am not aware of any updates to my phone in the last ten days.

  Thanks, and apologies for the late reply.

**Comment by afuna** [comment]
Thanks for the additional information!

**Comment by myhubchloe** [comment]
@zarhooie ..did u find any resolution for this issue? I am currently facing the same issue on android phone but works on iphone..

**Comment by mariohik** [comment]
Any news? I'm having the same issue.
