### ISSUE TITLE
Error viewing spam reports for deleted and purged accounts

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#1413]
Error: Can't call method "selectrow_array" on an undefined value at /home/dw/current/cgi-bin/LJ/User.pm line 4352

This happens and no list of reports is displayed when viewing spamreports by user, if the user has been deleted and purged, ie in https://www.dreamwidth.org/admin/spamreports?mode=view&by=posterid&what=(redacted)&state=open (userid redacted, poke me if you need it)

**Comment by rahaeli** [comment]
Huh, I could have sworn we had a bug open for this already, but looks like we don't!

**Comment by afuna** [comment]
Maybe the IPv6 one looks similar enough to trigger déjà vu?

**Comment by kareila** [comment]
I fixed this in #1318 two months ago, and this is the second time it's been reported again since then. We really need a code push.

**Comment by rahaeli** [comment]
Aha, that was why I thought it had been reported!

Yeah, let's do a code push at OSB.

**Comment by afuna** [comment]
Sounds good to me.


On Mon, Jun 15, 2015, at 05:41 PM, Denise Paolucci wrote:
> Huh, I could have sworn we had a bug open for this already, but looks
> like we don't!


> — Reply to this email directly or view it on GitHub[1].

>


Links:

  1. https://github.com/dreamwidth/dw-free/issues/1413#issuecomment-112245666
