### ISSUE TITLE
entry success page should not show metadata when deleting entry

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1445]
The new entry metadata on the success screen is still showing when you delete an entry, not just on post or edit. :)

**Comment by woggy** [comment]
Unsure whether to make an entirely new issue for this, but also. The subject line would be more helpful if it said "no subject" explicitly. Will likely fix the two in the same pullreq, so.

**Comment by kaberett** [comment]
Oh wait, I've actually fixed the metadata-on-deletion issue, just not all the other bits and bobs. Okay, might as well get the pull req in and open another issue for the other bits that've been discussed.

**Comment by kaberett** [comment]
(I took this one over with @woggy's blessing!)
