### ISSUE TITLE
ProcessSub failing with least helpful error message ever

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1447]
2015-06-26 05:10:34 in LJ::Worker::ProcessSub
This shouldn't happen at /usr/share/perl/5.18/Text/Wrap.pm line 84.

**Comment by anall** [comment]
Do we know *what* ProcessSub things this is failing on?

**Comment by rahaeli** [comment]
Mark fixed by upgrading the version of the module we're using.
