### ISSUE TITLE
update sample configs in dw-free repo to be current && be more clear they are samples

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1448]
The configs that we ship with dw-free are samples, not the actual configs that are live on dreamwidth.org (for several very good reasons!) However, the samples are kind of out of date (missing a few new features) and they aren't very clear that they are samples.

So, we need to do two things:

a) Make sure every flag/feature/option/etc that's in the production config files has a corresponding entry in the sample configs in the repo;

b) Put a comment/line in the sample configs in dw-free to make it more clear that these are samples and you should probably change them.

**Comment by Sophira** [comment]
I'll be paying attention to this issue; the Dreamhack creation process uses the sample configs as a base f

**Comment by Sophira** [comment]
I'll be paying attention to this issue; the Dreamhack creation process uses the sample configs as a base for creating the new configs for a Dreamhack.
