### ISSUE TITLE
add maxversion for openid modules in checkconfig.pl

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1449]
We need to add a maxversion for OpenID -- we only support OpenID 1.0, so we need checkconfig to only  allow for the max version of the module.

**Comment by anall** [comment]
Claimed!

**Comment by kareila** [comment]
I don't think this is needed any more.  When we migrated to the new infrastructure, we installed the newest Net::OpenID modules which still support the older protocol just fine.  We had to update one spot in our code that used deprecated module methods, which was fixed in #1899.
