### ISSUE TITLE
HTTPS proxy failing after code push

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1452]
Examples as given by user: 

https://aceattorneybigbang.dreamwidth.org/13371.html : imgur and tumblr userheads not using
http://aceattorneybigbang.dreamwidth.org/13371.html : everything loads properly

https://aceattorneybigbang.dreamwidth.org/26998.html : tumblr and AO3 userheads not loading

Inspecting element gets you: "Failed to load resource: the server responded with a status of 404 (Not Found)" for the proxied URLs.

**Comment by rahaeli** [comment]
I should add, I've verified that it's not just that account. I've spot-checked half a dozen entries where images should be proxied and they're all failing with the same 404.

**Comment by afuna** [comment]
Pushed out a hotfix.


On Fri, Jun 26, 2015, at 12:52 AM, Denise Paolucci wrote:
> I should add, I've verified that it's not just that account. I've spot-
> checked half a dozen entries where images should be proxied and
> they're all failing with the same 404.


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1452#issuecomment-115565134

**Comment by rahaeli** [comment]
<3

**Comment by rahaeli** [comment]
Closing issue because Mark fixed it this morning!

**Comment by afuna** [comment]
Reopening! I put in a hotfix, but we need to actually upgrade the proxy
+ undo my hotfix!


On Fri, Jun 26, 2015, at 01:57 PM, Denise Paolucci wrote:
> Closing issue because Mark fixed it this morning!


> — Reply to this email directly or view it on GitHub[1].


>



Links:

  1. https://github.com/dreamwidth/dw-free/issues/1452#issuecomment-115878774

**Comment by swaldman3** [comment]
Example public post where it's happening, in case it's of any use to anybody (but it sounds as though the problem has been diagnosed):

https://swaldman.dreamwidth.org/343622.html

**Comment by swaldman3** [comment]
From support: This is also breaking all custom mood themes. Which is unsurprising, I guess ;-)

**Comment by afuna** [comment]
Think this is a separate issue now; the error is about DNS failure, which makes me suspect the file descriptors not being closed error from #1381. 

Temporary fix (for both) for now is to rebuild the proxy to the new version and then restart it.

**Comment by swaldman3** [comment]
I note that #1381 is closed. Should it be reopened, with a high severity, if it is the cause of this?

**Comment by rahaeli** [comment]
I reopened that issue; re-close if I shouldn't have!

**Comment by alierak** [comment]
I've restarted the proxy and it's serving images now. #1381 probably is the cause of this failure, but the fix hasn't been deployed yet. Although main.go contains the fix, the running "proxy" binary was built on Jan 18. We need to rebuild, restart, and undo @afuna 's hotfix all at once.

**Comment by afuna** [comment]
Okay! Can we talk about what needs to be done to redeploy the proxy? Code is under src, can build using go build. It's deploying after that which I'm unsure about

**Comment by afuna** [comment]
Proxy rebuilt, hotfix undone, webs and proxy both restarted.
