### ISSUE TITLE
site search over-escaping characters

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1453]
Go to dreamwidth.org/search and enter something with quotes in it (or any other characters treated as needing escaping). Hit 'search'. The text in the search box is then escaped.

For instance, searching for "and the" (with the quotes) turns into &amp;quot;and the&amp;quot;. And if you hit 'more results', it becomes &amp;amp;quot;and the&amp;amp;quot;. Etc.

**Comment by rahaeli** [comment]
Also, you don't want to know how many tries it took me to properly escape the text in the above box so that it displayed incorrectly correctly.

**Comment by afuna** [comment]
Hmm. do we know if this is with the push or if it's always been like that?

**Comment by rahaeli** [comment]
New with push -- I've always used quotes for searching spam journals and it's never done that before.

**Comment by afuna** [comment]
This might have something to do with converting to tt #1286 

Not sure yet if this is something affecting all tt pages, or something with this one!

**Comment by kareila** [comment]
At a glance I think the html escaping filter in TT may be more aggressive than the LJ::ehtml function the old version used. I will claim this one since it's my pony.

**Comment by kareila** [comment]
Okay, I think what's going on is that `form.textbox` is escaping the value automatically, but I was also manually escaping it because that's what the BML version of the page did.  So I should remove the manual escaping, at least in that one section.

**Comment by kareila** [comment]
It looks like `form.hidden` also escapes its value automatically, so I should drop both manual escapes.
