### ISSUE TITLE
add Tumblr to external user links

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1461]
User asked about this in news; I could have *sworn* there was a reason we couldn't do it at one point, but I can't remember what it was and looking at things nothing comes to mind.

Username format: http://username.tumblr.com

Tumblr has no guaranteed 'profile' equivalent, so for the userhead, let's link to https://username.tumblr.com/archive (which everybody should have).

**Comment by rahaeli** [comment]
Turns out it does exist, heh. Oops! That's what I get for just opening the bug without checking.

**Comment by kaberett** [comment]
Should probably have flagged it up here, sorry!

**Comment by rahaeli** [comment]
no worries!
