### ISSUE TITLE
console reference doesn't grey out all unavailable commands

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1466]
https://www.dreamwidth.org/admin/console/reference greys out commands that you can't use because you don't have the privs for. However, three commands aren't greying out for people who don't have access to them:

bonus_icons
faqcat
note

All three do have permissions checks, so people without the priv can still use the command -- it's not a security issue. But we should still tidy things up so people aren't mislead about what commands they can use.

**Comment by kaberett** [comment]
Is this suitable for beginners?

**Comment by rahaeli** [comment]
Yes, it's a simple priv check and there's ample examples nearby I think.

**Comment by kaberett** [comment]
Fab, thank you!
##curated: beginner

**Comment by sgsabbage** [comment]
Claimed :)

@rahaeli From what I can see, faqcat can be used in list mode without any permissions - should it still be greyed out? Or, should list mode also require privs?

**Comment by rahaeli** [comment]
Oh, huh, I didn't realize faqcat could be used in list mode without privs. Yes, that should probably need privs -- being able to list things doesn't *hurt* anything, but there's no need for anybody without faq privs to ever use that command, so stick a priv check in while you're there?
