### ISSUE TITLE
Broken link on /site/opensource

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1467]
From https://www.dreamwidth.org/support/see_request?id=31149

"https://www.dreamwidth.org/site/opensource has a link (the last before the footer) to https://www.dreamwidth.org/support/submit.bml rather than https://www.dreamwidth.org/support/submit"

I've verified this. Nice easy fix for somebody.

**Comment by swaldman3** [comment]
##curated: beginner
##effort: (1) lower
##from: support
##severity: (1) minor
##is: bug

**Comment by dteklavya** [comment]
Claimed this one and also submitted a pull request.

**Comment by kareila** [comment]
Thanks! In the future, if you put e.g. "Fixes #1467" in the comment on the pull request, it will link and assign automatically. The formatting has to match exactly, and it has to be in the comment, not the title. GitHub is picky like that. 😁

**Comment by kaberett** [comment]
(Can this be closed?)

**Comment by kareila** [comment]
No. The pull request in question is #1494, which is waiting on requested changes, because the translation system is evil.

**Comment by dteklavya** [comment]
Sorry for the delay, I'll try and fix this ASAP.

On Thu, Aug 13, 2015 at 10:53 PM, Jen <notifications@github.com> wrote:

> No. The pull request in question is #1494
> <https://github.com/dreamwidth/dw-free/pull/1494>, which is waiting on
> requested changes, because the translation system is evil.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/dreamwidth/dw-free/issues/1467#issuecomment-130769058>
> .
>



-- 
Thanks,
Rajesh
