### ISSUE TITLE
let LJ::OpenID use the paranoid user agent on dev servers

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1468]
Related to #1418: when we switched modules from LWPx::ParanoidAgent to LWP::UserAgent::Paranoid, there were some API changes which made it to the live site undetected because LJ::OpenID does not use the paranoid user agent on dev servers. The error was fixed in #1460, but in the future, I believe such heartache could be avoided if we removed the dev server special casing.  The split dates from LJ days and I haven't seen any good arguments in favor of keeping it.

**Comment by alierak** [comment]
I think the only argument in favor might be that in a dev environment, you might actually want to access a URL that resolves to a private IP, if that's where you happen to be hosting a test site.

**Comment by kareila** [comment]
We might want to make that a user-configurable option instead of the default, then.

**Comment by afuna** [comment]
Hmm that's a good point -- but I think it makes sense to have it be something you turn on (or even just something we add when / if we ever need it) than having it magically happen behind the scenes.

**Comment by kareila** [comment]
We could just change the existing check for IS_DEV_SERVER to check for a config option instead, maybe call it SKIP_PARANOID_UA?

**Comment by afuna** [comment]
I would suggest USERAGENT instead of UA but otherwise I'm fine with those
