### ISSUE TITLE
Blank space missing after comma in credit module

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1478]
In Core2, in function print_module_credit(), there should be a blank space after the comma in:
```
else { $ret = $ret + ","; }
```

Easiest fix ever or what?! :)

**Comment by kaberett** [comment]
##curated: beginner

**Comment by dteklavya** [comment]
I'm claiming this one. Can someone please specify how to reproduce the issue? It looks like a simple fix but just need to make sure it actually fixes it :)

BTW, I'm new to DW.

**Comment by ninetyd** [comment]
Hi and welcome! When you use an official DW style (https://www.dreamwidth.org/customize/), you have a module section called 'credit' which appears in your sidebar. If the style lists several resources, they're separated by a comma but it lacks a space after the comma. You can see this on one of my testing accounts for example: https://experiment.dreamwidth.org/

For info, the file to edit is /styles/core2.s2

Hope I've been clear enough! :)

**Comment by rahaeli** [comment]
Quick note: once you make the change, you'll need to recompile core2 to see your changes. You can do that by running bin/upgrading/update-db.pl as the dw user. (You need to recompile every time you change core2 or else the changes won't take.)

**Comment by dteklavya** [comment]
Claiming.
