### ISSUE TITLE
"ContextualPopup-trigger" class added to icon URLs from non-DW sites

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1481]
http://www.dreamwidth.org/support/see_request?id=31207

I believe this is caused by the changes from #1319. We should make sure the relevant regex only triggers on icons from Dreamwidth and not LJ or IJ - the latter results in a blank white box when hovered over.

Pinging @afuna to take a look when she has time since it's related to a change she made. :love_letter:

**Comment by rahaeli** [comment]
And I have replied to the user!
