### ISSUE TITLE
Inconsistency in userheads for Ravelry

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1485]
The "Other Services" section of the profile uses http://s.dreamwidth.org/img/profile_icons/ravelry.png

The &lt;user name="" site="ravelry"&gt; tag uses http://www.ravelry.com/favicon.ico

It would be nice if these were the same image, but they're not!

**Comment by kareila** [comment]
So the userhead loads directly from the remote site by design, while the profile uses a static image from our site. Are you suggesting we update our profile image so that they look the same?

**Comment by rahaeli** [comment]
Hm. I don't know that they do need to be the same, actually -- the profile image is the site logo, the userhead image is intended to be the site's equivalent of the userhead. If somebody were doing the same thing with DW, for instance, the site logo/profile logo would be the swirly-D while the userhead logo would be the grey userhead. It's obviously more of an issue with sites that don't have the equivalent of a userhead, but I think it works to have them separate.

**Comment by kareila** [comment]
Having compared the two, I agree with D - the current configuration makes sense to me.

**Comment by kaberett** [comment]
Eh, fair enough. I was jarred because of the set of accounts I've got only twitter and Ravelry have differing icons in the two use-cases, and I _do_ read the list of other accounts in the profile and expect consistency of icons with userheads. I also sort of think it would be nice if we weren't sending one thing via a proxy and hotlinking the other for the sake of consistency, but there's me for you ;)

(Full disclosure: I really dislike the red-on-green of the new Ravelry userhead and much preferred the small green r. :-p)
