### ISSUE TITLE
"no text" error on entry posting loses security chosen from dropdown (beta update)

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1500]
1. Go to http://www.dreamwidth.org/entry/new 
2. Enter a title but no entry text 
3. Choose 'private' security
4. Hit post

You'll get a "yo, you need entry text" error. The title carries over and is pre-filled in the resulting form, but the security dropdown defaults back to public.

**Comment by kareila** [comment]
The controller is doing the right thing; the dropdown reverts to the selected security level if JavaScript is turned off.  Therefore the bug is somewhere in `htdocs/js/pages/entry/new.js` - probably in the `initSecurity` function, but I haven't been able to decipher it yet.

**Comment by kareila** [comment]
I think this line is the culprit:
```
var oldval = $security.data("lastselected");
```
In my testing, oldval is always undefined, but I can't figure out what the correct syntax should be.

**Comment by kareila** [comment]
```
var oldval = $security.closest('select').find('option').filter(':selected').val();
```

ALL HAIL STACKOVERFLOW.

**Comment by rahaeli** [comment]
Sweet!
