### ISSUE TITLE
Unicode characters in plaintext email notifications coming through as WTF-8

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1501]
This may be related to switching to SES for mail sending, or it might not be. (In other words, it might not be reproducable except in production; I haven't tried.) It did just start recently, though.

Text entered in UTF-8 is coming through in my (plaintext) email notifs as WTF-8. For instance, the following sentence in Russian:

Хва́стать, не коси́ть, спина́ не боли́т.

came through as:

Ð¥Ð²Ð°ÌÑÑÐ°ÑÑ, Ð½Ðµ ÐºÐ¾ÑÐ¸ÌÑÑ, ÑÐ¿Ð¸Ð½Ð°Ì Ð½Ðµ Ð±Ð¾Ð»Ð¸ÌÑ.

Text displays properly on website and in HTML emails. 

I'm not sure if this is worth spending too much time on, since encoding errors are enough to make strong people weep and it *does* work in HTML emails, but since it used to work and now it doesn't, I figured I'd file a bug.

**Comment by kareila** [comment]
Probably related: http://www.dreamwidth.org/support/see_request?id=31164

**Comment by kareila** [comment]
Possibly related: http://www.dreamwidth.org/support/see_request?id=31148

**Comment by kaberett** [comment]
I've started getting misc WTF-8 as well, in around the same timeframe (but it seems to be non-printing characters that are showing up in my e-mailed notifs). LMK if digging out examples is helpful.

**Comment by pseudomonas** [comment]
http://www.dreamwidth.org/support/see_request?id=31148 I think now is probably not related; I suspect a historical importer bug.
