### ISSUE TITLE
[Safari+JS] problem with input focus on /rename page

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1504]
If I visit dreamwidth.org/rename and try to input text into the "Rename token" text field, the focus immediately jumps up to the "Desired username" field.  Using control-click to paste text is the only workaround I've figured out so far.

I'm only able to reproduce this in Safari.  If I use Firefox or Chrome, the focus doesn't jump away.  I haven't checked to see if earlier versions of Safari are affected, but the same thing seems to happen in Safari on my iPad running iOS 8.3 as well.

There's no special JavaScript being loaded on the page, just the default site-wide stuff.

**Comment by afuna** [comment]
The label for the first form isn't closed :x

**Comment by rahaeli** [comment]
Confirming in 6.2.7 (8537.85.16.12)

**Comment by kareila** [comment]
Confirming that closing the labels (neither was closed!) fixes the issue in my testing. Will submit the fix shortly.
