### ISSUE TITLE
Show name of poster on "Edit tags" page

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1509]
https://dw-suggestions.dreamwidth.org/1375578.html

Was bug 4962 in the days of 'zilla.

Text of suggestion:

Description:
The "Edit Tags on an Entry" page currently has the fields:

* subject
* current tags
* [journal]'s tags
* entry text

This is fine if you're tagging within your own journal. However, when I'm tagging in a community, and especially tagging dw_suggestion's posts, I sometimes get curious about Who Submitted This, & it would be lovely to be able to see that information at the same time as tagging, rather than having to click about (which disrupts my concentration).

I can also see this being useful for batch-tagging in communities where posts are routinely tagged with the name of the poster.

Possible solutions include:

(1) always showing the username of the poster on the Edit Tags on an Entry page
(2) show the username of the poster only when editing tags on an entry posted to a community

Downsides: you end up with one extra uneditable line on the Edit Tags on an Entry page. Personally I can't get too worked up about that. ;)

**Comment by kaberett** [comment]
claim

##from: suggestions

**Comment by rahaeli** [comment]
Yeah, stick 'poster' (user-tagged) in as the top line of the list.
