### ISSUE TITLE
include table of contents on faqcat view

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1517]
Users can see all FAQs in a single category all at once by using the faqcat view, eg:

  https://www.dreamwidth.org/support/faqbrowse?faqcat=paidaccounts

It would be a nice touch if we included a table-of-contents at the top of that view, so each FAQ title is displayed up top, with the FAQ title in the ToC serving as an inside-the-page link to the FAQ in the list. (Because FAQ titles can change and we don't want to have to define a shortcode for each FAQ, permalink by number is probably best, so -- for instance -- ?faqcat=paidaccounts would have a ToC whose first element was "What is a paid/premium paid/seed account?" and the link goes to a #faq233 permalink, linking to the display of faq233 further down the page.)

**Comment by sgsabbage** [comment]
Claimed :)

@rahaeli What kind of styling are you thinking for the ToC? Something like the ordered list used for the FAQs on https://www.dreamwidth.org/support/faq, just smaller? Or some other option?

**Comment by rahaeli** [comment]
Ordered list styling like /support/faq is fine!
