### ISSUE TITLE
convert all http links to https in faqs

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1519]
(Similar to, but not exactly, issue #1520 .)

There are still a bunch of http:// links scattered through the FAQs. They should be changed to https:// links. I did Account Payments just now in #1518, but didn't do any of the others.

This can only be done on-site and by someone who has the faqedit priv, so it's a non-code-change. (Paging @kaberett and @zarhooie.)

As noted in #1520, the &lt;a href="site://faq/4">-style construct does automatically choose HTTPS now, so this is only correcting the non-FAQ links.

**Comment by kaberett** [comment]
Claim

**Comment by kaberett** [comment]
(Done up to the end of Paid Accounts.)

**Comment by kaberett** [comment]
NB I don't have the privs to edit FAQ summaries, and some summaries contain links that need updating. I can drop a list here, I guess? I'm flagging them up in the spr0t-tracking doc.

**Comment by kaberett** [comment]
@kareila, @rahaeli - issues of FAQ Summaries aside, I have now converted all site-internal links to use https rather than http, where the site:// shorthand was not immediately obviously relevant.

**Comment by kareila** [comment]
Thank you!  I'll leave this open for the summaries.

**Comment by rahaeli** [comment]
Hm, what do you mean by summaries?

**Comment by kaberett** [comment]
The thing referred to as a summary in e.g. http://www.dreamwidth.org/admin/faq/faqedit?id=13 and http://www.dreamwidth.org/admin/faq/faqedit?id=51 -- the Summary box appears greyed-out for me!

**Comment by rahaeli** [comment]
OH. Yeah, we don't use those anymore! I thought we'd removed that box entirely, in fact. I guess that if there was stored data in that field, it's showing? IDK.

Anyway, just ignore it. :)

**Comment by kareila** [comment]
Yes, if there's data saved for that field, it shows as read-only even if the feature is disabled.

**Comment by rahaeli** [comment]
Okay cool, we can safely ignore that then. :)

On Aug 31, 2015, at 11:56 AM, Jen <notifications@github.com> wrote:

> Yes, if there's data saved for that field, it shows as read-only even if the feature is disabled.
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Denise Paolucci
denise@dreamwidth.org
Dreamwidth Studios: Open Source, open expression, open operations. Join us: www.dreamwidth.org
