### ISSUE TITLE
update faqs to use site:// internal links and [[faqtitle]] vars

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1520]
Similar to, but not exactly, issue #1519.)

I've been hellaciously inconsistent with when I use the proper [[faqtitle]] var and when I just copy out the title of the FAQ. (Mostly because I can never remember the damn syntax for the [[faqtitle]] var, sigh.) So, when somebody's feeling in the mood to tidy, the FAQs could use a scrubthrough to replace, eg:

> &lt;a href="https://www.dreamwidth.org/support/faqbrowse?faqid=4">What are the extra services available?&lt;/a>

with 

> &lt;a href="site://faq/4">[[faqtitle:4]]&lt;/a>.

This can only be done on-site and by someone who has the faqedit priv, so it's a non-code-change. (Paging @kaberett and @zarhooie.)

**Comment by rahaeli** [comment]
Note: the &lt;a href="site://faq/4"> type construct does default to https:// now, so really #1519 is just for fixing all the http:// links to non-FAQ pages.

**Comment by kaberett** [comment]
Claim

**Comment by rahaeli** [comment]
Also, don't feel like this is an all-at-once thing -- I'm perfectly content for all of us to do the scrubbing over the next few months, really. Just filed it while I was thinking of it so I didn't forget. :)

**Comment by kaberett** [comment]
Currently off work crazy and this is exactly the kind of thing I find soothing, so I'm fine to just sit down and plug away at it :-) but will keep a note here of where I'm up to if I do it piecemeal, so we don't duplicate effort!

**Comment by rahaeli** [comment]
I figured it might be the kind of soothing repetitive task you find to be kabnip, just wanted to make sure you knew I did not expect it to be done all in one go. :)

**Comment by kaberett** [comment]
(Done up to the end of Paid Accounts.)

**Comment by kaberett** [comment]
nb I am *not* using site:// when e.g. linking to the shop etc because it didn't occur to me until I was halfway through that it might be good to work out the syntax for that; I am *only* doing this for internal links to FAQs; if it's desired to use site:// for all site-internal links then shout and I'll go through again and sort that out.

**Comment by kaberett** [comment]
@kareila, @rahaeli - I have now completed putting in [[faqtitle]] and site:// where relevant. There are a couple of points I haven't addressed, described in my previous comment - if appropriate could a new issue be opened for them? This issue as it stands is good to be closed. :-)

**Comment by kareila** [comment]
I'll defer to @rahaeli on this, since she is much more familiar with the FAQ system than I am.

**Comment by rahaeli** [comment]
Yes, you can (and we should) use site:// URLs for non-FAQ URLs -- it replaces the siteroot (ie, http[s]://www.dreamwidth.org). Like, the shop is site://shop, the inbox is site://inbox, etc.

**Comment by kaberett** [comment]
Okay, I will go back through and add those in -- it wasn't immediately apparent to me that that would be a thing that worked or what the structure would be (given that site://faq/xxx is not the format of FAQ URLs!). I've just poked through the wiki and failed to find a list of Things This Works For (it's definitely not at http://wiki.dreamwidth.net/wiki/index.php/FAQ_variables); is there one floating around?

**Comment by rahaeli** [comment]
You know what, forget everything I just said, I'm smoking crack. It does indeed not work for arbitrary URLs, I was thinking of [[siteroot]]. 

Sigh.


On Aug 31, 2015, at 11:48 AM, kaberett <notifications@github.com> wrote:

> Okay, I will go back through and add those in -- it wasn't immediately apparent to me that that would be a thing that worked or what the structure would be (given that site://faq/xxx is not the format of FAQ URLs!). I've just poked through the wiki and failed to find a list of Things This Works For (it's definitely not at http://wiki.dreamwidth.net/wiki/index.php/FAQ_variables); is there one floating around?
> 
> �
> Reply to this email directly or view it on GitHub.
> 

-- 
Denise Paolucci
denise@dreamwidth.org
Dreamwidth Studios: Open Source, open expression, open operations. Join us: www.dreamwidth.org

**Comment by kaberett** [comment]
No worries! If it makes sense to go back through and replace (currently hard-coded) https with [[siteroot]] that is totally a thing I can do :-)

**Comment by kareila** [comment]
For documentation purposes, you can figure out what site:// works on by looking at LJ::CleanHTML::ExpandLJURL.  (Looks like the syntax was lj:// on LJ.)
