### ISSUE TITLE
Possible to see tags used by deleted account

### ISSUE THREAD

**Issue by me-and** [dreamwidth/dw-free#1523]
If you view the profile page of a deleted user account, there's a link to be notified when the account is purged, which points to `http://www.dreamwidth.org/manage/tracking/user?journal=<username>`. If you follow that link, you get the list of things you can subscribe to, which includes "<username> posts a new entry tagged \<dropdown\>".

Where that dropdown includes all the tags that user ever used.

I'm pretty sure that, when a user deletes their account, they don't want other people to be able to see all the tags they had used. There's potentially a hell of a lot of information there. Certainly there is in the account where I just spotted this behaviour.

**Comment by rahaeli** [comment]
Can probably be fixed by just showing the "when the account is purged" subscription as an option if the account's deleted.
