### ISSUE TITLE
Unclear or absent error/success messages relating to tag removal permissions

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1528]
Specifically, relating to behaviours when attempting to add or remove tags from posts in commnities with restricted tagging permissions. Behaviour described occurs for user with permission to add (but not create) tags but not to remove them.

_Via /edittags:_ delete tag from _Current tags_ bar. Hit "Save changes". You are returned to the entry page with no error message; the tag you attempted to delete is still in place. Any tags you added from the existing list have been added.

_Via beta Edit Entry page (if you are post-owner):_ Remove tag from tag module. Hit "Save". Edit Entry page reloads with error message at top "Tags error: You are not allowed to delete tags from entries for this journal; the entry is still tagged with [[tag]]." <i>However</i>, any additional tags <i>added</i> are now visible in all other views of the entry (and possibly edits of body text/subject similarly go through - haven't tested) - this success is not indicated in any way. Suggest error message shows up on entry success landing page instead.

_Via old update/edit entries page:_ Not tested, sorry, don't quite have brain.

**Comment by chrisboyle** [comment]
claim

**Comment by kaberett** [comment]
HURRAH THANK YOU

**Comment by chrisboyle** [comment]
Old editjournal gets you this:

> ## Edit Entries
> 
> ## Error
> 
> [missing string /editjournal.bml.error.modify]
> 
> * Tags error: You are not allowed to delete tags from entries for this journal; the entry is still tagged with dienstag.

(nothing below)
