### ISSUE TITLE
tag merging is case-sensitive, tags are not

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1529]
From the suggestions queue, better just moved over to an issue since it's a bug:

In the Merge Tags page, strange things happen with comparisons to determine whether two tags can be merged into a tag with the same name as one of the user-supplied new tag name has capital letters (as iOS keyboards tend to capitalize words on the fly, this is easy to do there).

For example, I want to merge "beer" and "stout" and supply "Beer" as the new name. The merge facility tells me that this is not allowed as the new tag already exists but is not one of the tags to be merged — evidently the check against the main list is case-insensitive but the one against the merge list isn't.

**Comment by kaberett** [comment]
(Also theoretically very easy to do on Android keyboards, but this is outside my use-case for Android devices so I haven't run into it.)

**Comment by kaberett** [comment]
(Is this suitable for beginners?)

**Comment by kareila** [comment]
Yes, it's probably as simple as using the `lc` operator in the appropriate place. The trick is finding the appropriate place.

**Comment by rahaeli** [comment]
Chalk mark, $1. Knowing where to put it: $499,999.
