### ISSUE TITLE
Display "Default" instead of "All" on navstrip when viewing default reading page

### ISSUE THREAD

**Issue by sgsabbage** [dreamwidth/dw-free#1539]
From https://dw-suggestions.dreamwidth.org/578825.html

**Comment by sgsabbage** [comment]
And claimed :)

**Comment by sgsabbage** [comment]
Congratulations me on hitting the wrong button

**Comment by rahaeli** [comment]
The number of times I've hitten the wrong button are legion. :)

**Comment by sgsabbage** [comment]
I may potentially have thought that the close and comment button closed the window. Maybe. But I'll never admit it in court.
