### ISSUE TITLE
disable anon comments on entries by default if IS_DEV_SERVER is on

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1541]
Spambots tend to find entries on Dreamhacks that have been left running, and fill them up with spammer pee. (qv http://qdb.dreamwidth.net/dw/669 )

So, if IS_DEV_SERVER is on, the default setting for a newly-created account should be to disable anon comments, and people can re-enable on specific accounts/specific entries if they need anon comments on.

**Comment by pseudomonas** [comment]
On my dreamhack, in `etc/config.pl`, `$USER_INIT{opt_whocanreply}` already seems to be set to 'reg';
is `opt_whocanreply => $LJ::IS_DEV_SERVER ? 'reg' : 'all',` the desired behaviour?

**Comment by rahaeli** [comment]
Hm. Okay, if it's already the default, then that should suffice! I guess the worst of the spam happens in accounts that people manually switch to allow anon comments.

Note to self: write wiki page/dw-dev entry about spam prevention on a 'hack.
