### ISSUE TITLE
RTE sorts external sites alphabetically by character, capitals first

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1544]
The [insert] Account control in the RTE offers a list of External Accounts. Since everyone but me managed to capitalize the external site names, lower-case "github" is at the bottom of the list. 

a) we could just find out where it's pulling from and capitalize Github. 
b) it's the RTE on the old update page. Is it really worth going after with pitchforks and making it sort the list differently?

**Comment by azurelunatic** [comment]
It's probably in dw-free/cgi-bin/DW/External/Site/Github.pm 

line 19 is:

package DW::External::Site::github;

Would it break anything if I just capitalized it??

**Comment by kaberett** [comment]
nope, that's where I'd go to kick it, and capitalising it should make shit Just Work provided you check that it's capitalised consistently anywhere that's referred to (i.e. External::Site)

**Comment by fastbean-au** [comment]
I'll claim this.

**Comment by azurelunatic** [comment]
Woohoo! Go for it!

**Comment by kareila** [comment]
Fixed by #1598.
