### ISSUE TITLE
bonus_icons console command could use an 'xfer' param

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1546]
bonus_icons right now just has:

bonus_icons username: lists # of bonus icons
bonus_icons username add #: adds # of bonus icons
bonus_icons username remove #: removes # of bonus icons

I would also like "bonus_icons username xfer otherusername", which should:

a) Check to make sure that username and otherusername have the same confirmed email address (and fail if they don't with a "Email addresses do not match" error)

b) Remove all the bonus icons from username

c) Add all the bonus icons to otherusername

It will save me time, typing, and trouble. :)

**Comment by kaberett** [comment]
Are enough of the reqs for transfer of *all* bonus icons that you'd rather have transfer-all be the only option rather than having a baked-in transfer X?

**Comment by rahaeli** [comment]
Transfer-X can be handled with the existing add/remove -- it's pretty uncommon, yeah.

**Comment by kaberett** [comment]
Claimed!

**Comment by kaberett** [comment]
Hmm. I'm having trouble working out how to phrase the usage instructions if adding a subcommand that doesn't require count: the closest I'm at so far is 

> bonus_icons \<username\> [ \<subcommand>\ [ \<count\> | \<otherusername\> ] ]

...  which doesn't strike me as super clear. Is that acceptable/am I overlooking something obvious?

(The answer to this question determines how I re/structure my existing implementation, is the thing, and currently it's a repetitive sprawling monstrosity so it'd be nice to know which parts to trim. ;) )

**Comment by kareila** [comment]
What about `bonus_icons <username> [ <subcommand> <arguments> ]` and clarify the arguments for each subcommand in the descriptive text?  There's a similar existing case in the "faqcat" reference.

**Comment by kaberett** [comment]
Excellent point (I... clearly did not look hard enough when checking the reference for things to model off). Thank you!
