### ISSUE TITLE
Tracking notifications provide http links

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1547]
e.g. comment notifications - reply, view comment, view thread, etc.

These should, given https everywhere, be https. I assume. Given that I've dealt with this bit of ESN before and given that I'm doing some https tidying elsewhere (hi FAQs), I am going to claim this (and am indeed seeing if this works :-p)

**Comment by kaberett** [comment]
nope, it doesn't. cool. claimed!

**Comment by kareila** [comment]
This may be the same issue as #1354.

**Comment by kaberett** [comment]
it is and I am a failpanda who should sleep more

**Comment by kareila** [comment]
:heart: I am going to close this as a duplicate, but I would encourage you to get in touch with @afuna and see if she would mind you taking it over.  I doubt very much that she's worked on it recently.
