### ISSUE TITLE
Text consistency across comment submission buttons

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1550]
It seems to be the case that when prepping a comment for posting, *everywhere* but the Preview page your options are "Post Comment", "Preview", "More Options" (unless you're already looking at More Options, in which case it's still Post Comment). On the Preview page instead of "Post Comment" there's "Submit" - and I am me and consequently this inconsistency is annoying me (and is, of course, potentially confusing).

Had a chat with @anall who said to go ahead and file the issue; this probably qualifies for curated: beginner.

**Comment by ljacob** [comment]
I'd like to claim this, please.
