### ISSUE TITLE
Embedded fonts from Google blocked for being non-secure

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1551]
Report: https://www.dreamwidth.org/support/see_request?id=31469

"Since Dreamwidth is now on HTTPS and Google font serves from HTTP, Chrome and Firefox show Mixed Content warnings and will sometimes block the font from showing."

This is an issue in particular for a few of our official styles which use Google fonts (e.g. Database). My FF always prevents the font from being used.

**Comment by pseudomonas** [comment]
For official styles, can DW host its own fonts? Better for privacy as well as HTTPS.

**Comment by alierak** [comment]
Or at least use Google's HTTPS URLs for them?

**Comment by kareila** [comment]
Marked as beginner-level on the assumption that we only need to change font URLs to use https.

**Comment by ninetyd** [comment]
Using HTTPS instead worked for me in a custom layer.
