### ISSUE TITLE
"0E0" is not a number of spam reports

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1560]
When someone closes the spam report you were looking at before you try to close it, when you try to close it, it says that "0E0" reports were closed. 

This is an error state (http://www.perlmonks.org/?node_id=423714) which should probably be handled better. 

This is super low priority.

**Comment by kareila** [comment]
This can be fixed by changing `$rv->{count} = $count` to `$rv->{count} = $count + 0` in the appropriate place.  I will leave it as an exercise for the beginner to figure out the appropriate place.

**Comment by azurelunatic** [comment]
:D

**Comment by kaberett** [comment]
claim!
