### ISSUE TITLE
FAQ variables: [[journalurl]] should expand to HTTPS not HTTP

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1561]
Currently the FAQ variable [[journalurl]] expands to _http://username.dreamwidth.org_; it should expand to the HTTPS version.

**Comment by kareila** [comment]
Because you fixed journal_base, it will do the right thing if you are looking at an HTTPS page.  I verified this in production by visiting https://www.dreamwidth.org/support/faqbrowse?faqid=261 and seeing that it printed https links using [[journalurl]].
