### ISSUE TITLE
Entry QuickReply textarea too tall at small resolutions and/or large font sizes

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1562]
Reported in dw-maint: http://dw-maintenance.dreamwidth.org/68168.html?thread=2427976#cmt2427976

Here's a copy of the screenshot:

![image](https://cloud.githubusercontent.com/assets/1976742/9578574/c1b5e8fe-4fb0-11e5-9470-82e2b309cad3.png)

**Comment by kaberett** [comment]
If this is on an entry page, it is QuickReply not QuickerReply? (Trying to get my head around nomenclature here!)

**Comment by kareila** [comment]
Oops, I think you're right.  We should probably use more descriptive names, such as Entry QuickReply vs. Reading Page QuickReply.

**Comment by rahaeli** [comment]
I will confess that "quickerreply" was me and fu trying to think of something to call it that wasn't THINGY and it stuck :P

**Comment by sgsabbage** [comment]
Claimed

**Comment by sgsabbage** [comment]
Investigations thusfar seem to show that the textarea rowsize stays the same, but it doesn't calculate the font-size until you start typing, so that when you type in it goes 'this text area should be bigger!' and resizes it.

**Comment by kareila** [comment]
Seems legit. In my testing the whole thing reflows when you background the browser, but of course a mobile device won't do that.
