### ISSUE TITLE
we keep running out of new accounts on /stats

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1573]
Turns out when there's a flood of spammers and you're camping http://www.dreamwidth.org/stats you can burn through the 20 most recently created accounts pretty quickly when they're all spammers. 

Not sure what to do about it -- fetch more? idk.

**Comment by kareila** [comment]
We could add `AND u.statusvis != 'S'` to the query, if it's not a noticeable performance issue.

**Comment by zorkian** [comment]
That should be fine
