### ISSUE TITLE
Whitelist embeds from vid.me

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1574]
Request: http://www.dreamwidth.org/support/see_request?id=31555

Sample code (might need tweaking to follow whitelist standard template?):

        <iframe src="https://vid.me/e/v63?stats=1&amp;tools=1" width="640" height="360" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen scrolling="no"></iframe>

**Comment by cesy** [comment]
Claim
