### ISSUE TITLE
QuickerReply + access-locked post + OpenID = inaccurate error message

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1577]
From a support request left by an OpenID user (http://www.dreamwidth.org/support/see_request?id=31619): 

> I was on my reading page and clicked on Reply on a friend's locked entry. The quicker reply box opened up (surprising me because I typically open entries in new tabs before hitting reply). After typing in my comment I clicked on Post Comment and the following error popped up:
>
> Comment error: OpenID users aren't authorized to reply to this entry.
>
> I then opened up the entry in a new browser tab, pasted my comment in the reply box and was able to post my comment successfully.

**Comment by chrisboyle** [comment]
claim

A similar error happens when QuickReplying on the individual entry page. You get bounced to `www/talkpost_do` with a heading "Comment Not Posted" and a bullet point immediately below of the same "OpenID users aren't authorized to reply to this entry."

**Comment by chrisboyle** [comment]
Actually QuickReply on the entry page worked once I validated my email. There's still a bug there; the message should have said go validate your email. So to summarise, there are bugs in all three places

* Reading page: incorrect message, and should have allowed commenting once I validated my email.
* Entry page: incorrect message only (behaviour is correct).
* Reply page: incorrectly **allowed** a comment without validated email.

This is all with the default `opt_whocanreply=reg` ("registered accounts") - I assume the intent there is that OpenID users must validate their email to be allowed under that setting.

**Comment by chrisboyle** [comment]
* Reading page is AJAX-y via `/username/__rpc_addcomment` -> `RPC::Misc` -> `LJ::Protocol` -> `LJ::Comment->create` -> `LJ::Talk::Post::init` ("handles all the error checking") and `LJ::Talk::Post::post_comment` -> `enter_comment` which INSERTs.
* Entry page: Full-page post to `talkpost_do` -> `LJ::Talk::Post::post_comment`
* Reply page: as entry page.

**Comment by chrisboyle** [comment]
Having checked with Kareila about whether access-grant without verification is supposed to be sufficient, it is. This gives:

Page | -V-A | -V+A | +V-A | +V+A | Change?
--- | --- | --- | --- | --- | ---
Reading page (AJAX) | link | link | fail & wrong msg | fail & wrong msg | **Make both +V cases work.** Could also enable QR for -V+A?
Entry page (talkpost_do w/o explicit ID mode) | wrong msg | fail & wrong msg | works | works | **Fix message.**
Reply page (talkpost_do with explicit ID mode) | greyed | works  | works | works | No change. 

where "link" = no quickreply, instead it's just a link to the reply page; "greyed" = the OpenID radio button is correctly greyed out with a correct mesage about verification

**Comment by kareila** [comment]
Excellent writeup! This will be very helpful when figuring out which part of the site to test with and without the PR applied.

**Comment by chrisboyle** [comment]
My change seems to work:

Page | -V-A | -V+A | +V-A | +V+A
--- | --- | --- | --- | --- | ---
Reading page (AJAX) with **broken theme e.g. Black** | (link) | (link unnecessarily) | (link unnecessarily) | (link unnecessarily)
Reading page (AJAX) | **right msg** | **works** | **works** | **works**
Entry page (talkpost_do w/o explicit ID mode) (regardless of theme) | **right msg** | **works** | (works) | (works)
Reply page (talkpost_do with explicit ID mode) | (unavailable) | (works) | (works) | (works)

I've also briefly checked quick reply as invoked by the `recent` and `day` modes, now that #1611 allows that. I don't think an OpenID can get paid time so it can never view the `network` page?

**Comment by rahaeli** [comment]
Just confirming (for future reference) that an OpenID without a validated email address should be grouped in with 'anonymous' for screening/commenting purposes, while an OpenID with a validated email address should be grouped in with 'registered users'.

Also, yes, by all means move things out into a separate issue (ia ia S2 fth'agn), and you are correct that an OpenID can never view the network page.

**Comment by chrisboyle** [comment]
claim again (to get assigned now I'm in the org)
