### ISSUE TITLE
Whitelist flickr video embeds

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1578]
Flickr photo embeds are already whitelisted, I think, but it uses a totally different format for videos. Here's an example:

    <a data-flickr-embed="true" href="https://www.flickr.com/photos/simonwaldman/21226379018/in/dateposted/" title="Monika_catepillar">
    <img src="https://farm6.staticflickr.com/5722/21226379018_63393ea716_c.jpg" width="800" height="450" alt="Monika_catepillar"></a>
    <script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script> 

Knowing the way Flickr URLs tend to work, there's a good chance that everything after "/photos/" in the first URL is variable.

**Comment by cesy** [comment]
Claim

**Comment by kareila** [comment]
I'm sorry for not noticing this sooner, but this is the same issue as #1707, and as explained there, we can't whitelist this because the given embed code contains offsite JS.
