### ISSUE TITLE
in Lynx site skin, journal search page has no button to proceed to the next page of results

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1589]
Page just suddenly ends after printing the first 20 matches.

**Comment by chrisboyle** [comment]
I can't reproduce this, but maybe I'm looking at the wrong kind of search? When I view https://www.dreamwidth.org/directorysearch?int_like=cats&opt_format=pics&opt_pagesize=100&start_search=1 it has a set of numbered page selection links, with << and >> links at the ends, at the top and bottom of the results.

A query from https://www.dreamwidth.org/search has a "More Results..." button at the bottom.

**Comment by kareila** [comment]
I filed this when I was working on a bandwidth-restricted connection. I'll try again and see if I can still reproduce.

**Comment by kareila** [comment]
Yeah, the problem was happening on this computer consistently on the other connection but it works on my regular one.  Sorry for the false alarm!
