### ISSUE TITLE
manage/tags should not silently truncate renamed tags

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1590]
Probably the "rename" textbox should be of fixed length, _or_ there should be an error if you try to rename to something longer than the longest permissible tag.

**Comment by mmaceda** [comment]
Claiming this as my first bug fix!

**Comment by rahaeli** [comment]
Sweet! Welcome to DW development. :) Do I have your CLA on file? If so, remind me (by email is fine) what name it's filed under so I can doublecheck. If not, the instructions are here: http://wiki.dreamwidth.net/wiki/index.php/CLA

**Comment by kaberett** [comment]
Hi @mmaceda! I'm just wanting to check if you're still interested in this bug. If you are, is there anything I can do to help? :-)

(Asking because I'm at a contributor weekend and running through the curated bugs!)

**Comment by kaberett** [comment]
(use sub has_too_many, or is that overcomplicating things?)

**Comment by kaberett** [comment]
Turns out this was previously Bugzilla 1960, and included

> We should probably re-trim the tags after they're truncated as well.  This is an issue because if they get truncated immediately after a space (so the tag becomes 'this+is+a+long+tag+', the tag link doesn't work unless you place something arbitrary after the final '+' so that it doesn't get trimmed as trailing whitespace.

**Comment by pauamma** [comment]
Limiting the length in the text field is not a complete solution, because there's actually a limit both on number of bytes and characters. Plus, I'm not sure it qualifies as "not silent". Best to give an error message, I think.

**Comment by pauamma** [comment]
Should the same check be applied to merging tags? The code paths parallel each other. Or should that be another bug?

**Comment by pauamma** [comment]
Working with the existing data path severely limits the possibilities. The only easy option is to make all canonicalization loud, including truncation, space collapsing, and case folding. That sounds like a poor solution UX-wise, but the other ways I can think of all involve major rewriting of the code. Opinions?

**Comment by zorkian** [comment]
Oh I missed the questions somehow, sorry about that!

This is a good question. Hmm. Without knowing how much this happens, it's hard to tell if this will be an occasional annoyance or really flow breaking. We can try this as-implemented and just watch the reports; if it gets out of hand we will need to revisit.
