### ISSUE TITLE
Add 'Pattern' style by ninetydegrees

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1595]
https://dreamscapes.dreamwidth.org/132261.html
https://dreamscapes.dreamwidth.org/132936.html

Default theme is Found in the Desert.

**Comment by ninetyd** [comment]
Claimed!

Is it ok if I don't do the @ media stuff and leave it for someone else? Because I didn't get it even though Afuna gave me some pointers.

**Comment by rahaeli** [comment]
Sure, do what you can and then file a bug for whatever you don't get. :) It's not the end of the world if one or two styles aren't totally cross-device-enabled up front, since we have so many of them.

**Comment by ninetyd** [comment]
Awesome! Thank you!
