### ISSUE TITLE
Clarity & consistency when joining moderated-membership communities

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1599]
If you have been invited to join a moderated-membership community, the invitation shows up at http://www.dreamwidth.org/manage/invites with the options Accept and Decline.

If you hit "join community" on the hover information (from hovering over a userhead), after you have been invited, nothing obvious happens. 

It seems to me that either you should get an error message at this point <i>or</i> hitting "join community" on the hover info (sorry, proper terminology has gone missing) should be equivalent to hitting "accept" on the invitations management page.

**Comment by rahaeli** [comment]
Oh, good call.

**Comment by kaberett** [comment]
Okay, so it turns out that what actually happens is that hitting "join community" sends a join request, which the comm admin can then approve *even if you've already accepted the invitation*, and this is a bit of a mess and could be tidied.

**Comment by cesy** [comment]
claim

**Comment by cesy** [comment]
Okay, there is an outstanding potential thing where there may be other places that you could hit join instead of accept, such as on the community profile. But this will fix the hover menu one, and we can split off another issue for any other places you can find.

**Comment by kaberett** [comment]
Hmm. The nav strip should, I belatedly realise, probably have similar behaviour, for consistency's sake. Should I open a new issue?

(and THANK YOU @cesy. <3)

**Comment by kareila** [comment]
New issue please!
