### ISSUE TITLE
Drifting base layout always users 'topcomment' as the reply_container target so quickreply doesn't work on some pages

### ISSUE THREAD

**Issue by sgsabbage** [dreamwidth/dw-free#1609]
Specifically, here: https://github.com/dreamwidth/dw-free/blob/develop/styles/drifting/layout.s2#L1207-L1208 which is incompatible with how quickreply uses the target container.

**Comment by rshatch** [comment]
Claiming

**Comment by kareila** [comment]
Fixed by #1914.
