### ISSUE TITLE
Entries deleted via http://www.dreamwidth.org/editjournal offer the option to "Edit this entry again" on Success page

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1613]
They shouldn't.

**Comment by kaberett** [comment]
claim

**Comment by kaberett** [comment]
... https://github.com/dreamwidth/dw-free/blob/develop/htdocs/editjournal.bml line 369 already has "unless $deleted" next to where that line gets printed. That's exciting.

**Comment by me-and** [comment]
So yes, [line 369](https://github.com/dreamwidth/dw-free/blob/8851e01aa5cd49a6c9d7fcc658a207750b0eef94/htdocs/editjournal.bml#L369) has `unless $deleted` on it. But that's the line that's printing `.success.fromhere.viewentry`.

[The line that's printing `.success.fromhere.editentry`](https://github.com/dreamwidth/dw-free/blob/8851e01aa5cd49a6c9d7fcc658a207750b0eef94/htdocs/editjournal.bml#L370) is missing that, and that's probably why the bug.

**Comment by kaberett** [comment]
>:(

**Comment by me-and** [comment]
Yay, you pulled a face. I call that success.
