### ISSUE TITLE
dwscoalition.org deprecated

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1620]
There are a number of places where dwscoalition.org still appears, mostly in wiki references but a few emails. 

These should get cleaned up and replaced with the modern equivalent.

**Comment by kareila** [comment]
See also dreamwidth/dw-nonfree#102

**Comment by kaberett** [comment]
Is this issue now dealt with?

**Comment by kareila** [comment]
No, there are still some left that haven't been updated.

**Comment by srukle** [comment]
I'm claiming the rest I can find. I'm curious if we want to keep Mark's email the same. I do not know if he checks mark@dreamwidth.net or mark@dwscoalition.org

**Comment by kareila** [comment]
It is mark@dreamwidth.org everywhere else in the code. (not .net)

**Comment by srukle** [comment]
OK -- good distinction. The wiki then is wiki.dreamwidth.net

**Comment by rahaeli** [comment]
Also, I'm not sure if my email address is down anywhere as dwscoalition.org, but denise@dreamwidth.org is preferred for me, too. (I still get mail in both places, but it forwards.)

**Comment by srukle** [comment]
I made a pull request here.
https://github.com/dreamwidth/dw-free/pull/1673

When referring to a few places, should I look into other branches as well?

**Comment by srukle** [comment]
I did notice deprecated URLs in codetour. I'll wait back on your review before making changes.

**Comment by kareila** [comment]
You only need to check the develop branch. The other branches are release snapshots.

**Comment by rahaeli** [comment]
If you mean the codetour directory in the 'dreamhack' repository, I do believe there are still some wiki references in there to the old URL, yeah. They can probably stand to be changed!

**Comment by kareila** [comment]
This is now complete except for dreamwidth/dw-nonfree#102 and dreamwidth/dw-nonfree#106, leaving this open for reference since issues filed in nonfree are likely to be overlooked...

**Comment by kareila** [comment]
All done!
