### ISSUE TITLE
Country lists include two United Kingdoms with identical text

### ISSUE THREAD

**Issue by chrisboyle** [dreamwidth/dw-free#1623]
For example at `/manage/profile/` -> Location. One has value `GB`, the other `UK`.

**Comment by rahaeli** [comment]
Deliberate: see #1252.

**Comment by kareila** [comment]
We needed to add it so that we could properly display countries that were saved as UK previously, but do we want to continue to present two identical options for the user to select from?  That seems like bad UX.

**Comment by rahaeli** [comment]
Hm, good point.

**Comment by kaberett** [comment]
claim

**Comment by swaldman3** [comment]
Sorry to comment on what's perhaps a dead issue, but... Why is it necessary to keep both for legacy reasons? Why not do a one-off database update to convert the UKs to GBs, and then not have to keep the confusing duplicate entry, even hidden?

They both already display, if not overridden, as "United Kingdom of Great Britain and Northern Ireland", so AFAICS there's no worry about forcibly changing somebody's profile.

Possibly I'm missing something obvious and important, though :-)

**Comment by kaberett** [comment]
Query: is https://www.dreamwidth.org/support/see_request?id=36930 plausibly a result of this?
