### ISSUE TITLE
Last N Hours reports do not do the right thing with IPv6 addresses

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1628]
http://www.dreamwidth.org/admin/spamreports?mode=last06hr_a will illustrate this for a little while, and http://www.dreamwidth.org/admin/spamreports?mode=last24hr_a for a while longer. 

These are accessed from http://www.dreamwidth.org/admin/spamreports and you will need the antispam privs to see these pages. http://wiki.dreamwidth.net/wiki/index.php/Developing_Antispam

a) it has an IPv6 address and displays the correct count for that address
b) it displays an OpenID user in the listing and the link reflects a user not an IP
c) when you get to the report, it's not the IPv6 results, it's by=posterid rather than by=ip and there's nothing there because the OpenID user hasn't had any spam reports generated against it http://www.dreamwidth.org/admin/spamreports?mode=view&by=posterid&what=2601:282:301:17&state=open / http://www.dreamwidth.org/admin/spamreports?mode=view&by=posterid&what=2601:282:301:17&state=closed
d) when you change the by= to by=ip, it displays the IPv6's reports http://www.dreamwidth.org/admin/spamreports?mode=view&by=ip&what=2601:282:301:17&state=open / http://www.dreamwidth.org/admin/spamreports?mode=view&by=ip&what=2601:282:301:17&state=closed

My guess is that the lastn hours page sees something that "doesn't look" like an IP in there, and then treats it as a user even though it should not do so; if you also want to poke at the individual spam report page to make sure that it's not possible to have a mistaken identity situation, that would also be good. 

Spamwhackers have been instructed that if they see an OpenID in the "last N hours (anonymous)" spam roundup, to not do anything to that OpenID (if they have the powers to) as it has done nothing wrong and is the victim of a mistaken identity situation.

**Comment by kareila** [comment]
claiming

**Comment by kareila** [comment]
If the given report key contains a period, it is treated as an IP address.  OpenID display names contain periods. *headdesk*
