### ISSUE TITLE
whitelist google ngrams

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1640]
This handy little tool from google lets you display how often Google finds a given phrase, or two, in its literary corpus. 

It uses iframes. 

Example: 

<iframe name="ngram_chart" src="https://books.google.com/ngrams/interactive_chart?content=bussard+ramjet&case_insensitive=on&year_start=1970&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CBussard%20ramjet%3B%2Cc0" width=900 height=500 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no></iframe>

Request: 
http://james-davis-nicoll.dreamwidth.org/8429313.html (subject: "I wish I could still embed ngrams")

**Comment by rahaeli** [comment]
Do you have a sample of the actual code?

**Comment by azurelunatic** [comment]
I could have sworn I'd put it in! Let's try putting in some iframe-breaking spaces. 

< iframe name="ngram_chart" src="https://books.google.com/ngrams/interactive_chart?content=bussard+ramjet&case_insensitive=on&year_start=1970&year_end=2008&corpus=15&smoothing=3&share=&direct_url=t1%3B%2CBussard%20ramjet%3B%2Cc0" width=900 height=500 marginwidth=0 marginheight=0 hspace=0 vspace=0 frameborder=0 scrolling=no>< /iframe>

**Comment by azurelunatic** [comment]
Ha, I had put it in, but it seems like Github ate the iframe.

**Comment by rahaeli** [comment]
Lol.
