### ISSUE TITLE
Punctuation marks in comment subjects are converted to HTML entities when replying by email

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1643]
Keep forgetting to file this:

If someone posts a comment with a word like "don't" in the subject, it will be converted to `don&#39;t` in the re: subject when replying by email.

**Comment by kaberett** [comment]
This looks to me as though the responsible section of code might well be around line 270 in cgi-bin/DW/EmailPost/Base.pm, but I am not sure I have the brain to work it out further than that!
