### ISSUE TITLE
support notification (plain-text, at least) emails missing the [[sitename]] var

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1644]
support.email.notif.update.body3 starts with:

> A follow-up to the following [[sitename]] support request has been submitted:

In practice, that comes out as:

> A follow-up to the following  support request has been submitted:

(Github may eat the two spaces after 'following' and before 'support', but there's two spaces there.)

Looks like something ain't being set right. (And I looked back at my inbox -- where old email goes to DIE -- and discovered that for at least the year and a half since the last time I cleared out old email, it's never been working. Heh.)

**Comment by rahaeli** [comment]
Same problem exists in support.email.notif.new.body2 (the email that gets sent out for a new support req, not a followup) as well.

**Comment by kareila** [comment]
Yeah, the argument hashes for these ml calls need to be updated in cgi-bin/LJ/Support.pm to include `sitename => $LJ::SITENAMESHORT` in order for "Dreamwidth" to get printed there.
