### ISSUE TITLE
add Google Calendar to embed whitelist

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1646]
From http://www.dreamwidth.org/support/see_request?id=32273 (2/2)

Old Google Calendar embeds that use www.google.com still work, but new ones use calendar.google.com and need whitelisting.

Example content:
```
<iframe src="https://calendar.google.com/calendar/embed?src=en.usa%23holiday%40group.v.calendar.google.com&ctz=America/Chicago" style="border: 0" width="800" height="600" frameborder="0" scrolling="no"></iframe>
```

**Comment by srukle** [comment]
I can claim this.

**Comment by srukle** [comment]
pull request made: #1648
