### ISSUE TITLE
Cross-posting Markdown doesn't work

### ISSUE THREAD

**Issue by me-and** [dreamwidth/dw-free#1649]
I've just tried to cross-post from Dreamwidth to LiveJournal, where the original Dreamwidth post had `!markdown` in the first line and was correctly formatted as such. The LiveJournal post was cross-posted successfully, but with the raw formatting still in place (`*` around words that should be italics, double `<br>` around paragraphs, `!markdown` on the first line).

I'm using the beta Create Entries page, in case that makes any difference.

**Comment by me-and** [comment]
@kaberett tells me they're sure they've seen this discussed, but neither of us can find any kind of issue for it…

**Comment by kaberett** [comment]
HA. Bugzilla 4527.

**Comment by kareila** [comment]
@zorkian did some initial work on this which is still viewable here: https://github.com/zorkian/dw-free/commit/2a9e8c791baf3ec5b4504b192793fd29d12b61d3

The given caveat is that it doesn't send opt_preformatted to the remote site, plus @alierak pointed out significant overlap with existing code in LJ::CleanHTML::clean_event.

**Comment by kareila** [comment]
claiming
