### ISSUE TITLE
comment links inconsistent with regards to styling.

### ISSUE THREAD

**Issue by woggy** [dreamwidth/dw-free#1650]
While most links in the comment header (reply, hide/show, thread navigation, etc) preserve the given styling of the current page (light, site, mine), the permanent link to the comment (text "link", at least in the styles I've looked at) does not.  For consistency, I suggest changing the permalink to also preserve styling, unless there's a compelling reason not to.

**Comment by rahaeli** [comment]
Hm. The theory behind leaving the permalink stripped bare of ?formatting arguments is that it should be a permanent link -- if in the future we ever change the ?formatting args, those links would no longer be correct. Also, I think permalinks should be as bare-bones as possible.

I could probably be talked out of this if people feel strongly about it, but my instinct is to say WONTFIX...

**Comment by kareila** [comment]
I was about to say the same thing.

**Comment by woggy** [comment]
Fair enough! I can certainly appreciate the logic behind keeping permalinks stripped of clutter. It just struck me (and the acquaintance who brought it to my attention) as odd, that those were the only links in the comment section that didn't preserve stylating.
