### ISSUE TITLE
Quick*Reply on non-reading-page views needs to update comment count

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1651]
Related to #1626 (magical jQuery pluralisation): implementation of Quick*Reply for views other than the reading page as implemented for #1306 does not (but should!) include updating the comment count link, for consistency.

Specifically, when using Quick*Reply from kaberett.dreamwidth.org (or any other journal) on a post with no comments, the comment count indicator does not appear. If one comment exists, the second comment triggers an update to "2 comment" per #1626.

**Comment by kareila** [comment]
So to clarify, it does update the numeric count if one exists, but doesn't add the "1 comment" text if no comments exist?

**Comment by kaberett** [comment]
Correct.

**Comment by sgsabbage** [comment]
Claiming
