### ISSUE TITLE
Punctuation marks in PM subjects are converted to HTML entities

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1652]
e.g. (from a seven-reply-deep conversation): *Re: [...] just so I don&amp;amp;amp;amp;amp;amp;#39;t go more [...]*

This should probably not happen; compare with #1643.

**Comment by rahaeli** [comment]
Huh, I could've sworn we had an issue open for this already.

**Comment by kaberett** [comment]
If so I haven't seen it go past (and I did yesterday pull out of memory a 'zilla bug, for whatever *that's* worth)...

**Comment by rahaeli** [comment]
Aha, I think I was thinking of #1453.

**Comment by kaberett** [comment]
(LJ::Protocol around line 495?)

**Comment by kaberett** [comment]
claim
