### ISSUE TITLE
entry title on post-update success landing page does not interpret HTML

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1656]
If you have HTML in your subject line (used frequently in dw-tos, for instance: subject lines are all in the form of "&lt;a href="site://support/12345">12345&lt;/a> | brief case summary"), it's not interpreted in the entry metadata on the post-update success landing page. It should have the same display/escaping/etc as the entry does when viewed!

**Comment by kaberett** [comment]
Not fixed by #1641.
