### ISSUE TITLE
Quick Reply: clicking on Browse icons posts comments (Recent page)

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1657]
http://www.dreamwidth.org/support/see_request?id=32462

Clicking on browse icons in the QR form immediately posts the comment. This seems to be true on recent pages but not on reading pages. Haven't tested it on day pages or network pages.

**Comment by kareila** [comment]
This and #1651 probably need the same fix, to make sure the QR-related JS is loaded in the other views.

**Comment by kaberett** [comment]
The user reports in comments on the support ticket that 
> Quick bit of more info. I saw on the bug page for this that day and network pages hadn't been tested yet. So I did a quick test to see what would happen. It works fine on the Network page, but the glitch happens on the Day page. Just wanted to let you know!

**Comment by sgsabbage** [comment]
Claimed
