### ISSUE TITLE
.bmp in multiple icon uploads returns human-unfriendly error message

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1660]
Attempting to upload multiple icons, of which one is unsupported file type .bmp, returns an error message of "Hook: 'enddata' returned false" instead of a report that .bmps aren't supported. 

Singular upload attempt of a .bmp returns the expected message of "file type not supported", however, and multiple uploads with supported file types go through fine.

(Was Bugzilla 4546 and has just been raised again in Support - http://www.dreamwidth.org/support/see_request?id=32477. I have copied across all the text from bug excluding headers and so on, but I haven't tested to confirm whether this is a problem that only affects bitmaps.)

**Comment by kareila** [comment]
http://www.dreamwidth.org/support/see_request?id=33278
