### ISSUE TITLE
Page title for viewing custom access filters uses filter number not name

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1669]
i.e. "kaberett | (XX)" rather than "kaberett | (groupname)".

The equivalent issue for reading pages/subscription filters was bug 5320 (and subsequently fixed post-transition to GHI though I can't find any trace of it on Github).

**Comment by kaberett** [comment]
claim

**Comment by kareila** [comment]
I found the line you need to change! It's in LJ/S2/FriendsPage.pm, line 155:
`$p->{filter_name} = $opts->{securityfilter};`

To change that to the name of the group, you'll need to call the trust_groups method:
`my $filter = $u->trust_groups( id => $opts->{securityfilter} );`

Then once you have the filter object, `$filter->{groupname}` will get you what you need.

**Comment by kaberett** [comment]
Ah, excellent! Thank you so so much for digging that out for me.
