### ISSUE TITLE
/admin/translate should probably not be visible if you don't have privs

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1670]
Someone reported this (Google had apparently cached one of the pages involving FAQ text) -- it's not a security problem since there are permissions checks for being able to change the text and/or save your changes, but we should probably make it that you can't load the pages, too.

(Originally on LJ there was no priv check so people could view the progress and watch the translation process -- see http://www.livejournal.com/translate -- but since we moved into the /admin directory a while back, it does LOOK like we're exposing things we shouldn't even though it doesn't really matter.)

**Comment by kareila** [comment]
I've found it useful to have the read access for development purposes. What if we restrict it to logged in users? That would solve the Google caching issue.

**Comment by rahaeli** [comment]
Logged in users would be fine! Honestly I'm not worried at all about it being visible (it was, and still is, public on LJ so people could check on how up-to-date a particular translation was), it's just that when you have something in an /admin directory world-visible it certainly LOOKS like you're exposing something you shouldn't and that makes people nervous.
