### ISSUE TITLE
Beta update time weirdness: 23:30

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1671]
One of my folks observed that when you create an entry using the new beta update page between 23:30 and 00:00 (the nearest she could figure), the timestamp sticks at 23:30 and cannot be changed. I'm duplicating the same in GMT -8. 

Things I have tried so far during the affected time range: 
* posting without stickyticky tickied (23:30)
* posting with stickyticky tickied (23:30)
* posting with stickyticky tickied, and whacking the "hey change the time y0!" button (23:30) 
* trying to edit the time post-posting to the correct value of 23:53 or whatever (allowed to type in, but upon loss of focus jumped back to 23:30) 
* trying to edit the time in the box manually before posting (allowed to type in, but upon loss of focus it immediately jumps back to 23:30) 

Of interest, it displays the time correctly at first load of the page, then jumps to 23:30. 
After midnight hit, I thought of editing the time to something that was not 23:30; values before 23:30 worked (such as 23:19, and any value for any other hour I tried). 

Is this the same thing as #1502?

**Comment by azurelunatic** [comment]
My correspondent is in GMT -4, and this is happening in both our local times, so probably safe to say that this is related to local time rather than GMT.

**Comment by rahaeli** [comment]
Weird. I'm reproducing in both Chrome and Firefox.

**Comment by sgsabbage** [comment]
Claiming

**Comment by sgsabbage** [comment]
This can also be replicated outside of the times 23:30 - 00:00 by setting the timestamp on the entry to 23:40. At which point it changes back. Whee. >:[
