### ISSUE TITLE
add DeviantArt to profile list

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1674]
Suggestion seen on Twitter and I'm not gonna bother with making them go through dw-suggestions :) 

For profile: username should link to username.deviantart.com
For user tag: userhead should link to username.deviantart.com/gallery, username should link to username.deviantart.com

**Comment by kaberett** [comment]
Already exists! And even I got around to putting it in the FAQ: http://www.dreamwidth.org/support/faqbrowse?faqid=87

Want me to tweet back @ them?

**Comment by rahaeli** [comment]
Huh, I didn't see it on the profile page as an option when I checked. (I did look!) Am I just missing something?

**Comment by kaberett** [comment]
... huh, no, okay. So the username tag does exist, but the profile field doesn't.

**Comment by rahaeli** [comment]
right then! Title of issue edited. (The person tweeting only mentioned the profile, not the username tag, anyway.)

**Comment by srukle** [comment]
I might be able to claim this. This is a quick right up of what I think _might _need to be done, but I did not look too extensively.

https://gist.github.com/srukle/08d4e5a70b05d3aadc0d

**Comment by rahaeli** [comment]
You also need to add the userprop to the props list! You can see the last thing that was added to the profile here:

   https://github.com/dreamwidth/dw-free/commit/fe0000fc597cdca99eb9c52b224a4b1976d31d69

**Comment by srukle** [comment]
OK -- so I'll make changes on my hack space today:
https://gist.github.com/srukle/ed1667fdd3eefada4134 -- in bin/upgrading/proplists.dat
https://gist.github.com/srukle/08d4e5a70b05d3aadc0d -- in dw-free/blob/3868ae55348e08737ad2eba430b504d90b649f06/cgi-bin/DW/Logic/ProfilePage.pm

I'll update this space with the result.

**Comment by rahaeli** [comment]
Sounds excellent!

**Comment by srukle** [comment]
Followed this example: https://github.com/dreamwidth/dw-free/commit/fe0000fc597cdca99eb9c52b224a4b1976d31d69

Received this error when going to edit profile:

Kinda messy to go through right now. I'll run a reinstall on Dreamhack and try again.

`[Error: syntax error at /dreamhack/home/8425-srukle/dw/htdocs/manage/profile/index.bml line 412, near ""deviant_art," $ML" syntax error at /dreamhack/home/8425-srukle/dw/htdocs/manage/profile/index.bml line 438, near "; }" syntax error at /dreamhack/home/8425-srukle/dw/htdocs/manage/profile/index.bml line 443, near "; }" syntax error at /dreamhack/home/8425-srukle/dw/htdocs/manage/profile/index.bml line 537, near "; }" syntax error at /dreamhack/home/8425-srukle/dw/htdocs/manage/profile/index.bml line 734, near "} }" @ newhack.dreamwidth.net]`

**Comment by rahaeli** [comment]
Looking at that error, I'd guess you've got an extra " somewhere in line 412 (or the line before it), which is throwing everything off!

**Comment by srukle** [comment]
Alright -- on spring break, so I can look at this. Right now I found this error:

`[Error: Invalid userprop deviant_art passed to preload_props. at /dreamhack/home/8425-srukle/dw/cgi-bin/LJ/User/Account.pm line 790. @ newhack.dreamwidth.net]`

Line 790 >>
`           die "Invalid userprop $_ passed to preload_props." unless $p;`

`           next if exists $u->{$_};
            my $p = LJ::get_prop("user", $_);
            die "Invalid userprop $_ passed to preload_props." unless $p;
            if (defined $mem->{"uprop:$uid:$p->{'id'}"}) {
                $u->{$_} = $mem->{"uprop:$uid:$p->{'id'}"};
                next;
`

I'm unsure what the following list does, so I simply added a 40 arbitrarily. I believe the problem should be fixed if I have the correct number.

Found at  htdocs/manage/profile/index.bml 
lines 425*.

`            foreach my $p (
                           ["ao3", $ML{ '.services.ao3' }, 40],
                           ["aolim", $ML{'.chat.aolim'}, 28],
                           ["delicious", $ML{ '.services.delicious' }, 40],
                           ["diigo", $ML{ '.services.diigo' }, 16],
                           ["etsy", $ML{ '.services.etsy' }, 20],
                           ["ffnet", $ML{ '.services.ffnet' }, 30],
                           ["github", $ML{'.services.github'}, 39],
                           ["deviantart," $ML{'.services.deviantart'}, 40],
                           ["google_talk", $ML{'.chat.googletalk'}, 60],
                           ["icq", $ML{'.chat.icquin'}, 12],
                           ["jabber", $ML{'.chat.jabber'}, 60],
                           ["last_fm_user", $ML{'.services.last_fm'}, 255],
                           ["pinboard", $ML{'.services.pinboard'}, 30],
                           ["pinterest", $ML{'.services.pinterest'}, 30],
                           ["plurk", $ML{ '.services.plurk' }, 255],
                           ["ravelry", $ML{ '.services.ravelry' }, 40],
                           ["skype", $ML{'.chat.skype'}, 40],
                           ["tumblr", $ML{ '.services.tumblr' }, 255],
                           ["twitter", $ML{ '.services.twitter' }, 40],
                           ["yahoo", $ML{'.chat.yahooid'}, 33],
                          )
`

**Comment by kareila** [comment]
Once the userprop is defined in bin/upgrading/proplists.dat, the information in that file must be reloaded by running bin/upgrading/update-db.pl again. That should clear up the invalid userprop problem.  But I would prefer using "deviantart" instead of "deviant_art" so that it matches the site name.

The number associated with the profile field is the maximum username length. For Deviantart, that appears to be 20. If that's not clear, feel free to add a helpful comment in the code!

**Comment by srukle** [comment]
I changed deviant_art to deviantart throughout. I also changed my initial 40 to 20. I found two syntax problems, but they did not result in the error above. ((There was a space between the colon and no comma in the list.))

After this, I run:

`perl bin/upgrading/update-db.pl`

and

`./bin/upgrading/update-db.pl`

I get this in the terminal:

`Updating cluster: 0
# Warning: unknown live table: exitstatus
# Warning: unknown live table: funcmap
# Warning: unknown live table: note
# Warning: unknown live table: job
# Warning: unknown live table: error

cluster: status
      0: OKAY

# Done.
`

I still have the same problem.

`[Error: Invalid userprop deviantart passed to preload_props. at /dreamhack/home/8425-srukle/dw/cgi-bin/LJ/User/Account.pm line 790. @ newhack.dreamwidth.net]`

I apologize that this has taken me so long to get this right. Wow. O.O

**Comment by rahaeli** [comment]
Don't apologize! These systems are more complex than they look at first glance. (The "failed to run upgrade-db.pl" problem has bit me on the ass more times than I can count; I should have thought of it.)

Looking at your original Gist, I've just spotted something that might be the problem: there's a space between the propname and the colon. 

> userproplist.deviant_art :

After you changed it to 'deviantart', is that space still there? That might be the problem...

**Comment by srukle** [comment]
Hi Jen -- yes I did spot this mistake and fixed it. I'm updating my Gist now and placing the links below.

This is what my current code looks like. I'm thinking I'm doing something wrong with the perl script Kareila mentioned above. If I had a larger knowledge of the scope of the program, maybe I would have a better idea what it all does. :blush: 

1: https://gist.github.com/srukle/ed1667fdd3eefada4134
2: https://gist.github.com/srukle/08d4e5a70b05d3aadc0d
3: https://gist.github.com/srukle/8458bf4ea375a475add5

**Comment by rahaeli** [comment]
Gah, sorry, yeah, you said you'd spotted that and fixed it. I was reading too quickly and missed that part.

Dumb question: did you rerun update-db.pl after changing deviant_art to deviantart? That error message implies that the userprop isn't properly created, so, hrm.

Let's check to see what userprops exist for a user on your 'hack.

1) Go to /admin/priv and grant your account the 'canview' priv with argument 'userprops'. Save changes.
2). Go to /admin/propedit and put in any username.
3). Scroll down and look for the userprop you created. Is it there? 

(also, just FYI, I'm Denise, Jen is kareila! Sorry, usernames->real names are tough sometimes.)

**Comment by srukle** [comment]
Sorry about that, Denise. I _do_ know your name. I'm just reading this thread from my browser and email and mixed up your names. :sweat: 

So I went to /admin/console/ with my test account me1. But the commands you asked me to execute did not work. Am I supposed to have an admin account? I couldn't find docs about that.

**Comment by kaberett** [comment]
Hi Sam! You're going to need to make sure that your account has the necessary privs. You might need to do this by logging in as the system user -- see http://wiki.dreamwidth.net/wiki/index.php/System_account and http://wiki.dreamwidth.net/wiki/index.php/Privs! I'm happy to go into more detail if there's anything you're unsure about in those pages (and then to update them so they're clearer).

**Comment by rahaeli** [comment]
It's cool, I figured I'd just make sure. :)

And sorry, I forgot a step! In order to grant privs on /admin/priv you need to be logged in as an account that has the priv admin:*. By default, on a new install, the only account that has admin:* is the system account (system). If you don't do your work/on-site testing as system, you can grant admin:* to another account by logging in as system and granting that priv to somebody else. To do that:

1) Use /bin/upgrading/make_system.pl to reset the password for 'system' if you've forgotten it.
2) Log in as 'system'.
3) Go to /admin/priv. Enter the name of the account you usually use for on-site testing.
4) You'll see a list of the privs that account has. In the drop-down box at the bottom, select 'admin' for the priv, and enter "*" for the argument.
5) Save.

Then, log out of system and log in as your primary on-site testing account, then go back up and grant that account canview:userprops. (You can also just grant canview:userprops to system and check it that way, but it's a good idea to give your regular testing account admin:* so you can grant yourself future privs if you need them. Also, a lot of priv checks check against "does this person have the priv they need OR do they have admin:*", so granting yourself admin:* will sidestep the need to grant a lot of individual privs.

**Comment by kareila** [comment]
Sorry Sam, check the wiki docs for the arguments we use when running the script, I think it's "./bin/upgrading/update-db.pl -r -p"

Without the -p the props won't get updated!

**Comment by rahaeli** [comment]
Sigh. I keep suggesting Helpful Things that are not in the least bit helpful; I think Jen's right.

(At least now you know how to grant yourself privs? And I massively expanded the wiki priv documentation? Sigh.)

**Comment by kaberett** [comment]
Well, *I'm* pleased the wiki's more complete :-)

**Comment by srukle** [comment]
Thank you for all the resources. Learned a lot today. And look, it works now. :-) Sending PR soon.
![untitled](https://cloud.githubusercontent.com/assets/9255609/13902474/e1f7b042-ee17-11e5-9d6e-754c116c6843.png)

**Comment by rahaeli** [comment]
VICTORY. Congratulations and excellent work!
