### ISSUE TITLE
HTTPS URL not working to add OpenID to my circle

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#1687]
My friend's WordPress blog is available via HTTPS at [example]:

https://friend.wordpress.com/

I try that at https://www.dreamwidth.org/manage/circle/edit in the "Account name or OpenID URL" field, click "Add/Save", and get the error:

"User https://friend.wordpress.com/ does not exist."

If I remove the "s" in the protocol and try 

http://friend.wordpress.com/

then the OpenID gets successfully added to my circle.

I'd like to be able to use the HTTPS URL to add my friend.

I see in [the WordPress.com documentation on using them as an OpenID provider](https://en.support.wordpress.com/settings/openid/) that the example URL they use is not SSL-protected:

> An OpenID is a URL, and your OpenID is the URL of your blog, for example: http://matt.wordpress.com/

So maybe this is a WordPress-specific issue? I'm not sure.

**Comment by brainwane** [comment]
I don't know whether this is related to #1355.

**Comment by rahaeli** [comment]
I think it's the same issue as #1355, yeah.
