### ISSUE TITLE
Posting to a moderated comm gives landing page with missing subject

### ISSUE THREAD

**Issue by cesy** [dreamwidth/dw-free#1688]
If you post an entry to a moderated comm, you get to a landing page with the message "Your entry is in the moderation queue. The community administrators will accept or reject it." The next line says "The entry was posted with the following subject:" and doesn't display the subject even if there was one.

**Comment by kareila** [comment]
This sounds vaguely familiar. Can you check and see if it still happens with #1658 applied?

**Comment by cesy** [comment]
It still happens when the subject doesn't have any HTML in.

**Comment by kareila** [comment]
Sorry I wasn't clear. The changes I made to editjournal.bml in #1658 fix a case where the "no subject" text wasn't being printed.  I can test it later if it's not convenient for you to do so right now.

**Comment by kaberett** [comment]
The entries in question have a subject (rather than no subject). There is no additional information at all provided after the colon in the "This entry was posted with the subject:" string. @cesy, could you maybe grab a screenshot if you've still got the page open? <3

**Comment by cesy** [comment]
![dw error 1](https://cloud.githubusercontent.com/assets/570999/13198314/a16a177a-d7fd-11e5-9c07-21b90fc90e49.png)
![dw error 2](https://cloud.githubusercontent.com/assets/570999/13198315/a16d4300-d7fd-11e5-82a8-510681604c3d.png)

**Comment by kareila** [comment]
Does it only happen with the beta entry form?

**Comment by cesy** [comment]
Yes: 
![dw error 3](https://cloud.githubusercontent.com/assets/570999/13199160/7efbeaac-d815-11e5-8f51-b9ce78c74dc7.png)

**Comment by kareila** [comment]
So it looks like the "following subject" text is being printed unintentionally in this case, since it isn't displayed on the older form's success page.

**Comment by me-and** [comment]
Claim. Fix is almost done, too.
