### ISSUE TITLE
Banning an OpenID user exposes their ext_?? username.

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1691]
To reproduce:
- Log in as a user
- Hover over an OpenID user's usericon, and select "Ban User"
- Note that the resulting popup, which asks "Are you sure you want to ban $user", uses the ext_?? username for the OpenID user rather than their friendly one. It probably shouldn't.

Only tested on dreamhack.

**Comment by kareila** [comment]
Confirmed this is also happening in production.

**Comment by kareila** [comment]
See similar issue #1608 for the type of fix needed.

**Comment by ljacob** [comment]
claim please

**Comment by me-and** [comment]
Not sure if the fix will be the same here, but it might be worth checking out PR #1615, which was my fix for the similar bug #1608.

**Comment by me-and** [comment]
...oh, @kareila already said that. Never mind!

**Comment by kareila** [comment]
Hi @ljacob, are you still interested in working on this?  If so, please check in and let us know!  If not, I'll unassign this so someone else can pick it up.

**Comment by Darael** [comment]
I'd be happy to do this, but while I'm at it and since I'm *very* out of the loop: is there a system in place for doing English-stripping on JS?  Is that even a thing we still care about doing?

**Comment by Darael** [comment]
Oh, yeah, I can definitely do that, it was more that I looked at the file, saw it wasn't stripped, and wondered if I should be doing something about it at the same time.  The actual issue at hand isn't particularly affected.

**Comment by rahaeli** [comment]
And to answer the underlying question, IIRC we concluded that JS couldn't be easily English-stripped but we officially Did Not Care as the chief benefit of stripping these days is being able to change text on the fly without having to do a commit and push.
