### ISSUE TITLE
Logging out from community settings gives error, but only on Dreamhacks

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#1692]
- Log in as the owner of a community
- Go to the community's settings page (Organise -> Manage Communities -> Settings)
- Hit the "log out" button in the top right

* the following error message is produced:
`Can't call method "user" on an undefined value at /dreamhack/home/8374-swaldman/dw/htdocs/manage/settings/index.bml line 198. @ newhack.dreamwidth.net`

This is reproducible on up-to-date dreamhacks, but does not occur on production.

**Comment by rahaeli** [comment]
I'm guessing it was the change in #1330 that removed the "if $GET{user};" from line 41.

**Comment by kareila** [comment]
Right changeset, wrong line :)

**Comment by rahaeli** [comment]
Pfft, I was close.
