### ISSUE TITLE
Add max-height to workaround Chrome on Android's font-boost making pages unreadable

### ISSUE THREAD

**Issue by cesy** [dreamwidth/dw-free#1698]
There are certain pages that are unreadable in parts in Chrome on Android, including anything in format=light or more importantly site style. Mobile Chrome has a "feature" called font boost, where any paragraph over a certain length gets enlarged, leaving the rest of the site too small to read. This frequently applies, for example, to a journal post with comments. This is a problem. It applies both to any link from www.dreamwidth.org/mobile/read, and also to following a link from an email notification to a journal post where someone has chosen to display journal entries in site style, which is something I like to do quite often on my phone. Setting a large max-height should fix it. Discussed on http://dw-dev.dreamwidth.org/182633.html

**Comment by rahaeli** [comment]
Can you get a screenshot of your phone showing one of the unreadable pages, btw? (Just to give a sense of what's going on!)

**Comment by cesy** [comment]
![screenshot_2016-02-21-16-58-01](https://cloud.githubusercontent.com/assets/570999/13204108/2f558e04-d8bf-11e5-8c3d-2691d32e9564.png)

**Comment by cesy** [comment]
That one just has subject and author tiny. I'll watch out for a public one with comments as that's even clearer.

**Comment by kaberett** [comment]
As far as I'm concerned you're welcome to use any of my public posts!

**Comment by azurelunatic** [comment]
Mine as well!

**Comment by cesy** [comment]
Example where names are unreadable and reply/expand links are too small to hit without zooming:
![screenshot_2016-02-22-07-06-03](https://cloud.githubusercontent.com/assets/570999/13211733/037dd5ba-d933-11e5-9143-19298372ca2e.png)

**Comment by rahaeli** [comment]
Thanks! The screenshots make it a lot easier for me to picture what the problem is. :)

**Comment by kaberett** [comment]
Have a particularly egregious example:

![screenshot_2016-03-16-08-40-40](https://cloud.githubusercontent.com/assets/2436239/13806599/75bcafb0-eb54-11e5-86c7-3bafe140172a.png)

**Comment by chrisboyle** [comment]
claim

**Comment by chrisboyle** [comment]
Unfortunately what was asked for doesn't achieve what was wanted. The max-height hack does disable font boost, but that just leaves all the text at the "unreadable" size. It's consistent, and you can zoom in, but you then need to scroll side to side to read a line of text. Furthermore, the hack makes the browser's Accessibility / Text Size setting do nothing. I don't think that's an improvement.

![screenshot_20160514-140818](https://cloud.githubusercontent.com/assets/127305/15269013/e677460c-19e9-11e6-919a-94ef24d74581.png)

![screenshot_20160514-140825](https://cloud.githubusercontent.com/assets/127305/15269014/eb27ad68-19e9-11e6-91bf-3b464efeebda.png)

![screenshot_20160514-140901](https://cloud.githubusercontent.com/assets/127305/15269016/f2cc2fc6-19e9-11e6-8e90-c9d0f73f3235.png)

There is a semi-standardised way to disable this sort of thing: `[-webkit-]text-size-adjust`, but Chrome ignores it.

CSS does not have "min-font-size". One could imagine doing something like `@media (max-width: 600px) { html * { font-size: 48px; } }` and relying on the apparently established accessibility policy that styles should only adjust font sizes relatively (using ems). An initial unscientific test of that did not go well:

![screenshot_20160514-155535](https://cloud.githubusercontent.com/assets/127305/15269098/89d6a660-19ec-11e6-9516-16d12a7a83a1.png)

Seems to me the most correct way to make all the text bigger without the side-scrolling problem is to do the "stop pretending there's a huge viewport" thing that many pages on the site do already (but not the `style=site` / `format=light` ones that are the subject of this bug):
```
<meta name="viewport" content="width=device-width, initial-scale=1.0"/>
```

**Comment by chrisboyle** [comment]
Viewport device-width does fix all of these issues, but something would need doing about the top of the page:

![screenshot_20160514-162040](https://cloud.githubusercontent.com/assets/127305/15269222/39bfb136-19f0-11e6-9b4d-c590676aa5ea.png)

![screenshot_20160514-162047](https://cloud.githubusercontent.com/assets/127305/15269221/39bce708-19f0-11e6-9416-fa461e11e062.png)

**Comment by rahaeli** [comment]
Ugh. I'm not sure what the best solution to this is. Paging some people who might know a workaround: @afuna @deborahgu

**Comment by nfagerlund** [comment]
I think the s2foundation beta fixes this whole family of disgusting mobile Chrome issues.

**Comment by kareila** [comment]
In that case I will consider this closed! We can always come back to it if needed.
