### ISSUE TITLE
Use RSS update interval hints

### ISSUE THREAD

**Issue by chrisboyle** [dreamwidth/dw-free#1700]
Feeds are updated [every 60 minutes](https://github.com/dreamwidth/dw-free/blob/develop/cgi-bin/LJ/SynSuck.pm#L519) (or 30 mins if there were new items, all overridden to 1 day if there are no readers).

There's a [specification](http://web.resource.org/rss/1.0/modules/syndication/) for a feed to declare that it updates e.g. weekly (e.g. a webcomic), which would save many updates in such cases.

**Comment by chrisboyle** [comment]
claim

**Comment by kareila** [comment]
I would respectfully suggest that the refresh interval should reset to 60 minutes if the advertised interval passes with no new content.  If a weekly source is at all inconsistent about the time it is updated, it would be possible for fresh content to go undetected for almost a week, which is bound to create support requests when readers notice.  Our users expect feed content to show up in a reasonable amount of time.

**Comment by chrisboyle** [comment]
Among a few of the feeds I subscribe to:

* provision of these hints is relatively rare, ~50%
* those that do all leave out the "updateBase" time, making the next update time unclear/ambiguous (Feedburner is the exception)
* almost everyone supporting this is Wordpress, and those all say "1" "hourly" which would be no change from (or sometimes worse than) current behaviour

There are also @kareila's concerns above, which seem impossible to ever completely solve, if people just declare wrong hints. So I now think implementing this is likely to do more harm than good, so I'm closing it. Happy to be told I'm wrong if, for example, excessive bandwidth from RSS updates is a problem Dreamwidth is actually having.

**Comment by kareila** [comment]
Agreed. Thanks for looking into it!

**Comment by rahaeli** [comment]
RSS polling is not a significant enough amount of our traffic that we have to care about it!
