### ISSUE TITLE
List "Other Services" in columns on profile pages

### ISSUE THREAD

**Issue by me-and** [dreamwidth/dw-free#1702]
Currently the "Other Services" list on profile pages (e.g. [mine](http://me-and.dreamwidth.org/profile)) is a single column with a lot of whitespace on the right hand side. I think it'd look neater formatted into multiple columns.

Currently the list is formatted using a table; I think the sensible way to implement this would be to switch to formatting using `<ul>`, then using CSS column width properties to do the formatting; that should mean it looks fine regardless of the screen size – you specify the column width in CSS and the browser formats the content into an appropriate number of columns for the screen – and will degrade to a vertical list on old browsers that don't support CSS column widths.

If we want example code, that sort of CSS formatting is how a lot of reference lists on Wikipedia are formatted. [The article on CN Lester](https://en.wikipedia.org/wiki/CN_Lester), for example, has 30em wide columns in its references section.

Per discussion on IRC, this didn't seem to quite warrant a suggestion in dw_suggestions, so I'm just opening an issue to see if anyone can spot any glaring problems with the plan.

**Comment by rahaeli** [comment]
That makes lovely sense, and fits nicely into our long term low-priority "remove all tables-for-layout" goal.

**Comment by me-and** [comment]
Claim
