### ISSUE TITLE
Facebook image specifier

### ISSUE THREAD

**Issue by pseudomonas** [dreamwidth/dw-free#1705]
This isn't a bug per se, but  when a DW post is shared, Facebook tends to choose as an image the usericon of the last commenter. That's suboptimal, even if it's Facebook rather than DW being suboptimal.

I think there's some Meta tag for this: https://developers.facebook.com/docs/sharing/opengraph

(I'm sure we can bikeshed the choice between the DW swirl, the post's usericon, or giving the author a per-post or per-DW choice of summary image. All are fine by me; the DW swirl is easiest to implement and looks tidy enough.)

**Comment by rahaeli** [comment]
What size does the image get displayed at?

**Comment by kaberett** [comment]
Inspect Element suggests that it claims to be 90x90px.

**Comment by rahaeli** [comment]
Hm. In that case, let's do "poster's icon choice defaulting to the no-icon image if the poster doesn't have or doesn't specify an icon". (I didn't want to use that if FB made them much smaller/larger, but the difference between 100x100 and 90x90 is not visually that different.)

**Comment by azurelunatic** [comment]
So from reading https://developers.facebook.com/docs/sharing/opengraph/using-objects -- 

The badger is accomplished by adding certain meta tags to the `<head>` section, to wit, their example: 

`<meta property="og:image"           content="[asset:471072486292602]" /> `

They have a tool to see if you're Doing It Rite: https://developers.facebook.com/tools/debug

**Comment by chrisboyle** [comment]
claim

**Comment by chrisboyle** [comment]
I have a first attempt at https://github.com/dreamwidth/dw-free/compare/develop...chrisboyle:facebook-preview-icon-1705 but it's not a useful PR yet because it fails with

> Provided og:image URL, http://www.shortcipher.hack.dreamwidth.net/userpic/1/3 was not valid because it did not meet the minimum size constraint of 200px by 200px.

AFAIK DW does not store that many pixels for userpics, so this would require one of:
1. Store more pixels and awkwardly rescale all existing userpics (too radical a change for this IMHO).
2. Discover some flag or other metadata format that is not in [Facebook's docs](https://developers.facebook.com/docs/sharing/best-practices#images) to get them to accept a 100x100 image.
3. Provide a URL at which a given userpic (in a range of possible file formats) will be rescaled on the fly for Facebook's benefit. Presumably we have image resizing code somewhere to shrink them when they're uploaded.

Option 3 looks the least implausible.

**Comment by kaberett** [comment]
Okay, the fact that they're wanting to display at 200x200 means that the boss (hi @rahaeli) is gonna need to weigh in again about her preferred option -- that doesn't strike me as a reasonable scaling to apply to user icons and is likely to change desired behaviour.

**Comment by kareila** [comment]
Yeah, you'll want to take a look at the Image::Magick module if you decide to proceed with scaling.

**Comment by chrisboyle** [comment]
Also, the first time Facebook's debug tool encountered that userpic URL, it complained (in its response given after a fraction of a second) that the image URL didn't respond fast enough. Pressing "Scrape again" persuaded it to reconsider; I don't know whether in real life that would happen on a second share, or at all.

On the one hand, DW production is probably faster than a Dreamhack. On the other, I wasn't doing any on-the-fly image resizing yet...

**Comment by azurelunatic** [comment]
Is this a thing where it would be desirable to retool the entire so-and-so to allow uploading of 200x200 images and en-smallen them directly after upload, so there's the possibility of a legit 200x200 version onboard? This would also possibly answer a long-standing request for the ability to magnify icons for tinytext/low vision.

**Comment by rahaeli** [comment]
Hnrgh. Okay, all this is wandering pretty far afield of the original quick & easy fix. Let's just go with the no-icon image, resized to 200x200, for everything. (I went looking and sadly do not have it in SVG, just the PNG version checked into the code.)

**Comment by swaldman3** [comment]
@rahaeli may I suggest opening an issue that we should have a SVG version? I'm guessing there might be a few people out there who don't code, but are quite happy tracing a bitmap to SVG! (although admittedly they're unlikely to be reading GHI)

**Comment by kareila** [comment]
Here's the largest version I know of, from the wiki: http://wiki.dreamwidth.net/wiki/images/1/12/Swirly-d.png
