### ISSUE TITLE
Add Flickr videos as an allowed embed

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1707]
_NotSimon_ is not able to embed Flickr videos, and I think that's a pity. 

Someone who has a flickr account with a video (I do not at this juncture) can give an example of the embed code.

**Comment by rahaeli** [comment]
I believe the problem was that Flickr video embed requires JS, but someone with a Flickr account can confirm.

**Comment by sgsabbage** [comment]
Flickr embed example (not my video):

`<a data-flickr-embed="true"  href="https://www.flickr.com/photos/89829656@N02/24827796019/in/pool-703374@N20/" title="Tidepool octopus is changing color"><img src="https://farm2.staticflickr.com/1470/24827796019_7021e8a095_z.jpg" width="640" height="360" alt="Tidepool octopus is changing color"></a><script async src="//embedr.flickr.com/assets/client-code.js" charset="utf-8"></script>`

**Comment by rahaeli** [comment]
Yup, script tag in the embed means we can't enable it.
