### ISSUE TITLE
XML-RPC call to LJ.XMLRPC.postevent returns a string rather than an int as the faultCode

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1709]
https://www.dreamwidth.org/support/see_request?id=32830

"It looks like the response to an XML-RPC call to LJ.XMLRPC.postevent is returning a string rather than an int (and also not working) as the faultCode. Which causes the XML-RPC parser I'm using to fall over in a big heap.

Is this something that a DW dev can have a look at?

I can give exact times that this would have happened at, if it would be showing up in the DW logs?"

Please let me know if you'd like me to ask the user to provide timestamps, or any further information!

**Comment by rahaeli** [comment]
Man, I don't even know where to start in on this.

**Comment by alierak** [comment]
I'd start with cgi-bin/Apache/LiveJournal.pm lines 1646 - 1648. That's where the faultCode is set using a substring (first three characters) of the error string produced by do_request. I think it's assumed that do_request will always produce an error that looks like a typical protocol response starting with a 3-digit number. We'd best check whether that assumption holds everywhere in do_request, or do away with the assumption and just validate the error string.

**Comment by kareila** [comment]
I've asked for more information about the problematic transaction in the support request.  I would also consider putting a warning on that block of code so that Apache will log any error message that doesn't start with a three digit number.

**Comment by kareila** [comment]
The warning I added hasn't appeared in the logs since the last code push, and the user who opened the support request hasn't provided any further information.  I'm closing this but leaving the warning intact for future debugging should this turn up again.
