### ISSUE TITLE
E-mailed Support notifications do not include referenced FAQs

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1715]
e.g. my notification e-mail for my visible answer at https://www.dreamwidth.org/support/see_request?id=32907 reads:

> A follow-up to the following  support request has been submitted:
> 
> Category: Entries
> Subject: Only 14 days worth of posts?
> User: kaberett
> URL:http://www.dreamwidth.org/support/see_request?id=32907
> Type: Screened Answer
> Text:
> 
> Hi stormcloude,
> 
> As explained in the linked FAQ and as you've observed, the Reading Page
> displays only the most recent 1000 entries from the last 14 days. These
> limits are the same as those on LiveJournal
> (http://www.livejournal.com/support/faq/219.html), for the same reasons of
> issues with server load and site performance. It is possible to bypass
> these limits by filtering the Reading Page by date
> (https://www.dreamwidth.org/support/faqbrowse?faqid=76), but this is a
> feature that is only available to paid accounts on both Dreamwidth and
> LiveJournal because of the demands it places on the servers.
> 
> As such there isn't any setting you can change, other than purchasing paid
> time. Details on how much paid accounts cost are available at
> https://www.dreamwidth.org/support/faqbrowse?faqid=153, and a summary of
> additional features available to paid account holders is provided at
> https://www.dreamwidth.org/support/faqbrowse?faqid=4. Alternatively, you
> can visit individual journals or communities to read their entire archives.
> 
> 
> I'm sorry that this wasn't what you were hoping to hear, and please do let
> me know if you have any further questions.
> 
> Best,
> -kaberett.
> 
> 
> ====
> 
> You can view this request here:
> 
> http://www.dreamwidth.org/support/see_request?id=32907
> 
> You are receiving this email because you've requested notifications of
> changes to support requests. You may change this notification setting here:
> 
> http://www.dreamwidth.org/support/changenotify

There's no indication that https://www.dreamwidth.org/support/faqbrowse?faqid=25 was included as a Reference FAQ, and it would be useful for record-keeping purposes not to have to click through to see this. I suspect this would also be useful from the perspective of users. I suggest adding a line to the effect of:

> FAQ Reference: What is my reading page? (https://www.dreamwidth.org/support/faqbrowse?faqid=25&view=full)

... for plaintext e-mails, with the FAQ title linkified for HTML e-mails.

**Comment by rahaeli** [comment]
I'm like 98% sure that the FAQ is referenced in the email sent to the user (which is not the same as the email sent to people who have support notifs on).

(Not to say that it shouldn't be added to the support notif! Just that users do get it.)

**Comment by kaberett** [comment]
Will double-check that myself if I end up doing this one, but want to see if it's deemed suitable-for-beginners before I grab it! :-)

**Comment by rahaeli** [comment]
The actual changes would be, but getting your 'hack to send mail so you can receive the notifications probably not.

On Mar 19, 2016, at 5:56 PM, kaberett <notifications@github.com> wrote:

> Will double-check that myself if I end up doing this one, but want to see if it's deemed suitable-for-beginners before I grab it! :-)
> 
> �
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

-- 
Denise Paolucci
denise@dreamwidth.org
Dreamwidth Studios: Open Source, open expression, open operations. Join us: www.dreamwidth.org

**Comment by azurelunatic** [comment]
Below is an answer to your support question regarding "I need a FAQ reference"
(https://www.dreamwidth.org/support/see_request?id=32947&auth= redacted).

======================================================================

FAQ REFERENCE: What is Dreamwidth Studios?
https://www.dreamwidth.org/support/faqbrowse?faqid=1&view=full

I'm very sorry to report that attempting to reference https://www.dreamwidth.org/support/faqbrowse?faqid=35 does not provide a spiffily formatted link. Nonetheless, I believe it should answer any questions you have.

Best,
-kaberett.

Did this answer your question?
YES:
https://www.dreamwidth.org/support/act?close redacted
NO:
https://www.dreamwidth.org/support/see_request?id=32947&auth= redacted


If you are having problems using any of the links in this email, please try copying and pasting the *entire* link into your browser's address bar rather than clicking on it.

Replies to this address are not monitored. To reply to your request, use the links above.

**Comment by azurelunatic** [comment]
Would also be nice to include the original text of the support request, for context, especially when the same person has multiple requests open, and/or the subject has been changed for tracking purposes.

**Comment by rahaeli** [comment]
That's been floated before, but we decided that since people don't read (especially anything more than a few paragraphs long) it was best to leave it out of the email. They can click through to the site to get the original text.

**Comment by azurelunatic** [comment]
Ah yeah; top-quoting is not a good idea. I was thinking bottom-quoting,
mostly for searchability and not having to load a separate thing.

**Comment by rahaeli** [comment]
It still does leave the impression of OVERWHELMING TEXT!! though, and when it comes to stuff like support responses where you want people to read your response, it's best to strip out everything extraneous!

**Comment by kaberett** [comment]
Hah, in which case (given that I am fairly comfortable with making hacks send e-mail), claim.
