### ISSUE TITLE
Some http:// image URLs not being run through the image proxy

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#1723]
I've been noticing that a lot of photos from feeds have not been showing up correctly on my reading page when I use https://. At first I thought the proxy was broken, but today I dug into it and found out it's not quite that!

It turns out we proxy image URLs in the `src` attribute, but not those in the `srcset` attribute (which is used for responsive images). So, for example:

    <img
    src="http://fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal.jpg" 
    srcset="http://fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal-590x331.jpg 590w, http://fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal.jpg 600w" sizes="(max-width: 600px) 100vw, 600px" />

Becomes:

    <img
    src="https://p.dreamwidth.org/692e1f13edd4/-/fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal.jpg"
    srcset="http://fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal-590x331.jpg 590w, http://fashionablygeek.com/wp-content/uploads/2016/03/Fraser-Stag-Brooch-Horizontal.jpg 600w" sizes="(max-width: 600px) 100vw, 600px" />

We should handle both but this is going to be just a little bit tricky because we'd have to parse out the URLs first.

(hullo)

**Comment by rahaeli** [comment]
Huh, is *that* why that keeps happening.

(ps: that brooch is amazing omg want)

**Comment by afuna** [comment]
Yes! That also explains why it mostly only happens on certain feeds (probably from bigger blogging sites that does the image resizing automatically)

(Also omg yes)

**Comment by kareila** [comment]
Hi, we've missed you!

Could the solution be as simple as m_\b(http://\S+)_proxyfunction($1)_g on the value of srcset, for whatever the proxyfunction is?  Or are there other steps involved?

**Comment by afuna** [comment]
I think that might work! Possibly some edge cases in there but not any I can think of off the top of my head. 

(Missed you all too <3)
