### ISSUE TITLE
Specify that no, you can't reply to an email about a PM and have it go through

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#1727]
As mentioned in https://www.dreamwidth.org/support/see_request?id=33039 - you can't reply to the email for a PM and have anything good happen -- at the moment! This will change after #1310. 

http://www.dreamwidth.org/support/faqbrowse?faqid=68 
Current: 

We have a message system you can use to send private messages to other Dreamwidth users. You can reach it either by selecting the "Send Message" option in your own Inbox or the "Send Message" icon and text on the Profile of the person you want to send the message to.

When you reach the Compose Message page, you'll need to fill out the "To" field in order for your message to be sent, but all the other fields are optional. You can send your message to multiple recipients by separating their usernames with commas.

(+) 

Proposed: 

+ You cannot reply to a private message by replying to the email notification. You must reply through the Inbox. 

http://www.dreamwidth.org/support/faqbrowse?faqid=71  
Current: 
You can get notifications sent to your Inbox, and you can also get them emailed to you.

Almost all notifications are sent to your Inbox. Notifications for replies to your comments in somebody else's journal or your posts in a community, as well as notifications for your own comments, can only be received via email. You can also have all other notifications emailed to you by checking the "also notify me by email" box when setting up your notification preferences.

(+) 

It isn't possible to receive notifications only by email without them appearing in your Inbox, although this is scheduled for a future release.

Proposed: 

+ You can reply to comments by replying to the email notification (link to 265) if you wish, but you must use the Inbox to reply to private messages.

**Comment by kaberett** [comment]
done!
