### ISSUE TITLE
/fastclick. added to ad-blocker blacklists

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1732]
http://www.dreamwidth.org/support/see_request?id=33048

Some elements of the beta Create Entries page rely on the JS element fastclick, which seems to have just been added to a blacklist (https://forums.lanik.us/) used by multiple adblockers (at least Adblock and uBlock0).

![screenshot](https://cloud.githubusercontent.com/assets/2436239/14229368/f60e2058-f929-11e5-94c5-381be25443c5.png)

Note that "browse tags" has been replaced by "go to journal tags" (and there's no auto-completion), and that selecting "custom filtered" does not pop up the lightbox for selecting which filter.

My IC:

>Thing being filtered, because of https://forums.lanik.us/, according to uBlock0:
>
>/fastclick. (http://s.dreamwidth.org/js/??jquery/jquery-1.8.3.js,foundation/vendor/custom.modernizr.js,foundation/foundation/foundation.js,foundation/vendor/fastclick.js,foundation/foundation/foundation.topbar.js,dw/dw-core.js,jquery/jquery.ui.core.js,jquery/jquery.ui.widget.js,jquery/jquery.ui.tooltip.js,jquery.ajaxtip.js,jquery/jquery.ui.position.js,jquery.hoverIntent.js,jquery.contextualhover.js?v=1440903277; http://s.dreamwidth.org/js/??jquery/jquery-1.8.3.js,foundation/vendor/custom.modernizr.js,foundation/foundation/foundation.js,foundation/vendor/fastclick.js,foundation/foundation/foundation.topbar.js,dw/dw-core.js,jquery/jquery.ui.core.js,jquery/jquery.ui.widget.js,jquery/jquery.ui.tooltip.js,jquery.ajaxtip.js,jquery/jquery.ui.position.js,jquery.hoverIntent.js,jquery.contextualhover.js?v=1440903277)

**Comment by rahaeli** [comment]
Well, in the meantime while we figure out what to do about it, at least we can tell people in good conscience to turn off their adblock for DW. ;)

**Comment by rahaeli** [comment]
PS: Excellent detective work! And I have now updated the BBB and will now go tweet about it.

**Comment by kareila** [comment]
I checked https://forums.lanik.us just now and it looks like they updated their whitelist not to block this any more.  Can someone who has installed one of the affected blockers update their filters and verify that it's working again?

**Comment by kaberett** [comment]
Yep, working for me again!

**Comment by kareila** [comment]
Okay, then we can close this once someone re-updates the BBB.

**Comment by rahaeli** [comment]
BBB updated!
