### ISSUE TITLE
fix UserMessaging.pm to use method instead of raw prop

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1733]
http://www.dreamwidth.org/support/see_request?id=33001

If a user is a minor and hasn't changed their UserMessaging setting from the default, the Settings page will tell them that they can receive PMs from Registered Users, when in fact they are only allowed to receive PMs from Mutually Trusted Users.

Fix: on line 35 of LJ/Setting/UserMessaging.pm, change `$u->prop("opt_usermsg")` to `$u->opt_usermsg`.  This will use the correct logic to display the effective value of the setting.

**Comment by rahaeli** [comment]
Let's just remove the specialcasing for under-18 accounts -- that has to be holdover from LJ.

**Comment by kareila** [comment]
We can do that too, but using the method instead of the raw prop is still the correct approach.

**Comment by rahaeli** [comment]
Opened 1735 for eliminating the special casing!
