### ISSUE TITLE
Crossposter failing to correctly handle un/checking the Disable Auto-Formatting option (old Create Entries, HTML editor)

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1734]
http://www.dreamwidth.org/support/see_request?id=33047

If you make a post to DW that is cross-posted to LJ with the Disable Auto-Formatting box (in the HTML editor of the old Create Entries page) checked, and subsequently edit that post to uncheck the Disable Auto-Formatting box, the crossposter fails to handle the edit elegantly.

In my test case (private post; no comments on either the DW or LJ entry) the line-breaks haven't been inserted on the LJ copy despite attempting to crosspost the edited version, with no failure notification in my DW inbox. (I made no other changes to the post; I am set up to use the HTML editor by default on LJ.)

In the case of the user reporting this issue, there were comments on (at least) the LJ version of the post; unchecking the DA-F box and crossposting the edited version reportedly created a new post on LiveJournal with correct formatting, rather than editing the previous post.

**Comment by kareila** [comment]
I've verified that this only happens when editing a crosspost to uncheck the option.  If you initially post with it unchecked and edit to have it checked, the behavior is correct.
