### ISSUE TITLE
Should we add an LJ::dhtml function?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1737]
When I was fixing #1643 just now, I thought it was odd that we didn't have an LJ::dhtml function for undoing LJ::ehtml, similar to LJ::durl and LJ::eurl.  Current practice is to use HTML::Entities::decode (or decode_entities - same function, different name).

I think it might be a good idea to add this, (a) for symmetry and ease of remembering, and (b) so that if we ever want to use a different method of decoding in the future, we only need to change it in one place.

**Comment by kareila** [comment]
Affected files:

- cgi-bin/DW/CleanEmail.pm
- cgi-bin/DW/EmailPost/Entry.pm
- cgi-bin/DW/External/XPostProtocol/LJXMLRPC.pm
- cgi-bin/DW/Worker/ContentImporter/LiveJournal/Userpics.pm

**Comment by kaberett** [comment]
Er, so it looks to me like an ehtml sub is defined in at least cgi-bin/LJ/S2.pm, cgi-bin/LJ/BML.pm, src/jbackup/jbackup.pl, and cgi-bin/LJ/TextUtil.pm. (For my possible future reference, eurl and durl appear to live in bin/ddlockd).

... consequently I am suddenly a bit more perplexed about where dhtml should be defined (even though it should presumably just be handed a string and return that string having been fed through HTML::Entities::decode?

(Would it be the appropriate way to address e.g. #1652? I think not *immediately*, but *flail*!)

**Comment by kareila** [comment]
I was referring to the suite of functions in cgi-bin/LJ/TextUtil.pm which defines LJ::ehtml et al.

TMI follows, for the curious:

The one in S2.pm is a wrapper for using LJ::ehtml in S2 code.  The one in BML.pm defines a similar function in the BML package and can be ignored, because BML; similarly for HTMLCleaner.pm.  From the line where the subroutine is defined, search backward for the most recent line starting with `package` to discover where the function will be referenced from.

As for ddlockd and jbackup.pl, those are command line scripts and not code library modules.  My guess is they pasted in local copies of those functions to avoid having to load the entire TextUtil library (although the current version is pretty self-contained as LJ modules go).

**Comment by zorkian** [comment]
Since the subject is a question, I'm going to say yes. I'm a fan of having standardization of how we do things, and while it sounds like this is _mostly_ standard it's probably better to have the actual `LJ::dhtml` function to use.

**Comment by kaberett** [comment]
Claim!
