### ISSUE TITLE
Insecure HTTPS Connection when going to https://(*.)dreamwidth.org/ in FFx 45.0.1

### ISSUE THREAD

**Issue by emceeaich** [dreamwidth/dw-free#1740]
Please note, this is happening with HTTPS Everywhere disabled.

Steps to Reproduce

Go to https://emceeaich.dreamwidth.org/ or https://dreamwidth.org in Firefox 45.0.1

Expected result: user's journal
Result: firefox insecure connection error

Error doesn't occur when viewing site in Chrome. 

Error details reported from FFx:

https://dreamwidth.org/

Peer's Certificate issuer is not recognized.

HTTP Strict Transport Security: false
HTTP Public Key Pinning: false

Certificate chain:

-----BEGIN CERTIFICATE-----
MIIFcjCCBFqgAwIBAgIQB/Ohff19wlrvNsvcWRBTkjANBgkqhkiG9w0BAQsFADBC
MQswCQYDVQQGEwJVUzEWMBQGA1UEChMNR2VvVHJ1c3QgSW5jLjEbMBkGA1UEAxMS
UmFwaWRTU0wgU0hBMjU2IENBMB4XDTE2MDQxMDAwMDAwMFoXDTE3MDYwOTIzNTk1
OVowGzEZMBcGA1UEAwwQKi5kcmVhbXdpZHRoLm9yZzCCASIwDQYJKoZIhvcNAQEB
BQADggEPADCCAQoCggEBAOnY48LUAVzVuta6lBCMIjhoee1v2S7b3fDOZrkokMnd
21MURiRSBsJHwuoBVszTxc+Z+Xnv7MbaAKztoiWH4gY3ZDZw6SB0sBJENppcCN13
g7Vi2PqGAVItsFfFbfqSa6KqrWcYwGTIAXT36dQAT0xLbeUA9JRxCC2mlm8umiC9
qb5q52h01kiZdNZ2L/pWchkmbUk7esXhmiEX3FoicdkzQziotlBB3zHS+vkSuhy/
pwN0gywwqFVa1BYw3UuLj9ldtU64XXg/GNt5dCtYJ+50JL/oP17oRbn0fXIEkwnV
nSzm5WWXeXvqSyr2NlGLeh6gUuDifnF8JVPpx+h/Yb8CAwEAAaOCAokwggKFMCsG
A1UdEQQkMCKCECouZHJlYW13aWR0aC5vcmeCDmRyZWFtd2lkdGgub3JnMAkGA1Ud
EwQCMAAwKwYDVR0fBCQwIjAgoB6gHIYaaHR0cDovL2dwLnN5bWNiLmNvbS9ncC5j
cmwwbwYDVR0gBGgwZjBkBgZngQwBAgEwWjAqBggrBgEFBQcCARYeaHR0cHM6Ly93
d3cucmFwaWRzc2wuY29tL2xlZ2FsMCwGCCsGAQUFBwICMCAMHmh0dHBzOi8vd3d3
LnJhcGlkc3NsLmNvbS9sZWdhbDAfBgNVHSMEGDAWgBSXwidQnsLJ7AyIMsh8reKm
AU/abzAOBgNVHQ8BAf8EBAMCBaAwHQYDVR0lBBYwFAYIKwYBBQUHAwEGCCsGAQUF
BwMCMFcGCCsGAQUFBwEBBEswSTAfBggrBgEFBQcwAYYTaHR0cDovL2dwLnN5bWNk
LmNvbTAmBggrBgEFBQcwAoYaaHR0cDovL2dwLnN5bWNiLmNvbS9ncC5jcnQwggEC
BgorBgEEAdZ5AgQCBIHzBIHwAO4AdQDd6x0reg1PpiCLga2BaHB+Lo6dAdVciI09
EcTNtuy+zAAAAVP/H10nAAAEAwBGMEQCIFkfIzdvUxdbQtoCnFrZ0+cfFRilOHmJ
qIr1tlymvvx1AiBOppfkTGSlVDHtogsE4YQdijYjkz2+FZT4G/BrKAGMbQB1AKS5
CZC0GFgUh7sTosxncAo8NZgE+RvfuON3zQ7IDdwQAAABU/8fXV4AAAQDAEYwRAIg
Dtn7Ri0UKQt+kVe4KAf0KtP7t/DCHIbubqRcw/7EQYMCIEnPoVMGoYDQY51MtNby
f2+W5kSpT/rOGgTM0IbAq2CKMA0GCSqGSIb3DQEBCwUAA4IBAQBHGbLXLAkD17WV
NRaSt5N6XezQGdgGFYK5BsGrG6ETyAs2UaRMY48VHuClrUfoGTFvfVWLEjlmGPUW
ufGqEa4k+dMMeNosBLMTOM7wThyBdfhed8/1Te8crRKYMkCgI1FnUY8as7g8XIiR
Ug4oKlpcbQgOkU+H5rt+eC/7dDVpBqtnApy3FT3NY8dTKSbBw8ILwyVOVKmnna7y
x1DbOFXmcTSLQqqXT9/YbqF1F+AvRMXv6T8YxiD3bVkf30C3D/96cM4SIxquwGjp
2QsIGL6y7oNfZ9M11rVQxBAQPIkxhm/N9VwYPe1AGTY+7FPuiJ8QC5iBHSGg10Lc
2eogm+UL
-----END CERTIFICATE-----
-----BEGIN CERTIFICATE-----
MIID1TCCAr2gAwIBAgIDAjbRMA0GCSqGSIb3DQEBBQUAMEIxCzAJBgNVBAYTAlVT
MRYwFAYDVQQKEw1HZW9UcnVzdCBJbmMuMRswGQYDVQQDExJHZW9UcnVzdCBHbG9i
YWwgQ0EwHhcNMTAwMjE5MjI0NTA1WhcNMjAwMjE4MjI0NTA1WjA8MQswCQYDVQQG
EwJVUzEXMBUGA1UEChMOR2VvVHJ1c3QsIEluYy4xFDASBgNVBAMTC1JhcGlkU1NM
IENBMIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAx3H4Vsce2cy1rfa0
l6P7oeYLUF9QqjraD/w9KSRDxhApwfxVQHLuverfn7ZB9EhLyG7+T1cSi1v6kt1e
6K3z8Buxe037z/3R5fjj3Of1c3/fAUnPjFbBvTfjW761T4uL8NpPx+PdVUdp3/Jb
ewdPPeWsIcHIHXro5/YPoar1b96oZU8QiZwD84l6pV4BcjPtqelaHnnzh8jfyMX8
N8iamte4dsywPuf95lTq319SQXhZV63xEtZ/vNWfcNMFbPqjfWdY3SZiHTGSDHl5
HI7PynvBZq+odEj7joLCniyZXHstXZu8W1eefDp6E63yoxhbK1kPzVw662gzxigd
gtFQiwIDAQABo4HZMIHWMA4GA1UdDwEB/wQEAwIBBjAdBgNVHQ4EFgQUa2k9ahhC
St2PAmU5/TUkhniRFjAwHwYDVR0jBBgwFoAUwHqYaI2J+6sFZAwRfap9ZbjKzE4w
EgYDVR0TAQH/BAgwBgEB/wIBADA6BgNVHR8EMzAxMC+gLaArhilodHRwOi8vY3Js
Lmdlb3RydXN0LmNvbS9jcmxzL2d0Z2xvYmFsLmNybDA0BggrBgEFBQcBAQQoMCYw
JAYIKwYBBQUHMAGGGGh0dHA6Ly9vY3NwLmdlb3RydXN0LmNvbTANBgkqhkiG9w0B
AQUFAAOCAQEAq7y8Cl0YlOPBscOoTFXWvrSY8e48HM3P8yQkXJYDJ1j8Nq6iL4/x
/torAsMzvcjdSCIrYA+lAxD9d/jQ7ZZnT/3qRyBwVNypDFV+4ZYlitm12ldKvo2O
SUNjpWxOJ4cl61tt/qJ/OCjgNqutOaWlYsS3XFgsql0BYKZiZ6PAx2Ij9OdsRu61
04BqIhPSLT90T+qvjF+0OJzbrs6vhB6m9jRRWXnT43XcvNfzc9+S7NIgWW+c+5X4
knYYCnwPLKbK3opie9jzzl9ovY8+wXS7FXI6FoOpC+ZNmZzYV+yoAVHHb1c0XqtK
LEL2TxyJeN4mTvVvk0wVaydWTQBUbHq3tw==
-----END CERTIFICATE-----

**Comment by kareila** [comment]
Mark updated our SSL certificates a couple of hours ago and something seems to have gone awry. We're working on it, but it's an ops issue not related to last night's code push.

**Comment by emceeaich** [comment]
Thanks, @kareila!

**Comment by emceeaich** [comment]
https site is now loading for me in FFx 48.x (Nightly)

**Comment by kareila** [comment]
We had to make a change to one of the intermediate certificates - looks like everything is sorted out now.
