### ISSUE TITLE
directory search shenanigans

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1742]
http://www.dreamwidth.org/support/see_request?id=33110

Doing a directory search for journals located in North Carolina, updated at any time, returns no results.

https://www.dreamwidth.org/directorysearch?opt_format=simple&opt_pagesize=200&start_search=1&widget%5Bgeosearchlocation%5D_country=US&widget%5Bgeosearchlocation%5D_statedrop=NC

Doing a directory search for journals located in North Carolina, updated in the past 7 days, returns tons of results, none of which seem to be located in North Carolina.  I'm not sure any of the results have any location set at all; most are syndicated feeds.

https://www.dreamwidth.org/directorysearch?opt_format=simple&opt_pagesize=200&start_search=1&ut_days=7&widget%5Bgeosearchlocation%5D_country=US&widget%5Bgeosearchlocation%5D_statedrop=NC

If the directory search is this egregiously broken, we should either figure out how to fix it, or give up and replace it with something that's actually possible to get working in development environments.

**Comment by rahaeli** [comment]
My preference is for replacement and has been for a long time; the directory's badly integrated and we have too many search options (none of which talk to each other).

(Ideally I want a replacement that can do tag search the way Tumblr does.)

**Comment by kaberett** [comment]
Pedantry alert:

The way tumblr *currently* does, or the way tumblr *did* up until a couple of months ago?

**Comment by rahaeli** [comment]
The way where you can search & browse the whole site for any post tagged with [whatever] and read them all together, like how the Latest Things tag feed works but for literally any tag.


On Apr 11, 2016, at 2:58 PM, kaberett <notifications@github.com> wrote:

> Pedantry alert:
> 
> The way tumblr currently does, or the way tumblr did up until a couple of months ago?
> 
> �
> You are receiving this because you commented.
> Reply to this email directly or view it on GitHub
> 

-- 
Denise Paolucci
denise@dreamwidth.org
Dreamwidth Studios: Open Source, open expression, open operations. Join us: www.dreamwidth.org

**Comment by alierak** [comment]
The wiki instructions for setting up directory search are missing info on the directory-meta worker, and the wiki list of workers needs some help. Unfortunately I don’t seem to be able to edit the wiki…

http://wiki.dreamwidth.net/wiki/index.php/Search/UserSearch <http://wiki.dreamwidth.net/wiki/index.php/Search/UserSearch>

http://wiki.dreamwidth.net/wiki/index.php/Workers <http://wiki.dreamwidth.net/wiki/index.php/Workers>

**Comment by kareila** [comment]
@alierak I can do it when I get home.

**Comment by alierak** [comment]
I think this is a bug in the controller or some more general handling of URL parameters. Somewhere between submitting the search form and displaying the results page where start_search=1, the Widget[GeoSearchLocation]_foo URL parameters are all being lowercased, which means post_fields_by_widget is never going to see them. It’s looking case-sensitively for “Widget” and an appropriate subclass name.

Note that if you add “&loc_st=NC” to the failed search, you do get journals in North Carolina, so I think the directory search backend is working fine.

**Comment by kareila** [comment]
Wow! Ok, I'll claim this for the controller issue.

**Comment by rahaeli** [comment]
Whoa, good troubleshooting there.

**Comment by alierak** [comment]
get_args in DW/Request/Base.pm is doing this by design ("We lowercase GET arguments because these are often typed by users, and that's nicer on them.”). Wonder if we have any other widgets that are submitted using URL params instead of post...

**Comment by kareila** [comment]
I'll look into it later, but the obvious workaround would be to add a parameter for making sure case is preserved by get_args when we want it to be.

**Comment by zorkian** [comment]
Ooohh... technically that lowercasing behavior is totally bogus. Query
string parameters are case sensitive.
 
We could stop doing that, but then users will run into '?FOOBAR DOES NOT
WORK' errors. We could whitelist the things to lowercase. We could
blacklist things NOT to lowercase (Widget.*).
 
I'm generally in favor of removing the lowercasing entirely and training
people not to type query strings by hand -- but if they're going to be
advanced enough to do that they should do it right?
 
--
Mark Smith
mark@qq.is
 
 
On Tue, Apr 12, 2016, at 12:22 PM, Jen wrote:
> I'll look into it later, but the obvious workaround would be to add a
> parameter for making sure case is preserved by get_args when we want
> it to be.
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub[1]
>
 

Links:

  1. https://github.com/dreamwidth/dw-free/issues/1742#issuecomment-209063004

**Comment by kareila** [comment]
I'm worried that removing the lowercasing entirely, and thereby changing the default behavior of get_args, will have unforeseen consequences.  We've had it this way for years and this is the first time we've discovered an unintended consequence of doing it this way... in a barely used legacy system.

I'm going to proceed with adding an override parameter to get_args that will preserve the case-sensitivity only when requested.  Theoretically, we could audit the code over time by adding the parameter in more places, if you think it's important to try to adhere to the expectation of preserving case sensitivity.

**Comment by alierak** [comment]
Au contraire, a few months after Afuna committed the lowercasing change in 2013, Mark came along and limited it to lowercasing GET args only (as opposed to GET and POST) because he said it broke the Widgets.

https://github.com/dreamwidth/dw-free/commit/f909bc4c9807e853276f0ce2b2961ee23986b6a0

https://github.com/dreamwidth/dw-free/commit/2a3558db4c49cc11dd854a1c3d9ba87e70c01b97

**Comment by kareila** [comment]
Well, that doesn't contradict what I said about get_args.  That's post_args, which is different.  :)

But yeah, considering the name of the other subroutine is "post_fields_by_widget" I'm guessing it was only ever intended to be used for POST requests.  Oh well!

**Comment by rahaeli** [comment]
Could we change it so that we aren't auto-lowercasing (since parameters are case sensitive) but make it so that if a lowercase version of the string fails it falls through to checking the uppercase version (and if the uppercase version would succeed, then assuming uppercase)? Or is that too much load?

**Comment by kareila** [comment]
We would need to pass around two different hashes with two different sets of keys, so that's not really practical, no.

**Comment by rahaeli** [comment]
Gotcha.

**Comment by kareila** [comment]
Okay, here are the other pieces of the puzzle I've found:

`<meta http-equiv='Refresh' content='1;URL=[% refurl %]' id='refresher' />`

That's in the header of the interstitial page (views/directory/searchdots.tt) and the value of `refurl` comes from LJ::page_change_getargs, which returns a call to LJ::create_url.

That's where the usage of get_args happens:

`my $orig_args = $opts{cur_args} || DW::Request->get->get_args;`

In this particular case, we definitely don't want the result to be changed in any way.  We're asking for a verbatim copy of the original arguments.

However, again, I am concerned about breaking things that rely on this behavior, so I propose to implement a conservative fix that passes along Widget arguments unchanged, and log a warning if any other case changes are being requested in this particular instance.  If we don't see any warnings happening after the next code push, we can simplify it to always preserve case.

**Comment by kareila** [comment]
You can check out my proposed changes at https://github.com/kareila/dw-free/commit/7d0f440be11e25057ed1a2f54a824f266b105deb but I'm not going to submit a PR until after I do some testing.

**Comment by kareila** [comment]
Reopening this for further investigation and eventual removal of log lines.

**Comment by kareila** [comment]
Closing this - LJ::create_url now always preserves case, fixing the original issue.
