### ISSUE TITLE
remove domain forwarding feature

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1757]
Due to increasing our protection with Cloudflare, we're going to have to retire the domain forwarding feature -- we can't make it work without paying CF more per month than we can afford given the lack of adoption of the feature. (It's not a major paid account driver.)

I've emailed the people affected and edited the FAQs, but https://www.dreamwidth.org/manage/domain needs to be removed, and possibly some other stuff.

**Comment by kareila** [comment]
Claimed.
