### ISSUE TITLE
get_maintainer console command needs more error checking

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1762]
I noticed just now that using the get_maintainer command on a deleted community prints no results, nor does using the command on a user that does not administer any communities.  This is counter to expected behavior that a console command should return either information or an error.

In the first case, if we can't access the information for a deleted community (which is what I was trying to do), it should print an error saying that the community is deleted.

In the second case, it should point out that no administered communities were found.

**Comment by rahaeli** [comment]
Finduser will pull admin info for a deleted comm, but the one you were looking at (if it's the same one as the one I was looking at), the admin de-adminned themselves after deleting the comm. (That being the only case in which a comm can have no admin: the last admin can remove themselves if the comm is deleted.)

But yeah, we should probably have the command return a "No admins" or "No communities adminned" in the case of the comm having no admins and the user adminning no comms, respectively.

**Comment by kaberett** [comment]
Claim!
