### ISSUE TITLE
embedded flash widgets work on HTTP journals but not HTTPS

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1766]
http://www.dreamwidth.org/support/see_request?id=33307

Seems like if you use HTTPS, the widget will just silently fail to load, even though it's going through our site-embed process so that it appears to be sourced from embedded.dreamwidth.net.

**Comment by kareila** [comment]
I've poked at this a little more - the actual error I'm seeing in the browser console is this: 
```
[blocked] The page at https://embedded.dreamwidth.net/?journalid=1221431&moduleid=86&preview=&auth_token=sessionless:1486184400:embedcontent:1221431%2686%26:7f18fa04ee6b81e986d18b3f475485c0ad2b3b86 was not allowed to run insecure content from http://muzicons.com/musicon_v_srv_new.swf.
```
The raw embed src is `http://muzicons.com/musicon_v_srv_new.swf` which makes me think it would work if the user edited the embed code in the entry to use `https://muzicons.com/` or `//muzicons.com/`, although when I try connecting to `https://muzicons.com/musicon_v_srv_new.swf` I get another browser error about not trusting self-signed certificates.

The only way for us to handle it on our end would be to change the behavior of the HTML cleaner, which I don't think is a good idea in this case.

I'm going to leave this open as needing documentation because when we turn on HTTPS Everywhere, I think we're going to see a lot more complaints similar to this one, and it should probably be listed in the Known Issues FAQs.

**Comment by kaberett** [comment]
... oh dear uh have we... fixed this? should it be closed anyway?

**Comment by kareila** [comment]
Well, my prediction of seeing more complaints similar to this one didn't come true, presumably because most websites have improved their HTTPS support in the interim.  I'm fine with closing it.
