### ISSUE TITLE
dw-free shouldn't default to using en_DW for translation

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1768]
... since the en_DW data is in dw-nonfree.

LJ::Global::Defaults does the right thing: `@LANGS = ("en") unless @LANGS;`

However etc/config.pl says: `@LANGS = qw( en_DW );`

One possible solution could be to put this config line in a conditional that only executes if `-d $HOME/ext/dw-nonfree` is true.

**Comment by kareila** [comment]
Alternatively, we could move the LANGS line to the config-local.pl in dw-nonfree which I didn't realize was there until 30 seconds ago. 😱

**Comment by kareila** [comment]
BTW pinterface is working on this issue, but hasn't submitted a CLA yet.

**Comment by pinterface** [comment]
I suppose since I've submitted a patch I should actually claim this.

**Comment by pinterface** [comment]
Argh.  Previous patch stuck @LANGS in both config and config-local, which doesn't
work so well (config would just override config-local).  With a better
understanding of how the config system works comes a smaller patch.

**Comment by kareila** [comment]
I thought that might be the case, but I hadn't had a chance to test it yet. Kudos for catching that 😊

**Comment by kareila** [comment]
Hmm, what if config.pl does `//=` instead of `=`, i.e. only assign the given value if it was undefined?  Then config-local.pl can be allowed to have a different value for `@LANGS` and config.pl won't clobber it.  We want to encourage people to put all their local changes in config-local.pl and not override config.pl unless absolutely necessary.

**Comment by pinterface** [comment]
`//=` seems mostly reasonable--it'll be a little weird as the one and only thing set in config.pl that can be overridden from config-local.pl, but I think I see where you're trying to go to make nonfree "just work" for dreamhacks.

I've got some bikesheddy ideas for adjusting the config system to work better, but rather than derail this one, I'll save those for another bug.  (Or would a dw-dev post be better?  I'm not really clear on where detailed dev discussion should happen.)

**Comment by pinterface** [comment]
PR so updated.  Ended up wrapping it in an `unless`, because apparently `//=` and `||=` force things into scalar context, which doesn't work so well when attempting to operate on lists.

**Comment by kareila** [comment]
Yeah, DW-dev is the best place for a discussion of that nature, I think.

**Comment by rahaeli** [comment]
Yeah, dw-dev -- anything that has the potential to turn bikesheddy should go there first for people to hash it out. :)

**Comment by pinterface** [comment]
Let the bikeshedding commence!

http://dw-dev.dreamwidth.org/186511.html
