### ISSUE TITLE
Possible precedence issues (complaints by Perl 5.20)

### ISSUE THREAD

**Issue by pinterface** [dreamwidth/dw-free#1772]
These appear in the apache logs on startup.

```
Possible precedence issue with control flow operator at /home/dw/dw/cgi-bin/LJ/Stats.pm line 66.
Possible precedence issue with control flow operator at /home/dw/dw/cgi-bin/LJ/Stats.pm line 113.
Possible precedence issue with control flow operator at /home/dw/dw/cgi-bin/DW/Hooks/SiteSearch.pm line 25.
Possible precedence issue with control flow operator at /home/dw/dw/cgi-bin/DW/Shop.pm line 191.
```

For instance, in Stats.pm, around line 66:
```perl
    return LJ::Stats::get_db("dbr")
        or die "Can't get db reader handle.";
```
Which, by Perl's rules of precedence, is equivalent to
`(return f) or (die "msg")`, which is pretty nonsensical.
Presumably, this should be something more like `return f || die`,
to match the ordering of `return (f or die)`.

see http://perldoc.perl.org/perldiag.html#Possible-precedence-issue-with-control-flow-operator

**Comment by kareila** [comment]
I can't find anything about it in the programming style guide on the wiki (http://wiki.dreamwidth.net/wiki/index.php/Programming_Guidelines) but general practice has been to prefer '||' when chaining nouns, and 'or' when chaining verbs. If that produces a precedence warning under 5.20, I would prefer to rewrite the statement onto two lines to make the flow clearer, something like: my $dbr = get_db or die; return $dbr;

(Apologies for vague formatting; I'm writing this on the iPad, which makes proper punctuation difficult.)

**Comment by pinterface** [comment]
To be honest, I'm a little surprised Perl didn't go the DWIMmy route and make `return x or die` work as desired, because `return x || die` is definitely uglier.  The only other single-line alternative I can think of is `return (x or die)`.  Two lines is better than any of those options by a pretty wide margin, so I'm perfectly happy to go that route.
