### ISSUE TITLE
Link to other days from /read?date=YYYY-MM-DD

### ISSUE THREAD

**Issue by cesy** [dreamwidth/dw-free#1778]
Was Bugzilla 2371 from http://dw-suggestions.dreamwidth.org/249713.html

Summary:

Link to the previous and next day when viewing the reading page by date. 

Description:

When viewing the reading page by date, at least in my style, there are only
?skip= links, and not links to the previous and next dates. It would make for a
more intuitive use of this feature if these links were available. 

One could have these in two ways. 

1) Link to date only when there is no ?skip going in the indicated direction.
For example, on /read?date=2020-01-01, a link to /read?skip=20&date=2010-01-01
(previous) and /read?date=2010-01-02 (next), and only link to 2009-12-31 once
there is no more previous for 2010-01-01. 

2) Link to previous and next date in addition to the ?skip= links. 

If you have a preference on which of these should be done, please say so in
comments. 

Suggested by:

azurelunatic

Implementation notes: Implement as #1 above.

Ordinary case;       previous ?skip, and next ?skip
If no previous skip; previous ?date, and next ?skip
If no next skip;     previous ?skip, and next ?date
If no skips;         previous ?date, and next ?date

Ideally it should find the next day with entries and use that -- so, for instance, if you're on the day page for 2013-01-30 and there was no entry on 2013-01-29 or 2013-01-28, but there was on 2013-01-27, the link on 2013-01-30 should be to the day page for 2013-01-27.

Notes from Chebe:
The files I think need to be looked at are $LJHOME/styles/core2.s2 (and
cgi-bin/LJ/S2/FriendsPage).
To rebuild to see changes to core2.s2 on your dreamhack you need to run the usual dwdb script.

**Comment by cesy** [comment]
Should this apply to journals/recent entries view as well as reading pages?

**Comment by rahaeli** [comment]
I *think* it already does that on journals/recent entries view.

**Comment by kareila** [comment]
See also #1569.
