### ISSUE TITLE
Some ML item codes are over-long

### ISSUE THREAD

**Issue by pinterface** [dreamwidth/dw-free#1787]
Seen in the apache logs:
> '/customize/options.bml.widget.navstripchooser.option.color.control_strip_bordercolor' exceeds maximum code length, truncating to 80 symbols at /home/dw/dw/cgi-bin/LJ/Lang.pm line 329.
> '/customize/options.bml.widget.navstripchooser.option.color.control_strip_linkcolor' exceeds maximum code length, truncating to 80 symbols at /home/dw/dw/cgi-bin/LJ/Lang.pm line 329.

Fortunately, they're the only such strings:
```
mysql> select itcode from ml_items where length(itcode) = 80;
+----------------------------------------------------------------------------------+
| itcode                                                                           |
+----------------------------------------------------------------------------------+
| /customize/options.bml.widget.navstripchooser.option.color.control_strip_bgcolor |
| /customize/options.bml.widget.navstripchooser.option.color.control_strip_borderc |
| /customize/options.bml.widget.navstripchooser.option.color.control_strip_fgcolor |
| /customize/options.bml.widget.navstripchooser.option.color.control_strip_linkcol |
+----------------------------------------------------------------------------------+
4 rows in set (0.00 sec)
```

bgcolor and fgcolor happen to fit exactly, but bordercolor and linkcolor overflow slightly.

Since they're still unique based on those first 80 characters it's not a practical problem, but probably something to consider.  It may make sense to widen itcode, or shorten those names.

And in case you're wondering, for the most part things are well within the size limit.  There are only a handful of items above 70 characters, the majority are under 50:
```
mysql> select ceil(length(itcode)/10)*10 len, count(*) cnt from ml_items group by len order by len;
+------+------+
| len  | cnt  |
+------+------+
|   10 |   29 |
|   20 |  524 |
|   30 | 2178 |
|   40 | 2746 |
|   50 | 1255 |
|   60 |  415 |
|   70 |  159 |
|   80 |   39 |
+------+------+
8 rows in set (0.01 sec)
```

**Comment by kareila** [comment]
I also noticed that the other day, but after looking at it a bit, I came to the conclusion that we probably can't easily change those string codes, since they are determined programmatically by the style wizard and the name of the relevant S2 property.  If we want to remove the warning, I would ask @zorkian if he's OK with widening the relevant table column to 85 characters.

**Comment by zorkian** [comment]
No reason not to extend it I think. Maybe go a bit more than we strictly
need though, 120?
 
--
Mark Smith
mark@qq.is
 
 
On Mon, May 16, 2016, at 10:58 AM, Jen wrote:
> I also noticed that the other day, but after looking at it a bit, I
> came to the conclusion that we probably can't easily change those
> string codes, since they are determined programmatically by the style
> wizard and the name of the relevant S2 property.  If we want to remove
> the warning, I would ask @zorkian[1] if he's OK with widening the
> relevant table column to 85 characters.
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub[2]
>
 

Links:

  1. https://github.com/zorkian
  2. https://github.com/dreamwidth/dw-free/issues/1787#issuecomment-219497037

**Comment by kareila** [comment]
Marking this for beginners since widening a table column is pretty straightforward.  An example: https://github.com/dreamwidth/dw-free/blob/develop/bin/upgrading/update-db-general.pl#L3690

**Comment by pinterface** [comment]
Would a patch need to do anything to adjust the names of the two
over-long items which are presently truncated in the table, or should it
rely on them being recreated?

**Comment by kareila** [comment]
I would expect texttool.pl to recreate them, but I don't think it will drop the truncated ones unless we add them to deadphrases.

**Comment by pinterface** [comment]
Whoops, forgot to claim.
