### ISSUE TITLE
Swirly D icon should be in dw-nonfree

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1797]
I just noticed an issue with #1754, which is that the Swirly D icon was committed in dw-free.  In the past, we've insisted on DW-specific iconography being reserved for dw-nonfree, since we don't want daughter sites using our specific logo.

The image information should be specified via config parameter, similar to what we did for `$LJ::APPLE_TOUCH_ICON`.

**Comment by cesy** [comment]
claim
