### ISSUE TITLE
extra padding on /entry/new

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1820]
After the code push, there's now extra padding on the security/location buttons on /entry/new:

![extrapadding](https://cloud.githubusercontent.com/assets/1716035/16188658/9895ce54-36a4-11e6-9b02-9684df473f34.png)

Previously, those drop-downs were closer to each other (and I think they still should be).

Happens in Tropo and Celerity; haven't tried it in anything else.

**Comment by kareila** [comment]
Probably due to #1793.  I'll look into it.

**Comment by kaberett** [comment]
(This also affects the tag box, and the bullet-pointed "you can view this entry/view your journal entries/etc" section on the success landing page.)

**Comment by kareila** [comment]
... Okay!  Thanks for the additional info.

**Comment by kareila** [comment]
I've updated the PR to address the tag widgets. The list on the success page doesn't currently belong to any CSS classes, so there's nothing to target an adjustment with.
