### ISSUE TITLE
'0000-00-00' is no longer a valid default value for MySQL DATETIME fields as of Ubuntu 16.04 LTS

### ISSUE THREAD

**Issue by Sophira** [dreamwidth/dw-free#1822]
When running "$LJHOME/bin/upgrading/update-db.pl -r --innodb" on Ubuntu 16.04 LTS (MySQL v14.14) for setting up a new Dreamhack installation, MySQL chokes on one of our table definitions:

> ```
> CREATE TABLE clientusage (
>     userid int(10) unsigned NOT NULL default '0',
>     clientid smallint(5) unsigned NOT NULL default '0',
>     lastlogin datetime NOT NULL default '0000-00-00 00:00:00',
> 
>     PRIMARY KEY  (clientid,userid),
>     UNIQUE KEY userid (userid,clientid)
> )
>  ENGINE=INNODB;
> # Running...
> #  ERROR: Invalid default value for 'lastlogin'
> ```

...and the process stops there. It seems that later versions of MySQL don't allow for '0000-00-00 00:00:00' as a default value. I'm not sure if changing this would have any unintended side-effects in the code, however.

We should probably be allowing the field to be NULL instead, and changing any checks for the 'special' date (if any exist) to check for NULL instead.

Output of `mysql -V`:

> ```
> mysql  Ver 14.14 Distrib 5.7.12, for Linux (x86_64) using  EditLine wrapper
> ```

[edit: Apologies for the previously obtuse title - I've changed it now.]

**Comment by alierak** [comment]
Anything wrong with using a unix timestamp in an int field instead?

**Comment by zorkian** [comment]
AFAIK all times should be (in the sense that there's no reason not to and many reasons to, not in the sense that they already are) Unix epoch times in unsigned integer columns.

**Comment by Sophira** [comment]
There are many other cases where we also do the same thing - these tables all use `DATETIME` fields with a default of '0000-00-00':

* `authactions`
* `dirsearchres2`
* `duplock`
* `clientusage`
* `infohistory`
* `talk2`

**Comment by zorkian** [comment]
Yes; they should all be updated. DATETIME is how things Used To Be,
there's no reason to keep doing things that way. (Leaving aside the
question on whether or not it's _easy_ to update these...)
 
--
Mark Smith
mark@qq.is
 
 
On Tue, Jun 21, 2016, at 01:55 PM, Sophira wrote:
> There are many other cases where we also do the same thing - these
> tables all use DATETIME fields with a default of '0000-00-00':


>  * authactions
>  * dirsearchres2
>  * duplock
>  * clientusage
>  * infohistory
>  * talk2
> — You are receiving this because you commented. Reply to this email
> directly, view it on GitHub[1], or mute the thread[2].
>
 

Links:

  1. https://github.com/dreamwidth/dw-free/issues/1822#issuecomment-227568957
  2. https://github.com/notifications/unsubscribe/AAWD1GIePzAHSJ8JxiXGDK5QBqnAYHzWks5qOE_HgaJpZM4I7JsH

**Comment by Sophira** [comment]
(Just a note, you may want to edit your comment so it doesn't have the unsubscribe link in, in case a bot comes across this following links or something)

**Comment by Sophira** [comment]
Turns out that it's slightly worse than I thought, because the use of '0000-00-00 00:00:00' as a default value was implied in older versions of MySQL if a DATETIME field marked NOT NULL was used, even if the default wasn't explicitly supplied. This means that in addition to the above list, the following tables also need to be fixed and the corresponding code updated:

* `faquses`
* `userusage`
* `ml_langs`
* `ml_latest`
* `syndicated`
* `synitem`
* `pollsubmission2`

**Comment by Sophira** [comment]
I did some more investigation and it turns out that the cause of this is that MySQL now defaults to using [Strict SQL mode](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-strict) using the [`STRICT_TRANS_TABLES`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_strict_trans_tables) SQL mode:

>     mysql> SELECT @@sql_mode;
>     +-------------------------------------------------------------------------------------------------------------------------------------------+
>     | @@sql_mode                                                                                                                                |
>     +-------------------------------------------------------------------------------------------------------------------------------------------+
>     | ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION |
>     +-------------------------------------------------------------------------------------------------------------------------------------------+
>     1 row in set (0.00 sec)

It's possible to toggle this behaviour so that we don't use strict SQL mode (which is also giving other errors when updating; it might be worth turning this issue into a "Strict SQL mode" issue rather than just this one aspect of it, as I foresee some interesting issues ahead), but obviously this isn't the best idea.

Note that #1823 is *not* caused by the use of Strict SQL mode (or any of the `sql_mode` options, in fact) and needs to be fixed regardless of the decision here.

What does everybody think?

**Comment by kareila** [comment]
I think that while strict SQL mode for new projects is a good thing, for a 15+ year old project like ours that hasn't followed best practices from the start, it will take a tremendous amount of time and energy to bring it fully into compliance.  I think it would be better to turn it off and improve things on a gradual basis, like we have been doing with the Perl code all along.

That said, I spent most of my flight time yesterday looking at the first list of tables and determined that all except talk2 can be altered to use integer seconds without too much grief, I think (didn't finish reviewing infohistory).  I haven't looked at the newer list yet.

**Comment by zorkian** [comment]
Oh this is related to a newly enabled strict mode? I missed that fact. Yeah, IMO we have far bigger fish to fry than dealing with a lack of strictness in our SQL. Development efforts put towards getting off of BML and migrating to Foundation are probably going to pay off more longterm IMO.

(To be clear, of course, people are welcome to work on whatever motivates them -- I am just trying to be clear about what I feel the global importance levels are.)

**Comment by Sophira** [comment]
Well, I only realised that it was a strict mode setting that was causing the problems in the comment before @kareila's, so you didn't miss much!

In any case, that's what I thought people would say. The easiest way to disable the strict SQL mode is to do so in the server's configuration, which on Ubuntu is at `/etc/mysql/mysql.conf.d/mysqld.cnf`. If we want to revert it entirely back to old MySQL behaviour (including reverting some other changes that aren't strict-mode-specific, such as the [`NO_ENGINE_SUBSTITUTION`](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sqlmode_no_engine_substitution), then in the `[mysqld]` section, the line to add is:

    sql_mode = ''

After a restart, the server will then have no SQL mode flags active. Unfortunately, I don't know how to simply disable flags rather than setting all of them at once, so I'm not sure how you'd only disable strict mode in a way that'd be compatible in an expected way with future versions. I'll take a look to see if I can figure it out.

We'll need to document this somewhere, including in any relevant OS upgrade documentation (not just in the documentation to create a DW instance). It may also be worth altering update-db.pl so that on an error it detects if strict mode is enabled, and informs the user about it if so.

As for issues arising with the strict SQL mode, I'm guessing that a single issue for each type of problem with strict SQL mode should be raised, since this will no longer be a blocker for upgrading and thus there's no need to have them all in a single issue. Is it worth having a new GitHub milestone for Strict SQL mode issues?

**Comment by zorkian** [comment]
I think it'd be better to set it at runtime like some of the other
things we set. I.e., you should be able to set it on the session handler
when you connect to the database.

**Comment by wohali** [comment]
FYI I wanted to note that I've documented the `sql_mode` workaround on the [wiki scratch install](http://wiki.dreamwidth.net/wiki/index.php/Dreamwidth_Scratch_Installation) page and validated that it works as expected.

If you move to setting this at runtime I'm guessing it will need to go in `update-db.pl` and should then be removed from the wiki page.

From my perusal of the [MySQL documentation](https://dev.mysql.com/doc/refman/5.7/en/sql-mode.html#sql-mode-setting) it seems the correct command is `SET SESSION sql_mode = '';`

**Comment by kareila** [comment]
I'm reducing the estimated effort on this since we are no longer looking at changing columns on various database tables.  Thanks for all the investigation work.

**Comment by kareila** [comment]
Updating this to note that we are still using MySQL 5.5 in production and on the dreamhack box, so we haven't run into this problem yet.  It is likely only an issue for MySQL 5.7 and newer.

**Comment by kareila** [comment]
I'm going to tweak the spec for the desired solution based on my experiments and observations.  It occurred to me that we can't update only `update-db.pl` because that only changes the code that handles initial setup and schema changes.  Updates executed in routine operation of the site might also have unforeseen problems if strict mode is enabled.

The best and most obvious way to make sure all connections to the database have the correct mode is to add it to `mysqld.cnf` as outlined above.  In addition, we can add code to `checkconfig.pl` to check the mode of the active database.  This is the query for checking what the current mode is:
```
SELECT @@sql_mode;
```

If I run this against a vanilla MySQL 5.6 install, it returns `NO_ENGINE_SUBSTITUTION` which should be considered an acceptable value, since this doesn't cause problems.  An empty return value is also acceptable.  If the query returns any other modes, it should print an error explaining the problem and how to fix it.

**Comment by Sophira** [comment]
Just an update: The Dreamhack server has now been running with this in its `/etc/mysql/conf.d/mysqld.cnf` file since the server rebuild about three months ago:

    [mysqld]
    sql_mode = ''

During this time I haven't heard of any issues relating to this setting, so this sounds like a good way to do it. I'm thinking that having `NO_ENGINE_SUBSTITUTION` in there is probably a good idea though.

**Comment by EmTee70** [comment]
Different system (Ubuntu 16.04.) so first check:
`mysql:> select @@sql_mode`
then
edit: 
`/etc/mysql/my.cnf`
insert the following  to overwrite default:
into **[mysqld]** section.
`sql_mode=ONLY_FULL_GROUP_BY,ERROR_FOR_DIVISION_BY_ZERO,NO_AUTO_CREATE_USER,NO_ENGINE_SUBSTITUTION`
Then:
`service mysql restart`
and check with 
`select @@sql_mode``

only `sql_mode='' `was not working.

**Comment by Sophira** [comment]
The Dreamhack server also runs on Ubuntu 16.04, and [my comment above yours](https://github.com/dreamwidth/dw-free/issues/1822#issuecomment-315398481) describes what I've been doing to fix it, so it's a little odd that it didn't work for you!

When you say that `sql_mode=''` wasn't working, exactly what do you mean? Were you still getting the errors described in this issue?

**Comment by EmTee70** [comment]
Hmm, you are right, its odd, and I retried it and now it works! ...

In the end I think I edited the wrong file /etc/mysql/mysql.conf.d/mysqld.cnf. You mentioned.
Not /etc/mysql/my.cnf. Then I searched for another solution and I only removed the necessarily part of the sql_mode string.  So your solution is ok, but you have to ensure, that the file is really  the the conf file in use  :-)

**Comment by pauamma** [comment]
Can this be closed?

**Comment by kareila** [comment]
I recommend leaving it open until there's a failsafe in place for making sure this is enforced.  I suggested adding a check to `checkconfig.pl` somewhere in the above discussion.

**Comment by Adwooo** [comment]
is it possible that on one server with the seame sql server veriosn there is /etc/mysql/conf.d/mysqld.cnf

and on the othere in  /etc/mysql/conf.d/   i have only mysql.cnf  mysqldump.cnf. where mysql.cnf contains ONLY [mysql] inside??
i have no idea where can i put sql_mode=''  
anny ideas pleas?

**Comment by mopsyd** [comment]
You can approach this pretty easily with column changes to get 5.7 compliance.
- Change defaults from `'0000-00-00 00:00:00'`  to `'1970-01-01 00:00:01'` (the unix epoch in mysql date format).
- Change `TIMESTAMP`, `DATETIME` and `TIME` columns to `TIMESTAMP(0)`, `DATETIME(0)`, and `TIME(0)` respectively, to avoid the microtime formatting applied to new time format columns applied after mysql 5.6.

- Don't set the entire `sql_mode` to `''`, which is very unsafe and tends to make the database chug overall. Instead remove just the relevant flags, eg: `SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'NO_ZERO_IN_DATE','')); SET GLOBAL sql_mode=(SELECT REPLACE(@@sql_mode,'NO_ZERO_DATE',''));`. You will potentially introduce security and performance vulnerabilities otherwise.

- Find all the columns that need the date updated with the following:
```
SELECT * FROM INFORMATION_SCHEMA.COLUMNS
WHERE TABLE_SCHEMA NOT IN ('information_schema', 'performance_schema', 'mysql', 'sys')
AND DATA_TYPE IN ('timestamp', 'datetime', 'time')
AND COLUMN_DEFAULT LIKE '%00:00:00'
;
```
Then update to use the unix epoch instead of zeros. You will still get a string/valid date back, so the application code impact should be minimal or nonexistent.

Cheers.

**Comment by momijizukamori** [comment]
Closing this as superseded by the work in https://github.com/dreamwidth/dw-free/pull/2856
