### ISSUE TITLE
textcaptcha always fails if answer is 0

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1848]
Say the question is "what is the third digit of 1304873111": the answer is 0. Reports say that whether you answer '0' or 'zero', it always fails. I don't know if this is a bug on our end or a bug with textcaptcha, but my gut instinct is that it's a Perl problem on our end, since Perl treats equivalence checks on the string '0'/'zero' as always false.

**Comment by kareila** [comment]
Hmm. It treats "0" as false, but "zero" is just another string.

**Comment by rahaeli** [comment]
I might have misunderstood the way it was reported to me.
