### ISSUE TITLE
add alert for email output dropping too far

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1851]
Whether through Datadog or Nagios or what-have-you, I think we need an alert for the mail queue being backed up, especially with SES.

**Comment by kareila** [comment]
@alierak says that the size of the mail queue will spike depending on site activity.  Meanwhile Datadog is already monitoring the rate of outgoing mail, and as soon as he can concentrate again, he'll figure out how to set up an alert for when that drops off.

**Comment by rahaeli** [comment]
\o/ that will also work! Assigning him.

**Comment by alierak** [comment]
Okay, we now have a Datadog monitor for "no mail sent in the last 15 minutes". This will definitely catch the case where all of the send-email-ses workers are hung. If only some of them are hung, then it may not appear anything is wrong until a large burst of notifications need to go out, and they're going out too slowly. I haven't quite worked out how to catch that case without alerting whenever there's a notification spike. It would probably need to involve an assumption about the minimum acceptable delivery rate, but only during periods when we have a high queue.

**Comment by rahaeli** [comment]
That should still be an improvement!
