### ISSUE TITLE
add absolute time to inbox timestamps

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1852]
Suggestion from Feedback (modified slightly): there are cases, especially with high-volume discussion/writing-meme communities, where being able to tell the absolute time a comment was left, at a glance, from notifications in the inbox is helpful. Relative time ("X hours ago") is also useful for other use cases, so let's do both. Where the inbox timestamp is currently:

> 2 hours ago

It should be:

> 2016-08-09 3:41 AM EST 
> 2 hours ago

Timestamp should be in user's timezone if they've set it in preferences, otherwise UTC.

**Comment by brainwane** [comment]
Is this from https://dw-suggestions.dreamwidth.org/1491929.html ?

**Comment by rahaeli** [comment]
oh hey I forgot that this issue existed, otherwise I would've bounced the suggestion with "already in GHI"! DON'T MIND ME

**Comment by alexwlchan** [comment]
Looking at this
