### ISSUE TITLE
Email posting: post-security tag not working (possibly under some conditions)

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#1854]
From support with some useful info and testing:
https://www.dreamwidth.org/support/see_request?id=34146

It seems placing the post-security tag after body text or using it with no body text means it's ignored and security reverts to your default mobile posting one (or entry security?). The user mentions having issues only when attaching images but I was having the same issues with text only.

I'm also having issues with the post-security tag no matter where I place it. It is parsed as body text no matter what I do (text-only; latest Thunderbird).

**Comment by kareila** [comment]
Second report: http://www.dreamwidth.org/support/see_request?id=35832
