### ISSUE TITLE
Can cgi-bin/LJ/TextMessage.pm and htdocs/tools/textmessage.bml go away?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1864]
We inherited from LJ the ability to let users tell us their mobile number and provider, and display a link on their profile that would let anyone send them a text message using our site as the gateway.  That code includes an extensive list of providers that hasn't been maintained over the years, and I doubt anyone has any interest in keeping it up to date.  (Sites like Twilio charge money for that sort of thing.)

We should decide whether to remove the feature or to put in the effort of converting it from BML to TT and updating the list of providers.  (I vote for code machete.)

**Comment by rahaeli** [comment]
I also vote for code machete.

**Comment by kareila** [comment]
CODE MACHETE IT IS.

**Comment by kareila** [comment]
.... tfw when you realize you wrote DW::Setting::TxtMsgSetup (or at least refactored it out of a larger BML page... but still) 😅 

brb killing my darlings

**Comment by zorkian** [comment]
hahaha that's always one of my favorite parts -- less code for people in
the future to come ask me about
