### ISSUE TITLE
Unhelpful support volunteer error messages

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1867]
A support request comes into a public catgeory (e.g. G/UNK) that needs moving into a restricted category (e.g. account payments). If you open the request, get distracted, and then come back to move it *after someone else has already moved it*, you receive the error "Invalid reply type" rather than the "You don't have the necessary privileges to view this request" error. It would be preferable to receive the latter error.

**Comment by kareila** [comment]
The "Invalid reply type" error is in append_request and the "necessary privileges" error is in see_request, so it's not as simple as replacing one with the other.  My suggested fix would be to make a list of the possible reply types (which appear to be one of the five following: answer, bounce, comment, internal, and screened), return the "Invalid reply type" error if it's not one of these five, and return a different error, something like "the action you were attempting to perform was not allowed," if the requested reply type isn't included in the return value of LJ::Support::get_answer_types (see append_request.bml line 70).

**Comment by rahaeli** [comment]
Alternately, we could just save the effort/hassle and change that error message to "Either the reply type was invalid, you've tried to do something you aren't authorized to do, or someone else handled the request between when you opened it and when you submitted your response".

**Comment by kareila** [comment]
It's English-stripped, so if you want to just edit it on the site, `/support/append_request.bml.invalid.type` is what needs to be changed.

**Comment by rahaeli** [comment]
"Invalid reply type. Either something's broken, you've tried to do something your account isn't authorized to do, or someone else has moved the request into a private category between when you opened the request and when you hit submit."

**Comment by kaberett** [comment]
\o/ thank you!
