### ISSUE TITLE
remove support for lj-template/site-template custom tag?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1869]
I was trying to make a list of all the custom formatting tags the site supports, and ran across one I'd never seen before: site-template, formerly known as lj-template.  As far as I can tell from reading through the code, it only does anything if we define a hook for "expand_template_video" and we have no such hook.  Does anyone have any further insight into this?

**Comment by rahaeli** [comment]
Probably an old ljcom or ljcomint hook -- I keep meaning to go through the code and find hooks that we don't define and yank them out. This one can safely be yanked, I'm 99.9% sure.

**Comment by kareila** [comment]
I tried that once and there's just too many of them.

Also related: anything classed "ljvideo" - git grep has several matches.

**Comment by kareila** [comment]
Er, perhaps not anything.  Here's context from IRC:
```
10:07 < Wohali> Kareila: I'm also ignoring this appears-to-be-deprecated ljvideo tag.
10:07 < Wohali> the button is disabled in the RTE so I'm guessing it's been removed for a
                while now, possibly forever at DW itself.
12:50 < Kareila> Wohali: which disabled button? Embed Media seems to work OK for doing
                 site-embed
12:52 < Wohali> not embed media
12:52 < Wohali> there is separate support (sorta) for an ljvideo tag
12:52 < Wohali> it is no longer exposed to the end user
12:53 < Kareila> okay, it's a bit confusing because fcklang.ljvideo2 is "Embed Media" so
                 I thought that was the button, but it's not disabled
12:54 < Wohali> not the <site-embed> tag no
12:54 < Wohali> i have that one properly supported
12:54 < Kareila> yeah, I know
12:54 < Kareila> but I do see where something classed ljvideo in HTML is translated to
                 site-template
12:54 < Wohali> aha!
12:54 < Kareila> which is the one I want to make sure gets ripped out to avoid confusion
12:54 < Wohali> so that's the no-longer-valid thing.
12:54 < Wohali> yup i will not insert that at all
```

**Comment by kareila** [comment]
It looks like the relevant dead FCK code here is in LJVideoCommand.  The related string I found says "Please enter the YouTube or Google Video URL:" so it's definitely something for automatically translating URLs to embed codes.  @wohali says the new CKEditor she's using with the beta update page has better built-in support for that functionality via plugins that we could enable at a later date.

**Comment by rahaeli** [comment]
Yeah, let's go with "don't implement and see if anyone complains", then. :)

**Comment by Sophira** [comment]
I'm pretty certain that on LJ the tag was (is?) used for the initial 'welcome to LJ, here's your journal' entry which would appear in all new journals by default.

Obviously, we don't do that, but it's one other thing it was used for on LJ.

**Comment by rahaeli** [comment]
ohhhh that makes sense! I'd forgotten about that.
