### ISSUE TITLE
weird FAQ rendering issue

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1886]
I tried to add a FAQ just now that contained an unordered list using `<ul>` tags.  When I previewed the FAQ, it rendered normally, but when I looked at it via faqbrowse after saving, the list displayed as an ordered list with numbers.

**Comment by kaberett** [comment]
This is consistent behaviour throughout the FAQ system.

**Comment by rahaeli** [comment]
Guessing it's something to do with the CSS reset or something? IDK.

**Comment by pinterface** [comment]
Do y'all still experience this?  I can't duplicate it.  The only weirdness that I see is that faq.css has `list-style-type: outside`, which is invalid (should be `list-style-position: outside`), but all that should do is get ignored, not cause it to effectively treat everything as being `list-style-type: decimal`.

**Comment by kareila** [comment]
Interesting, this appears to be a rendering bug in Firefox.  Looks fine in Chrome and Safari.

I do think you correctly identified the problem, though.  If I change the page CSS to use `list-style-position: outside` instead, the bullets appear as expected.
