### ISSUE TITLE
issues with various site elements on Windows phone

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1890]
- icon browser not working on entry page comment forms - images fail to load (but works OK with comment previews and the beta update page) http://www.dreamwidth.org/support/see_request?id=33361
- can't delete post using beta update page - acts like entry was edited instead http://www.dreamwidth.org/support/see_request?id=33362
- both account management page and community management pages have authas menu issues http://www.dreamwidth.org/support/see_request?id=33531

**Comment by momijizukamori** [comment]
As we have no reports for the last seven years, and Windows phones are now basically deprecated, I'm going to close this. If we get new reports, we'll deal with them when they come in.
