### ISSUE TITLE
notifyarchive table shouldn't be used if esn_archive is disabled

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1896]
From conversation elsewhere...

@zorkian: "DID YOU KNOW... About 5-10% of our database is the `notifyarchive` table which contains
notifications that have been archived. It doesn't contain text -- just the link saying 'user X has notification Y in this state'. This is bonkers..."

@rahaeli: "LOL, that's hysterical. I think the maximum # of notifications you can have in the inbox is 2000 for premium paid accounts? Whatever that # is (it's in the config) we can cap it at that."

Looks like the cap is "inbox_max" which we have set at 2000, 4000, or 6000 depending on account type.  Not sure if we want to do lazy cleanup when a message is archived, or create a worker for the job; since many of the affected accounts are inactive, using a worker may make more sense.

**Comment by kareila** [comment]
Let's make this a bin/maint script which is scheduled via cron.

**Comment by kareila** [comment]
Can I claim this? (We just switched all site services over to new hardware, including the claimbot.)

**Comment by kareila** [comment]
I could use some advice figuring out the best way to phrase the SQL for this task.

My first draft does a single SELECT to get the 100 worst offenders on a given cluster, then 100 DELETES to remove all but the most recent 7500 rows for each of those users - the idea being every time it is run, it will reduce it a little further, instead of trying to do all the cleanup at once.  Is this a reasonable approach, or should I be looking at the problem differently?  Should I also filter for rows that are in a "deleted" state, which might require an additional index?
```sql
SELECT userid, COUNT(*) AS count FROM notifyarchive GROUP BY userid
 ORDER BY count DESC LIMIT 100;                                                 

DELETE FROM notifyarchive WHERE userid=$userid ORDER BY createtime
 LIMIT ($count - 7500);                                                         
```

**Comment by zorkian** [comment]
The first query is too heavy to run on the database since it requires a full index scan (and it's so large it requires creating a temporary table); that will take many minutes and make the database sad. I think there's no sane way to do it in a single query given the indexes we have and what you want, so I'd suggest batching like:

```SELECT userid, COUNT(*) AS count FROM notifyarchive
    WHERE userid BETWEEN 1 AND 1000 GROUP BY userid HAVING count > 7500;```

You'd have to iterate over all the blocks of 1,000 userids. It looks like 1,000 is a reasonable batch size: these queries take ~0.1 seconds.

**Comment by kareila** [comment]
1. Is it still reasonable to try to purge the entire table every time this is run? There are 2729236 accounts, so this loop will run 2730 times and take almost 5 minutes, just for the SELECT statements.

2. I mentioned the possibility of filtering the results for notifications in a deleted state.  Did you have any thoughts on that?

**Comment by zorkian** [comment]
1. This should be a one-time job just to get the table under control. Separately, whenever someone archives a notification we should delete anything that is past the 7500 limit i.e. your second query. (And, this separate part has to come first. We need that deployed before the one-time cleanup.)

2. Is the purpose to make sure we keep 7500 *visible* notifications? If so, that still wouldn't necessarily work b/c if we prune to 7500 and someone deletes one then they're down to 7499 right? So, I am not sure what filtering on delete buys us?

**Comment by kareila** [comment]
I was just envisioning a scenario where the most recent 7500 notifications might be mostly deleted but there might be older ones in a different state that would be purged instead of more recent deleted ones, if we're only looking at createtime. I don't know if it matters or not. I probably should investigate how and where the inbox_max limit is enforced before making any more design decisions.

**Comment by kareila** [comment]
Also I think any ongoing enforcement should happen whenever someone receives a notification, not when they archive one. Otherwise people who never interact with their inbox won't be affected.

**Comment by zorkian** [comment]
Makes sense. I didn't think about that edge case, that's definitely a possibility. Investigation sounds good -- happy to chat more about it when you've got more thoughts!

**Comment by kareila** [comment]
I've found that the inbox_max limit is applied in NotificationInbox.pm by the `enqueue` method, but it's only applied to notifyqueue, not notifyarchive.  It would be simple enough to delete the same userid/qid rows from notifyarchive that are being deleted from notifyqueue in that same block.

The logic there doesn't look at the state or createtime columns.  It deletes the rows with the smallest qids that aren't saved in notifybookmarks, which looks like where a message's flagged status is stored.

**Comment by kareila** [comment]
All told, there's three relevant tables: notifyqueue, notifyarchive, and notifybookmarks.  The inbox is notifyqueue, archived items are in notifyarchive, and flagged items are in notifybookmarks.  An item's qid is unique across all three tables, and an item can exist in any combination of the tables.  The size of notifyqueue is limited by inbox_max, and the size of notifybookmarks is limited by bookmark_max, but there's no limit on the size of notifyarchive.

I'm officially losing my mind trying to decipher this, though, because I can't see where in the code or on the inbox page that items are archived.  We know they are being archived, though, because of the size of the table.  Reading or deleting a message changes the state of the message, not what table it's in.  Very strange...

**Comment by kareila** [comment]
Ah, I think I understand it now.  The inbox's enqueue method also creates a row for every item in the notifyarchive table - `my $archive = delete $opts{archive} || 1;` is always true no matter what the value of `$opts{archive}` is.  They're just piling up there indefinitely.

The real kicker is that the archived items are only visible in the inbox if `esn_archive` is enabled.

We disabled it in 2009: https://github.com/dreamwidth/dw-free/commit/baa597dc224884d1c46ad912521812f73158eff5

I'm so done.

**Comment by kareila** [comment]
Once my Karzilla rampage is over, I think we need to do two things:

1. Change the above line to `my $archive = delete $opts{archive} || LJ::is_enabled( 'esn_archive' );`

2. Let one of the sysadmins delete all rows from notifyarchive on all our clusters.

Good night.

**Comment by rahaeli** [comment]
> I'm so done.

I think after the past few weeks, I owe you a large quantity of your Favorite Sophisticated Adult Beverage.

**Comment by kareila** [comment]
How about a Teavana gift certificate? 😁
