### ISSUE TITLE
error in stats/site

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1909]
Error: undef error - Illegal division by zero at /home/dw/production/views/stats/site.tt line 152.

I'm guessing a cron job isn't running (ping @alierak @zorkian) to produce something, hence the divide-by-zero error, but we should also fix it so it fails gracefully with a "hey dumbass start this cron job" error.

**Comment by kareila** [comment]
Reopening to also fix the "Illegal division by zero" error in the template.
