### ISSUE TITLE
$STATDOCS no longer optional if using dw-nonfree?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1910]
Distilled from conversations on http://dw-dev.dreamwidth.org/193443.html and elsewhere - following the changes in #1897, resource file concatenation is no longer optional and as a result, if using dw-nonfree CSS or JS resources, site admins need to take steps to make sure the compiled nonfree files make it into a shared build directory as indicated with the $LJ::STATDOCS global variable.  It looks like if STATDOCS isn't set, it falls back to HTDOCS and returns a 404.

There are at least two possible approaches to this problem that I can see.  One would be to note that the dw-free script `bin/build-static.sh` assumes the shared directory is "$LJHOME/build/static" and add this assignment to one of the default config files, then educate developers to use that script.  Another, more backward-compatible solution might be to reintroduce the CONCAT_RES config variable that makes the concatenation logic optional, so that it will simply be skipped if the variable isn't set.  I could make an argument in favor of either approach.

**Comment by zorkian** [comment]
Let's not add more options (or re-add old ones).

I'd prefer either making the static build part of the required process (then it mirrors prod), or, making the concat code know how to look at the ext/ directory for other files. I.e., it can learn how to pull files from overlapping directories.

**Comment by Sophira** [comment]
I'll be adding `bin/build-static.sh` to the Dreamhack build script and editing the config to suit, so new Dreamhacks (and reinstallations) after I do this won't have to have this done manually. Existing Dreamhacks, on the other hand, will need to do this if they don't choose to reinstall.

**Comment by pauamma** [comment]
Is the process steady enough to document at this time? It looks like at least http://wiki.dreamwidth.net/wiki/index.php/Dev_Maintenance#Compile_the_SCSS needs a mention of build-static.sh.

**Comment by alierak** [comment]
Documented as-is there (with unfortunate name change for the section) and in http://wiki.dreamwidth.net/wiki/index.php/Dreamwidth_Scratch_Installation -- we still need a config.pl default for $STATDOCS though.

**Comment by Sophira** [comment]
I'm rebuilding the Dreamhack server after the demise of the old server, and I'm putting `bin/build-static.sh` into the new user script (ie. it'll run once when a Dreamhack gets set up, but will have to be run manually after that). It seems like a reasonable default for $STATDOCS would be `$LJHOME/build/static`, as that's where the built resources end up.

(By the way, I notice that it warns me about not having a compressor; is this something I need to be worried about?)

**Comment by kareila** [comment]
I think that's just for using if you want CSS and JS gzipped to save bandwidth? I wouldn't worry about it outside of production.

**Comment by Sophira** [comment]
Fair enough.

For now I'm going to make it so that the Dreamhack installer sets the variable to `$HOME/build/static` so that the styles aren't broken. If this isn't the right thing to do, please let me know and I'll change it!
