### ISSUE TITLE
"Welcome to nginx!" on some community pages

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1911]
"Welcome to nginx!

If you see this page, the nginx web server is successfully installed and working. Further configuration is required.

For online documentation and support please refer to nginx.org.
Commercial support is available at nginx.com.

Thank you for using nginx."

Logged in, using Cyanogen on a OnePlus One, looking at thevault.dreamwidth.org.

**Comment by kaberett** [comment]
Also http://www.dreamwidth.org/support/see_request?id=35437

**Comment by kaberett** [comment]
Error message on attempting to load same community from firefox-esr under Debian 8:

"404 Not Found
nginx/1.4.6 (Ubuntu)"

**Comment by kaberett** [comment]
Resolved by @zorkian!

**Comment by kareila** [comment]
http://dw-maintenance.dreamwidth.org/73907.html
