### ISSUE TITLE
Suppress tag creation errors on community import

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#1921]
http://www.dreamwidth.org/support/see_request?id=35485

There exists a non-DW community for which creation of new tags is limited to maintainers only. Community members who are not aware of this try to tag their entries anyway. The non-canonical tags are not displayed in the community, but are recorded in the post's metadata, possibly via serving the user an error about how these tags do not exist.

Some of these communities will then be imported to Dreamwidth. If the Dreamwidth community is also configured such that only maintainers/admins can create new tags, the person who kicked off the import will get notified about every single post that has non-canonical tags _because they are considered the poster by Dreamwidth_. This is Not Great.

Discussion with @zorkian concluded that probably the best thing to do is just suppress these errors, so the importer (who never saw the tags to begin with!) doesn't get spammed with baffling error notifications.

**Comment by azurelunatic** [comment]
So, this means that in the case that the source community restricted canonical tag creation to maintainers, and the destination community does not, the admins of the destination community are going to have A Number Of previously non-canonical tags to clean up? And potentially no way of telling what they are? 

Is there any (sensible!) way to filter out the non-canonical tags on import?
