### ISSUE TITLE
link to file management in CORES menu

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1942]
Once #1936 is implemented, we should:

* Link to https://www.dreamwidth.org/file/edit under Organize (as "Manage files")
* LInk to https://www.dreamwidth.org/file/new under Create (as "Upload files")

**Comment by kareila** [comment]
Changing this to "Manage Images" / "Upload Images" per discussion elsewhere.

... The "Upload Images" menu item is already in the code, just commented out. 😳
