### ISSUE TITLE
/support/search isn't linked anywhere

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1957]
I keep forgetting it exists... where can we put it to make it discoverable for support volunteers?

**Comment by kareila** [comment]
My implementation suggestion: add additional field to the privileged view of /support/history which will take input text and hand off to /support/search. Label can be something like "Containing text".

**Comment by rahaeli** [comment]
oh, I like that.

**Comment by rahaeli** [comment]
alternately, we could also put a link to support search somewhere on each individual request, like down by the answer box? but that might be TOO prominent.
