### ISSUE TITLE
allow embeds from coub.com

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1973]
http://www.dreamwidth.org/support/see_request?id=35768

Example code:
```
<iframe src="//coub.com/embed/3l67l?muted=false&autostart=false&originalSize=false&startWithHD=false" allowfullscreen="true" frameborder="0" width="640" height="264"></iframe> 
```

**Comment by kareila** [comment]
Another request: http://www.dreamwidth.org/support/see_request?id=36128

I'll try to get around to grabbing all the open embed whitelist requests in the next few days.

**Comment by srukle** [comment]
Claim. Currently the commits are in the wrong PR. PR #2008
