### ISSUE TITLE
need to do lazy cleanup of userpicfactory temp files

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#1979]
@zorkian says there are about a million of these lying around in our MogileFS - nothing ever expires them.

**Comment by pauamma** [comment]
Should this be in a TheSchwartz worker, or triggered (perhaps with a reasonable limit on number of files, eg oldest 10) when user uploads a new userpic?

**Comment by zorkian** [comment]
Now that we're on S3, it's less relevant. I created a lifecycle management rule that prunes them after a few days. That said, I think a good ticket here would be 'document S3 settings' or something.

**Comment by pauamma** [comment]
See bug #2276. (Should this be closed, then? Or perhaps left open for sites that still use MogileFS?)

**Comment by zorkian** [comment]
I wouldn't spend any time on MogileFS stuff, we've basically removed it and will not be supporting it in the future. The only options are localdisk (for development, in which case we're not worried about temp files really) or S3 (which has this as a built in feature that saves money to use vs building it ourselves).
