### ISSUE TITLE
HTML cleaner no longer autolinkifying URLs

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1981]
I'm guessing this is related to the fix for #1948. See, for instance, https://dw-dev.dreamwidth.org/195668.html:

> url1;http://www.dreamwidth.org/file/edit&&urlend; works! url2;http://www.dreamwidth.org/file/edit&/&urlend; should also work. It didn't. Now it will. 

It's adding url1 at the beginning and &urlend; at the end, as well as a stray & in the middle, which is causing them to not auto-link and not even be copy/pastable.

**Comment by kareila** [comment]
Oh, I think this is happening inconsistently. It almost certainly has to do with breakpoint placement.  I'll look into it.
