### ISSUE TITLE
investigate image proxy use for background images in journal layouts

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1984]
https://dw-maintenance.dreamwidth.org/74385.html?thread=2614161#cmt2614161 says they're getting a mixed content warning over images from Photobucket. Journal stylesheet looks like they're replacing some of the icons with versions from imgur loaded via http (and might also have mood theme icons loaded from elsewhere but none of their entries are public so I can't confirm). 

May be nothing we can do about this (and if so, the answer would be "change your CSS and mood theme to use a SSL version") but is that something we can run through the proxy?

**Comment by kareila** [comment]
I've confirmed that mood theme images are being run through the proxy as needed.  I think we only need to address insecure layout resources.
