### ISSUE TITLE
add file hosting quota utilization to manage page

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1985]
https://www.dreamwidth.org/file/list and https://www.dreamwidth.org/file/edit should probably have "you have used XXX of your 500MB quota".

**Comment by kareila** [comment]
I recently created functions for these in cgi-bin/DW/Media.pm: `DW::Media->get_usage_for_user( $u )` and `DW::Media->get_quota_for_user( $u )`.  They will need to be converted from bytes to megabytes for display purposes.

**Comment by rahaeli** [comment]
Your ability to read my mind in advance is, as always, amazing. :)
