### ISSUE TITLE
add Medium to profile other-sites block

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#1997]
Given a user "username", the URL for the name link would be https://medium.com/@username/latest and the link for the profile link would be https://medium.com/@username. 

For the profile, we can linkify the username provided as https://medium.com/@username/latest

For the userhead image: hmm, I guess let's take https://medium.com/favicon.ico and turn it into a 16x16 png or something.

**Comment by srukle** [comment]
Claim

**Comment by srukle** [comment]
@rahaeli Should we link to the latest posts or the profile? The spec seems to want latest, which is a column in the user's profile. I think we should link to just the profile. I also have a thread in #2008.

**Comment by srukle** [comment]
Shouldn't this be closed now?

**Comment by alierak** [comment]
Github won't auto-close the issue unless a pull request that is properly linked to the issue gets merged and closed. I think this requires something along the lines of a commit message in the pull request containing "Fixes #issue-number", but then I've screwed it up myself... Oh, there we go, https://help.github.com/articles/closing-issues-using-keywords/

In this case, neither of your pull requests (2008 nor 2110) contained such a keyword, and neither has been merged. @kareila's pull request (2145) has been merged, but implemented medium support in the user tag only, so I believe she chose to reference this issue but not close it at that point.

This issue should stay open until dreamwidth/dw-free supports medium in both the profile and the user tag.

**Comment by srukle** [comment]
Ok, I'll rebase and send another PR tonight.

**Comment by kareila** [comment]
Unassigning this since #2110 was closed, but feel free to pick it back up later!

Also I will update the title of this issue to just request the profile listing, since the user tag was done in #2145.

**Comment by kareila** [comment]
I just noticed that the user tag did get done already, so this is all done now!
