### ISSUE TITLE
import failure messages should include the journal name

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2006]
Current message when failing to import entries is only "Your entries have failed to import and will not be retried" so if you tried to import multiple journals, you can't diagnose which one has the problem.  Other types of import failures may also have the same problem.

Marking this as higher priority since it affects our ability to diagnose annoying importer problems.

**Comment by srukle** [comment]
This handles the error?
 dw-free/cgi-bin/LJ/Event/ImportStatus.pm
Is there a global variable for a journal name?

**Comment by kareila** [comment]
Thanks for looking at this!  Now that I'm taking a look myself, it appears that there are several layers of code redirection here.  Instead of making the change in LJ/Event/ImportStatus.pm, you will want to change the message that is passed to the event, which is generated in each of the submodules in cgi-bin/DW/Worker/ContentImporter/LiveJournal/ when calling the fail method.  (Maybe start with Verify.pm since that's the most basic, but Entries.pm is the one we want to make sure to change.)

The information about the journal should be contained in the $data passed to try_work, most likely `$data->{usejournal}` if my interpretation of the import_data table columns is correct.
