### ISSUE TITLE
Manage Circle page should not show accounts you've banned unless you specifically ask it to

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2009]
If you've banned someone who's subscribed to you/given you access, their username won't show in the "subscribes to you" and "has given access to you" sections on your profile, but it will show to you on the Manage Circle page. We don't want to remove that entirely, because it can be a safety/personal-security issue for people to know for sure that someone is definitely reading their public entries. (Yes, it's not possible to say with confidence that someone *isn't* reading their entries -- there's always the "log out first and then directly visit journal", but if someone's subscribed to you, you know that they're reading your public entries.) Likewise, though, a lot of people ban people so they don't have to see That Failweasel's username staring at them every time they view their profile, and it would be nice if they could load their circle management page without That Failweasel's username staring them right in the face as well.

So, let's split the difference: change https://www.dreamwidth.org/manage/circle/edit so that by default banned accounts are hidden, but add a new ?view=banned (or whatever) argument. 

If you visit the page in ?view=banned mode, there should be a link right under the "Jump to: People | Communities | Feeds" that says "Hide accounts you have banned?" which leads to the normal (non-full) page. If you visit in normal/non-full mode, the link should read "Show accounts you have banned?" which leads to the full page.

**Comment by ninetyd** [comment]
\o/

This is https://dw-suggestions.dreamwidth.org/1280266.html which is partially a dupe of https://dw-suggestions.dreamwidth.org/548333.html :)
