### ISSUE TITLE
Remove "ban community" link from hover menu

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2010]
https://www.dreamwidth.org/support/see_request?id=35817

A ban community link is visible on hover pop-ups. And it works! I don't believe banning a community does anything, though.

**Comment by azurelunatic** [comment]
I believe it suppresses the display of that community's membership from the user's profile, though the user would still be listed on the community profile.

**Comment by kareila** [comment]
Is there a use case where we would want users to be able to hide their community membership on their profile?  Because it's sure as heck confusing to be presented with the option on the hover menu.

**Comment by srukle** [comment]
GitHub by default hides your association with projects and organizations. Why shouldn't Dreamwidth support a similar feature? In this case, the default would be not to hide your association.

**Comment by alierak** [comment]
Sounds like a feature hidden behind a misleading link.

**Comment by rahaeli** [comment]
The reason for not allowing people to completely hide their membership in communities is that other members of many communities need to know who their audience is -- for instance, if Alice is posting to a community for relationship problems about her abusive ex Barbara, Alice needs to know whether Barbara is a member of the community and will see the post.

**Comment by kareila** [comment]
So should we (a) remove the ability to do this, (b) remove the link from the hover menu that makes it too easy to do this, or (c) rename the link to more accurately describe the effect?

**Comment by rahaeli** [comment]
Hmm. Let's go with just "remove link from hover menu".

**Comment by srukle** [comment]
Would another issue need to be made to make sure users who've hidden themselves be unhidden after code push?

**Comment by kareila** [comment]
Maybe if we had chosen (a) above, but we're going with (b) instead.

**Comment by azurelunatic** [comment]
@srukle To clarify, the current behavior is only to hide the community on the user's profile, rather than the user on the community's profile -- if I am a member of the "embarrassing_hobby" community and ban it, someone looking at azurelunatic.dreamwidth.org/profile wouldn't see embarrassing_hobby listed there, but anyone looking at embarrassing_hobby.dreamwidth.org/profile would see azurelunatic listed there.
