### ISSUE TITLE
Change 'people' to 'users' on /manage/banusers

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2012]
https://www.dreamwidth.org/manage/banusers uses the word 'people' in some places. I believe we prefer the word 'users'.

**Comment by kareila** [comment]
Can this be changed via the translation system?

**Comment by rahaeli** [comment]
<a href="https://www.dreamwidth.org/manage/banusers?uselang=debug">Yup</a>, and some of the phrasing was clunky anyway!

Edits made just now:

.intro.ban.self = Enter the account names you want to ban from commenting in your journal. If you want to ban multiple accounts, separate the names with commas.

.header.unban = Unban Accounts

.intro.bannote.self = If you want, you can leave yourself a short note about why you're banning an account. You're the only one who will see the note.

.editwarn = <b>Warning:</b> If you re-ban someone you've already banned, the note you add here will overwrite the note you already have added. To edit the note instead, click "Edit" next to the note in the list below.
