### ISSUE TITLE
Can't log in with your Dreamwidth OpenID on LiveJournal

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2013]
https://www.dreamwidth.org/support/see_request?id=35844
https://www.dreamwidth.org/support/see_request?id=35803
https://www.dreamwidth.org/support/see_request?id=35767

@kaberett says "Dreamwidth's servers get stuck trying to authenticate the request."

**Comment by kareila** [comment]
FYI I got a different error trying to log into LJ with an OpenID from my Dreamhack.  Only seems to be a problem with LJ as far as I can tell.

**Comment by alierak** [comment]
LJ is violating the OpenID spec by presenting a trust_root of http://www.livejournal.com/ and a return_to URL of https://www.livejournal.com/identity/callback-openid.bml... where http and https do not match. I think for this specific case (user comes in to /openid/server with openid.trust_root=http://www.livejournal.com/ and openid.return_to=https://www.livejournal.com/blah) we _could_ work around it by generating a redirect to /openid/server with openid_trust_root=https://www.livejournal.com/ and all the other parameters the same. I was able to log in that way just by editing the trust_root parameter.

Returning a redirect to fix this would also violate the spec, but, well, the spec is contradictory regarding what to do when trust_root and return_to are both specified and don't match. It says to return an indirect error response, which is a redirect to the return_to URL, but you can't use the return_to URL if it failed validation.

**Comment by rahaeli** [comment]
I am OK with putting in a special case that violates spec to make LJ work, since it's our major OpenID source by far.

**Comment by alierak** [comment]
Realized I could just rewrite the incoming parameter rather than reconstructing the URL and returning a redirect. Tested in production 😎
