### ISSUE TITLE
all instances of status_image in DW/Logic/ProfilePage.pm use HTTP requests, plus most seem dead or dying

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2023]
Seeing mixed content warnings when viewing https://zorkian.dreamwidth.org/profile caused by the following resources:
- `http://big.oscar.aol.com/xb95?on_url=http://cdn.aim.com/remote/gr/MNB_online.gif&off_url=http://cdn.aim.com/remote/gr/MNB_offline.gif`
- `http://web.icq.com/whitepages/online?icq=2903909&img=5`
- `http://opi.yahoo.com/online?u=xb95&m=g&t=0`
- `http://cdn.aim.com/remote/gr/MNB_offline.gif`
- `http://status.icq.com/online.gif?icq=2903909&img=5`

Looks like Skype is also affected, with a status_image that starts with `http://mystatus.skype.com/smallicon/...`

Additionally, opi.yahoo.com and mystatus.skype.com seem to be down, possibly permanently.  As for the others:
- big.oscar.aol.com doesn't support HTTPS, plus there's a rumor going around that OSCAR is going away on March 28: https://www.aivanet.com/2017/03/aol-appears-to-be-killing-third-party-access-to-aol-instant-messenger/
- cdn.aim.com has an invalid cert (belongs to akamai.net)
- web.icq.com and status.icq.com **do** support HTTPS.  Long live ICQ?

**Comment by zorkian** [comment]
Any reason not to kill this functionality?

**Comment by kareila** [comment]
It was useful for its time, but yeah, I think it should go.
