### ISSUE TITLE
security on image cannot be set to access list on image upload page

### ISSUE THREAD

**Issue by endlist** [dreamwidth/dw-free#2036]
If you try to change the security level from public to access list, it will be set to private security instead.  Changing the security to private or leaving it on public acts as expected.

Repro Steps: 

1. Upload an image 
2. Set the visibility to access list from the upload page 
3. Image is still set to private security despite showing as being changed to access list 

Workaround: Can be fixed by going to the Manage Images page and re-saving all the settings (don't need to change the dropdown), but it'll remain private until either a new image is uploaded or you hit save on the Manage Images page instead of the upload page.

**Comment by kareila** [comment]
Hmm, I thought I had done this myself and not seen the problem, but maybe that's because I was also using the management page.  From this description of symptoms, it sounds like a trustmask isn't being passed in correctly, since access + no trustmask = private.

**Comment by kaberett** [comment]
https://www.dreamwidth.org/support/see_request?id=36535
