### ISSUE TITLE
Image security settings persisting incorrectly and unhelpfully

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2037]
A user reports an access-locked image not being visible to people on their access list (https://www.dreamwidth.org/support/see_request?id=35946); I believe a friend of mine recently ran into this too. 

>Okay, so for what it's worth, I uploaded a new image and this ended up fixing itself. And I also have repro steps:
>
>1. Upload an image
>2. Set the visibility to private from the upload page
>3. Set the visibility to access list from the upload page
>4. Image is still set to private security despite showing as being changed to access list
>
>Can be fixed by going to the Manage Images page and re-saving all the settings (don't need to change the dropdown), but it'll remain private until either a new image is uploaded or you hit save on the Manage Images page instead of the upload page.

The changed state should actually get saved!

**Comment by kareila** [comment]
Looks like this got double filed :) Closing as a duplicate of #2036.
