### ISSUE TITLE
can't import icons from LJ: code error

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2041]
http://www.dreamwidth.org/support/see_request?id=35940
http://www.dreamwidth.org/support/see_request?id=35943

Both requests quote the same error message:

`Failure running job: Store requires data be a scalar reference. at /home/dw/production/cgi-bin/DW/Worker/ContentImporter/LiveJournal/Userpics.pm line 103. `

**Comment by pauamma** [comment]
Getting the same error, pointed here by kaberett, commenting in lieu of filing a support request. Any additional troubleshooting info you'd like?

**Comment by alierak** [comment]
On LJ, you've got a broken icon that is zero bytes in size. Keywords "EFW Ex boyfriend - white on blue". I assume this is related since there were no actual errors in the importer log and this is the only one for which it didn't say "Userpic already present, not created."

**Comment by pauamma** [comment]
Eeeeeenteresting. I can either delete or reupload that icon to LJ, if you want to check whether that's the cause. MIght have to wait until the rest of my import job completes, though. Let me know whether/which?

**Comment by kareila** [comment]
Yes, please try removing and/or readding the icon and see if the import error goes away!

**Comment by kareila** [comment]
Noting for future workarounds: the indicated line of code is a DW::BlobStore call, which is likely to explain why these conditions are now causing an error where there wasn't one before.

**Comment by pauamma** [comment]
Deleting the icon on LJ allowed the import (icons only) to proceed without errors. Next step is to reupload it to LJ and try importing again, but I'll wait to do that until you guys have had a chance to look at the importer log (if needed/wanted) and get back to me.

**Comment by kareila** [comment]
If the subsequent import succeeded, there's no new information in the logs. Go ahead and try reimporting it :)

**Comment by kareila** [comment]
Another report: http://www.dreamwidth.org/support/see_request?id=36045

**Comment by pauamma** [comment]
OK, after reuploading the icon to LJ, icons import proceeded without error. I think that and the after-delete test are conclusive evidence that broken icon(s) at the import source were the cause of the internal error. It would still be nice to have a less scary error message, IMO.

**Comment by kareila** [comment]
Another report: http://www.dreamwidth.org/support/see_request?id=36113

**Comment by kareila** [comment]
One more: http://www.dreamwidth.org/support/see_request?id=36098
