### ISSUE TITLE
remove opt_nomodemail userprop

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2052]
Looks like `opt_nomodemail` is a legacy userprop from the days before ESN, which means it was never effectively used on DW.

I believe removing this will also let us remove the `migrate_prop_to_esn` user method.

**Comment by pinterface** [comment]
Are there any rows in the production userprop table for the `opt_nomodemail` prop?  Or perhaps a better question: would a patch for this need to ensure any such rows, were they to exist, got migrated?  (Assuming DW never had the prop, it would presumably only be an issue for a site old enough to have been using LJ code, that then switched to DW code, and had users who had somehow managed to never trigger the migration.  That sequence of events seems unlikely, but figured I'd double-check.)

**Comment by kareila** [comment]
Well, that's the purpose of the `migrate_prop_to_esn` user method, to migrate the rows if they exist. But we certainly have no such rows, and since it's so highly unlikely that we have anyone trying to combine current DW code with 10 year old legacy data, it makes more sense to me to just remove it and not worry about it - especially since the theoretical consequence of failing to migrate this particular prop is very small.
