### ISSUE TITLE
increase size for icon description field

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2055]
https://dw-suggestions.dreamwidth.org/1469860.html

Suggested by: alucinari
Description: Hello! I have friends that use screen readers, and a problem I have found is that when I am trying to describe icons, especially if it's a text icon with a longer quote on it, there's not enough room for me to properly describe what's going on; I either have to leave a lackluster description, or resort to chat speak, and sometimes even that doesn't really do the trick. It would be really helpful if DreamWidth allowed longer icon descriptions! It should be easy to allow more characters, and there shouldn't be any drawbacks, I don't think? Thank you for your consideration.

In the comments, lightgetsin opined that the description field should be "Longer than a tweet, shorter than a paragraph", and suggests 250 characters; let's be a bit more generous and go for 300.

**Comment by kareila** [comment]
Please don't make any changes to editicons.bml until I finish my rewrite.  It's almost done!

**Comment by rahaeli** [comment]
Hee! Thankfully, I don't need to touch editicons.bml to do it! Should have the PR up in a bit, just keep getting distracted...

**Comment by kareila** [comment]
Oh yeah, you're right!  It just references `LJ::CMAX_UPIC_DESCRIPTION` for the maxlength.

I have so many moving parts in this changeset it's easy to lose track of what points where.

**Comment by rahaeli** [comment]
I hear ya.
