### ISSUE TITLE
Reflect RP account status in site stats

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#2056]
In reference to #2048 / #2049, show the number of roleplay accounts vs. the number of non-roleplay accounts in /stats. 

Where should this breakdown happen? 

Flat total of RP/Other? 
Active accounts? 
Gender? (if so, as a fifth gender category, or a header with the four categories underneath?)
Recently active accounts: should there be a fourth category? 
New accounts: should there be a fourth category? 
(Will sp*mmers take advantage of this? (The answer is always yes.))
Demographics: location?
Demographics: age? 
(I don't necessarily think that client type is a helpful thing to break down this way.) 

Is it worth noting in the stats that this flag was added as of [push date for #2049] and that older accounts therefore may not be reflected in the stats?

**Comment by rahaeli** [comment]
Let's hold off on having an open issue for this until we see what adoption/uptake is like.

**Comment by azurelunatic** [comment]
Whee, issue machete! 😁
