### ISSUE TITLE
Small change for filter option when posting an entry

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2060]
From suggestions: https://dw-suggestions.dreamwidth.org/1432037.html (by hebethen)

"Right now, in order to designate an entry as viewable by a certain filter, one must select 'Custom' from the 'Show this entry to:' dropdown menu. Only then do the individual filters show up as checkboxes. I think it would be clearer if the option said something like 'Access Filter', or if the filter checkboxes were visible from the get-go."

This change is moot in the beta update page (how security is labeled is entirely different), so I just went and edited label.security.custom on the live DW site to be "Access Filter" via translation system.

**Comment by rahaeli** [comment]
String changed via translation system!

**Comment by kareila** [comment]
We got some pushback on this change from someone with accessibility issues: http://dw-maintenance.dreamwidth.org/76052.html?thread=2798612#cmt2798612

**Comment by azurelunatic** [comment]
I wonder if "Filtered access" would answer?

**Comment by rahaeli** [comment]
Changing, using Azz's suggestion!
