### ISSUE TITLE
Shop: Country list contains UK twice

### ISSUE THREAD

**Issue by swaldman3** [dreamwidth/dw-free#2065]
Not sure if this is strictly a dw-free or a dw-nonfree issue, but:

- Buy something in the shop. Go to the checkout
- Drop down the "country" dropdown
- Scroll down to U
* Note that "United Kingdom of Great Britain and Northern Ireland" is listed twice.

The top one works for a transaction. I haven't tested the second one!

Tested in Firefox 52.0.2.

**Comment by kaberett** [comment]
see #1623

**Comment by swaldman3** [comment]
Ach. Stupid GHI search. (it didn't show up when I searched because it was closed - but presumably the fix hasn't made it to live yet. Which I guess is maybe not *entirely* GHI's fault).

I can't see any way to mark this as a dupe, so I'll just close it.

**Comment by kaberett** [comment]
No, sorry, this is NOT an issue I think should be closed and is NOT obviously (to me) a dupe: I think this is a case where country lists were being set up in several different places and I only changed one of them, and I DEFINITELY think that the argument (about continuing to provide support for both variants) doesn't apply to the shop, where the information's being provided fresh each time. It's just that the discussion about why this even happens is included at #1623, and I think that's useful information to have to hand when considering how to fix this!

Sorry for being brief to the point of confusing. <3

**Comment by swaldman3** [comment]
Boh, sorry. I skimmed the PR, hadn't noticed it was for somewhere else. (and how silly to think that we might have one country list that would be used everywhere :-P). Reopening.

In the shop there's definitely no reason to keep the UK one as legacy.
