### ISSUE TITLE
Use HTTPS for 'some' rights reserved in site footer

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2073]
Noticed it's the only link in the footer which doesn't use HTTPS. Pau said I should file a bug...

Link is: http://www.dreamwidth.org/site/opensource

**Comment by kareila** [comment]
I think this needs to be fixed in the translation system.  The text in dw-free is different.

The string that needs to be changed is sitescheme.footer.info (see also #1796).

**Comment by rahaeli** [comment]
Fixed via translation string!
