### ISSUE TITLE
allow /support/submit to have URL argument for supportcat

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2077]
When replying to a user, I often find myself typing out something like "&lt;a href="https://www.dreamwidth.org/support/submit">open a support request&lt;/a> in the Account Payments category" (or "the Anti-Spam category", or "the Terms of Service category", etc) to direct them to the right supportcat. Wouldn't it be nice if I could type "&lt;a href="https://www.dreamwidth.org/support/submit?cat=accounts">open a support request&lt;/a> in the Account Payments category" and specify the category's shortcode (the one used for URL filtering on support/help.bml) to have the form render with the specified category pre-selected in the drop-down box? Yes, yes it would be.

**Comment by kareila** [comment]
Oh, hey, the code already has this feature, but the argument name is `category` instead of `cat`.  I'll update it to accept either argument.
