### ISSUE TITLE
Support for e-mail TLDs needs expanding

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2086]
Per https://www.dreamwidth.org/support/see_request?id=36226: a valid e-mail address at a .tech domain was rejected during sign-up.

Having followed check_email via valid_email_domains via load_include, I suspect the thing that needs editing is https://github.com/dreamwidth/dw-free/blob/3467339cd823c6d71b8a235bf76409d5dab93b85/htdocs/inc/tlds.

**Comment by kareila** [comment]
Yep! See #982. We just need to pull in a newer version of the file.

**Comment by rahaeli** [comment]
On-site include file updated with most recent list from https://data.iana.org/TLD/tlds-alpha-by-domain.txt so the user can use their preferred email address; leaving issue open to update the version shipped with the code.

**Comment by kaberett** [comment]
Want me to respond to the user thanking them again & saying that .tech is now accepted? (Want me to set a ~6-monthly reminder for myself to check if this needs doing again? It can live in the same place as my "code tour", "babydev bait", and as of this January "years in site footer" reminders...)

**Comment by kareila** [comment]
It's probably OK to leave it until someone else writes in, since so many of these new TLDs are primarily targeting e-commerce sites.

Worth noting: in the 2.5 years since the last update, the file has more than doubled in size, from 736 lines to 1533.

**Comment by rahaeli** [comment]
Yeah, I'm okay with not auto-updating the list, since most of the new TLDs are unlikely to ever show up in email addresses of people who will want accounts with us. We can just update the include file whenever somebody lets us know we're behind again.
