### ISSUE TITLE
URL link to remote entry not correct in some importer notifications

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2089]
http://www.dreamwidth.org/support/see_request?id=36241

> A few weeks ago I received a bunch of notifications re: imports, and one
> was a a failure to import a post to a community for reason of "not being
> able to create tags" in said community.
> 
> Along with the notification was a link pointing to said entry. This link
> read (abstracted for form) 'site.xyz/communityname/entryDigits' but the
> actual link was resolved to
> https://www.dreamwidth.org/inbox/site.xyz/communityname/entryDigits.
> 
> The href attribute for that link was 'site.xyz/communityname/entryDigits'.
> it needs to be prepended by 'http(s?)://(www.)?' 

I think I've discovered the responsible statement, in DW/Worker/ContentImporter/LiveJournal/Entries.pm:

`$evt->{key} = $evt->{url} = $data->{hostname} . '/' . ( $data->{usejournal} // $data->{username} ) . '/' . ( $evt->{itemid} * 256 + $evt->{anum} );`

I suspect that `$evt->{key}` should remain unchanged, but `$evt->{url}` should prepend a protocol.

**Comment by alierak** [comment]
That's not going to produce a correct URL either. It really is just a key. Keep in mind the source site hasn't told us whether to use http or https, they probably want the journal name as a subdomain in front of their hostname, underscores would need to be converted to dashes, and it might require a .html at the end. At least, that's what I can think of off the top of my head.

**Comment by kareila** [comment]
Yeah, I don't see any other spots in the importer code where the canonical URL is used.  The call_xmlrpc method constructs its destination via something like:

`"http://" . ( $opts->{server} || $opts->{hostname} ) . "/interface/xmlrpc"`

.. and then does getevents or whatever.

I've also browsed through the modules in cgi-bin/DW/External/ and although there's code there for returning a user's journal URL, there's nothing yet for returning a URL to a specific entry if we know the itemid.  That might be enough to start with, though.

**Comment by kareila** [comment]
http://www.dreamwidth.org/support/see_request?id=36284
