### ISSUE TITLE
remove lj.rossia.org as xpost destination (while keeping it in the user tag)

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2095]
https://www.dreamwidth.org/support/see_request?id=36290

From the error message, I'm going to guess that the problem is either a) lj.rossia.org doesn't have a working version of the protocol running, or b) they do but the xposter is having trouble handling it because it's a three-level domain and not a two-level domain. (I know that was a problem with adding LJR to the user tag.)

Obviously we can't fix A, but if it's B, that's something we can do something about!

**Comment by kareila** [comment]
It's definitely their protocol that's broken.  I tested it with jbackup.pl and got the same error.

```
do_sync: calling syncitems with lastsync = none yet
		xmlrpc_call_helper: LJ.XMLRPC.getchallenge
xmlrpc_call_helper error:
	String: Failed to access class (LJ::XMLRPC): Can't locate LJ/XMLRPC.pm in @INC (@INC contains: /home/lj-admin/lj/cgi-bin [etc. etc.]) at (eval 1326) line 2.

	Code: Client
Aborted.
```

**Comment by rahaeli** [comment]
Reopened issue and changed subject accordingly! Thanks for the investigation.

**Comment by rahaeli** [comment]
Although we should probably wait a few days and see if they fix it.

**Comment by kareila** [comment]
Ah, I didn't realize it was in the list of defaults.  I assumed they were just using the "Other Site" option.

To clarify: on /manage/externalaccount we need to remove the "LJRossia" option from the site menu.

But we probably don't want to delete it from the backend, or else existing crosspost setups will be very confused.

**Comment by rahaeli** [comment]
I feel like there's some way to temporarily disable an xpost destination so the site doesn't try xposts to it but the existing xpost configs users have specified don't get wiped, but fucked if I know what that process would be.

**Comment by kaberett** [comment]
Didn't that literally just get done for the insanejournal meltdown?

**Comment by kareila** [comment]
I think we only temporarily disabled imports for that case, not crossposts.

**Comment by kaberett** [comment]
(Noting that the dw_maint post does say crossposting was temporarily disabled, but ???? https://dw-maintenance.dreamwidth.org/75223.html)
