### ISSUE TITLE
make feed-fetch user agent use the same size limits as synsuck

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2097]
https://www.dreamwidth.org/support/see_request?id=36264

Trying to create a feed with that feed URL (http://feeds.feedburner.com/ProbablyOverthinkingIt) and putting in the name think_bayes (so it becomes think_bayes_feed) leads to a page on DW that just says "Error: 200 OK". 

The feed does validate as valid Atom, but has a few warnings. I don't think any of them could cause the problem, though?

**Comment by kareila** [comment]
I'm reproducing this on my hack box, but no server warnings were printed.  I'll dig into it and see if I can figure out where the problem is happening.

**Comment by rahaeli** [comment]
ia ia feed-system fth'a'gn

**Comment by kareila** [comment]
I'm looking at line 119 of DW/Controller/Feeds.pm and have come to the conclusion that the "200 OK" status line is printed because no content is being returned from `decoded_content`.  I've confirmed there is content in the response, but when I try to log the return value of `decoded_content`, I get the following warnings:
```
Use of uninitialized value $content in warn at /home/dw/dw/cgi-bin/DW/Controller/Feeds.pm line 122.
Can't gunzip content: unexpected end of file at /usr/share/perl5/HTTP/Message.pm line 299.
        ...caught at /home/dw/dw/cgi-bin/DW/Controller/Feeds.pm line 122.
```
I'm not inclined to investigate any further at this point, because if the problem is in our code, it's happening off in a CPAN module somewhere.

**Comment by rahaeli** [comment]
Sounds good to me! I'll let the user know that it seems to be a problem with the content of the feed and they should try again next week/month/etc when the feed's contents may have shifted, in case it's due to specific posts.

**Comment by rahaeli** [comment]
PS: thank you for investigating! you are a rockstar, except in the good way and not the douchey tech-industry asshole way

**Comment by kareila** [comment]
🎸 🌟 😁

**Comment by rahaeli** [comment]
and I have replied to the user letting them know that we can't keep debugging, suggesting that they contact the blogger and ask them to turn on Blogspot's native RSS/Atom feeds in addition to Feedburner, in case one of those work better.

**Comment by alierak** [comment]
The feed is 913k (406k gzipped) but the useragent used to check it is created with max_size = 300k. So it cuts off in the middle and can't un-gzip it.

**Comment by kareila** [comment]
Is that something we *want* to increase, or are we OK with not supporting obnoxiously large feed sources? If the former, that *is* something we can change, and if the latter, we should improve the error message.

**Comment by rahaeli** [comment]
Oho! Good find, Robby.

I'm okay with not supporting super large feed sources, so let's go with "improve the error message".

**Comment by alierak** [comment]
No, it's a hardcoded 300k, and I think we should increase it to match what's actually used by synsuck (which defaults to something larger and is configurable).

**Comment by rahaeli** [comment]
Oh, I thought you meant that the size limit was the one in synsuck! In that case, yes, whatever's setting that should use the same size limit as synsuck. (What *is* setting that, anyway?)

**Comment by alierak** [comment]
The bit in DW/Controller/Feeds.pm that @kareila pointed at earlier. It's just trying to validate the feed URL before letting the user create it.

**Comment by kareila** [comment]
https://github.com/dreamwidth/dw-free/blob/develop/cgi-bin/LJ/SynSuck.pm#L94
