### ISSUE TITLE
add Facebook and Instagram to external user tag formats

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2105]
http://www.dreamwidth.org/support/see_request?id=36301

We should consider adding these to "Other Sites" on the profile page as well.

### Instagram 
userhead icon: https://www.instagram.com/static/images/ico/favicon-192.png/b407fa101800.png 
(Note: this is 192x192, we will need to find a 16x16 version)
link: https://www.instagram.com/$USERNAME (for both username and userhead)
site attributes that would make sense: "instagram.com", "instagram" 

### Facebook
userhead icon: https://www.facebook.com/favicon.ico
link: https://www.facebook.com/$USERNAME (for both username and userhead)
site attributes that would make sense: "facebook.com", "facebook", "fb"

**Comment by azurelunatic** [comment]
![instagram](https://cloud.githubusercontent.com/assets/7589142/25369272/815ed150-2937-11e7-9f9d-71d5ca2330b3.png)

Happily, many .ico files include a layer with the required size image, which can then be extracted with an image manipulation program that knows about layers. 

Ogres have layers...
