### ISSUE TITLE
Some Support requests sometimes incorrectly marked as still needing help

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2119]
https://www.dreamwidth.org/support/see_request?id=36264

History also says it still needs help.

I was also the case for:
https://www.dreamwidth.org/support/see_request?id=36152
https://www.dreamwidth.org/support/see_request?id=36226

**Comment by kareila** [comment]
These have all been taken out of the queue.  Let us know if you find any others.

**Comment by kareila** [comment]
We think #2122 may have fixed this.  I've only seen two mysterious regreens since then, but both turned out to be initiated by the user who opened the request.

If another one turns up, leave a comment here with a link and I'll investigate.
