### ISSUE TITLE
BML::get_query_string not preserved when doing an SSL redirect?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2121]
This wins the longevity prize for surviving as a bug since the LJ fork:

LJ::make_auth_code returns a string of random letters and digits from a preselected list, but support/act.bml parses the query string with a regular expression that assumes the auth code doesn't contain any digits.

Changing `\w{15}` to `[\w\d]{15}` should fix the problem.

Reported in an antispam request: http://www.dreamwidth.org/support/see_request?id=36360

**Comment by rahaeli** [comment]
Whoa. That might actually win the prize for "oldest bug we've ever fixed", in fact: it was present in the original checkin from 16 years ago. (https://github.com/dreamwidth/livejournal/blame/master/htdocs/support/act.bml)

**Comment by kareila** [comment]
It's old enough that I wonder if the behavior of `\w` changed at some point - surely this worked at some point in the past?

**Comment by zorkian** [comment]
I'm pretty sure `\w` matches numbers?

```
    \w        [3]  Match a "word" character (alphanumeric plus "_", plus
                                      other connector punctuation chars plus Unicode
                                      marks)
```

And:

```
$ perl -e 'print 1 if "123" =~ /^\w+$/;'
1
```

**Comment by kareila** [comment]
Hmm, that wasn't my recollection, but if that's the case, can you figure out why the query string in the support request didn't match the regex?

**Comment by rahaeli** [comment]
Having looked more closely at the error the user was getting -- yeah, that code has worked for a while. Hrrrrmmmm.

**Comment by zorkian** [comment]
Issue is the SSL redirect. The original link in the support request is `http://` and when we do the redirect we're not preserving the GET arguments in this case somehow.

**Comment by kareila** [comment]
*spits curses at BML*

**Comment by rahaeli** [comment]
OHO. Good debugging work!

**Comment by kareila** [comment]
DW::Request->get->query_string is a drop-in replacement that doesn't rely on BML.  See if that has the same problem?

**Comment by kareila** [comment]
@zorkian says that the HTTPS Everywhere redirect is using code that only works for query strings that parse neatly into argument hashes.  Unorthodox query strings are getting dropped in the conversion process.  We'll need to update the LJ::create_url function to allow these to pass through.
