### ISSUE TITLE
fix typo in diversity statement

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2124]
I can't believe none of us have noticed this in eight years, lol.

Second-to-last graf: "undesireables" should be "undesirables".

**Comment by NightFlyer** [comment]
My first attempt at helping. I'm claiming this very easy one.

**Comment by rahaeli** [comment]
Hi NightFlyer! Welcome to Dreamwidth development -- we're thrilled to have you. :)

Have you submitted a contributor licensing agreement to me? If not, check http://wiki.dreamwidth.net/wiki/index.php/CLA for instructions on downloading and returning it. If you have, and I just missed adding you to the Github team, drop me an email (denise@dreamwidth.org) and let me know what name it was submitted under. 

Once I've got your signed CLA, I'll add you to the team and the bot will work to let you c-l-a-i-m stuff just by saying so, but it won't work until I add you to the team. :)

**Comment by NightFlyer** [comment]
I just sent in the CLA a moment ago.

**Comment by rahaeli** [comment]
Great! My email server is probably just greylisting it, then. As soon as it comes through, I'll send your team invites and merge the pull request. (As expected, there are no changes needed to your PR...)

So glad to have you on board. Holler if you hit anything that confuses you or if you have any questions that aren't covered in the wiki! The dw-dev and dw-dev-training comms are also full of useful information.

**Comment by NightFlyer** [comment]
I know all about greylists & email. If it would help, I can resend it 
through gmail, but I doubt there's a hurry on this one.

**Comment by rahaeli** [comment]
If you don't mind the wait, neither do I! (If you want to get it finished up now, though, feel free to resend. I AM FLEXIBLE)

**Comment by rahaeli** [comment]
And my inbox has coughed up the CLA, so I sent you the team invite!

**Comment by rahaeli** [comment]
Merged https://github.com/dreamwidth/dw-nonfree/pull/120 (which fixes this); holding off on closing the associated issue until I can properly assign it to NightFlyer.

WOOHOO FIRST PULL REQUEST, WOOHOO FIRST COMMIT 🍾 🍾 🍾

**Comment by zorkian** [comment]
CHAMPAGNE!!!!! Welcome! :)

**Comment by rahaeli** [comment]
ALSO I GOT TO MERGE IT, NEENER NEENER @zorkian YOU SNOOZE YOU LOSE <3

**Comment by zorkian** [comment]
I am definitely snoozing here. I can recommend Soylent 1.7 though! It's
pretty good!

**Comment by rahaeli** [comment]
I almost never get to do the welcome dance myself! Ha ha ha!

**Comment by NightFlyer** [comment]
Gosh, now I feel like I have to do something real.

**Comment by rahaeli** [comment]
You already have done something real! But if you feel like you need to do something *bigger*, I won't stop you. ;)

**Comment by rahaeli** [comment]
And now that NightFlyer and I have waited out the greylisting on both our mailservers, he has received the team invite and accepted it, I have officially (and belatedly) assigned this issue to him, and we can close it. \o/
