### ISSUE TITLE
Can't remove purged user who Subscribes to you" and/or "Grants you access"

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2128]
https://www.dreamwidth.org/support/see_request?id=36298

User isn't subscribed to or grants access to this user and has no way of removing them from their Circle. If this is intended behavior then see #2120 otherwise it's a bug.

**Comment by kareila** [comment]
See also:
- http://www.dreamwidth.org/support/see_request?id=10903
- http://www.dreamwidth.org/support/see_request?id=30516
- http://www.dreamwidth.org/support/see_request?id=35858

I believe this is intended behavior, not to allow a journal to remove itself from connections others have made to it, even if the user who made the connection is purged.  Previous advice has consistently been to uncheck the "Circled By" display option on Manage Profile, which hides all users who have the journal in their circle but have not been reciprocated.  We also added the functionality to hide banned users on the profile in #1403, although I'm not sure whether it's possible to ban a purged user.

**Comment by ninetyd** [comment]
> although I'm not sure whether it's possible to ban a purged user.

Nope, you can't.

**Comment by kareila** [comment]
Right, that just leaves the blanket solution of the profile setting, then.

**Comment by kareila** [comment]
Actually, 90d, I tried it just now using the ban_set console command and it seemed to work for me.

**Comment by ninetyd** [comment]
> Actually, 90d, I tried it just now using the ban_set console command and it seemed to work for me.

RequestUser said you couldn't but maybe that's just using the settings interface.

**Comment by rahaeli** [comment]
Yep, it works with the console; I'm ok with that.
