### ISSUE TITLE
add imzy to the user tag

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2136]
&lt;user name=username site=imzy.com>/&lt;user name=username site=imzy> (hard to abbreviate a four-letter site name!)

Journal and profile should both link to https://www.imzy.com/@username
For the userhead, see if we can scale https://d13yacurqjgara.cloudfront.net/users/209119/screenshots/2669593/imzy_dino.jpg down to 16x16, or convert https://www.imzy.com/favicon.ico to png and scale it down to 16x16

**Comment by azurelunatic** [comment]
![imzy-16](https://cloud.githubusercontent.com/assets/7589142/25293253/d56c1ad8-268e-11e7-8895-2ed5e1265336.png)

By the power of GNU, I command it!
