### ISSUE TITLE
DW::User::trustmask prints useless stack trace in server logs

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2160]
I've greatly reduced the number of regular warnings in the server logs as of yesterday's code push, but I'm still seeing frequent occurrences like the following:
```
va-web06: attempted to set trustmask on non-trusted edge at /home/dw/production/cgi-bin/DW/User/Edges/WatchTrust.pm line 323.
va-web06: 	DW::User::trustmask('LJ::User=HASH(0x7f957b551358)', 'LJ::User=HASH(0x7f957ba7fce0)', 1) called at /home/dw/production/cgi-bin/DW/Controller/Circle.pm line 272
va-web06: 	DW::Controller::Circle::individual_edit_handler('DW::Routing::CallInfo=HASH(0x7f957b421920)', 'armandathos') called at /home/dw/production/cgi-bin/DW/Routing/CallInfo.pm line 82
va-web06: 	DW::Routing::CallInfo::call('DW::Routing::CallInfo=HASH(0x7f957b421920)') called at /home/dw/production/cgi-bin/DW/Routing.pm line 233
va-web06: 	eval {...} called at /home/dw/production/cgi-bin/DW/Routing.pm line 233
va-web06: 	DW::Routing::_call_hash('Apache2::RequestRec=SCALAR(0x7f957ba0ca98)') called at -e line 0
va-web06: 	eval {...} called at -e line 0
```
Most of the arguments are references which print as memory addresses in the log, making them useless for debugging.  Instead of just dumping a stack trace here, we should figure out the necessary information to diagnose the problem, and print that instead.

**Comment by pauamma** [comment]
So what *is* the needed info? Userids of from_u and to_u so someone with appropriate access can go database-spelunking?

**Comment by zorkian** [comment]
Yeah can we just make the stringification of the `LJ::User` object be something like `LJ::User=username(#id)`? Would that be respected by Carp here?

**Comment by kareila** [comment]
I never figured out what the desired solution would be here, but now we know thanks to #2568 why this specific error is happening, so let's just fix that and move on.
