### ISSUE TITLE
Reverbnation for embed source

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#2162]
Requested in dw_news: http://dw-news.dreamwidth.org/38065.html?thread=5606065#cmt5606065 

Examples: 

<iframe width="100%" height="520" scrolling="no" frameborder="no" src="https://www.reverbnation.com/widget_code/html_widget/artist_5538308?widget_id=55&pwc[included_songs]=1&context_type=page_object&pwc[branded]=1" style="width:0px;min-width:100%;max-width:100%;"></iframe>

<iframe width="100%" height="265" scrolling="no" frameborder="no" src="https://www.reverbnation.com/widget_code/html_widget/artist_5538308?widget_id=55&pwc[included_songs]=1&context_type=page_object&pwc[size]=small&pwc[branded]=1" style="width:0px;min-width:100%;max-width:100%;"></iframe>

**Comment by pauamma** [comment]
This and bug #2199 give different sample codes for ReverbNation. Which one should be kept?

**Comment by kareila** [comment]
This is a duplicate of #2199.
