### ISSUE TITLE
Whitelist embeds from Wistia

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2164]
http://www.dreamwidth.org/support/see_request?id=36631

Example code: `<iframe allowtransparency="true" frameborder="0" scrolling="no" class="wistia_embed" name="wistia_embed" src="https://fast.wistia.com/embed/iframe/k1akcpc0ik" width="480" height="295"></iframe> `

**Comment by SporkyRat** [comment]
YAY.

**Comment by rshatch** [comment]
claiming
