### ISSUE TITLE
Allow escaping of @ in DW-flavoured Markdown

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2166]
https://www.dreamwidth.org/support/see_request?id=36660

A user was composing a post in Markdown that included `@-reply`; it was rendered `<user name="_reply">`. \-escaping of @ should be supported.

**Comment by kareila** [comment]
To be clear, the proposed change is to allow user input of `\@user` to be rendered as `@user` when using Markdown. Usernames that begin with underscores, or hyphens translated to underscores, are acceptable usernames.

**Comment by pauamma** [comment]
Since the patch for this was merged, I think it can be closed.
