### ISSUE TITLE
Can image proxy support svg?

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2168]
https://www.dreamwidth.org/support/see_request?id=36683

User trying to use svg images in an img tag, proxy doesn't like it. Can the proxy support svg or is user sol?

**Comment by alierak** [comment]
SOL, I think. The svg format supports URL references and links, which we can't guarantee will be secure (or work at all) through the proxy without investing a great deal of time and effort in a specialized svg cleaner.

**Comment by kareila** [comment]
My reading of the proxy code is that it depends on how the remote server is configured. If the file is served with a MIME type of `image/svg+xml`, the proxy should be fine. If instead it is served as `application/svg+xml` the proxy will reject it.

**Comment by alierak** [comment]
Oh, sounds like a potential security bug then.
