### ISSUE TITLE
newly uploaded images on /file/new should reflect correct security settings when user has a more restrictive minimum security setting

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2169]
http://www.dreamwidth.org/support/see_request?id=36685

Report from a user who was confused that images uploaded on /file/new came up with a menu that had "public" security selected, when the actual security in effect was the user's default minimum security, access-only.

**Comment by pauamma** [comment]
So all the heavy lifting is in JS and all we have is an unparsed-text HTML fragment for the image-to-be's metadata, which is stowed in a <script> tag and probably handled using innerHTML somewhere down the line. This means conventional methods won't work, and all we can do is make the selected option in the HTML text fragment reflect newpost_minsecurity. This should achieve the desired result unless the user plays tricks with newpost_minsecurity in another tab or window while uploading files.
