### ISSUE TITLE
improve no-such-user 404

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2177]
Line 1372 of cgi-bin/Apache/LiveJournal.pm needs a more explanatory error message ala #2061/#2063, bug me to come back to this if I haven't come up with something better in a day or two

**Comment by azurelunatic** [comment]
:beetle:

**Comment by pauamma** [comment]
*buggity bug bug bug*

**Comment by kaberett** [comment]
yo @rahaeli if you don't want me to make something up and have you sign off on it after lmk!
