### ISSUE TITLE
Check whether IP::Country::Fast is still needed

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2179]
The only grep hit I see is in bin/checkconfig.pl, and there's also a reference in http://wiki.dreamwidth.net/wiki/index.php/Dreamwidth_Scratch_Installation#Install_Perl_modules_with_CPAN .

**Comment by Sophira** [comment]
I was the one who added IP::Country::Fast to that wiki page just over a month ago, and I did so based on the output of `bin/checkconfig.pl`. So it's possible that that reference only exists there because it was in the config checker. I'll take a look around and see where it comes from.

**Comment by Sophira** [comment]
So it seems IP::Country::Fast was used by the LJ code when we forked, but along the way (in commit 2486cf79b5072b8839bbabe769283e74e7a9ef14) the only function that used it disappeared.

We should be able to remove the check from checkconfig.pl without issue, so far as I can see!
