### ISSUE TITLE
Incorrect number of links in Links List for premium/seed accounts

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2181]
https://www.dreamwidth.org/support/see_request?id=36733

FAQ says 100 but current limit is 50.

**Comment by kareila** [comment]
Do we want to correct the FAQ or give premium/seed accounts more links?

If the latter, we need to add `userlinks => 100` to `%CAP_PREMIUM` in etc/config.pl.

**Comment by rahaeli** [comment]
Let's make reality match the docs and up the limit to 100 in prod rather than making the docs match reality. ;)
