### ISSUE TITLE
Update user profile Delicious link

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2184]
https://www.dreamwidth.org/support/see_request?id=36745:
> The links on a user's profile will go to www.delicious.com/username which worked in the past I think but doesn't now. The new link needs to be del.icio.us/username to work. 

... and in fact integration with Delicious is in general broken by the move to del.icio.us.

**Comment by kareila** [comment]
The site map in cgi-bin/DW/External/Site.pm will need to be updated as well.

**Comment by kaberett** [comment]
Yep, had found that :-) Claim!
