### ISSUE TITLE
imzy shutting down at end of june

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2189]
https://www.imzy.com/imzy/post/imzy_is_shutting_down

And we just added it, too. :(

**Comment by kareila** [comment]
What's the best way to handle this? It seems to me that people would find value in continuing to refer to Imzy usernames after the site shuts down, even though the associated links will stop working.

**Comment by rahaeli** [comment]
With past shutdowns I believe we removed everything. Inksome is an example, maybe we kept the username tag?

**Comment by kareila** [comment]
Yes, we kept the user tag, so just remove the profile field and related userprop.

The badge_icon links to https://www.imzy.com/favicon.ico so we'll have to cache that before it goes away.

**Comment by pauamma** [comment]
Snarfed https://www.imzy.com/favicon.ico locally, in case no one did before.

**Comment by kareila** [comment]
Pau, can you upload your copy of the image as an attachment on this issue?  Thanks.

**Comment by pauamma** [comment]
[imzy_favicon.zip](https://github.com/dreamwidth/dw-free/files/1110328/imzy_favicon.zip)

There. (Had to ZIP it, because GHI wouldn't let me upload a .ico file.) Will keep it around until you tell me it's OK to delete.

**Comment by kaberett** [comment]
Claim!

@pauamma, thank you -- I've grabbed a copy and am intending to deal with this tomorrow.
