### ISSUE TITLE
add screening level option to post-by-email options

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2190]
http://www.dreamwidth.org/support/see_request?id=36803

Allow users who post by email to change the screening level on the emailed entry to something different than their journal default.

My suggestions for syntax:

post-screenlevel: disabled/none | anonymous/anon | untrusted | all

**Comment by pauamma** [comment]
What should happen if the option is present, but with an incorrect keyword? Possibilities are:

1. reject the attempt to post
2. post with maximum screening (All comments) for safety.
3. post with user default screening.

1 seems perhaps too drastic, but I'm undecided between 2 and 3. Opinions welcome.

**Comment by pauamma** [comment]
Another option is either 2 or 3 with a status report, similar to what's done when the trust group name is unrecognized. With that in mind, I'm leaning toward 2 with a status report.

**Comment by zorkian** [comment]
I agree with 2, basically "fail safe." Worst case someone has to open it up a bit and they'll notice once they get a comment or two (probably).
