### ISSUE TITLE
beta update page broken in portrait mode in Chrome on Android

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2195]
https://dw-beta.dreamwidth.org/12259.html?thread=462819#cmt462819

Just to let you know, I've had a consistent problem for the last few months while trying to use the mobile version of the beta update page, and I can't find any mention of it on the Current Issues page. The dropdown to change the post security doesn't work at all (cannot select it; is not displayed in the site's style at all) unless I load the page in landscape mode. If I forget and load it while my phone is portrait, turning the phone sideways doesn't fix the problem, I specifically have to reload the page.

This happens every time, and it's fine, I can work around it, it's just an "ugh, forgot AGAIN!" problem, so I thought I'd check to see if anyone else was having this problem. My phone is a Samsung S4, running Chrome version 57.0.2987.132.

**Comment by kaberett** [comment]
Seeing similar broken behaviour in both portrait and landscape mode in
Firefox under Android (LineageOS); can check Chrome later.

**Comment by kaberett** [comment]
I've seen a couple of recent aggravated reports about this -- any thoughts, or shall I just Offer A Bounty?

**Comment by kaberett** [comment]
I believe this is indeed now fixed and can be closed!
