### ISSUE TITLE
Add ReverbNation to embeds whitelist

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2199]
https://www.dreamwidth.org/support/see_request?id=36965

Sample code:
`<iframe width="640" height="150" scrolling="no" frameborder="no" src="https://www.reverbnation.com/widget_code/html_widget/artist_299962?widget_id=55&pwc[song_ids]=4189683&context_type=song&pwc[size]=small&pwc[color]=dark" style="width:0px;min-width:100%;max-width:100%;"></iframe>`

**Comment by pauamma** [comment]
This and bug #2162 give different sample codes for ReverbNation. Which one should be kept?

**Comment by kareila** [comment]
Keeping this one; although there don't appear to be any significant differences between the two, this report has the advantage of being more recent and in a more easily readable format.

**Comment by rshatch** [comment]
claiming
