### ISSUE TITLE
allow specifying multiple access groups in post-security email header

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2201]
http://www.dreamwidth.org/support/see_request?id=36907

Assuming we don't allow access group names to contain commas, this should be a relatively straightforward adjustment.  The relevant parsing logic starts at line 218 of DW/EmailPost/Entry.pm.

**Comment by pauamma** [comment]
> Assuming we don't allow access group names to contain commas

Unfortunately, we do. (I just checked.) What other separator can we use? (I also checked ; and it's  also accepted as well.)

**Comment by zorkian** [comment]
I think group names can be... nearly anything.

How would everybody feel about still using commas, but if someone writes
in about "can't use it" we suggest they don't put commas in their group
names? I don't believe commas are in widespread use in group names.

**Comment by rahaeli** [comment]
,100% for it + start enforcing no punctuation in group names

**Comment by pauamma** [comment]
Suggested further behavior specification: if some of the groups don't exist, they're ignored and the entry is posted to the remaining groups, if any. (If none of the groups exist, it ends up posted as "usemask"/allowmask=0, which is the same in effect as private.) All unrecognized group names are listed in the error message the user gets.

**Comment by zorkian** [comment]
That behavior makes sense to me, and approved & merged the PR. Much
appreciated!
