### ISSUE TITLE
Don't allow rename tokens to be bought for d&p accounts 

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2204]
If someone wants a deleted and purged username and accidentally puts in that username for getting the token sent to it, the token goes off into the ether and we have to make them a new one. Instead, let's error with a "send the token to the account you want to rename" error.

**Comment by pauamma** [comment]
The code to validate given-to usernames (which currently only checks the username exists) appears to be common to all types of shop items. On the grounds that it doesn't make sense to buy the other shop items for expunged accounts either, I'm tempted to go the easy way and check for those in the common code path. Objections?

**Comment by zorkian** [comment]
That sounds like the right approach to me!
