### ISSUE TITLE
hook admin/renames on  payments priv

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2205]
Right now admin/rename uses siteadmin:rename which we did so other sites could give people rename admin access without having to give access to payment info. In practice this has turned out to be a pain where poor Jen keeps finding shit she can't access when I'm sulking in bed because my hand hurts from being irradiated.

Let's go ahead and switch it to payments:* and not siteadminrenames.

**Comment by kareila** [comment]
We don't need to choose one or the other - we can allow both, and that's more in keeping with existing practice.

**Comment by Sophira** [comment]
I notice that the merged PR is granting access to just "payments" and not ''payments:*" as requested here.  I believe the two are subtly different - is this what was wanted?

**Comment by zorkian** [comment]
I didn't remember if payments used subargs or not, so I merged as-is. If
we never grant un-argumented payments then yes, we would need to use
payments:*.

**Comment by pauamma** [comment]
Based on a quick grep, most of the code, eg cgi-bin/DW/Controller/Admin/CapEdit.pm, uses unarged "payments". There's one instance, cgi-bin/DW/Console/Command/BonusIcons.pm, which uses payments:bonus_icons. So now I don't know what to do. Should it be "payments", "payments:*", or both? (I can't look at the payments privlist to tell what was done on Dreamwidth.)

**Comment by zorkian** [comment]
Unarged sounds right then, since that's already used elsewhere in
admin pages.
