### ISSUE TITLE
Whitelist embeds from giphy.com

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2207]
https://www.dreamwidth.org/support/see_request?id=37158

Sample code: `<iframe src="https://giphy.com/embed/Om0tF9bYdLCKI" width="480" height="366" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="https://giphy.com/gifs/rue-mcclanahan-Om0tF9bYdLCKI">via GIPHY</a></p>`

**Comment by rshatch** [comment]
claiming
