### ISSUE TITLE
Better wording for 'no html allowed' on support request page

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2209]
https://www.dreamwidth.org/support/see_request?id=37019

/support/submit says not to use HTML in your submission, making it confusing for users who need to paste some code to explain to us what their pb is or to provide embed codes. As ysobel suggested we could say that HTML will show up as bare code or something simple like that.

**Comment by kareila** [comment]
Can/should this be done via the translation system?

**Comment by pauamma** [comment]
My understanding is that if you do it via the translation system, it doesn't become available to others using the dw-free code.

**Comment by azurelunatic** [comment]
I believe the time-honored solution is: do it via translation system for the immediate improvement on the site, and then change it in the code for everybody else.

**Comment by pauamma** [comment]
How does
> Don't include confidential information like your password or phone number. Any HTML in your submission will be escaped, not rendered.

sound?
