### ISSUE TITLE
Allow embeds from Funny or Die

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2210]
https://www.dreamwidth.org/support/see_request?id=37079

```<iframe src="//www.funnyordie.com/embed/7156588dc7" width="640" height="400" frameborder="0" allowfullscreen webkitallowfullscreen mozallowfullscreen></iframe><div style="text-align:left;font-size:x-small;margin-top:0;width:640px;"><a href="http://www.funnyordie.com/videos/7156588dc7/gay-of-thrones-s7-e3-recap-the-kweens-juicefast-with-carla-jimenez" title="from Carla Jimenez, Jonathan Van Ness">Gay Of Thrones S7 E3 Recap: The Kween’s Juicefast (with Carla Jimenez)</a> from <a href="http://www.funnyordie.com/gayofthrones">Gay of Thrones</a></div>```

**Comment by kaberett** [comment]
claim
