### ISSUE TITLE
Increase font size in Tropospherical to 100%/1em

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2211]
https://dw-suggestions.dreamwidth.org/318393.html

https://www.dreamwidth.org/support/see_request?id=37035

This is an old issue, and an old suggestion. I know this would mean some redesign so everything could fit and be responsive but DW does state that accessibility is not an afterthought and having the default skin not to follow these guidelines is just... sad.

**Comment by kareila** [comment]
I believe the font size is 100% in the SCSS version of Tropo, and the "fix" is to convert all site pages to Foundation.  We already have a "Foundation Conversion" milestone for this, so I'm closing this issue.

If you have any specific pages to recommend for conversion, you can open separate issues for those and add them to the milestone.
