### ISSUE TITLE
FAQ: how to report private messages as spam 🐖🍣🔨

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#2212]
We got a request mentioning that the FAQ doesn't cover how to report a private message as spam:
 http://www.dreamwidth.org/support/see_request?id=37253 (🔒 🐖🍣🔨)

Changing http://www.dreamwidth.org/support/faqbrowse?faqid=92 might be the best place? 

Title change: What are spam comments (etc) to What are spam comments and messages? What can I do about them? 

Insert paragraph after "This will send a report to the people who deal with spam, who will review it and then take action to block the spammer if appropriate.": 
When reading private messages in the Inbox (link to http://www.dreamwidth.org/support/faqbrowse?faqid=72) you can mark it as spam. Use the "Mark as Spam" link near the "Reply" link {instead of/before, whichever is appropriate} deleting it. 

Insert paragraph at the end: 
You can also change who is allowed to send you a private message. (link to http://www.dreamwidth.org/support/faqbrowse?faqid=224)

**Comment by kaberett** [comment]
claim

completed
