### ISSUE TITLE
US states drop down not in alphabetical order in /manage/profile/

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2215]
https://www.dreamwidth.org/support/see_request?id=37165

First letter is fine, second or third letter is where it gets weird sometimes. Like Maine is after Maryland or Vermont is after Virginia.

**Comment by kaberett** [comment]
... it's gonna be alphabetical based on two-letter state code

**Comment by ninetyd** [comment]
Oh so it's a backend vs UI kind of thing?

**Comment by rshatch** [comment]
It does look like the sort is based on the two-letter code, with the bonus that the first time it's loaded (which I think is via JS), the order is correct.

Double-bonus, we have codes in the db for Canadian provinces and territories, Australian states and territories, and German states, but the code to load them as dropdown lists are disabled.

**Comment by rshatch** [comment]
Also, claiming!
