### ISSUE TITLE
whitelist embeds from open.spotify.com

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2216]
https://www.dreamwidth.org/support/see_request?id=37140

Sample code: `<iframe src="https://open.spotify.com/embed/track/5IsdA6g8IFKGmC1xl37OG1" width="300" height="380" frameborder="0" allowtransparency="true"></iframe>`

@ninetyd notes that embed.spotify.com is already on the list, but not open.spotify.com. It looks like Spotify might have retired the embed.spotify.com scheme?

**Comment by rshatch** [comment]
claiming

**Comment by rshatch** [comment]
fwiw it looks like the old paths redirect on to the new subdomain, so I've left in the old subdomain and explicitly whitelisted both path styles on it.
