### ISSUE TITLE
add console command that gives information on which beta features a user is opted in to testing

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2217]
#1835 is great! However, it would also be great if Support volunteers with appropriate privs had the ability to ask the adminstration console what beta features an arbitrary Dreamwidth account was opted into. In particular, this would be helpful for (a) support requests filed via e-mail, where the associated account is identificable, and (b) support requests filed on behalf of a third party who's having difficulty accessing Dreamwidth.

I am currently fighting the Great Support Board Misery of the 2k17 HTTPS Everywhere update. This would really help me work out which template paragraph to paste into my response.

**Comment by kaberett** [comment]
@rahaeli tells me that it is currently possible to view this information but *only* in a way that reveals a lot of other employee-only info. Is there scope for creating a console command that determines whether you can ask for this information based on whether you can see it on the Support Board? (Is it publically-visible on the Support Board? Try logging out and testing, Alex.)

**Comment by pauamma** [comment]
It's not publicly visible, it requires the user to have some support priv (currently defined as any of supportclose, supporthelp, supportdelete, supportread, supportviewinternal, supportmakeinternal, supportmovetouch, supportviewscreened, supportviewstocks, supportchangesummary).
