### ISSUE TITLE
[needs investigation] Icons mysteriously becoming distorted with no user action?

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2221]
There have now been two Support requests about this: https://www.dreamwidth.org/support/see_request?id=37448 and https://www.dreamwidth.org/support/see_request?id=37298. I have absolutely no idea what's going on, I've asked for some more information, and I'm sincerely hoping it will help narrow down what on earth's happening.

**Comment by zorkian** [comment]
This probably happened during the migration from MogileFS to S3. Have there been any other reports of this?

**Comment by kaberett** [comment]
NAFAIK

**Comment by zorkian** [comment]
Okay! Going to close this for now then, but if it does crop up again please let me know so I can investigate.
