### ISSUE TITLE
Advertise http://openid.net/signon/1.1 via Yadis

### ISSUE THREAD

**Issue by owtaylor** [dreamwidth/dw-free#2225]
When acting as a OpenID provider, discovery via the Yadis protocol advertises OpenID 1.1:

https://github.com/dreamwidth/dw-free/blob/f54a0ad3e0ae7cc03219d73c03ffff47c1f61fbc/cgi-bin/LJ/Feed.pm#L798

However, the implementation seems to be something more like OpenID 1.1. There are very few differences between the two protocols, but one difference is that with OpenID 1.1 there is an
is_valid element in the mode.check_authentication response, something that the dreamwidth.org response seems to have.

I just worked around this in the outreachy.org application system:
https://git.gnome.org/browse/opw-web/commit/, which has a fork of code from LightOpenID - see:
https://github.com/iignatov/LightOpenID/blob/master/openid.php

**Comment by alierak** [comment]
Thanks. I assume you mean we're currently advertising 1.0 and implementing 1.1. The implementation is Net::OpenID::Server, which may have implemented 1.0 at the time it was introduced but has been upgraded over the years. I agree we should bump this to 1.1 (but also remove the $LJ::OPENID_COMPAT option to avoid any possibility of a site implementing 1.0).
