### ISSUE TITLE
Handle image proxy links with URL parameters

### ISSUE THREAD

**Issue by alierak** [dreamwidth/dw-free#2229]
When the HTML cleaner converts an HTTP image link to an image proxy link, any URL parameters in the original link seem to be causing an "invalid signature" error in the proxy. For example,

http://www.cakewrecks.com/storage/thumbnails/10710906-14590968-thumbnail.jpg?__SQUARESPACE_CACHEVERSION=1318394646445

will be converted to

https://p.dreamwidth.org/b7bc69cde021/54690-735769/www.cakewrecks.com/storage/thumbnails/10710906-14590968-thumbnail.jpg?__SQUARESPACE_CACHEVERSION=1318394646445

But the proxy reports:

Invalid signature in request: /b7bc69cde021/54690-735769/www.cakewrecks.com/storage/thumbnails/10710906-14590968-thumbnail.jpg

It appears to disregard anything after the question mark when calculating the signature, always comes up with a signature mismatch, and refuses to proxy the image. I can't tell if this would best be handled by having the proxy reassemble the URL to include any query string parameters it has received, or by having the HTML cleaner url-encode any question marks...

**Comment by alierak** [comment]
Somehow this used to work but stopped on 9/17/2017. Proxy logs show the proxy doing signature calculations with the question mark and query string parameters included, up to that date but not after. If I try manually URL-encoding the question mark, then the proxy includes it but doesn't decode it, and calculates an incorrect signature based on the percent sign, 3, F, and query parameters.

We probably have some hosting layer in front of p.dreamwidth.org that changed and is no longer passing query string parameters.

**Comment by zorkian** [comment]
Oh yes this is totally a setting in CloudFront, let me fix

**Comment by zorkian** [comment]
It works now. Had to enable passing query string parameters in the CDN.
