### ISSUE TITLE
Trying to access a private entry sends the user into a 302 Redirect loop

### ISSUE THREAD

**Issue by alexwlchan** [dreamwidth/dw-free#2233]
Steps to reproduce:

1. Create a private entry in a journal. I created a test post with “This is a test post” as a title and “Show this entry to: Private (Just You)”.
2. Send that link to somebody who doesn’t have journal access. e.g. https://alexwlchan.dreamwidth.org/2896.html
3. Attempt to access the entry.

In this case, I’d expect the returned HTTP status to be one of:

* 404 Not Found – deny any knowledge of the post’s existence. If a user isn’t authorised to see a post, they can’t know anything about it, even whether it exists.
* 401 Unauthorized or 403 Forbidden – with an appropriate error message.

In general I favour the 404 approach, but either one is probably fine. I’m not sure what information is encoded in the post IDs, which look entirely numeric, so admitting the existence of a post I can’t see may not be hugely problematic.

I *don’t* expect the server to return a 302 Redirect to *the same page*, which is the current behaviour. This sends a browser into an infinite redirect loop, and the user doesn’t get a helpful error messages.

Example responses, from a private post, and from a non-existent post (edited for brevity):

```console
$ curl --head "https://alexwlchan.dreamwidth.org/2896.html"
HTTP/1.1 302 Moved Temporarily
Content-Type: text/html; charset=iso-8859-1
Connection: keep-alive
Date: Sun, 05 Nov 2017 23:43:29 GMT
Server: Apache/2.4.7 (Ubuntu) mod_apreq2-20090110/2.8.0 mod_perl/2.0.8 Perl/v5.18.2
Location: https://alexwlchan.dreamwidth.org/2896.html

$ curl --head "https://alexwlchan.dreamwidth.org/404.html"
HTTP/1.1 404 Not Found
Content-Type: text/html; charset=utf-8
Connection: keep-alive
Date: Sun, 05 Nov 2017 23:49:17 GMT
Server: Apache/2.4.7 (Ubuntu) mod_apreq2-20090110/2.8.0 mod_perl/2.0.8 Perl/v5.18.2
```

**Comment by pauamma** [comment]
Duplicating with Chrome Version 62.0.3202.75 (Official Build) Built on Ubuntu , running on Ubuntu 14.04 (64-bit).

This page isn’t working

alexwlchan.dreamwidth.org redirected you too many times.
Try clearing your cookies.
ERR_TOO_MANY_REDIRECTS

**Comment by srukle** [comment]
I too am receiving a redirect error. If I recall correctly, Dreamwidth did not always do this in the past. I'll do some tests in Dreamhack tomorrow morning.

**Comment by kareila** [comment]
Reproducing with a locked community entry, both not logged in at all, and logged in with an account that can't see the entry.  Definitely a Cloudfront-related issue. @zorkian @alierak

**Comment by alierak** [comment]
No, this does not appear to be a Cloudfront-related issue. I observe the same behavior if I make the request directly to ELB instead of Cloudfront.

**Comment by alierak** [comment]
Ok, I think I've got it. A locked entry you can't see generates an internal_redir to /protected. In cgi-bin/Apache/LiveJournal.pm, the internal_redir is handled with DW::Routing->call( uri => foo ). DW::Routing->call will generate a redirect to https if the prefer_ssl option is true (which it is, because $LJ::USE_HTTPS_EVERYWHERE causes it to be defaulted to 1) and the ssl option isn't. It looks to me like that routing call for internal_redir needs to have ssl => 1 in the parameters if $LJ::USE_HTTPS_EVERYWHERE is true (or possibly just if the original request was using https).

**Comment by alierak** [comment]
Or we could explicitly set prefer_ssl => 0 for internal redir routing, but I'm not sure if that would have undesired effects. The only use case for internal_redir appears to be /protected.

**Comment by zorkian** [comment]
Sounds like the same situation as the adult content interstitial the
other day. I believe I just passed down the $is_ssl variable in that
codepath...?
