### ISSUE TITLE
Changing account status gives error message

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#2236]
When going to https://www.dreamwidth.org/accountstatus and setting an account either to Active or Deleted you get an error message. The generic "Sorry, there was a problem" or something like this one:

[Error: The event (uid=2551672, extra='old=D&new=V', 'new=V&old=D', logtime=1511115639) was found in log, but with wrong ip address (2a01:e35:2eff:5, but not 2a01:e35:2eff:5200:b8df:4c0d:93f3:617) at /home/dw/production/cgi-bin/LJ/Event/SecurityAttributeChanged.pm line 56. @ va-web05]

The change goes through, though.

Firefox Quantum for me (v57) or Chrome for Android for @momijizukamori.

**Comment by kareila** [comment]
Duplicate of #1818.
