### ISSUE TITLE
whitelist embeds from vk.com

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2238]
https://www.dreamwidth.org/support/see_request?id=37841
embeds for vk.com need to be whitelisted, sample included below

<iframe src="https://vk.com/video_ext.php?oid=-49280571&id=165718332&hash=5eb26e7a4cd9982d" width="640" height="360" frameborder="0" allowfullscreen></iframe>

**Comment by rshatch** [comment]
claiming
