### ISSUE TITLE
whitelist embeds from livejournal

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2239]
https://www.dreamwidth.org/support/see_request?id=37841

embeds from livejournal.com (is that even a thing?! wow.)
<iframe style="max-width: 100%" src="https://shad-tkhom.livejournal.com/1244088.html?embed" width="502" height="324" frameborder="0"></iframe>

**Comment by SporkyRat** [comment]
Second request for it from support here:
https://www.dreamwidth.org/support/see_request?id=38021

**Comment by rshatch** [comment]
claiming
