### ISSUE TITLE
whitelist embeds from music.yandex.ru

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2240]
https://www.dreamwidth.org/support/see_request?id=37747
whitelisting music from music.yandex.ru, code sample provided by requester

<iframe frameborder="0" style="border:none;width:600px;height:100px;" width="600" height="100" src="https://music.yandex.ru/iframe/#track/31910432/247808/">Слушайте <a href='https://music.yandex.ru/track/31910432'>But the wind was stronger</a> — <a href='https://music.yandex.ru/artist/469932'>Diary of Dreams</a> на Яндекс.Музыке</iframe>

**Comment by rshatch** [comment]
claiming
