### ISSUE TITLE
FAQ 103 and FAQ 155 differ on whether h4..h6 tags are allowed

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2244]
https://www.dreamwidth.org/support/faqbrowse?faqid=155 says they are, https://www.dreamwidth.org/support/faqbrowse?faqid=103 implies they aren't (by not including them in its list). Judging by https://pauamma-testcomm000000000.dreamwidth.org/2794.html?style=mine, FAQ 155 is correct. (Brought to you by poking at https://www.dreamwidth.org/support/see_request?id=37939.)

**Comment by kaberett** [comment]
Claim; done.
