### ISSUE TITLE
Consider removing LJ::User functions and methods unused since at least August 2009

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2254]
The following LJ::User functions and methods, which were marked as unused in August 2009 (see https://github.com/dreamwidth/dw-free/commit/a397a0cc33c090c4531b8bb85f1045aa3697158c) are still unused after 8 years and change and should perhaps be removed:

- note_transition (now in cgi-bin/LJ/User/Data.pm)
- last_transition (now in cgi-bin/LJ/User/Data.pm) only used in note_transition which also goes away
- transition_list (now in cgi-bin/LJ/User/Data.pm) only used in last_transition which also goes away
- format_time (now in cgi-bin/LJ/User/Display.pm)

**Comment by zorkian** [comment]
Yeah anything that isn't referenced anywhere should be wiped for sure.
We don't need to leave it in for deprecation purposes, since we can
always undelete the code later if we need to.

**Comment by alexwlchan** [comment]
I’ll have a go at this for kab’s volunteer weekend, sounds easy enough.
