### ISSUE TITLE
Enforce new "no commas in trust group names" rule

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2262]
Per discussion in #2201, commas (and other punctuation?) should no longer be permitted in trust group names. What should happen to existing groups?

**Comment by zorkian** [comment]
Do we have to do anything with them? I think we can continue to accept
them wherever we already do, modulo the case where we're going to be
splitting on comma for posting?
We can note it in the next news post + also make the UI reject creating
new ones, but we don't need to proactively delete them/rename them.

**Comment by chrisboyle** [comment]
claim
