### ISSUE TITLE
Incorrect CSS on Latest Things page?

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2263]
For me, https://www.dreamwidth.org/latest displays with the menus (and my icon, etc) hidden behind the white bar the full DW logo sits on. Stacking order gone wrong, perhaps? (Firefox ESR, Debian.)

**Comment by kareila** [comment]
Which site scheme are you using? Tropo or something else?

**Comment by rahaeli** [comment]
This can happen if one of the entries appearing on the page has invalid html (too many close tags) and can't really be fixed without serious overengineering. It always goes away when the entry in question drops off the page!
