### ISSUE TITLE
Error messages in cgi-bin/DW/Setting/ShortcutsKeypress.pm lines 73, 83, 93

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2264]
Useless use of concatenation (.) or string in void context at /dreamhack/home/8091-pauamma/dw/cgi-bin/DW/Setting/ShortcutsKeypress.pm line 73.
Useless use of concatenation (.) or string in void context at /dreamhack/home/8091-pauamma/dw/cgi-bin/DW/Setting/ShortcutsKeypress.pm line 83.
Useless use of concatenation (.) or string in void context at /dreamhack/home/8091-pauamma/dw/cgi-bin/DW/Setting/ShortcutsKeypress.pm line 93.

Those lines read "$ret .+ ..." instead of (presumably) "$ret .= ...".

**Comment by akpdw** [comment]
claim

my typo, my bug.
