### ISSUE TITLE
Do not include deleted & purged accounts in the Support High Scores Board

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2281]
... because it's confusing, a D&P user presumably wants their account to have actually mostly vanished, and there's also a confusing little grey clock symbol with no alt text or anything adjacent it.

As discussed with @zorkian.

**Comment by kareila** [comment]
I think in the case you noticed, the clock emoji was the former account's journal name.  A different D&P account on the list had different text there.
