### ISSUE TITLE
document new config parameter ALL_TRAFFIC_IS_SSL

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2293]
In #2231 @zorkian added a new config parameter, `$LJ::ALL_TRAFFIC_IS_SSL` that can be set to `1` as a shortcut to bypass some types of routing code.  We should make sure this gets documented in the stock config files.

**Comment by zorkian** [comment]
Actually I think we should just remove it and not have those checks
anymore. In 2018, no web site should be insecure, and we should drop
support for insecure Dreamwidth. We can write up directions for
people to get self-signed certs, and you can also get absolutely free
valid certs from https://letsencrypt.org/ ... no reason to support
HTTP anymore.

**Comment by Sophira** [comment]
Time for me to finally do something about the Dreamhacks box and SSL then, I guess...

**Comment by kareila** [comment]
Let's document it for now and let the development community know that we are moving away from non-SSL support, with a deadline for implementing SSL in order to continue to keep up with current Dreamwidth code.

**Comment by zorkian** [comment]
Sounds good!

**Comment by kareila** [comment]
Looks like this has vanished!
