### ISSUE TITLE
remove code referencing ADV_PER_PAGE

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2294]
This is a line in LJ::start_request:
```
    $LJ::ADV_PER_PAGE = 0;            # Counts ads displayed on a page                  
```

This should go away, and any other variable declarations in the same subroutine that are also unused in our code.

**Comment by zorkian** [comment]
lol ads

**Comment by alexwlchan** [comment]
I’ve just grepped the codebase and I can’t find this variable anywhere. I think it got removed in 8406c21?

**Comment by kareila** [comment]
I agree, it looks like #2230 took care of this.
