### ISSUE TITLE
"MIME::Lite is not recommended by its current maintainer"

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2296]
From http://search.cpan.org/~rjbs/MIME-Lite-3.030/lib/MIME/Lite.pm#WAIT!:

> MIME::Lite is not recommended by its current maintainer. There are a number of alternatives, like Email::MIME or MIME::Entity and Email::Sender, which you should probably use instead. MIME::Lite continues to accrue weird bug reports, and it is not receiving a large amount of refactoring due to the availability of better alternatives. Please consider using something else.

So maybe do as they say? (The obvious question is: "What else?")

**Comment by kareila** [comment]
We also continue to accrue weird bug reports.  Until any of those point back to our use of MIME::Lite, or we begin to have trouble using it with newer versions of Perl, I'd be inclined to let it be.

**Comment by zorkian** [comment]
Agreed. No sense throwing it out until/unless we know we need to (and that should become apparent then).
