### ISSUE TITLE
Remove HTTPS Everywhere beta feature

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2300]
Obsolete now that we've implemented HTTPS Everywhere for reals.

**Comment by rshatch** [comment]
Claiming!

**Comment by kareila** [comment]
When I look at https://www.dreamwidth.org/beta on the live site, I still see the HTTPS Everywhere option, and the button seems to still work even though I suspect it doesn't affect anything.  We should make sure that gets cleaned up...

**Comment by rshatch** [comment]
Hmm, I'll have a look and see if I can find what's generating that.

**Comment by rshatch** [comment]
Actually, can someone confirm that the config file changes were made? That seams like the most obvious reason it's still showing up, but it's not one I can verify myself.

**Comment by kaberett** [comment]
Yep, that would be my bet

**Comment by kareila** [comment]
You were correct! Should be fixed now.
