### ISSUE TITLE
Make the email spellcheck test a soft reject/hint instead of the hard reject it is currently.

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2304]
See discussion in https://github.com/dreamwidth/dw-free/issues/993#issuecomment-360951407 and in the https://dw-dev.dreamwidth.org/203374.html?thread=1579886#cmt1579886 thread.

**Comment by chrisboyle** [comment]
claim

**Comment by chrisboyle** [comment]
All of these need an override ticky or command-line option

- [x] Create account
- [x] Change account/comm email
- [ ] Change **displayed** email
- [x] Submit support request while logged out
- [ ] Support ticket action "bounce"
- [ ] Buy shop items to be delivered by email, checked x3: `ShopItemOptions`,  `Shop::Item`, `shop/confirm.bml`
- [ ] `Admin/SupportCat.pm`
- [ ] Console command `email_alias`
- [ ] Sysban
- [ ] `tellafriend.bml`
- [ ] `manage/circle/invite.bml`
