### ISSUE TITLE
New Whitelist site requests: mixstep.co, audiomack.com, chirb.it

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2307]
<iframe src="https://mixstep.co/embed/20v1uter690o" scrolling="no" frameborder="0" width="100%" height="150"></iframe> 

<iframe src="https://audiomack.com/embed/song/ariox-1/faded" scrolling="no" width="100%" height="252" scrollbars="no" frameborder="0"></iframe> 

<iframe src="https://chirb.it/wp/pnC9Kh" width=380 scrolling="NO" frameborder=0>If you can not see this chirbit, listen to it here https://chirb.it/pnC9Kh</iframe> 

https://www.dreamwidth.org/support/see_request?id=38225

**Comment by kaberett** [comment]
claim
