### ISSUE TITLE
whitelist iframes of facebook

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2310]
<iframe src="https://www.facebook.com/plugins/post.php?href=https%3A%2F%2Fwww.facebook.com%2Froman.khimich%2Fposts%2F1833062543390842&width=500" width="500" height="629" style="border:none;overflow:hidden" scrolling="no" frameborder="0" allowTransparency="true"></iframe> 

https://www.dreamwidth.org/support/see_request?id=38229

requested to whitelist facebook iframes

**Comment by kaberett** [comment]
This is, happily, a duplicate! Of #1946. This issue can be closed; it will all Just Work come the ~~glorious revolution~~next code push.

**Comment by zorkian** [comment]
So it is written!
