### ISSUE TITLE
yank badpassword support

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2320]
Console command + bin script for setting bad passwords still work, but the user-facing interface has bitrotted. Can go byebye.

**Comment by kaberett** [comment]
To clarify: is that *all* badpassword support *everywhere* can go, or just the user-facing interface bit?

**Comment by zorkian** [comment]
This is the thing that lets us set a password that is banned/not allowed to be used?

I think we can rip that all out.

**Comment by kareila** [comment]
I think it's more like "we know this user has a bad password and we are forcing them to change it" but if D says rip it out, I will rip it out. Claiming.
