### ISSUE TITLE
Beta update page userpic widget appears blank/confusing with no userpics

### ISSUE THREAD

**Issue by chrisboyle** [dreamwidth/dw-free#2323]
As a user with no icons, go to the beta update page:

![userpic-picker-empty](https://user-images.githubusercontent.com/127305/37844489-d746a244-2ebf-11e8-9ea2-89d84f4153fb.png)

The tiny square area can be scrolled down to show
"""
[blank lines]
Upload a
[more blank]
userpic
[further emptiness]
"""

Removing the class "icon" from the "upload a userpic" link fixes things, so we could just do that:

![userpics-better](https://user-images.githubusercontent.com/127305/37844687-7992cc3a-2ec0-11e8-906c-197b8b9a83e1.png)

**Comment by kaberett** [comment]
claim
