### ISSUE TITLE
Googles invisible reCaptcha failing on Android mobile platform

### ISSUE THREAD

**Issue by myhubchloe** [dreamwidth/dw-free#2330]
Implemented invisible recaptcha for our site and it works on desktop and on all ios devices. 

It doesnt work on Android.when clicked on the button , nothing happens...also this happens intermittently , when i refresh the page it works.

P.S : I am able to see the badge though!

**Comment by rahaeli** [comment]
Hi Chloe! I think you have the wrong issue tracker -- this is the issue tracker for Dreamwidth (www.dreamwidth.org), not for Google's recaptcha system. Looks like their support area is here: https://developers.google.com/recaptcha/docs/faq
