### ISSUE TITLE
Trying to access xmlrpc results in 307 redirect

### ISSUE THREAD

**Issue by sunchaserinfo** [dreamwidth/dw-free#2352]
``Received non-200 HTTP Code: 307``

with body
```
<html>
<head><title>307 Temporary Redirect</title></head>
<body bgcolor="white">
<center><h1>307 Temporary Redirect</h1></center>
<hr><center>CloudFront</center>
</body>
</html>
```

on main dreamwidth.org

**Comment by alierak** [comment]
Interesting. My guess would be that CloudFront has replaced the XML results with its own page corresponding to status code 307. In the LJ Protocol, status 307 means "Selected journal no longer exists."

**Comment by alierak** [comment]
(Except, no, if the LJ Protocol result is a 307, the HTTP status code should still be 200 OK in that case, and the 307 would appear as the faultCode value in the XML result)

**Comment by alierak** [comment]
I don't suppose you have a way to tell what it was redirecting to? That would be the Location header in the HTTP response.

**Comment by Sophira** [comment]
I can reproduce this; for me, it occurs when POSTing to the non-HTTPS endpoint. For me, the `Location` header points to the equivalent HTTPS URL.

@sunchaserinfo, does this occur for you when posting to the same endpoint when using HTTPS?

**Comment by sunchaserinfo** [comment]
I tried to adapt https://github.com/darkk/ljfeed for DW. I thought that changing url to https:// is enough but instead I needed to change Transport to SafeTransport. I'm not a Python coder :(
Thank you for pointing out that issue is indeed with https. It works now and the issue can be closed

**Comment by zorkian** [comment]
Awesome, glad you got it working!
