### ISSUE TITLE
add Discord to "Other Sites" list on user profile

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2358]
Requested: https://dw-maintenance.dreamwidth.org/77357.html?thread=2874157#cmt2874157

**Comment by zorkian** [comment]
Yessssssss

**Comment by kareila** [comment]
Also: https://dw-suggestions.dreamwidth.org/1499325.html

**Comment by sklei4** [comment]
claiming

**Comment by kareila** [comment]
This was resolved in #2363.
