### ISSUE TITLE
whitelist GoogleDrive

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2361]
Request for whitelisting GoogleDrive in iframes

<iframe src="https://drive.google.com/file/d/1hd_Kqj-Mop_lZyYeqyySMg38V-_deM4p/preview" width="640" height="480"></iframe>

https://www.dreamwidth.org/support/see_request?id=38991

**Comment by kaberett** [comment]
<3 Duplicate, with some commentary from @rshatch: https://github.com/dreamwidth/dw-free/issues/2196
