### ISSUE TITLE
Autoformat post-by-email using markdown

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2365]
This is already the case for reply-by-email comments, and avoids the issue of unhelpful forced line breaks.

I am also pro being told whether sticking "!markdown" at the beginning of an e-mail post currently provides markdown formatting so I can add it to the FAQ, because this is not a feature I have used in probably over a decade and I don't have the brain to test right now. <3

**Comment by kareila** [comment]
I also don't have time to test right now but I think it is likely to work; also, if we change the default behavior for email posts, then there won't be a way for users to opt back out of the Markdown formatting, which might lead to unforeseen headaches, since posts are more likely than comments to include other formatting?  I am in favor of making sure it works and then updating the FAQ.

**Comment by miome** [comment]
I can test for you, if you can give me some inputs and expected outputs.

**Comment by Alyndra** [comment]
https://www.dreamwidth.org/support/see_request?id=40242

Putting !markdown at the top of an email avoids the issue of unhelpful forced line breaks in the main body of the text, but if there are too many tags to fit on one line, they won't all be read as tags.

**Comment by larissa-k** [comment]
I've had that problem for years. [Relevant support request](https://www.dreamwidth.org/support/see_request?id=37170), with a lot of example/test posts linked.

**Comment by Alyndra** [comment]
Ooh, thank you! ...So does separating tags with commas but no spaces fix it? And if not, would the user be able to do multiple post-tags commands to get them all without hitting a linebreak?

**Comment by kareila** [comment]
After the next code push, commit bbfc48c has fixed this so that emailed posts will be automatically formatted with Markdown, and including the tag `post-format: html` will use the previous behavior instead.
