### ISSUE TITLE
Add ehtml and eurl to DW::Template::Filters

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dw-free#2371]
We make LJ::ejs_string available as a dynamic filter in TT, we should probably also add LJ::ehtml and LJ::eurl as well so that individual handlers don't have to pass sub refs to their templates to use them.

**Comment by kareila** [comment]
The reason we haven’t added those is because they are natively supported in TT:

- http://template-toolkit.org/docs/manual/Filters.html#section_html

- http://template-toolkit.org/docs/manual/Filters.html#section_url
