### ISSUE TITLE
more "Other Sites" upkeep: remove Delicious

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2376]
Delicious has been gone for a while and most of their hardcore users moved to Pinboard.  I'm not suggesting we automatically migrate usernames, but the URL displays should be similar if not identical.

**Comment by kareila** [comment]
I was capturing issues in a hurry and didn't notice that Pinboard was already added, so this is just the Delicious removal then.

**Comment by rshatch** [comment]
Claiming
