### ISSUE TITLE
properly anchor header navlinks in Tectonic

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dw-free#2378]
(augh hit enter too early.)

If you use a larger height than the 'auto' height for the header in Tectonic, the navlinks bar ends up unmoored from it's spot at the top of the content and looks pretty weird. This is a quick fix with CSS, though! 

```
#header {
    position: relative;
}

#header .inner {
    position: absolute;
    width: 100%;
    bottom: 0;
}
```

**Comment by momijizukamori** [comment]
(augh hit enter too early.)

If you use a larger height than the 'auto' height for the header in Tectonic, the navlinks bar ends up unmoored from it's spot at the top of the content and looks pretty weird. This is a quick fix with CSS, though! 

```#header {
    position: relative;
}

#header .inner {
    position: absolute;
    width: 100%;
    bottom: 0;
}```

**Comment by rshatch** [comment]
claiming
