### ISSUE TITLE
Typos in https://www.dreamwidth.org/manage/settings/?cat=shortcuts

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2380]
"Enables keyboard shorcuts" and "Enables touch shorcuts" should both be "shortcuts".

Pointed out by Musyc in IRC.

**Comment by momijizukamori** [comment]
This got refiled by accident (#2891), and the newer ticket has the translation string names + is closer to the top of the list, so I'm going to close this one as the duplicate.
