### ISSUE TITLE
remove fastclick.js

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2381]
Located in `htdocs/js/foundation/vendor/fastclick.js`

@momijizukamori says: "Turns out the issue with dropdowns not opening in mobile FF is that they require double-clicks... I'm seeing scattered reports online that it's an issue with the FastClick library which Foundation vendors in... and it looks like FastClick is in fact the culprit. Comment it out of the foundation resource group = dropdowns work normally again both in Chrome and FF."

> Note: As of late 2015 most mobile browsers - notably Chrome and Safari - no longer have a 300ms touch delay, so fastclick offers no benefit on newer browsers, and risks introducing bugs into your application. Consider carefully whether you really need to use it.

**Comment by rshatch** [comment]
claiming

**Comment by rshatch** [comment]
So evidence points to this being a non-breaking change - while the version isn't mentioned, [this thread](https://foundation.zurb.com/forum/posts/26143-fastclickjs-and-ubermenu) has a comment from a Foundation dev saying it's safe to just comment out FastClick.
