### ISSUE TITLE
Find/implement replacement for GitHub Services for posting to changelog.

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2383]
Per https://developer.github.com/changes/2018-04-25-github-services-deprecation/ and https://developer.github.com/changes/2018-10-01-denying-new-github-services/,  that feature is going away in a little over a  month.

**Comment by rahaeli** [comment]
Hmm, do we use GHS at all? I thought we were still doing a post-by-email thing.

**Comment by alierak** [comment]
Every recent post in https://changelog.dreamwidth.org/ contains the deprecation notice inserted by GHS.

**Comment by rahaeli** [comment]
Lol, okay, nevermind then! Shows what I know.

**Comment by rshatch** [comment]
Irritatingly we may have to run an extra service somewhere to mediate between the webhooks format and entry format. The quick and dirty way would be to host something separately (maybe on dreamwidth.net?) to receive the webhook post and generate a post-by-email/post-by-api for the changelog journal.

The alternative would be to create a new endpoint on Dreamwidth itself and essentially special-case the changelog journal which, uh, I'm a bit leery of.

**Comment by rshatch** [comment]
additional thought - does this affect the claimbot as well?

**Comment by alierak** [comment]
We run an extra service using nginx on the admin box to map /interface/github to the ghi-assist python script

**Comment by alierak** [comment]
See https://github.com/afuna/ghi-assist

**Comment by rshatch** [comment]
Sweet, we can probably add changelog stuff to that, then.

**Comment by pauamma** [comment]
If this makes the posting code simpler, the DW::Hooks::Changelog hook (and associated code in LJ::Protocol and {,ext/local/}etc/config-private.pl) can probably be resurrected. If not, that code should probably be nuked as bitrotten.

**Comment by rahaeli** [comment]
Hacky but low effort workaround solution: make a new GH account, subscribe to commits only, set its email address to the post by email address? (Downside, would also post all other github email sent to that address)

**Comment by pauamma** [comment]
Other possible downside: it would also reveal the posting PIN since (IIRC) account email addresses are public. May still be worth it as a stopgap measure. Your call.

**Comment by kareila** [comment]
I’m not sure if anyone took action to fix this or not, but the notice is no longer showing at the bottom of changelog entries and the entries are still being posted when a commit is made.

**Comment by pauamma** [comment]
Uh. Apparently, GitHub has partially changed its collective mind. See the "Updated 01-30-19" item at the end of https://developer.github.com/changes/2019-01-29-life-after-github-services/. I guess we can close this.
