### ISSUE TITLE
Librarian's Dream style doesn't use header image properly

### ISSUE THREAD

**Issue by momijizukamori** [dreamwidth/dw-free#2390]
via http://www.dreamwidth.org/support/see_request?id=39448
It looks like Librarian's Dream uses #header .inner instead of #header and consequently overrides the header background styling from TR, but it doesn't add the image styling back in properly.

```
#header {
    padding: 1px;
    background: none;}

#header .inner {
    padding: 1px 1em;
    background: $*color_header_background;
    }
```
versus
```

#header {
    $header_background
    $page_title_colors
}
``` in TR

**Comment by rshatch** [comment]
claiming, hopefully will have some time this week to get a few style fixes out.
