### ISSUE TITLE
add gimletmedia.com to embed whitelist

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2397]
https://www.dreamwidth.org/support/see_request?id=39611

Sample code:

`<iframe scrolling="no" allow="autoplay" frameborder="no" width="100%" height="130px" style="border-radius: 3px; box-shadow: 0 0 25px 0 rgba(0, 0, 0, 0.15);" src="https://player.gimletmedia.com/awhk76"></iframe>`

**Comment by rshatch** [comment]
claiming

**Comment by momijizukamori** [comment]
Fixed via #2407
