### ISSUE TITLE
whitelist embed from strava

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2402]
request from user: https://www.dreamwidth.org/support/see_request?id=39417

<iframe height='405' width='590' frameborder='0' allowtransparency='true' scrolling='no' src='https://www.strava.com/activities/1997053955/embed/54dd7dc49efe8f9b00b8fceb01fa822fcc7de662'></iframe>

**Comment by rshatch** [comment]
claiming

**Comment by momijizukamori** [comment]
Fixed via #2407
