### ISSUE TITLE
whitelist embed new spotify

### ISSUE THREAD

**Issue by SporkyRat** [dreamwidth/dw-free#2403]
user request from https://www.dreamwidth.org/support/see_request?id=39351

<iframe src="https://open.spotify.com/embed/album/2aE3VcIiNPqqo4VzOXiDoR" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>

New spotify code, possibly. @momijizukamori may be able to get a newer one.

**Comment by rshatch** [comment]
```
<iframe src="https://open.spotify.com/embed/user/64f31rn6hwblzmssibjvs75e8/playlist/1ACvcMYSJoqa3gwOw6j0NR" width="300" height="380" frameborder="0" allowtransparency="true" allow="encrypted-media"></iframe>
```
Playlist embed generated rn

**Comment by rshatch** [comment]
claiming
