### ISSUE TITLE
Beta "create entry" page has outrageous compounding blowout on mobile

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2415]
(`/entry/new`, not `/update`.)

You've probably already experienced this slapstick for yourself, but just in case:

![user-blowout](https://user-images.githubusercontent.com/484309/55937178-2b19d200-5bed-11e9-80b4-3b2036a9df29.gif)

The page starts ultra-hosed, and then every time you change the journal you're posting to it gets another 300+px wider. 

I have fixed this. Patch incoming. It's an ensemble comedy with multiple participants.

**Comment by SporkyRat** [comment]
That's beautiful.
