### ISSUE TITLE
TT-ified /logout controller breaks control strip "log out" button

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2417]
This can't be experienced in prod yet because the change was never deployed there, but it looks like `cgi-bin/DW/Controller/Auth.pm` does a `... = controller( anonymous => 1, form_auth => 1 )`, and the control strip logout form does not supply the necessary hidden input for form_auth. 

To reproduce: 

- Make a dev server running upstream `develop`, get some users w/ journals, yadda yadda. 
- Go to a user-styled S2 page like a journal or entry.
- Click the logout button in the control strip. 

Expected: my user logs out. Got: form submission error.

**Comment by alierak** [comment]
This is due to PR #2230 - I believe the nav strip will also have to specify logout_one=something, and there is no longer anything that uses the ret=1 parameter, so logging out while viewing a specific page will probably just display a variation of the new logout page.
