### ISSUE TITLE
Discord field on profile is over-escaped

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2425]
#2358 added Discord to the profile but it's being over-escaped on display: https://dw-maintenance.dreamwidth.org/77903.html?thread=2882639#cmt2882639

**Comment by kareila** [comment]
The Discord section of that code is identical to the ones for other sites, which makes me think it's a general problem with usernames that contain octothorpes?

**Comment by rahaeli** [comment]
Yeah, everything on the profile is double escaped, Discord is just the first one that it's shown on :)

**Comment by kareila** [comment]
This is fixed on the release-1.35 branch.
