### ISSUE TITLE
Putting usernames in subject lines breaks subject line permalinking

### ISSUE THREAD

**Issue by rshatch** [dreamwidth/dw-free#2426]
Reported here: https://dw-maintenance.dreamwidth.org/77903.html?thread=2883407#cmt2883407

**Comment by nfagerlund** [comment]
I think this is expected behavior!

```perl

**Comment by nfagerlund** [comment]
Fun fact, you can also trigger this by just saying "href" somewhere in your entry subject, lol

**Comment by kareila** [comment]
I think Nick is right and this is intended behavior. If you're already on the entry page, you can copy the link from your browser bar if you need it. If we removed this, links in subjects wouldn't be accessible from any journal view.
