### ISSUE TITLE
Inactive icons not being reactivated after quota update

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2429]
The 1.35 release added more icon quota for paid/prem accounts. The Edit Icons page is supposed to include a quota check (that will reactivate deactivated icons if quota has changed) when you load it if you're logged in, but https://dw-maintenance.dreamwidth.org/77903.html?thread=2886479#cmt2886479 is saying that it hasn't.

**Comment by kareila** [comment]
I combed through the relevant code and couldn't see an obvious culprit. Caching issue perhaps? I'm inclined to close this if we never received any other similar reports.

**Comment by rahaeli** [comment]
Yeah, no other reports
