### ISSUE TITLE
Don't insert script tags that invoke jquery at random points in the page content

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2434]
I ran into this because it was a blocker on #2427, but it also seems worth doing just for the sake of consistency and hygiene. 

Conventional practice says script tags go either in the head or at the very bottom of the body. DW's `need_res` deferred javascript loader does exactly that. By which I mean it does both thats: if the active resource group (bear with me here) is `"jquery"`, they go in the head, but if it's `"foundation"` then they go at the bottom of the body.

But DW also has a few spots where script tags just get squirted at random into the body text instead of deferred, because the code is older than heck and that's just what happened sometimes. These are mostly in S2 pages, I think, and I don't believe there's very many of them left. 

In most cases, that's "annoying" or "gross" instead of "bad." But if you're interested in converting the S2 site scheme pages to use the Foundation version of site scheme (#2427), then you've got a problem, because some of those random script tags try to call jQuery, and in Foundation land jQuery isn't loaded yet. It's just down there at the end of the body element, a chasm of content between it and the caller, watching helplessly as the footgun goes off in slow motion. 

The fix is pretty tractable tho. As far as I could tell, it's only the qrdiv-adder, the quotebutton, and the iconbrowser; the other rogue script tags use ancient vanilla JS and can wait their turn.

I've got a branch, but it depends on that quickreply PR, so I'm gonna wait until that's merged.

**Comment by zorkian** [comment]
Your issues are very entertaining to read -- and educational. Thank you for explaining not just what you're doing, but why you're doing it. That really provides helpful context for me (particularly as I'm not much of a frontend person).
