### ISSUE TITLE
dreamwidth.org/mobile should have a "log out" link when logged in, probably

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2444]
https://www.dreamwidth.org/support/see_request?id=39962

**Comment by kaberett** [comment]
or I suppose we could just... get rid... of the /mobile site... altogether...?

**Comment by kareila** [comment]
That’s the long-term goal, but for people who still use this, it seems like an easy fix.

**Comment by alexwlchan** [comment]
Found the relevant file, looks like a one-line fix.
