### ISSUE TITLE
whitelist embeds from peertube?

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2450]
Support request: https://www.dreamwidth.org/support/see_request?id=39844

Sample code:
`<iframe width="560" height="315" sandbox="allow-same-origin allow-scripts" src="https://fanvid.stopthatimp.net/videos/embed/e1626528-b74a-47ba-ac52-49bc54c418ba" frameborder="0" allowfullscreen></iframe>`

**Comment by chebegeek** [comment]
I can no longer reach this domain, should we close this request?

**Comment by kareila** [comment]
I agree, it looks like whatever was there before is not there now. I can reach https://stopthatimp.net but it's just a placeholder.
