### ISSUE TITLE
Broken "don't crawl this" link

### ISSUE THREAD

**Issue by alierak** [dreamwidth/dw-free#2459]
Source of DW pages can include a broken link to LJ's developer/exporting page -- see the "don't crawl this" line in cgi-bin/LJ/S2/EntryPage.pm -- so we should find a suitable link to replace it with.

**Comment by alexwlchan** [comment]
Possibly related: #2208?

**Comment by alierak** [comment]
Yep, sorry, this would be a duplicate.
