### ISSUE TITLE
504 Gateway Timeout for images crossposted to LJ

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2461]
https://www.dreamwidth.org/support/see_request?id=39914

> I've noticed lately that entries I've been crossposting to LJ with images are not displaying the images properly. The images display fine on Dreamwidth, but on LJ they give me a "504 Gateway Time-out" error. When I post the image directly in an entry to LJ, without using the crossposter, the images display normally. I think something may be happening between the DW image rehosting, crossposting, and the LJ image rehosting.

**Comment by kareila** [comment]
Needs reproduction with verification that the image links in the crossposted entry are the same as in the "directly posted" entry.

**Comment by kareila** [comment]
Further inquiry leads me to believe this is an LJ issue, so I'm closing this.
