### ISSUE TITLE
switch to working as community does not work on "your layers" page

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2462]
The button just doesn't do anything.

Support request: https://www.dreamwidth.org/support/see_request?id=40068

Ana says:
> Replicating. Can get to the page by appending "?authas=communitynamehere" to the url [ https://www.dreamwidth.org/customize/advanced/layers ] though.

**Comment by rshatch** [comment]
claiming - this is related to the TT conversion; I must not have passed the authas value along properly
