### ISSUE TITLE
[[comm]] variable failing to render correctly in permissions error message

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#2463]
Support request: https://www.dreamwidth.org/support/see_request?id=40069

> If I attempt to access the membership queue for a community where I am not an administrator (I clicked a link in a notification email while logged into a different account than the one with permission), I receive the following error message:
>
> "Only community administrators can accept and reject membership requests. You aren't an administrator of [[comm]]."

**Comment by pauamma** [comment]
Is this the same as https://github.com/dreamwidth/dw-free/issues/2430 ?

**Comment by kareila** [comment]
Yes, thanks.
