### ISSUE TITLE
Move or remove orphan .bml.text files

### ISSUE THREAD

**Issue by rshatch** [dreamwidth/dw-free#2464]
We have a bunch of .bml.text files under /htdocs which have no corresponding .bml file any more. We should check to see if the strings in them are still in use, and if so, move them to appropriate files under /views, to reduce confusion. Stuff I'm seeing at a quick glance:
- export.bml.text
- go.bml.text
- logout.bml.text
- talkpost.bml.text
- talkread.bml.text
- everything under community/

additionally, files/ only has a placeholder file in it.

**Comment by kareila** [comment]
Pretty sure that at least a few of those strings are still used by cgi modules, but I'm sure there are some that can go.

The files/ placeholder is to keep the directory open for use by admin/fileedit.

**Comment by kareila** [comment]
I guess I'll claim this. I looked at the first two and confirmed that the strings are still being referenced elsewhere.

- [x] export.bml.text
- [x] go.bml.text
- [ ] logout.bml.text
- [ ] talkpost.bml.text
- [ ] talkread.bml.text
- [ ] community/join.bml.text
- [ ] community/manage.bml.text
- [ ] community/member.bml.text
- [ ] community/transfer.bml.text
