### ISSUE TITLE
Remove spellcheck support

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2481]
- Even the worst desktop browsers have had spellcheck in textareas for the last ten years at least, and mobile platforms all have spellcheck in their keyboards. DW's preview-spellcheck doesn't seem to actually add any value over those. 
- Maintaining a custom dictionary is a fool's errand. 
- We don't support other languages, whereas platform spellchecks do.
- The current spellcheck behavior is bad. (Issues with recognizing contractions, other problems.)
- The current spellcheck code sounds like it might be remarkably bad.
- That valuable UI space can be used for better things.

This came out of #2480, and was the first part to get maintainer consensus in the discussion.

**Comment by Alyndra** [comment]
Got the first "I miss spellcheck" comment
https://dw-maintenance.dreamwidth.org/78131.html?thread=3040819#cmt3040819

**Comment by nfagerlund** [comment]
That's fascinating. 👀 

I don't think that's in the domain of core site features, tho. Really sounds like a job for a browser extension; if they need that lock on the launch button in one place, surely they need it elsewhere too.

**Comment by rahaeli** [comment]
Yeah, I'll let them know, thanks for the heads up.

**Comment by kareila** [comment]
Just pushed the new talkpost_do, and the first complaint is "where did spellcheck go?"

https://dw-maintenance.dreamwidth.org/82890.html?thread=3299018#cmt3299018
