### ISSUE TITLE
inbox/markspam form is sending multiple form_auths

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2487]
This is similar to the problem @momijizukamori recently fixed with the editprivacy page - the form returns "invalid form submission" because it tries to submit two copies of the form_auth token.

**Comment by alierak** [comment]
It looks like account-links-text contains an lj_form_auth input that isn't in a form tag at all?
In which case maybe it applies to the unnamed form that is the page's actual content

**Comment by rshatch** [comment]
claiming!
