### ISSUE TITLE
QR: Bring back username indicator and move "more options" up top

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2521]
cf. https://dw-maintenance.dreamwidth.org/78131.html?thread=2995763#cmt2995763 — some people with many accounts miss having the reply form display their logged-in username.

**Comment by rahaeli** [comment]
It could fit pretty nicely just under the icon.

**Comment by nfagerlund** [comment]
I was kind of thinking of having it off on the right-hand side, since that way it wouldn't increase the total height until everything gets super narrow. Is there anything especially good about having it under the icon?

**Comment by rahaeli** [comment]
Both username and user icon are visual-markers-of-identity rather than settings, metadata, etc, for the comment being composed, so under the icon picker would mean someone could verify that they were logged in with the right account at the same time they're choosing an icon. (Checking which account you're logged into and checking that you used the right icon are also two common last-checks-before-posting, so IMO it's logical to have them together.)

(I also feel like putting username off to the right side would also look kinda detached-head-floating-in-space, but my reason for wanting it to the left under the icon is primarily function-grouping.)

**Comment by Alyndra** [comment]
Whoops I was talking about this here: https://dw-maintenance.dreamwidth.org/78131.html?thread=3015731#cmt3015731

I think having it at the top right next to the icon (where Browse currently sits) would be closest to familiar for people, and would group by function pretty well too. (I admit part of my motivation is wanting the icon stuff all on one line, hee!)

**Comment by nfagerlund** [comment]
@Alyndra You've also gotten me thinking about the "more options" button. If you're right about "more options" really only being about "more _user identity_ options" (and the more I think about it, the more I think you're right; subjecticon \[doomed\] and "don't autoformat" \[coming to quickreply at some point\] are the only other things in the talkform), then it probably belongs next to the username indicator, right? 

(By the way, did we ever fix the issue where "more options" throws away your comment text if you click it from your reading page and you don't yet have an up-to-date cookie from the subdomain of the journal you're replying to?)

**Comment by kareila** [comment]
No, it’s #1484.

**Comment by Alyndra** [comment]
@nfagerlund if it helps, this is what I'm picturing (note preservation of ziggurat shape, pls ignore username spelling fail):
![IMG_2767](https://user-images.githubusercontent.com/51764699/60057887-caf2e200-96ab-11e9-8463-7de82333f02d.JPG)
I wouldn't be at all opposed to fitting all three lines next to the icon instead of the subject line being under it, ftr. 

But now I'm comparing it to your screenshots from #2517 to imagine how it would squeeze down into extra smallness on mobile, and urrgh, it would be just all the buttons  and boxes stacked vertically, which would be Not Good. At extra small mobile widths I can see the benefits of putting the username above or below the preview user icon.

It's really making me question how much we need those Browse and Random buttons: what if Random got added as a dropdown option, and we told everybody well in advance where to look? 

Or alternatively, just let people axe buttons they don't personally use?

**Comment by nfagerlund** [comment]
A while back I was messing with turning those buttons into symbols instead of words (with an accessible label that's only displayed to screenreaders). That's still what I'm leaning towards for the future formatting buttons, although it's not happening this month. Quote (❝❞) would be below the subject, in the cluster of formatting buttons.

**Comment by Alyndra** [comment]
You know, you could leave them as text buttons for the majority of uses and turn everything into symbols only when the form needed to degrade extra narrow...then everything would fit just fine!

**Comment by nfagerlund** [comment]
Huh, that's an interesting thought! The main problem I'm imagining is confusing people's visual memory of what they're looking for, but that might not be a problem if the expanded version included the symbol as well as text.

**Comment by Alyndra** [comment]
I was thinking it wouldn’t be an issue with only one or two buttons on each line, but including both word and symbol when there’s room  would probably make it even better!

...although dang it, I’d bet you a nickel people are going to want to customize it...

**Comment by nfagerlund** [comment]
claiming

**Comment by nfagerlund** [comment]
[My dev instance](http://www.rr-thrice.hack.dreamwidth.net/) currently has some temporary controls for switching between a couple possible designs for this. I'm now at a point where I need an executive decision:

<table>
  <thead>
    <tr>
      <th>&nbsp;</th>
      <th>Desktop</th>
      <th>Mobile</th>
    </tr>
  </thead>
  <tbody>
    <tr>
      <th>Side</th>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800022-2ed43d00-ba97-11e9-8f31-55ed9398670b.png" alt="qr-dt-side" title="" />
      </td>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800018-2e3ba680-ba97-11e9-9f01-68a9a52ca077.png" alt="qr-ph-side" title="" />
      </td>
    </tr>
    <tr>
      <th>Top</th>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800021-2ed43d00-ba97-11e9-8603-628952688e12.png" alt="qr-dt-top" title="" />
      </td>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800017-2e3ba680-ba97-11e9-87cc-f2aea2cb160c.png" alt="qr-ph-top" title="" />
      </td>
    </tr>
    <tr>
      <th>Bottom</th>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800019-2ed43d00-ba97-11e9-8401-39f2b76bdb03.png" alt="qr-dt-bottom" title="" />
      </td>
      <td>
<img style="width: 100%" src="https://user-images.githubusercontent.com/484309/62800016-2e3ba680-ba97-11e9-8325-6c5806a078d4.png" alt="qr-ph-bottom" title="" />
      </td>
    </tr>
  </tbody>
</table>

- It'll be trivial to use different layouts on mobile vs desktop, so these are separate decisions. 
- The screenshots (and the live stuff on dev) include a few other changes from #2522: 
    - The browse button is part of the icon preview again, but this time it's labeled. 
    - The dropdown includes a "random" option.
    - The random _button_ starts hidden, and appears beside the dropdown after the first time you pick "random" from the dropdown. (For re-rolls.) 

    These were important because they reduced the amount of STUFF I had to cram into the design.

**Comment by nfagerlund** [comment]
Feedback from the [dw-dev post](https://dw-dev.dreamwidth.org/215787.html) about this was sparse and not statistically significant, so this probably comes down to: make a judgment with our own taste, brace for impact, and then iterate once we get some REAL feedback. 

### FWIW:

- One tester preferred "beside," because it gave full width to the dropdown on mobile (thus doing less truncation on long icon keywords).
- Another tester preferred "beside" on desktop/tablet and "above" on phone. (And then the new-school sitescheme test muddied the waters a bit, because the Foundation form controls are so massively padded. Not wholly sure what to do about that, yet.) 
- **Personally,** I also prefer desktop->"beside" / phone->"above". I think the most important spatial relationship in this zone is the position of the dropdown relative to the icon preview, and that combination keeps it constant.

**Comment by rahaeli** [comment]
If no one else has a strong opinion, I prefer top.

**Comment by nfagerlund** [comment]
In the process of finalizing this, I combined it with a redesign of the talkform, to make sure the approach was flexible enough. That convinced me that on-top is correct, because it aligns with where the identity controls go in the talkform: 

![image](https://user-images.githubusercontent.com/484309/63543829-87182f80-c4d8-11e9-9343-3d557d51c1bb.png)

So in the QR the top just has the username indicator, and in the talkform that expands to the full identity controls. Conceptually clean.
