### ISSUE TITLE
@user breaks sharing custom CSS/custom layouts in textboxes

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2526]
This is golden. Look at https://tofuhouse.dreamwidth.org/5447.html and look closely at the CSS definitions: they are now all &lt;user name="font-face" /> instead of  @font-face

It's completely breaking custom layout sharing, because when you copy and paste that into your CSS overrides, the CSS cleaner (rightfully) freaks out because you're trying to put HTML in your CSS:

/* suspect CSS: start HTML tag? */

**Comment by kareila** [comment]
Commit a8d0cebfde changes the username expansion code to ignore the most common CSS @ keywords.
