### ISSUE TITLE
no obvious way to escape @word that isn't supposed to be @user

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2527]
See me flailing around in https://dw-maintenance.dreamwidth.org/78131.html?thread=3029299#cmt3029299 to try to communicate to the user what needs to be changed.

If I type /@word I expect it to display as @word (escaping the @ and not trying to user-link 'word') but it's displaying with the / because it's correctly identifying that the @ is not at the start of the word.

**Comment by rahaeli** [comment]
wait, nevermind, @kareila correctly identified that I was escaping incorrectly and \@word works.

**Comment by pauamma** [comment]
Which begs the question: how does one escape \@foo, which is a common perl idiom?

**Comment by zorkian** [comment]
At the moment there's probably a way to do that with a combination of multiple slashes, but I am going to spend some time on doing this in an actually context aware way so you can use raw-code or whatnot and not escape them. Going to try to spend time on it this weekend.

**Comment by Alyndra** [comment]
This is an excellent question. You would think two backslashes? But no, that only gives you two backslashes and userhead foo. Here is what works: &#92;\@foo
