### ISSUE TITLE
/admin/propedit needs better error checking for "user does not exist" other than just throwing a perl warning

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2530]
[Error: Can't call method "raw_prop" on an undefined value at /home/dw/production/cgi-bin/DW/Controller/Admin/Props.pm line 226. @ va-web02]

Tried it with a few users other than the one that errored on me and didn't get it, so I imagine some bad data happened somewhere, but it would be convenient to be able to load users with bad data and somehow flag it so it can be fixed, rather than erroring.

**Comment by kareila** [comment]
Usually that error means the user object wasn’t defined. Which user gave you the error?

**Comment by rahaeli** [comment]
...nevermind, my c&p missed the last character of the username, I'll see myself out &c

**Comment by rahaeli** [comment]
actually, second thought: sticking a "does this username actually exist" check so we can give a useful error message would be helpfuler
