### ISSUE TITLE
Talkform: site user fields are hidden if no one's logged in, and also for openid

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2532]
![Screen_Shot_2019-06-25_at_4 29 05_PM](https://user-images.githubusercontent.com/484309/60140443-a9a2fc00-9766-11e9-92e4-4d4fe9144c02.png)

NUTS. I bet this is in the javascript somewhere, and I bet it started being a problem when I fixed that code that was never being run because it was attached to a nonexistent event. :|

**Comment by rahaeli** [comment]
There comes a point where you just have to laugh helplessly...

**Comment by alierak** [comment]
Code that is never being run contains a nonzero number of bugs, as I see it.

**Comment by nfagerlund** [comment]
https://github.com/dreamwidth/dw-free/blob/master/htdocs/js/talkpost.js

rewrite as jquery, y/n

**Comment by rahaeli** [comment]
I'm making That Face at that JS and I don't even JS, so Y

**Comment by nfagerlund** [comment]
hey guess where these variables get used 

https://github.com/dreamwidth/dw-free/blob/master/htdocs/js/talkpost.js#L52-L53
