### ISSUE TITLE
@user expansion should be disabled in rss reeds

### ISSUE THREAD

**Issue by akpdw** [dreamwidth/dw-free#2534]
Pretty sure that nobody on any external sites are referring to Dreamwidth accounts when they use @user.

RSS feeds are transient, but until it expires you can look at

https://dailykos-feed.dreamwidth.org/23309270.html

for an example.

**Comment by nfagerlund** [comment]
I _think_ this is fixed by a combination of #2540 and #2604... we'll find out after the next code push.
