### ISSUE TITLE
Profile page "other sites" lists obsolete Google Talk

### ISSUE THREAD

**Issue by me-and** [dreamwidth/dw-free#2585]
Google Talk is one of the "other sites" you can fill in on your profile page. That's no longer a service that exists; it should either be replaced by "Google Hangouts" (probably a drop-in replacement, since I assume most people will have just filled in the email address on their Google account, and that works for both), or removed entirely.

Seems like this would be a good first fix for a new contributor, at least once there's a steer on whether to just replace one label with another or to remove the thing entirely.

Reference for Google Talk no longer being extant:

* [Wikipedia has a whole bunch of onwards links to articles about the gradual retirement/replacement of Google Talk](https://en.wikipedia.org/wiki/Google_Talk).
* [The G Suite Updates Blog talks about "fully transitioning Google Talk to Hangouts"](https://gsuiteupdates.googleblog.com/2017/03/updates-in-g-suite-to-streamline-hangouts-and-gmail.html).
* <https://talk.google.com> redirects to <https://hangouts.google.com>.

**Comment by kareila** [comment]
+1 for switching from Talk to Hangouts, and just changing the labels and the URL.
