### ISSUE TITLE
Broken Markdown processing in html cleaner

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2601]
PR #2540 broke Markdown pretty thoroughly. It hasn't been deployed to prod.

Here's what I've learned so far: 

- ~[This bit right here](https://github.com/dreamwidth/dw-free/pull/2540/files#diff-a84240ca7cbff9cf6b58a0eee16ba5b4R1231-R1238) isn't tenable -- dropping into HTML is part of the Markdown language As She Is Played, so disallowing it breaks all existing user expectations about how it works and a lot of existing text.~

    Correction!!! I misunderstood how this breakage was working. Intended behavior is fine. As described in the PR text:

    > While using Markdown, you can also "drop to HTML" by opening any tag. This will suspend Markdown processing and @-user mentions until you close the tag. This enables you to drop in a textarea or whatever and not have to stress about it.

    That's part of the md spec, and is totally fine. Sorry for the false alarm! I interpreted the code as "any HTML locks you out of Markdown mode," due to the next bug:
- MD processing can't recognize "empty" (singleton) HTML tags, unless they're self-closed (XHTML style). So throwing in an `<img>` tag will break the rest of the post, unless you write it like `<img />`. We should at least make it so it can recognize the HTML5 forms of the most common empty tags. (img, br, etc.)
- Same for DW special tags, which are mostly the same issue but more inconsistent. For example, `<user>` tags can be self-closed, but poll placeholders can't; you need to add a full dummy closing tag like `<poll-132></poll-132>`. Cut tags are an even specialer case, because they render differently on last-N pages and entry pages -- using a cut tag around some markdown will make a post that works on its entry page but breaks on the flist. (Actually, pretty sure cut tags need to be a special exception to "no markdown-in-html-in-markdown".)
- There's also bugs when an HTML tag occurs inside a Markdown token. So far I've observed this with images inside links (`[<img src="..." />](url)`), but it might also break with tags inside blockquotes or something; still need to test. 
- Markdown image tags are broken. That syntax looks like this: 

    ```markdown
    ![alt text](http://image-url.example)
    ```

    This might be a problem with `HTML::TokeParser`'s configuration, but I can't tell yet.
- Actually, MD seems to be broken entirely on last-N pages. Switch to canary and check out [this entry page](https://roadrunnertwice.dreamwidth.org/577566.html) vs. how it appears [on the tag page](https://roadrunnertwice.dreamwidth.org/tag/didread). 
- Something's goofy with md link syntax, but need to investigate more. (I'm seeing a post where one inline link works fine, a reference link is busted, and then the NEXT inline link is busted.)
- Email posts. 
- Crossposter (DW/External/XPostProtocol/LJXMLRPC.pm).
- RSS/Atom feeds.

**Comment by zorkian** [comment]
I hear you on what would be nice, but this is the best compromise I could come up with that allowed all of the user complaints to be reasonably met and still allow us to clean HTML with our system.

So unless there's some viable alternative someone else can think of (and that would be great!), we'll stick with the current implementation (modulo bugfixes of course).

**Comment by nfagerlund** [comment]
@zorkian Pardon my initial alarm! 😅 I misunderstood the intended behavior. (Thought it was "no html-in-markdown," which... would have been wild. "No markdown-in-html-in-markdown" is pretty standard.)

I expanded the description with a better view of the specific bugs I've identified!

**Comment by zorkian** [comment]
Ahhh -- yeah, okay! That makes more sense.

Thanks for the bugs, I'll try to take a look! (But by all means, go to town if you want -- I'm trying to figure out this notification stuff for 90d...)

**Comment by nfagerlund** [comment]
Fixes for 90% of that all got merged, so I'll close this and open a new ticket for the crossposter!
