### ISSUE TITLE
DW can't run on dreamhacks anymore due to SQS requirement

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2617]
Ever since the SQS stuff, I've been having to test my fixes by checking out the last pre-SQS commit and rebasing my patches onto it. Currently works, but it's gonna get untenable real quick. 

It'd be good to have a way to configure dev servers that doesn't require AWS billing. Is SQS API-compatible with anything open-source? Is there a way to do a nice and stupid local-disk replacement for it, the way we do with blobstore? 

Failing that, it'd be good for volunteers if the hacks could get attached to SQS. But a dummy replacement would be better; imo it's important to have the option of roll-yr-own dev servers, since some people don't feel comfortable Asking For Free Stuff before they've contributed anything. (hi.)

**Comment by rshatch** [comment]
It looks like it may be possible to use moto to do local SQS - https://github.com/phstc/shoryuken/wiki/Using-a-local-mock-SQS-server

I'll investigate and get back to you, because I keep meaning to look into this for work testing.

**Comment by nfagerlund** [comment]
In terms of enabling dev work, this is fixed by #2622 (although a local SQS server might be interesting in the future!).
