### ISSUE TITLE
LJ::ljuser and LJ::User::ljuser_display mutate their opts hashref

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2632]
They set the `del` key in their opts hashref, thus changing it for whatever called the function. As of https://github.com/dreamwidth/dw-free/pull/2616, the html cleaner now just reuses the same opts hashref every time it calls these functions. Thus, if a post/comment refers to a strikethrough'd user, all following user tags get struck through.

**Comment by rahaeli** [comment]
🍆
