### ISSUE TITLE
s2foundation beta: little stuff

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2633]
Right now I think we've fixed everything, but I'm going to hold off on closing this until the beta goes opt-out and we get a new wave of people using it.

<details><summary>Completed</summary>

- ~Duplicated "thread" links in the comment footers! The first one is `.footer .commentpermalink`, and the old site skin CSS has a rule to set it as display: none. The second one is `.footer .thread`, and is apparently the one to keep. In conclusion... what?~
- ~In "Blue for Drifting" theme (possibly all Driftings), new talkform gets pushed down past the end of the sidebar content. The `clear: both` I put on on `#qrformdiv` to fix quickreply issues in a different style seems to be reacting to the float-based sidebar. I hate float-based layouts.~
- ~In lynx skin, the turquoise blue of the action box background makes it hard to distinguish the blue prev/next arrows.~ #2644 
- ~Actually, I could use some policy input about lynx. The old lynx comments had basically NO css, so adding normal CSS makes major changes.~ #2644 
- ~The new icon browser still wastes too much space in the upper area, esp. on mobile. I really want to tighten these controls up a bit more.~ (#2643) 
- ~Code blocks (like `<pre><code>...</code></pre>` as opposed to plain `<code>` spans) look whacked.~
- ~"action links" box on entries can sometimes impinge on large mood icons. (e.g. yhlee's mood theme.) Add some margin maybe.~
- ~The username indicator above quick-reply looks way too small on site skin pages.~
- ~Although the font size went up a bit for comments on tropo, it went DOWN for comments on gradation, which has always used 16px. Gotta make the scaling configurable per skin.~
- ~Should comment boxes in site skin `clear: both` to defend against floated images in the previous comment trashing the indentation (which is usually the only indicator of thread hierarchy)? Since these pages shouldn’t do any float layout bullshit in the beta, this should be safe and reasonable.~
- ~In site skin, can't resize reply form textarea wider than its parent.~
    - ~HOLY HELL, how many times do I have to fix this exact same bug??? This time it's Foundation's fault, not mine.~
- ~Tropo purple at mobile width has a weird display turd behind the username menu in the header. (Predates this, but more noticeable now.)~ #2653 
- ~The submit button for the "multiform" at the bottom of the page is missing the foundation button styles for some reason. Must be outside of an area-of-effect container.~

</details>

<details><summary>Not gonna bother with it for now</summary>

- On site skin, the reply form textarea is too tall to fit in the available screen space above the keyboard on an iPhone 5SE. It fits on most journal styles. 
    - Tricky. Should I set the starting height (user-resizeable, on desktop) to a fraction of the viewport height? That SEEMS reasonable, but it'll definitely result in a tall boi on huge desktop monitors. 
- Hey, let's go ahead and finish making site skin available on reading/recent/other-last-N pages. So far here's the only problems I'm seeing: 
    - The "Previous 20" etc. links are styled as a bulletted list. Functional, but could be less janky. 
    - Could probably stand to put a horizontal line between entries. Right now the transition is a bit abrupt. 
    - ~The cut tag expander triangle images have inline CSS that expects to be parachuting into a `box-sizing: content-box` regime (which most journal styles are). This assumption makes it go tiny on the site skin flist. It should just set box-sizing inline too.~
    - Need to add "site" as an option in the control strip on those pages, alongside "light."

</details>

**Comment by rahaeli** [comment]
Poking at the history of the file a little: I think that was back from when we were converting from talkread.bml to S2-generated comment pages, to keep the display of both site-skinned comment pages and user-skinned comment pages the same as they had been without moving things, and it might still even be necessary, I don't know for sure.

**Comment by nfagerlund** [comment]
Nod nod. My conclusion about the extra “Thread” was that it was for making some fragment of S2 code usable for both ReplyPage and EntryPage comments. (Since reply page DOES use the first “thread” and omits the second.)

**Comment by nfagerlund** [comment]
I'm closing this because we ended up with another omnibus bug for tracking post-beta issues. #2784
