### ISSUE TITLE
Rehabilitate Lynx site skin's foundation version

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2644]
The Foundationized version of Lynx (aka "style=light") has way too much actual styling in it; although the HTML frame of the page is appropriately chopped, the styling on the remaining inner sections looks exactly like the other foundationized site skins, just using turquoise (?!?!) as an accent color. 

As I understand it, this isn't desired, and Lynx is meant to be a web-brutalist promised land filled with juicy blue-and-purple links. However, until now, no one's really noticed it, because tbh the pages that have been converted to the foundationized skins so far are not pages that get heavily used. There are a few that might be _moderately_ used: 

- Image management stuff
- The beta new entry page

...but even those are likely NOT being used by the type of user who browses their flist from /mobile and sets every page to `=light`. 

The s2foundation beta changes that by imposing foundationized skins on the pages people spend actual time on; the "light" users who've turned it on have immediately noticed the problems.

Anyway, this is looking surprisingly tractable. I'm making some satisfying progress over at https://github.com/nfagerlund/dw-free/tree/may20_lynx_try2. 

- I seem to have gotten entry/reply/icons pages looking about like they used to. 
- All the simple foundationized pages I've tried seem fine. (Up to and including the image management pages.) 
- The beta icon browser looks great, since I already went to some trouble to make it work in journal pages. 
- The beta new entry page is the one remaining mess:
    - The fancy-selects crashed p. hard.
    - Section toggle icons floated away to heaven. (already fixed that.) 
    - Date picker's trashed.
    - Big chunks of the tag completer are transparent. 
    - Something weird happening to checkbox labels in the settings. (Is there some kinda float shit going on in there? Ah, no, it's splitting some inline containers across CSS columns.)
    - Textarea and text input widths go to hell at mobile widths. 
    - But all told, that's actually less busted than I expected...

**Comment by rahaeli** [comment]
I am impressed that it broke that little!
