### ISSUE TITLE
The Squash, Part 3 (Save the RP Museboard Artisans)

### ISSUE THREAD

**Issue by nfagerlund** [dreamwidth/dw-free#2650]
This is distinct from The Squash, Part 2.5 (#2611, hide irrelevant zoom cursors) and the not-yet-documented The Squash, Part 2.8 (provide interface for zooming link-wrapped images without leaving the page). 

## Previously

**The Squash, Part 1:** CSS to shrink images in entry/comment content, to prevent them from:

- Overflowing their container width.
- Failing to fit in the browser viewport.

**The Squash, Part 2:** Click-to-zoom, to rescue 4-comi vertical strips and let people opt into overflows for important pics.

## Now

DW RPers (and certain other subcultures) like to use carefully-crafted fragments of markup with inline CSS to create intricate decorative units, for a variety of conversational/navigational/emotive purposes. In the local dialect, these inline-styled markup fragments are called "codes." The Squash has a tendency to vandalize them.

On reflection, all I care about with The Squash is **casual images.** There's always going to be a way around this CSS, if anyone REALLY wants to prank their followers with an flist overflow; all _I_ want to do is make it so anyone can huck an `<img>` up on there without stressing out about possibly being rude to your peeps. 

I _don't_ want to vandalize anyone's codes, and I especially don't want to keep fielding complaints and requests from the people whose codes I've vandalized. So, maybe we can find a semi-reliable way to exempt intricately styled markup from The Squash, while still hitting 95% of casual images. 

## Ideas

I had two initial ideas: 

- Look for `height=` and `width=` attributes on the img tags, and treat them as a (partial?) indicator that the author knows what they're doing. (This is problematic because a lot of things that give you pasteable markup for casual images will automate those attributes.) 
- Look for deeply nested structures or some other marker of complexity. 

## Complications

- A lot of casual images are pasted from "share" fields on image hosts, and they might have surprisingly complicated markup. Need to investigate prevalence of that, and also to what extent DW actually tolerates their weird shit. (e.g. Flickr uses JS to spawn an iframe, given its druthers.)
    - iframe contents are unaffected by the embedding document's CSS anyway, so shrug. 
    - html cleaner seems to disallow random embed JS, so what you paste is what you get. In flickr's case, that's `a img`. 👍🏼 
    - Instagram are such creeps. Their image embeds don't even appear on sites that don't allow their spyware JS to run. So, don't have to worry about them. (Although that test did turn up another context where @ mentions aren't appropriate to render.)
- Various feeds wrap their casual images in markup that might look like a code to an insufficiently rigorous check, because they expect to be displaying in a totally different original context. (Shit like `div div img`, `figure a img`...) Casual images in feeds are kind of public flist enemy number 1.
- Combinatorial CSS selector explosion.

**Comment by rahaeli** [comment]
This way lies madness, I know, but for your complication 2, we could just say "any entry in a feed account can bypass the complicated squash CSS with umpty exceptions  and only include the simple squash". Complicated CSS in entries is a local journal thing only, people are used to entries from feeds not looking the way they do at the source.

**Comment by rahaeli** [comment]
(I *think* we have CSS wrappers in entries to distinguish between a feed entry and a personal/community entry but if we don't, we totally should)

**Comment by nfagerlund** [comment]
I checked and couldn't see one, but yeah, seems reasonable to add an extra class to feed entries.

**Comment by nfagerlund** [comment]
I thought about this a little more.

I like the idea of "feed images get squashed, no exceptions." And it turns out there IS an entry wrapper class for feed entries! I just didn't recognize it because it uses old LJ guts jargon. 😅 It's `journal-type-Y`. (where `journal-type-P` is a personal journal, etc. etc.)

Depth-checking won't work, I think. I've seen `div a img`s that should definitely be left alone, but something like `ul li a img` is definitely a casual image and should get squashed. So both of my initial ideas are a bust.

But here's a new idea:

- If an image is inside a table, leave it be. 
- If an image is inside a `<div style="...">`, leave it be. 

I perused the recent "dreamcodes" archives, and everything I could find uses either a table or a div with inline styles. As long as we're exempting feeds, I feel like those are both pretty good signals that you're putting a lot of effort into making something display right, and don't need any extra "help". And if there IS any casual image embed copypasta that uses inline styled divs, it's hopefully using them to make sure the image behaves responsively wherever it ends up, so we might as well trust it, too. 

It's always possible someone'll start a fashion of using HTML5 elements like `<section>` for decorative codes, but I kind of doubt it -- those are much more likely to run into default styling problems on some site or some journal style (or maybe even here in the site skin comments... remember that `<nav>` thing that went wild on "latest things" that once), so the inline-styled div is prrrobably here to stay.

**Comment by rahaeli** [comment]
I think that's all a good plan.

**Comment by nfagerlund** [comment]
Ran into some slapstick comedy while prototyping this. The upshot being, I'm still positive it's doable, but it's going to be a little more complex. 

- The way html5 defines the img tag's width= and height= attributes is kind of wild. They act as the default values for the CSS width: and height: props for that element, lower than the very lowest level of priority. BUT, there's absolutely no way within CSS to specify that you WANT to fall back to the attribute-specified defaults. If you try something like `unset` or `auto`, it'll use the image's intrinsic dimensions instead of the requested dimensions. 

    Basically that means that there's no way for CSS to truly _undo_ size CSS once it's been applied to an image; the only way to have height= and width= act like they do by default is to never apply sizing CSS to that element in the first place. So that's what we need to do for images that we want to be exempt from the squish. 
- Well ok, I knew all that already, so I came up with a pure CSS way to exclude "children of tables or styled divs" from the squish. Unfortunately, it relies on the enhanced `:not()` from selectors Level 4, and only Safari has implemented that one. There's no way to use Level 3 `:not()` to say "not a descendant of thing." (But it DID actually work in Safari! Dammit!)
- So that means I'll need to do some of this in Javascript. Figure I'll have a `squish-exempt` class or something and use a Level 3 `:not()` to exclude it from the squish, then use JS to add that class to image children of tables/styled divs. That'll retroactively make it so the squish was never applied to those. Simple enough. 
- Except guess what, it can't just happen on document ready; it needs to also catch stuff that rides in on ajax cuttag expansion and comment expansion. So that means I actually DO need to implement about 75% of The Squash Part 2.5, after all.

**Comment by zorkian** [comment]
I tried to use Google for 'level 3 not' and 'level 4 not' and mostly got things about various levels of alarm and 'do not travel' advisories...

I then tried adding 'JavaScript' to the search parameters and that also failed to turn up anything useful.

But, your description was quite thorough, so while I don't understand the nuances involved here with the underlying JS, it sounds like a sensible approach (as much as can be said given the systems you're dealing with and the user behavior in question).

**Comment by nfagerlund** [comment]
Oh, yeah, those are a CSS thing. 

- [CSS Selectors Level 3, negation pseudo-class](https://www.w3.org/TR/selectors-3/#negation) — can only accept a "simple selector" (i.e. no lists, no combinators). 
- [CSS Selectors Level 4, negation pseudo-class](https://www.w3.org/TR/selectors-4/#negation) — can accept a full selector list.
