### ISSUE TITLE
New spam report for spam admins: "comment in" (submitting user)

### ISSUE THREAD

**Issue by azurelunatic** [dreamwidth/dw-free#2721]
A previous version of this was filed in Bugzilla and didn't make it over. 

I'd like to be able to see a report of spam submitted by a particular user. This would be used for noticing if that user is submitting a lot of non-spam. The spam-admin would then be able to send it along to Terms of Service, to have The Talk. Currently, spamwhackers have to manually notice whether a particular user or community is generating a lot of not-spam reports, and then have to track down those reports manually. 

My knee-jerk feeling is this should be limited to spam admins, unless there's a reason someone else can think of that it should be available to more.

**Comment by kareila** [comment]
> A previous version of this was filed in Bugzilla and didn't make it over.

http://bugs.dwscoalition.org/show_bug.cgi?id=2070

**Comment by kareila** [comment]
I'm going to post screenshots here for feedback. Here's the initial front page mockup:

![Screen Shot 2020-06-29 at 8 59 44 PM](https://user-images.githubusercontent.com/1976742/86074446-9991bc80-ba4b-11ea-91dc-24f3780a2d0c.png)

**Comment by kareila** [comment]
Submitting the "reports from journal" form:
![Screen Shot 2020-06-29 at 9 26 15 PM](https://user-images.githubusercontent.com/1976742/86076175-46216d80-ba4f-11ea-98d7-b250df2db714.png)

It's the same as the "Comments By" form with the roles of journal and poster swapped.

Are there any other features needed for a first draft?

**Comment by azurelunatic** [comment]
That's lovely! Looks perfectly functional.

**Comment by azurelunatic** [comment]
Thinking about it, should Terms of Service get access to view this too, or do they have courtesy antispam privs?

**Comment by kareila** [comment]
The two people who currently work TOS also have antispam privs.
