### ISSUE TITLE
new comment preview form doesn't include "admin post" metadata when previewing

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2735]
https://www.dreamwidth.org/support/see_request?id=42154

> Hi, I'm just previewing a comment in my comm, and I checked the "admin post" box, but the little ribbon graphic and "as admin" text doesn't appear in the preview area. It'd be great if it showed up there so I don't keep checking to see if it's selected.

It sounds like this is a request for a new feature, as opposed to something that went missing during the conversion.

**Comment by nfagerlund** [comment]
Oh! Yeah, I have no idea whether that was present in the old preview, but should be a matter of minutes to get it in the new one.
