### ISSUE TITLE
Form for mass action on comments less subtle in s2foundation beta

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2777]
I don't know that this is a bug per se, but the big red button is telling me it wants to be the main focus of my attention and it shouldn't be.

Beta:
![Screen Shot 2020-07-22 at 12 48 14 AM](https://user-images.githubusercontent.com/1976742/88139463-60192080-cbb5-11ea-8029-7df7d69db9b9.png)

Old style:
![Screen Shot 2020-07-22 at 12 47 43 AM](https://user-images.githubusercontent.com/1976742/88139482-66a79800-cbb5-11ea-89d5-0020836eb058.png)

**Comment by nfagerlund** [comment]
Ha! 😅 I went specifically out of my way to make it look like other foundation form submit buttons. 

Could make it a grey “secondary” button instead, though. In terms of the page markup hierarchy, it kind of IS the culminating element of the whole scroll, but socially I agree it’s definitely “secondary.”
