### ISSUE TITLE
Community import still busted

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2785]
C/p from comment, this should have been fixed with this push yeah? 

The option to import to/from a community broke in the last code push at the end of June, when the button that let you switch user disappeared.

The switch user button is back now, but when trying to import to a community, I'm still getting the same error message:

https://www.dreamwidth.org/tools/importer?authas=notestoaprawn

Error

You must be logged in to a personal account (not OpenID) in order to import content into it.

I'm logged in to my personal accounts on both DW and LJ when I see this message.

**Comment by kareila** [comment]
Are we sure this wasn't related to workers needing to be restarted?

**Comment by rahaeli** [comment]
Nope! I  asked them to check again

**Comment by rahaeli** [comment]
User confirms they've tried it since the worker restart and it's still busted
