### ISSUE TITLE
issues with Markdown formatting of URLs in some cases

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2787]
https://www.dreamwidth.org/support/see_request?id=42243

In some circumstances, URLs in Markdown are forced to be lowercase, which breaks case-sensitive links (think YouTube ID strings).

This predates yesterday's code push.

**Comment by nfagerlund** [comment]
I think this can be closed. The issue report doesn't seem to be differentiating between two things:

- Capital letters in path names -- these are semantically meaningful depending on the server implementation, and must be preserved. 
    - We totally preserve these. 
- Capital letters in hostnames -- these are semantically meaningless, and are supposed to get normalized to lowercase during name resolution (though I'm not sure which agent is responsible for that normalization). 
    - Actually, we preserve these as well! BUT, if you hover over the link in your browser, it will show the hostname as normalized to lowercase in the "where'm i goin" preview. If you view source (or even the web inspector), it'll show the original capitalization on the hostname. 

Our behavior on this is identical across all three user-selectable markup dialects.

**Comment by kareila** [comment]
I'll reopen this if the user comes back with more actionable information. Closing for now.
