### ISSUE TITLE
entry preview uses wrong alert-box class

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#2791]
Noticed in Tropo Red, is probably in everything: the "this is only a preview, your entry has not been saved" alert box at the bottom of the preview window is using .div .alert-box when it should be .alert-box.alert (thanks to @momijizukamori for spotting the difference!)

**Comment by kareila** [comment]
It took me a while to realize this only displays in preview with the combination of the Create Entries beta turned on and the "display my entries in site skin" preference turned on. I'm guessing that's why no one noticed this earlier.

**Comment by kareila** [comment]
Should it be "alert-box alert" or "alert-box secondary"? Since it's not an error, I think secondary might be more appropriate. This is what that looks like.

![Screen Shot 2020-07-27 at 7 49 47 PM](https://user-images.githubusercontent.com/1976742/88606454-59b9f700-d042-11ea-80d0-ba2a4c5b52b7.png)

**Comment by kareila** [comment]
And yes, I noticed the double @@ in front of the date. One is in the template and one is added by the CSS. I can fix that too while I'm in here.

**Comment by rahaeli** [comment]
Ooh I like it as .secondary
