### ISSUE TITLE
feeds with YouTube embeds have invalid site-embed errors

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2821]
Happening in HTML cleaner: `[invalid site-embed, id is missing]` where raw source says something like `<site-embed id="30409"/>`

Probably an issue with "html_extra_raw" format setting `nodwtags => 1` vs Protocol's postevent stripping out the raw embed codes and replacing them with site-embed tags.

**Comment by nfagerlund** [comment]
Here's the commit where that would have happened — https://github.com/dreamwidth/dw-free/pull/2680/commits/f7a6f8743fcc875052292db7ff47b843f5d34cd7

**Comment by nfagerlund** [comment]
.........except, it doesn't seem to do anything around embeds. It looks like maybe I DID leave those alone.

**Comment by nfagerlund** [comment]
Nope, it must be in a different commit. Here we go. https://github.com/dreamwidth/dw-free/pull/2680/commits/f7a6f8743fcc875052292db7ff47b843f5d34cd7
