### ISSUE TITLE
reports of anonymous comment spam disappearing into the ether?

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2841]
https://www.dreamwidth.org/support/see_request?id=42466

@pauamma says that no anonymous spam has been reported since June 27, which corresponds with the date of the code push described in this code tour: https://dw-dev.dreamwidth.org/222909.html

Maybe something went awry with the refactoring of the talkpost code?

**Comment by alierak** [comment]
I went to test this by leaving an anon comment and trying to delete / report it as spam. Indeed it did not work, nor was the comment deleted. I found that the ampersands between parameters of all the comment management links had been escaped, preventing them from working. For example:

&lt;li class="link delete_comment first-item"&gt;&lt;a href="https://www.dreamwidth.org/delcomment?journal=alierak&amp;id=11024" &gt;Delete&lt;/a&gt;&lt;/li&gt;

(one additional layer of escaping applied to the angle brackets above for github display purposes)
