### ISSUE TITLE
Encoding issue in Icons API

### ISSUE THREAD

**Issue by bcholmes** [dreamwidth/dw-free#2899]
One of my icons has a comment with a single quotation mark (Unicode 2019) which, when I fetch my icons using /api/v1/users/{username}/icons it appears like the single quotation mark has been incorrectly encoded (showing me "thereâs" rather than "there’s").

UTF-8 is the standard encoding for JSON, and the content type header looks correct, but the JSON body appears wrong.

I don't really know Perl well enough to track down the bug, but there's some code in LJ::JSON traverse_fix_encoding that appears to make some decisions about how to encode based on what it thinks the contents contain.

**Comment by momijizukamori** [comment]
I definitely recall hitting some weirdness with utf8 parsing in api output before, so I will dig in and see what I can do. Thank you for reporting this!
