### ISSUE TITLE
the password length in the "change email" form needs to be larger

### ISSUE THREAD

**Issue by kareila** [dreamwidth/dw-free#2902]
https://www.dreamwidth.org/support/see_request?id=44313

Our current PASSWORD_MAXLENGTH is 72, but the maxlength of the password field in views/changeemail.tt is only 50.

**Comment by chebegeek** [comment]
I think this has already been fixed. I'm seeing maxlength='[% password_maxlength %] in views/changeemail.tt

**Comment by chebegeek** [comment]
Fixed here;
https://github.com/dreamwidth/dw-free/commit/edfeb3edc68d20320c7270f20587c27b6347ed72

**Comment by kareila** [comment]
Good catch, thanks!
