### ISSUE TITLE
"credit fix" wording next to support answers

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2940]
That one's been bothering me since I was a volunteer on LJ. It was a few months before I could stop parsing it as asking me to fix someone's credit instead of crediting their "fix". To make it more confusing, "fix" is unrelated to "answer". Maybe make it "credit this answer"?

**Comment by kareila** [comment]
string is `views/support/see_request.tt.credit.fix`

**Comment by rahaeli** [comment]
Updated by site copy
