### ISSUE TITLE
<details>/<summary> tags have no styling in sitescheme

### ISSUE THREAD

**Issue by analpi** [dreamwidth/dw-free#2958]
Using the < details > tag lets you hide text, which can then be expanded if you click on the block. On journal themes these blocks get preceded by little sideways triangles to let the reader know they're there, but on sitescheme pages they just look like plaintext. Can you add the little triangles there too?

**Comment by momijizukamori** [comment]
So the little triangle is actually default browser styling, and something in one of our CSS files is stripping that out by changing the display type for those tags. Which is very silly in this case, and once I'm sure it won't make other bits of the site layout go haywire I'm gonna see about fixing that.
