### ISSUE TITLE
Restore ability to apply user CSS to siteschemes

### ISSUE THREAD

**Issue by pauamma** [dreamwidth/dw-free#2959]
Per  https://dw-dev.dreamwidth.org/230972.html?thread=1807420#cmt1807420, applying user CSS to Dreamwidth using https://greasyfork.org/en/scripts/6096-dreamwidth-site-skin-detector stopped working (in or before 2020 per https://greasyfork.org/en/scripts/6096-dreamwidth-site-skin-detector/feedback), making it impossible for users to adjust brightness eg for photophobia. The switch to Foundation may be related.
This is probably an accessibility issue and even if not that, it's definitely poor UX.

**Comment by momijizukamori** [comment]
It's actually only Tropo and only on Foundation pages - there's probably a way to make the userscript work (given that that hasn't been touched in five years), BUT adding a class to body tags is a fairly simple fix, so may as well do it.
