### ISSUE TITLE
Incorrect text on screen comment "success" landing page

### ISSUE THREAD

**Issue by kaberett** [dreamwidth/dw-free#659]
On leaving a screened comment in someone else's journal, the "Post Comment: Success" landing page reads: "Your comment has been added. According to this account's settings, it was marked as screened and will be visible only to you and the journal's owner unless the owner chooses to unscreen it. [View your comment.]"

However, on leaving a screened comment in your own journal, the landing page reads: "Your comment has been added. According to this journal's settings, it was marked as screened, and will be visible only to you until you choose to unscreen it. You can view your comment [here]."

This true only if you are leaving a top-level comment or a threaded response to yourself, not if you are leaving a response to a screened comment made by somebody else on your post. (Edge-case I haven't tested: if you leave a reply to a comment you left in a thread that was started by someone else, call them AB. Is the conversation as a whole visible to AB, or only screened comments left directly in response to AB's comments?) The landing-page text should be edited to accurately reflect what actually happens.

**Comment by kareila** [comment]
Looks like this was fixed in #660.
