### ISSUE TITLE
switch suggestions generator to posting admin entries with GHI links, not Bugzilla links

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#662]
Suggestions generator (http://www.dreamwidth.org/site/suggest) posts two things: a public entry for discussion, and a private (admin) entry with a link that, when clicked, created a new Bugzilla bug with everything nicely preformatted.

Admin entry should be changed to post to Github instead. This will take some research into the Github API.

**Comment by me-and** [comment]
I don't think I can claim this because it's currently assigned to @stormerider, but given there's been no update since June 2014 and @kaberett pointed me at it, I've written a fix which'll be coming shortly...
