### ISSUE TITLE
Use color_header_link properties for links in journal headers

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#677]
Having header links such as navigation links use module colors can cause readability issues. When links are displayed in the header they should use their own set of colors, distinct from module link colors as header and module can have different background colors.
I think this is implemented everywhere but in Bases and Practicality.
Note1: props in Core2 already exist. You don't need to create them.
Note2: users shouldn't see any changes if possible. You'll probably have to set the options to whatever colors were used instead. Nobody will blame you if you decide you don't want to do this for Practicality seeing as it has about 100 themes...

**Comment by momijizukamori** [comment]
claiming because while it's in the 'beginner' category it's also been open for over a year now. @ninetyd, do you remember which two styles were left?

**Comment by ninetyd** [comment]
Bases and Pract according to what I said. :)

**Comment by momijizukamori** [comment]
...that's what I get for skimming comments, haha. Thanks!

**Comment by momijizukamori** [comment]
Hmm. Should we also handle the header link background colors for Bases in this, or leave them?

**Comment by afuna** [comment]
Hmm because it impacts visibility, I think that we should do the BG colors in the same as well.

**Comment by momijizukamori** [comment]
Sure thing. I will make a note with the commit because we'll have to warn
users (this will change custom color settings because we'd have to edit
every wizard layer otherwise)
