### ISSUE TITLE
Add 'Venture' style by onlyembers

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#687]
Submission entry: http://dreamscapes.dreamwidth.org/123136.html

**Comment by momijizukamori** [comment]
claiminng officially now

**Comment by momijizukamori** [comment]
claiming

**Comment by kareila** [comment]
Hey @momijizukamori, I appear to have been slightly hasty in merging this in; I just noticed that the font_entry_title variable is undefined.  Can you fix that when you get a sec?
