### ISSUE TITLE
Add new themes for Summertime style by ketsu

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#688]
Submission entry: http://dreamscapes.dreamwidth.org/127130.html
D, if you could confirm we have their CLA?

**Comment by afuna** [comment]
I backed out the merge because it had stray ">>>" in it which was preventing layers from being compiled. (And then I also added the "#" for the NEWLAYER" to enable compilation).

Please try it again! Hopefully we can get past git shenanigans this time.

**Comment by momijizukamori** [comment]
Let's hope this time's the charm!

**Comment by afuna** [comment]
Yes! (It needs a PR though <3)
