### ISSUE TITLE
Add 'Suit Yourself' style by flamingchemist

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#689]
Submission entry: http://dreamscapes.dreamwidth.org/96339.html
Note: this needs conversion to S2 and refactoring so it's a full-fledged Tabula-Rasa style.

**Comment by ninetyd** [comment]
Adding the links just in case:
https://www.dreamwidth.org/customize/advanced/layersource?id=573568&fmt=html
https://www.dreamwidth.org/customize/advanced/layersource?id=573570&fmt=html

This is just the basic outline; I hadn't started working on element styling.

**Comment by momijizukamori** [comment]
Closing this as the images are all unavailable and I have a vague memory of it having scaling issues on larger screens.
