### ISSUE TITLE
Create nice month view for siteviews

### ISSUE THREAD

**Issue by anall** [dreamwidth/dw-free#693]
[ former bug 1501 ] 

The month view is the last remaining journal-styleable view that is still using a BML page for ?style=site by default.

Compare:

http://exor674.dreamwidth.org/2013/06/?style=site
http://exor674.dreamwidth.org/2013/06/?style=site&fallback=s2

**Comment by afuna** [comment]
Poking my head in! How much more work is needed to get this done? :)

**Comment by zorkian** [comment]
@momijizukamori : that code you have above, is that supposed to be a pull request?

**Comment by momijizukamori** [comment]
Iiiii thought this was already merged? If it's not I'll go back and poke at it

**Comment by afuna** [comment]
Let me look into what happened and get back to you!

**Comment by afuna** [comment]
Ahh I do see what happened. We had the code here, but we were still using the BML page by default. Fixed that in #1160, and removing the s1shortcomings bml file! Hooray.

**Comment by momijizukamori** [comment]
Ahhh okay. Excellent!

**Comment by kareila** [comment]
I'm working on the code tour and just noticed this issue is still open.  Is there anything that still needs to be done?

**Comment by afuna** [comment]
Nope, I think we just didn't close it!

**Comment by kareila** [comment]
I hereby declare this issue closed!  Anything we missed can open a new issue.
