### ISSUE TITLE
Renamed pic#xxx icons revert to default

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#696]
Icons which were uploaded with a pic#xxx keyword then later renamed cannot be used correctly in entries and comments: they revert to the default icon when posted. It is unclear whether deleting then reuploading the icon with one's desired keyword lets you use the icon.

Related pull request: https://github.com/dreamwidth/dw-free/pull/444

We've had multiple requests about this issue.

**Comment by afuna** [comment]
Hmmm, can we tell if this is still happening? I know we fixed something that involved the pic#xxx keyword, which may have also affected this particular case.

**Comment by rahaeli** [comment]
I haven't seen a report in a few weeks, so we may have licked it. I'd leave this open for a bit, just in case.

**Comment by afuna** [comment]
It's been more than a couple weeks, with no further reports (that I've heard of). Closing. If it's still happening we can reopen.
