### ISSUE TITLE
Indicate subject lines in mod queue are truncated by adding "..." back to end

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#738]
Tiny nitpicky little thing: the new version of the moderation queue cuts off entry subjects at what looks like 30 characters. Between that and the 1em font size (which will look really large for people used to Tropo's former .75em) on the new Foundation pages, I'm finding it hard to get a sense of what the entry is. Could we up that to 50 characters, maybe?

**Comment by kareila** [comment]
This didn't get auto-closed.
