### ISSUE TITLE
Feeds won't accept HTTPS URLs

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#786]
I don't know if this has ever been fixed of if there's an issue with this particular URL but I can"t edit the URL of bruce-schneier-feed to https://www.schneier.com/blog/atom.xml although this feed is valid. I get an Invalid URL error message.
http://www.schneier.com/blog/atom.xml redirects to the https version but schneier_no_tracking_feed, which seems to use this alternate URL, won't update.

Request: http://www.dreamwidth.org/support/see_request?id=29076

**Comment by kaberett** [comment]
Sadly this is affecting enough users, and feeds are enough My Problem, that I claim this. (Input very VERY welcome, though.)

**Comment by anall** [comment]
I actually ran into a similar issue this week at Dre!wurk.

To LWP object creation ( I can give pointers to where we do that if you want, but trying to give you minimal pointers ) we need to actually pass in the `SSL_ca_file`, per `Mozilla::CA`.

**Comment by kaberett** [comment]
THANK YOU FOR FIX. Thank you for theft also. &lt;3
