### ISSUE TITLE
Should we limit what's returned from the /data/edges API?

### ISSUE THREAD

**Issue by Sophira** [dreamwidth/dw-free#821]
I'm developing a suite of tools (for my own use only as of right now) to use the data APIs to get data. For some reason I decided it would be a good idea to try it on dw_news. I'm not entirely sure why, but there you go.

I don't have verbose output yet for exactly what stages took the most time, but as a whole, the fetching and processing took about a minute. I looked in my database afterwards to see how many edges had been entered:

```
mysql> select type, count(*) from account_edges where from_id = 5 or to_id = 5 group by type;
+--------+----------+
| type   | count(*) |
+--------+----------+
| watch  |    50000 |
| member |        4 |
| admin  |        2 |
+--------+----------+
3 rows in set (0.13 sec)
```

Yep, that's quite a lot.

Do we want to limit the amount of data that's sent from the APIs? I don't want to run the query again without permission, but I'm guessing that the biggest bottleneck would have been the downstream bandwidth. For my server that's about 1MB/s, meaning that if the bandwidth is indeed the limiting factor, then the implications are rather worrying.

May I make this query one more time and save the data to a file locally so that I can test things without having get the data over the network again?

**Comment by zorkian** [comment]
cc @momijizukamori for your API stuff as a consideration. Since this hasn't cropped up as A Problem in 4 years I'm going to close it wrt our current APIs, but the new stuff should definitely make sure we have limits in them (at least planned, not saying we need them to begin with).

**Comment by Sophira** [comment]
Out of curiosity, was there something wrong with my patch?

**Comment by zorkian** [comment]
What patch? This is an issue, not a PR?

**Comment by alierak** [comment]
Look up in the thread, there's a referencing commit in her repo, not a PR.

**Comment by zorkian** [comment]
I don't review every random commit on every random fork. If someone wants a review, they need to submit a PR.

**Comment by Sophira** [comment]
Yeah, I apologise, sorry. I thought I had made a PR.

**Comment by Sophira** [comment]
Oh, I had (#856), and there were changes requested. Sorry.
