### ISSUE TITLE
Add Firedrive to media embed whitelist

### ISSUE THREAD

**Issue by ninetyd** [dreamwidth/dw-free#828]
Sample code:

```<iframe width='640' height='360' frameborder='0' allowfullscreen src='https://www.firedrive.com/file/8DB308355C7C9AB0'></iframe>```

Request: http://www.dreamwidth.org/support/see_request?id=29115

**Comment by afuna** [comment]
I just opened #1191 for the redirect, but when I tried to embed the sample code, it said server could not be found so I've not added firedrive to the whitelist.

**Comment by afuna** [comment]
Still unable to connect to the URL in the example; going to close this we can revisit if it starts working again.
