### ISSUE TITLE
Control strip: take up the entire width of the screen if possible

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#833]
We want to have the control strip take up the entire width of the screen as much as possible, but then break onto a newline if not

So, brainstorming:

1) display: flex
 I know this will make it able to fill up the remaining space, but I don't know if that will let it fall onto the next line

Note: must keep in mind older browsers don't do flex so need a fallback

2) display: table on larger screens, display: inline-block as we have it on smaller screens

3) ??

**Comment by kareila** [comment]
Hi @deborahgu, are you still interested in working on this? If so, please check in and let us know! If not, I'll unassign this so someone else can pick it up.
