### ISSUE TITLE
Use a more logical HTML structure for the control strip

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#844]
It no longer needs to be a table, therefore don't make it one.

(it's half-broken appearing with the current table forced to inline hybrid appearance is so let's might as well go all the way and actually make it reasonably easy to style)

**Comment by afuna** [comment]
Hey deborah, are you still interested in working on this? I'm thinking of working on the control strip stuff and I'm happy to take this off your hands.

**Comment by rshatch** [comment]
Checking in on this - @deborahgu did you still want to do this? Otherwise I can tackle it (and probably #833, #835, and #1335 by proxy)
