### ISSUE TITLE
HTTPS connections for reading content

### ISSUE THREAD

**Issue by brainwane** [dreamwidth/dw-free#871]
I'd like to be able to browse Dreamwidth journals over HTTPS, and be able to post content over an SSL-protected connection as well. Right now I can log in over HTTPS and read pages on dreamwidth.org via HTTPS, e.g., https://www.dreamwidth.org/nav/explore , but not journals.

(This was http://bugs.dwscoalition.org/show_bug.cgi?id=1239 .)

**Comment by brainwane** [comment]
Hi! [Goodness!](http://dw-news.dreamwidth.org/36470.html) Thank you all for doing so much work on this! I really appreciate it!

**Comment by afuna** [comment]
Thanks for kicking off the discussion so we could be sure to pick it up!

**Comment by afuna** [comment]
I'm not sure why we've kept this open. We've added the proxy and we've added the code that applies the proxying to the various pages. I've looked at the comments and we don't appear to have anything pending, so I'm closing this, 

Feel free to reopen if directly relevant, or (better) let's open a new issue if something related comes up.
