### ISSUE TITLE
Corinthian: get rid of comment-border

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#878]
##effort: lower ##severity: minor

**Comment by afuna** [comment]
@momijizukamori I'm closing this because it looks like it was a deliberate design decision and since this has been open without activity for so long, but let me know if you disagree we can revisit!

**Comment by momijizukamori** [comment]
It wasn't a deliberate design choice - I was the designer - I accidentally pulled it in from wherever I grabbed base styling from (Crisped, I think).

but eh it's been here long enough changing it is probably likely to cause more irritation for users

**Comment by afuna** [comment]
Aha sorry about that! Yeah I guess we can leave it as is.

**Comment by momijizukamori** [comment]
No worries, I kind of fell off DW because school

**Comment by afuna** [comment]
NP. School obviously takes priority! 

(But we'd love to have you back at any point you want / are free to)

**Comment by zorkian** [comment]
YES PLEASE COME BACK TO US :heart_decoration: @momijizukamori
