### ISSUE TITLE
Paper Me: .comment needs background

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#885]
##effort: lower ##severity: minor

**Comment by afuna** [comment]
I keep thinking about this and think that it's pretty much a trade off between making it uglier when the comments aren't nested too deeply, and improving the appearance in the nested comments case.

And I think I'm willing to throw my hands up and say well this style has this limitation, and leave it be.

**Comment by rahaeli** [comment]
Agreed. We have other styles!
