### ISSUE TITLE
track multiple email addresses on emailed-in support requests

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#945]
Scenario that crops up pretty often in Abuse: Party A emails in a request to abuse@, we reply, they fwd our reply to Party B, Party B uses the replyto link to add another comment to the request, we reply again, the email reply only goes to Party A.

If someone using a different email address than the one specified at creation comments to a request using the auth code and the email gateway, their email address should also receive a notification of any future replies. (This should *only* happen with the email gateway: someone leaving a comment on a request through the webform shouldn't get emailed notifs of future replies.)

**Comment by pauamma** [comment]
Which header should the additional addresses go to? To, Cc, or Bcc? (I favor Bcc, as if Alice forwards the email separately to Bob and Carol. she may not expect or want them to know the other saw it as well.)

**Comment by rahaeli** [comment]
For our replies back, you mean? Emails should be sent to each separate address individually, in the To field. 

Example: Alice emails in a support request to abuse@, I reply, Alice forwards my reply to Bob and Carol, both of them reply. When I make another reply, three separate email notifications should go to Alice, Bob, and Carol, with each notification having Alice/Bob/Carol's email address as the sole recipient in the To: field.

**Comment by pauamma** [comment]
1- What are the typical and maximum number of additional email addresses (not counting the one that opened the request) this would need to manage? (If there's no maximum or if the maximum is much larger than typical, that's OK.)

2- Should this be limited to those support categories which allow opening a request by sending an email, or does it apply to all categories?

**Comment by rahaeli** [comment]
Usually it's 1-2 additional addresses, and no, as I said in the initial comment, it doesn't need to be all categories -- just the ones that let you reply to the notification to reply to the request.
