### ISSUE TITLE
previewing too many times causes comment to be posted outside of thread

### ISSUE THREAD

**Issue by rahaeli** [dreamwidth/dw-free#964]
I have not been able to reproduce this myself, but it's been reported privately to me and I've only tested very lightly: if you try to reply to a comment that's part of a collapsed comment thread that you expanded, and hit 'preview' more than once (write comment, preview it, make changes, preview it again), then hit post, the comment is posted as a new toplevel comment and not as a reply to the comment you originally tried to reply to.

**Comment by afuna** [comment]
Reproducing if I do:

More options -> preview -> more options -> post

So I'll fix that and if there's something else that needs fixing we can handle that next bug report.

**Comment by rahaeli** [comment]
Awesome, I think just fixing that will help a lot.
