### ISSUE TITLE
Convert login.tt to use Foundation

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#967]
# curated: beginner #effort: lower #severity: minor

**Comment by momijizukamori** [comment]
claiming because I want to start trying to work on TT/Foundation stufff :U

**Comment by kareila** [comment]
It looks like this is currently only displayed from within protected.tt and most of the CSS on that page applies here. Probably best to convert both together - the issue for protected.tt is #968.

**Comment by momijizukamori** [comment]
roger that o7
