### ISSUE TITLE
security options for logging in: doesn't explain options

### ISSUE THREAD

**Issue by fhocutt** [dreamwidth/dw-free#988]
Is there any reason not to default to htps for logging in, at least from pages on dreamwidth.org? I expect logins from the navbar would be more complicated.

Regardless, adding some text on http://www.dreamwidth.org/login describing the difference between secure and standard login and why one might or might not want to choose "remember me" or "bind cookie to IP address" would allow users to make more informed decisions.

**Comment by me-and** [comment]
If HTTPS Everywhere is going to be a thing, won't this become entirely irrelevant? I'm just wondering if it's worth me/someone spending time on fixing this.

**Comment by afuna** [comment]
It will be. It was meant as a stopgap, but it turned out to be easier just to enable HTTPS instead.

**Comment by rahaeli** [comment]
So, close this one then?

**Comment by afuna** [comment]
Yes!

**Comment by rahaeli** [comment]
Done!
