### ISSUE TITLE
Detect misspellings of gmail, etc

### ISSUE THREAD

**Issue by afuna** [dreamwidth/dw-free#993]
Our current check_email sub looks for misspellings of hotmail, aol... and nothing else. We should probably update this ;)

(bonus if we can use some kind of distance algorithm to detect possible misspellings)

**Comment by deborahgu** [comment]
claim

**Comment by kareila** [comment]
Hi @deborahgu, are you still interested in working on this? If so, please check in and let us know! If not, I'll unassign this so someone else can pick it up.

**Comment by pauamma** [comment]
What misspellings other than gmail's should this check for? (In addition to the ones it already checks for.)

**Comment by zorkian** [comment]
We can answer this with data! Hang on...

```
| gmail.com                       |   554868 |
| yahoo.com                       |    79147 |
| hotmail.com                     |    57384 |
| outlook.com                     |    15896 |
| aol.com                         |    14316 |
| live.com                        |    10251 |
```

Let's do those.

**Comment by pauamma** [comment]
I ran the following code:

```
#!/usr/bin/perl
use strict;
use warnings;
use Text::Fuzzy;

my $maxdistance = 0;
my @domains = ();

foreach my $sld ("gmail", "gmal", "gmial", "gmil", "gmaul", "yahoo", "yhoo", "ahoo", "yhaoo", "yaahoo", "yahooo", "hotmail", "otmail", "hotmial", "hotmil", "hotamail", "hotmaul", "hoatmail", "hatmail", "htomail", "outlook", "otlook", "utlook", "uotlook", "outlok", "outloko", "aol", "ol", "aoll", "live", "ive", "liev", "leiv") {
    foreach my $tld ("cm", "co", "om", "cmo") {
        push @domains, "$sld.$tld";
    }
}

foreach my $domain (@domains) {
    my $tf = Text::Fuzzy->new($domain, trans => 1);
    my $nearest = $tf->nearestv(["gmail.com", "yahoo.com", "hotmail.com", "outlook.com", "aol.com", "live.com"]);
    my $distance = $tf->distance($nearest);
    print "Nearest from $domain is $nearest at distance $distance\n";
    $maxdistance = $distance if $maxdistance < $distance;
}

print "Max distance is $maxdistance\n";
```

to detect a suitable maximum distance (and eyeball for miscorrections), and it gave me 3. That magical constant will figure in the patch to come, with a link to this comment.

**Comment by alierak** [comment]
We have a few thousand users with @mail.com or @ymail.com addresses, can you add tests to make sure these are not considered bad spellings?

**Comment by pauamma** [comment]
I'm wondering whether, as discussed in the https://dw-dev.dreamwidth.org/203374.html?thread=1579886#cmt1579886 thread, a better solution isn't to make this a soft reject/hint instead of the hard reject it is currently.

**Comment by alierak** [comment]
Yeah, that would probably make more sense. Way too much potential for legitimate domains to be blocked as typos here.

**Comment by pauamma** [comment]
See bug #2304.

**Comment by kareila** [comment]
I can confirm @alierak's fears above, that the current code considers mail.com and ymail.com to be bad spellings.  We should add them to the `@common_domains` list so that they are not rejected, in addition to the other workflow improvements suggested elsewhere.

**Comment by kareila** [comment]
Thanks @chrisboyle for doing the remaining work on this!
